### ISSUE TITLE
[Bug] Unknown Registry w/ Tech Reborn's Recycler

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1014]
### What happened?

The details are all outlined here: https://github.com/TechReborn/TechReborn/issues/3007

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```
[12:24:41] [REI-ReloadPlugins/ERROR]: Throwing
java.lang.IllegalStateException: Displays registered for unknown registry: techreborn:recycler
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:266) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:366) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:142) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:482) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Anything else?

Now, the Tech Reborn team has said that they won't fix this but would accept a PR fixing it. I would like to make that PR but was hoping for more information on what actually causes this issue so I can begin to try and fix it (I've made small fix PRs before but this seems more complex).

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
The issue here is that the following line registers a filler for every recipe type in TR, while there are no corresponding `techreborn:recycler` REI category. A fix for this would be to not register that filler.

https://github.com/TechReborn/TechReborn/blob/29ade9092f51b1715b14e84b7340726c6bae0f3f/src/main/java/techreborn/compat/rei/ReiPlugin.java#L184
