### ISSUE TITLE
[Bug] ClassCastException When Getting tooltips

### ISSUE THREAD

**Issue by Phoupraw** [shedaniel/RoughlyEnoughItems#1033]
### What happened?

When I was searching, no matter what I typed, REI still showed all items.
After I disabled tooltips searching, it backed to normal.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[10:33:03] [ForkJoinPool.commonPool-worker-12/INFO]: [STDOUT]: Negative index in crash report handler (13/14)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: java.util.concurrent.ExecutionException: net.minecraft.class_148: Getting tooltips
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.prepareFilter(Argument.java:298)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.prepareFilter(SearchProviderImpl.java:87)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.get(AsyncSearchManager.java:122)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Getting tooltips
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.util.CrashReportUtils.throwReport(CrashReportUtils.java:68)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:237)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:91)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:76)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:45)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.lambda$prepareFilter$0(Argument.java:267)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	... 7 more
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: Caused by: java.lang.ClassCastException: class net.minecraft.class_2585 cannot be cast to class net.minecraft.class_2561 (net.minecraft.class_2585 and net.minecraft.class_2561 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @d8355a8)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:378)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:212)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	... 11 more
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Getting tooltips
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Getting tooltips
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.util.CrashReportUtils.throwReport(CrashReportUtils.java:68)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:237)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:91)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:76)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:45)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.lambda$prepareFilter$0(Argument.java:267)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	... 6 more
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: Caused by: java.lang.ClassCastException: class net.minecraft.class_2585 cannot be cast to class net.minecraft.class_2561 (net.minecraft.class_2585 and net.minecraft.class_2561 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @d8355a8)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:378)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:212)
[10:33:03] [ForkJoinPool.commonPool-worker-17/INFO]: [STDERR]: 	... 11 more
```

### Anything else?

Mods:
- advanced-xray-fabric: Advanced XRay (Fabric) 1.19-1.1.0-build.12
- advancementinfo: AdvancementInfo 1.19-fabric0.53.3-1.3.1
- ae2: Applied Energistics 2 12.0.1-alpha
  - noindium: No Indium? 1.0.2+1.18.2
- ae2additions: AEAdditions 3.1.2-fabric
- amecs: Amecs 1.3.8+mc.1.19-rc2
  - amecsapi: Amecs API 1.3.6+mc22w17a
- architectury: Architectury 5.10.33
- autoharvest: autoharvest 1.19.0
- badpackets: Bad Packets 0.1.2
- bettertaskbar: Better Taskbar 1.4
- can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.3.0
- clickthrough: ClickThrough 1.19-fabric0.53.3-0.4
  - crowdin-translate: CrowdinTranslate 1.4+1.19
  - gbfabrictools: GBfabrictools 1.3.4+1.19
- creeper_firework: Creeper Firework 1.3.3
- cyber-permissions: CyberPermissions 1.3
  - fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
- diggusmaximus: Diggus Maximus 1.5.8-1.19
  - kyrptconfig: Kyrpt Config 1.4.14-1.19
- disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
- enchantinginfuser: Enchanting Infuser 4.0.3
- extended_drawers: Extended Drawers 1.3.1+mc.1.19
  - com_github_llamalad7_mixinextras: MixinExtras 0.0.10
  - graphlib: Graph Lib 0.3.1+1.19
  - mconfig: Mconfig 1.2.0+mc.1.19-rc1
    - de_poiu_apron_apron: apron 2.1.1
- fabric: Fabric API 0.58.0+1.19
  - fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
  - fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
  - fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
  - fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
  - fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
  - fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
  - fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
  - fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
  - fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
  - fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
  - fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
  - fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
  - fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
  - fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
  - fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
  - fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
  - fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
  - fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
  - fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
  - fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
  - fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
  - fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
  - fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
  - fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
  - fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
  - fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
  - fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
  - fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
  - fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
  - fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
  - fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
  - fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
  - fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
  - fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
  - fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
  - fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
  - fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
  - fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
  - fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
  - fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
  - fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
  - fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
  - fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
  - fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
  - fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
  - fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
- fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
  - org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
  - org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
  - org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
  - org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
  - org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
  - org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
  - org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
  - org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
  - org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
  - org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
  - org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
- fabricloader: Fabric Loader 0.14.8
- farmersdelight: Farmer's Delight 1.19-0.3.0
- forgeconfigapiport: Forge Config API Port 4.0.0
  - com_electronwill_night-config_core: core 3.6.5
  - com_electronwill_night-config_toml: toml 3.6.5
- fpsreducer: FPS Reducer 1.19-2.0.2
- ftblibrary: FTB Library 1900.3.8-build.135
- infinitemusic: Infinite Music 1.6.2
- inmis: Inmis 2.7.0-1.19
  - omega-config: OmegaConfig 1.2.3-1.18.1
- inventoryprofilesnext: Inventory Profiles Next 1.6.0
- itemscroller: Item Scroller 0.16.0
- java: OpenJDK 64-Bit Server VM 17
- leaves_us_in_peace: Leaves Us In Peace 1.0.6
- lithium: Lithium 0.8.1
- magiclib: MagicLib 0.5.32
  - magiclib-1_19: MagicLib for 1.19 0.5.32
- malilib: MaLiLib 0.13.0
- minecraft: Minecraft 1.19
- minihud: MiniHUD 0.22.0
- modmenu: Mod Menu 4.0.4
- msr: MCMOD-Search-Reborn 1.0.0+1.18-1.19
- nodami: No Damage Immunity(NoDamI) Reload Mod 1.0.0
- ommc: Oh My Minecraft Client 0.5
  - ommc-1_19: Oh My Minecraft Client for 1.19 0.5
- picturesign: PictureSign 1.4.1
  - midnightlib: MidnightLib 0.5.2
- puzzleslib: Puzzles Lib 4.0.17
- quickhomes: QuickHomes 1.19-1.3.0
- reborncore: Reborn Core 5.3.2
  - team_reborn_energy: Energy 2.2.0
- roughly-enough-characters: Roughly Enough Characters 0.0.6+1.18.2-fabric0.13.3
  - com_github_towdium_pinin: PinIn 1.5.0
- roughlyenoughitems: Roughly Enough Items 9.1.517
- roughlyenoughresources: Roughly Enough Resources 2.6.0
- techreborn: Tech Reborn 5.3.2
- tweakeroo: Tweakeroo 0.13.3
- wthit: wthit 5.7.0
- xp_storage: XP Storage 1.4.3+1.19
  - cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
  - cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
  - cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
  - cloth-config: Cloth Config v6 7.0.72
    - cloth-basic-math: cloth-basic-math 0.6.1

This only happened after I installed AEAdditions and megane.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I believe this is caused by using a 1.18.2 version of AEAdditions on 1.19, and this is not related to REI.
