### ISSUE TITLE
[Bug] World crashes after changing gamemode with button

### ISSUE THREAD

**Issue by pewblaze** [shedaniel/RoughlyEnoughItems#1041]
### What happened?

I tried to change the gamemode with the shortcut buttons -> crashes;
![grafik](https://user-images.githubusercontent.com/96242065/181915691-0baad22f-993c-4777-ac37-72c48752a4c0.png)

RoughlyEnoughItems-9.1.518
fabric-api-0.58.5+1.19.1

Fabric 1.19.1

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2022-07-30 15:09:05
Description: mouseReleased event handler

java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_44099(java.lang.String)'
	at Not Enough Crashes deobfuscated stack trace.(1.19.1+build.1)
	at me.shedaniel.rei.plugin.client.favorites.GameModeFavoriteEntry.doAction(GameModeFavoriteEntry.java:150)
	at me.shedaniel.rei.impl.client.favorites.DelegatingFavoriteEntryProviderImpl.doAction(DelegatingFavoriteEntryProviderImpl.java:81)
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget.doAction(RegionEntryWidget.java:130)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.mouseReleased(EntryWidget.java:565)
	at net.minecraft.client.gui.ParentElement.method_20083(ParentElement:42)
	at java.util.Optional.filter(Optional.java:218)
	at net.minecraft.client.gui.ParentElement.mouseReleased(ParentElement:42)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.mouseReleased(FavoritesListWidget.java:309)
	at net.minecraft.client.gui.ParentElement.method_20083(ParentElement:42)
	at java.util.Optional.filter(Optional.java:218)
	at net.minecraft.client.gui.ParentElement.mouseReleased(ParentElement:42)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$17(RoughlyEnoughItemsCoreClient.java:366)
	at net.minecraft.client.Mouse.handler$zep000$onGuiMouseReleased(Mouse:1133)
	at net.minecraft.client.Mouse.method_1605(Mouse)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:96)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:197)
	at net.minecraft.client.util.Window.swapBuffers(Window:315)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1204)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:767)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$hll000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:29508)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:789)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.rei.plugin.client.favorites.GameModeFavoriteEntry.doAction(GameModeFavoriteEntry.java:150)
	at me.shedaniel.rei.impl.client.favorites.DelegatingFavoriteEntryProviderImpl.doAction(DelegatingFavoriteEntryProviderImpl.java:81)
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget.doAction(RegionEntryWidget.java:130)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25406(EntryWidget.java:565)
	at net.minecraft.class_4069.method_20083(class_4069.java:42)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at net.minecraft.class_4069.method_25406(class_4069.java:42)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.method_25406(FavoritesListWidget.java:309)
	at net.minecraft.class_4069.method_20083(class_4069.java:42)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at net.minecraft.class_4069.method_25406(class_4069.java:42)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$17(RoughlyEnoughItemsCoreClient.java:366)
	at net.minecraft.class_312.handler$zep000$onGuiMouseReleased(class_312.java:1133)
	at net.minecraft.class_312.method_1605(class_312.java)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9226506/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9226507/rei.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9226508/rei-issues.log)
[crash-2022-07-30_15.09.05-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9226512/crash-2022-07-30_15.09.05-client.txt)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by MisileLab** [comment]
Currently, 1.19.1 is not supported.
