### ISSUE TITLE
[Bug] Crash in server_translations_api

### ISSUE THREAD

**Issue by Diyagi** [shedaniel/RoughlyEnoughItems#1047]
### What happened?

When used 4 especific mods together, the server_translations_api crashes.

```
Without Journey - Works
Without Grave - Freezes on "Attempting to load modded language files"
Without REI - Works
Without D4F - Works

With all of them - Crash
```

### What mod loaders are you seeing the problem on?

Quilt

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[init] Changing uid of minecraft to 1001
[init] Changing gid of minecraft to 1001
[init] Running as uid=1001 gid=1001 with /data as 'drwxrwxr-x 12 1001 1001 4096 Aug  1 16:03 /data'
[init] Resolved version given LATEST into 1.19.1 and major version 1.19
[init] Resolving type given QUILT
[init] Checking Quilt Installer version information.
[init] Checking Quilt Loader version information.
[init] Skipping setup of server.properties
[init] Checking for JSON files.
[init] Using Aikar's >12GB flags
[init] Setting initial memory to 18G and max to 18G
[init] Starting the Minecraft server...
Starting org.quiltmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:16:18] [INFO] [Quilt Loader/GameProvider]: Loading Minecraft 1.19.1 with Quilt Loader 0.17.2-beta.2
[17:16:19] [main/INFO]: Loading Minecraft 1.19.1 with Quilt Loader 0.17.2-beta.2
[17:16:19] [ForkJoinPool-1-worker-3/WARN]: Warnings for mod "journeymap"'s mod json:
- Version 5.9.0beta1 does not respect SemVer -- comparison support is limited. "version" at  at line 4 column 26 path $.version
[17:16:20] [main/INFO]: Loading 99 mods:
	- architectury 6.0.35
	- club_minnced_discord-webhooks 0.8.0
	- com_fasterxml_jackson_core_jackson-annotations 2.13.1
	- com_fasterxml_jackson_core_jackson-core 2.13.1
	- com_fasterxml_jackson_core_jackson-databind 2.13.1
	- com_neovisionaries_nv-websocket-client 2.14
	- com_squareup_okhttp3_okhttp 3.13.0
	- com_squareup_okio_okio 1.17.2
	- com_vdurmont_emoji-java 5.1.1
	- common-protection-api 1.0.0
	- d4f 1.8.1
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- hologram-api 0.2.2+1.19
	- java 17
	- journeymap 5.9.0beta1
	- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT
	- minecraft 1.19.1
	- net_dv8tion_jda 5.0.0-alpha.12
	- net_sf_trove4j_trove4j 3.0.3
	- org_apache_commons_commons-collections4 4.4
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21
	- org_json_json 20160212
	- packet_tweaker 0.3.0+1.18.2
	- placeholder-api 2.0.0-beta.7+1.19
	- polymer 0.2.10+1.19.1
	- polymer-registry-sync-manipulator 0.0.1+1.19.1
	- quilt_advancement 3.0.0-beta.2+1.19.1
	- quilt_base 3.0.0-beta.2+1.19.1
	- quilt_biome 3.0.0-beta.2+1.19.1
	- quilt_block_entity 3.0.0-beta.2+1.19.1
	- quilt_block_extensions 3.0.0-beta.2+1.19.1
	- quilt_client_command 3.0.0-beta.2+1.19.1
	- quilt_command 3.0.0-beta.2+1.19.1
	- quilt_crash_info 3.0.0-beta.2+1.19.1
	- quilt_dimension 3.0.0-beta.2+1.19.1
	- quilt_item_content_registry 3.0.0-beta.2+1.19.1
	- quilt_item_group 3.0.0-beta.2+1.19.1
	- quilt_item_setting 3.0.0-beta.2+1.19.1
	- quilt_lifecycle_events 3.0.0-beta.2+1.19.1
	- quilt_loader 0.17.2-beta.2
	- quilt_networking 3.0.0-beta.2+1.19.1
	- quilt_recipe 3.0.0-beta.2+1.19.1
	- quilt_registry 3.0.0-beta.2+1.19.1
	- quilt_registry_entry_attachments 3.0.0-beta.2+1.19.1
	- quilt_resource_loader 3.0.0-beta.2+1.19.1
	- quilt_screen 3.0.0-beta.2+1.19.1
	- quilt_tags 3.0.0-beta.2+1.19.1
	- quilt_tooltip 3.0.0-beta.2+1.19.1
	- quilted_fabric_api 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_api_base 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_api_lookup_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_biome_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_blockrenderlayer_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_command_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_command_api_v2 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_commands_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_containers_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_content_registries_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_convention_tags_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_crash_report_info_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_data_generation_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_dimensions_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_entity_events_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_events_interaction_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_events_lifecycle_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_game_rule_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_item_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_item_groups_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_key_binding_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_keybindings_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_lifecycle_events_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_loot_api_v2 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_loot_tables_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_message_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_mining_level_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_models_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_networking_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_networking_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_object_builder_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_particles_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_registry_sync_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_renderer_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_renderer_indigo 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_renderer_registries_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_rendering_data_attachment_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_rendering_fluids_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_rendering_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_rendering_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_resource_conditions_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_resource_loader_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_screen_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_screen_handler_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_textures_v0 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_transfer_api_v1 4.0.0-beta.1+0.58.5-1.19.1
	- quilted_fabric_transitive_access_wideners_v1 4.0.0-beta.1+0.58.5-1.19.1
	- roughlyenoughitems 9.1.520
	- server_translations_api 1.4.16+1.19
	- sgui 1.1.3+1.19.1
	- universal-graves 2.1.1+1.19.1
[17:16:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Quilt Env=SERVER
[17:16:20] [main/INFO]: Compatibility level set to JAVA_16
[17:16:20] [main/INFO]: Compatibility level set to JAVA_17
[17:16:20] [main/WARN]: Error loading class: eu/vanish/commands/VanishCommand (java.lang.ClassNotFoundException: eu/vanish/commands/VanishCommand)
[17:16:20] [main/WARN]: @Mixin target eu.vanish.commands.VanishCommand was not found d4f.mixins.json:VanishCommandMixin from mod d4f
[17:16:24] [main/INFO]: Building unoptimized datafixer
[17:16:26] [main/INFO]: [Quilt Command] Networking support is enabled
[17:16:26] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[17:16:26] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[17:16:26] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[17:16:26] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[17:16:26] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[17:16:26] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[17:16:27] [main/INFO]: Login Successful!
[17:16:28] [JDA MainWS-WriteThread/INFO]: Connected to WebSocket
[17:16:28] [JDA MainWS-ReadThread/INFO]: Finished Loading!
[17:16:28] [main/INFO]: Attempting to load modded language files
[17:16:28] [main/INFO]: Initializing ServerSide Packet Registries
[17:16:28] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'server_translations_api'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.2-beta.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.17.2-beta.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) [quilt-loader-0.17.2-beta.2.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at fr.catcore.server.translations.api.resource.language.LanguageReader.read(LanguageReader.java:20) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:49) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.2-beta.2.jar:?]
	... 16 more
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: _comment=## Positional parameters (%1$s, %2$s, %3$s, etc.) may be reordered to suit your language's sentence structure and _comment=Config Tooltips
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_2477.method_29429(class_2477.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2477.<clinit>(class_2477.java:33) ~[server-intermediary.jar:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.read(LanguageReader.java:20) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:49) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.16+1.19.jar-e6108e10-fe29-4de7-967a-f606cbdfab1b-nested.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.2-beta.2.jar:?]
	... 16 more
```

### Anything else?

Mods Used:
https://modrinth.com/mod/roughly-enough-items
https://modrinth.com/mod/discord4fabric
https://modrinth.com/mod/universal-graves
https://modrinth.com/mod/journeymap

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I don't believe this is caused by REI, and that REI doesn't do anything special to trigger this crash (In the logs as well, there are no mentions of REI in the stacktrace). This is an interesting issue that I think you should report to server translations api instead. Please reopen the issue if you think this is actually REI's problem, then I will look into this further.
