### ISSUE TITLE
[Bug] Rei causes game crash do to going -1 when inventory is opened

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1069]
### What happened?

When the inventory is opened rei causes the widget search to go negative and crashes the game

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[10Aug2022 14:28:16.798] [main/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: position (-1) must not be negative
	Index: 1
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplClient event(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2969/1224143474@3c6e9976
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2969/1224143474@175d61e9
		5: ASM: xaero.pvp.events.BPVPEvents@4ac438d0 handleDrawScreenEventPost(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		6: ASM: class vazkii.arl.util.DropInHandler onDrawScreen(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		7: ASM: class com.legacy.blue_skies.client.events.SkiesClientEvents drawScreenEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		8: ASM: xaero.map.events.Events@6877447e renderTick(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		9: ASM: class com.swdteam.client.init.BusClientEvents renderEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		10: ASM: class net.blay09.mods.waystones.client.InventoryButtonGuiHandler onDrawScreen(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		11: ASM: vazkii.quark.content.client.module.ChestSearchingModule@59c2828d onRender(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		12: ASM: top.theillusivec4.cherishedworlds.client.ScreenEventsListener@8456ce2 onGuiDrawScreen(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		13: ASM: top.theillusivec4.polymorph.client.ClientEventsListener@7f2823f0 render(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post;)V
		14: net.minecraftforge.eventbus.EventBus$$Lambda$2969/1224143474@244c4c17
		15: ASM: me.pieking1215.startupqol.StartupQoL@627a9a0a onGuiDraw(Lnet/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent;)V
java.lang.IndexOutOfBoundsException: position (-1) must not be negative
	at com.google.common.collect.Iterators.checkNonnegative(Iterators.java:781)
	at com.google.common.collect.Iterables.get(Iterables.java:796)
	at me.shedaniel.rei.plugin.client.SearchFilterPrepareWatcher.provide(SearchFilterPrepareWatcher.java:53)
	at me.shedaniel.rei.impl.client.gui.widget.search.OverlaySearchField.lambda$drawHint$3(OverlaySearchField.java:158)
	at me.shedaniel.rei.impl.client.gui.widget.search.OverlaySearchField$$Lambda$47056/1093437809.apply(Unknown Source)
	at me.shedaniel.rei.api.common.util.CollectionUtils.flatMap(CollectionUtils.java:150)
	at me.shedaniel.rei.impl.client.gui.widget.search.OverlaySearchField.drawHint(OverlaySearchField.java:157)
	at me.shedaniel.rei.impl.client.gui.widget.search.OverlaySearchField.laterRender(OverlaySearchField.java:149)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:672)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$19(RoughlyEnoughItemsCoreClient.java:388)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient$$Lambda$23680/1954248675.render(Unknown Source)
	at me.shedaniel.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:151)
	at net.minecraftforge.eventbus.ASMEventHandler_4112_EventHandlerImplClient_event_Post.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3466/1746371201.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:364)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:356)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$532/1484177113.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9304664/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9304666/rei.log)
[debug.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9304668/debug.log)

Forge version is 36.2.39
Mc version is 1.16.5

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I am sorry but I no longer support 1.16.5
