### ISSUE TITLE
[Bug] REI Crash 

### ISSUE THREAD

**Issue by Vinson8970** [shedaniel/RoughlyEnoughItems#1100]
### What happened?

REI crashes on any/all versions of 1.18 when i open the REI setting

https://user-images.githubusercontent.com/108201128/186751262-6fa14548-6bb2-40f4-b9fd-ed39ed7da260.mp4

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/25/22, 2:24 PM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2561.method_43471(java.lang.String)'
	at me.shedaniel.clothconfig2.impl.ConfigEntryBuilderImpl.<init>(ConfigEntryBuilderImpl.java:38)
	at me.shedaniel.clothconfig2.impl.ConfigEntryBuilderImpl.create(ConfigEntryBuilderImpl.java:44)
	at me.shedaniel.clothconfig2.api.ConfigEntryBuilder.create(ConfigEntryBuilder.java:44)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:53)
	at me.shedaniel.autoconfig.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:102)
	at me.shedaniel.autoconfig.AutoConfig.getConfigScreen(AutoConfig.java:91)
	at me.shedaniel.rei.impl.client.config.ConfigManagerImpl.getConfigScreen(ConfigManagerImpl.java:344)
	at me.shedaniel.rei.api.client.config.ConfigManager.openConfigScreen(ConfigManager.java:66)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$init$12(ScreenOverlayImpl.java:313)
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.ButtonWidget.onClick(ButtonWidget.java:258)
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.ButtonWidget.method_25402(ButtonWidget.java:265)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25402(DelegateWidgetWithTranslate.java:67)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25402(ScreenOverlayImpl.java:873)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$16(RoughlyEnoughItemsCoreClient.java:351)
	at net.minecraft.class_312.handler$zcn000$onGuiMouseClicked(class_312.java:587)
	at net.minecraft.class_312.method_1611(class_312.java)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.clothconfig2.impl.ConfigEntryBuilderImpl.<init>(ConfigEntryBuilderImpl.java:38)
	at me.shedaniel.clothconfig2.impl.ConfigEntryBuilderImpl.create(ConfigEntryBuilderImpl.java:44)
	at me.shedaniel.clothconfig2.api.ConfigEntryBuilder.create(ConfigEntryBuilder.java:44)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:53)
	at me.shedaniel.autoconfig.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:102)
	at me.shedaniel.autoconfig.AutoConfig.getConfigScreen(AutoConfig.java:91)
	at me.shedaniel.rei.impl.client.config.ConfigManagerImpl.getConfigScreen(ConfigManagerImpl.java:344)
	at me.shedaniel.rei.api.client.config.ConfigManager.openConfigScreen(ConfigManager.java:66)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$init$12(ScreenOverlayImpl.java:313)
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.ButtonWidget.onClick(ButtonWidget.java:258)
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.ButtonWidget.method_25402(ButtonWidget.java:265)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25402(DelegateWidgetWithTranslate.java:67)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25402(ScreenOverlayImpl.java:873)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$16(RoughlyEnoughItemsCoreClient.java:351)
	at net.minecraft.class_312.handler$zcn000$onGuiMouseClicked(class_312.java:587)
	at net.minecraft.class_312.method_1611(class_312.java)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Veron37'/207, l='ClientLevel', x=145.38, y=76.00, z=310.99]]
	Chunk stats: 16384, 3658
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,67,0), Section: (at 0,3,0 in 1,4,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 75406 game time, 88073 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/glass_pane_culling_fix, continuity/default

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1333979888 bytes (1272 MiB) / 3321888768 bytes (3168 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2187
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1215
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18358.22
	Virtual memory used (MB): 13081.39
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 363.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.5
		architectury: Architectury 4.9.83
		badpackets: Bad Packets 0.1.2
		bettercombat: Better Combat 1.1.0+1.18.2
			player-animator: Player Animator 0.3.0
			tinyconfig: TinyConfig 1.0.2
		betterf3: BetterF3 1.2.5
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		bettervillage: Better Village 1.0.2
		boatcontainer: BoatContainer 1.2.2
		bottledair-fabric: Bottled Air (Fabric) 1.4
		bottleyourxp-fabric: Bottle Your Xp (Fabric) 2.0
		camerautils: Camera Utils 1.18.2-1.0.0
		cloth-config: Cloth Config v6 7.0.69
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.49
			fiber: fiber 0.23.0-2
		continuity: Continuity 2.0.1+1.18.2
		cryingportals-fabric: Crying Portals (Fabric) 1.5
		cyclepaintings-fabric: Cycle Paintings (Fabric) 2.5
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		doubledoors-fabric: Double Doors (Fabric) 3.6
		editsign: EditSign 2.3.1
		endportalrecipe-fabric: End Portal Recipe (Fabric) 2.9
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.9
		farmersdelight: Farmer's Delight 1.18.2-1.2.1
		friendsandfoes: Friends&Foes 1.4.5
			mm: Manningham Mills 2.3
		indium: Indium 1.0.7+mc1.18.2
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		libraryferret: Library Ferret 2.0.0
		lithium: Lithium 0.7.10
		minecraft: Minecraft 1.18.2
		mobscarecrow: Mob Scarecrow 2.1.1
		modmenu: Mod Menu 3.2.3
		notenoughanimations: NotEnoughAnimations 1.6.0
		phosphor: Phosphor 0.8.1
		reeses-sodium-options: Reese's Sodium Options 1.4.6+mc1.18.2-build.54
		roughlyenoughitems: Roughly Enough Items 8.2.492
		simplyswords: Simply Swords 1.5-1.18.2
		skinswapper: Skin Swapper 3.1.1
			org_apache_httpcomponents_httpclient: httpclient 4.5.10
			org_apache_httpcomponents_httpcore: httpcore 4.4.12
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.8+mc1.18.2-build.56
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		villagernames-fabric: Villager Names (Fabric) 3.8
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 2.5
		worldedit: WorldEdit 7.2.10+1742f98
		wthit: wthit 4.13.2
		xaerominimap: Xaero's Minimap 22.13.2
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
		zombievillagersfromspawner-fabric: Zombie Villagers From Spawner (Fabric) 2.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.15, NVIDIA Corporation
	Window size: 2560x1377
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/glass_pane_culling_fix, continuity/default
	Current Language: English (US)
	CPU: 6x AMD Ryzen 5 3500X 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Veron37'/207, l='ServerLevel[Le World]', x=145.38, y=76.00, z=310.99]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
You have Cloth Config for 1.19 and not 1.18.2

**Comment by Vinson8970** [comment]
alright thanks (btw sorry for the late reply)
