### ISSUE TITLE
Enhance searching alg if the search term is not all ascii char

### ISSUE THREAD

**Issue by eVic75** [shedaniel/RoughlyEnoughItems#114]
REI [Fabric 1.14.2] v2.9.4 Build **129** works fine with MC 1.14.**3** and Fabric loader 0.4.8+build.155-1.14.3, but Build **130** and later, crash game:
- Start game
- Open inventory
- Click on search field of REI
- Type any letter

 - Minecraft:  1,14.3
 - Fabric loader 0.4.8+build.155-1.14.3

Crash report:
https://pastebin.com/y9ESttE1

**Comment by shedaniel** [comment]
Can't reproduce.

**Comment by eVic75** [comment]
Unfortunately, the newest [Fabric 1.14.3] v2.9.6 Build 134 crashes MC 1.14.3 too. Try to open inventory and search any item in REI.
Crash report:
https://pastebin.com/m8hGcf1h

**Comment by shedaniel** [comment]
Can you post the full log? I have some ideas on what this is happening, what's your Minecraft language set to? Or did you try any non English characters?

**Comment by eVic75** [comment]
I didn't tried non English characters. But you're right. My MC language is Polish. I changed to English (US), and everything is OK, game didn't crash.
Is it possible to fix it?

**Comment by shedaniel** [comment]
i will just revert some changes to rei if it detects that it is not english.

**Comment by eVic75** [comment]
OK, I'll wait for new version of file.

**Comment by shedaniel** [comment]
Done, I will keep this issue opened as it is not the best solution, currently you will notice a big performance decrease when searching with non-ascii characters.

**Comment by eVic75** [comment]
Tested :)  Everything is OK. I used all Polish diacritics, and didn't notice any performance decrease. Or I didn't know what to look at ;)
Anyway, good job, you're great. Thank you. 
Regards.

**Comment by rekryt** [comment]
same problem

**Comment by shedaniel** [comment]
Try to update rei

**Comment by Rekryt** [comment]
`[18:28:18] [main/INFO]: Loading for game Minecraft 1.14.3
[18:28:22] [main/WARN]: Non-mandatory unsatisfied dependencies! 
 - Mod roughlyenoughitems recommends mod {cloth-config @ [>=0.1.0]}, which is missing!
[18:28:22] [main/INFO]: [FabricLoader] Loading 40 mods: fabric-networking-blockentity-v0@0.1.1+25fd0c52, fabric-renderer-api-v1@0.1.0+02a46d5b, fabric-keybindings-v0@0.1.1+7dfef87c, modmenu@1.6.2-92, fabricloader@0.4.8+build.155, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.7+029ec62e, fabric-containers-v0@0.1.2+25fd0c52, fabric-events-interaction-v0@0.1.0+59147463, fabric-crash-report-info-v1@0.1.0+59147463, org_slf4j_slf4j-simple@1.7.26, roughlyenoughitems@2.9.6+build.135, net_fabricmc_stitch@0.2.0.+, fabric-api-base@0.1.0+59147463, fabric-rendering-v0@0.1.1+6dad974e, cloth-config2@0.2.0, mm@1.6, fabric-rendering-data-attachment-v1@0.1.0+02a46d5b, fabric-resource-loader-v0@0.1.1+59147463, fabric-textures-v0@0.1.4+792c1c35, fabric-content-registries-v0@0.1.1+05f11b75, fabric-tag-extensions-v0@0.1.1+c189dc5c, blue_endless_jankson@1.1.0, optifabric@0.2.2, fabric-rendering-fluids-v1@0.1.0+dc4c57c2, fabric-commands-v0@0.1.1+25fd0c52, fabric-registry-sync-v0@0.2.2+f0d56800, waila@1.9.16, foamfix@0.12.1, fabric-mining-levels-v0@0.1.0+bdffbb2c, voxelmap@1.9.11, fabric-events-lifecycle-v0@0.1.0+59147463, fabric-loot-tables-v1@0.1.0+43028fa6, fabric@0.3.0+build.187, org_slf4j_slf4j-api@1.7.26, fabric-item-groups-v0@0.1.0+f0d56800, fabric-models-v0@0.1.0+59147463, fabric-networking-v0@0.1.2+200eb5c2, fabric-object-builders-v0@0.1.1+39ff57de, cloth@0.3.1+build.23
[18:28:22] [main/WARN]: Mod `net_fabricmc_stitch` (0.2.0.+) does not respect SemVer - comparison support is limited.
[18:28:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/D:/_MINECRAFT/rekryt.ru_minecraft.1.14.3/minecraft-1.14.3/mc.1.14.3.optifine.voxel.hwyla.foamfix/libraries/net/fabricmc/sponge-mixin/0.7.11.36/sponge-mixin-0.7.11.36.jar Service=Knot/Fabric Env=CLIENT
[18:28:22] [main/INFO]: Compatibility level set to JAVA_8
[18:28:22] [main/WARN]: Mixin config fabric-networking-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-networking-blockentity-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-mining-levels-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-containers-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-renderer-indigo.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-rendering-data-attachment-v1.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-events-interaction-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-loot-tables-v1.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-textures-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-registry-sync-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-models-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-keybindings-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-renderer-api-v1.debughud.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-containers-v0.accurate.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config mixins.mm.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-events-lifecycle-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config optifabric.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-rendering-fluids-v1.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-resource-loader-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-rendering-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config hwyla.client.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-object-builders-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-tag-extensions-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-item-groups-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-content-registries-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-crash-report-info-v1.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-commands-v0.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config fabric-renderer-api-v1.mixins.json does not specify "minVersion" property
[18:28:22] [main/WARN]: Mixin config foamfix.mixins.json does not specify "minVersion" property
[18:28:23] [main/ERROR]: Could not find Config.class inside optifine jar.
[18:28:23] [main/ERROR]: Could not find Config.class inside optifine jar.
[18:28:23] [main/ERROR]: Could not find Config.class inside optifine jar.
[18:28:23] [main/ERROR]: Could not find Config.class inside optifine jar.
[18:28:23] [main/ERROR]: Could not find Config.class inside optifine jar.
[18:28:23] [main/ERROR]: Could not find Config.class inside optifine jar.
[18:28:23] [main/ERROR]: Could not find Config.class inside optifine jar.
[18:28:23] [main/INFO]: Found existing patched optifine jar, using that
[18:28:23] [main/WARN]: Mixin config optifabric.indigofix.mixins.json does not specify "minVersion" property
[18:28:23] [main/WARN]: Mixin config optifabric.optifine.mixins.json does not specify "minVersion" property
[18:28:24] [main/INFO]: Setting user: Rekryt
[18:28:30] [main/INFO]: Definitely not up to no good
[18:28:30] [main/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[18:28:30] [main/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[18:28:30] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[18:28:30] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[18:28:30] [main/INFO]: [Indigo] Registering Indigo renderer!
[18:28:30] [main/WARN]: [REI] Config not found! Creating one.
[18:28:30] [main/INFO]: [REI] Config is loaded.
[18:28:30] [main/INFO]: [REI] Registered plugin roughlyenoughitems:default_plugin from DefaultPlugin
[18:28:30] [main/INFO]: [OptiFine] *** Reflector Forge ***
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_4184.getCameraPosition
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_4184.updateRenderInfo
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.addDestroyEffects
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.addHitEffects
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.canCreatureSpawn
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.canRenderInLayer
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.doesSideBlockRendering
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.doesSideBlockChestOpening
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.getBedDirection
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.getExtendedState
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.getFogColor
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.getLightOpacity
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.getLightValue
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.getSoundType
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.hasTileEntity
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.isAir
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.isBed
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.isBedFoot
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2248.isSideSolid
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1087.isAmbientOcclusion
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2680.canRenderInLayer
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2680.getLightValue
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2680.hasTileEntity
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2680.isAir
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_3610.canRenderInLayer
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1297.canRiderInteract
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.class_1297.captureDrops
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.class_1297.capturedDrops
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1297.shouldRenderInPass
[18:28:30] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1297.shouldRiderSit
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.class_1309.NAMETAG_DISTANCE
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.class_1792.delegate
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.getDurabilityForDisplay
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.getEquipmentSlot
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.getFontRenderer
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.getTileEntityItemStackRenderer
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.getRGBDurabilityForDisplay
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.isShield
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.onEntitySwing
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.shouldCauseReequipAnimation
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.showDurabilityBar
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.canDisableShield
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.getShareTag
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.isShield
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1792.readShareTag
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1738.hasOverlay
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.setKeyConflictContext
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.setKeyModifierAndCode
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.getKeyModifier
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_790.parseFromReader
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_790.fromJson
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1291.shouldRenderHUD
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1291.renderHUDEffect
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1293.isCurativeItem
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2586.canRenderBreaking
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2586.getRenderBoundingBox
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2586.hasFastRenderer
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2586.shouldRenderInPass
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_296$class_298.preDraw
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_296$class_298.postDraw
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1937.countEntities
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1937.getPerWorldStorage
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1937.initCapabilities
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2869.getCloudRenderer
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2869.getSkyRenderer
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2869.getWeatherRenderer
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2869.getLightmapColors
[18:28:31] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2869.getSaveFolder
[18:28:31] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
[18:28:31] [main/WARN]: Skipping bad option: lastServer:
[18:28:31] [main/INFO]: LWJGL Version: 3.2.2 build 10
[18:28:34] [main/INFO]: [OptiFine] 
[18:28:34] [main/INFO]: [OptiFine] OptiFine_1.14.3_HD_U_F1
[18:28:34] [main/INFO]: [OptiFine] Build: 20190627-153724
[18:28:34] [main/INFO]: [OptiFine] OS: Windows 7 (amd64) version 6.1
[18:28:34] [main/INFO]: [OptiFine] Java: 1.8.0_91, Oracle Corporation
[18:28:34] [main/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[18:28:34] [main/INFO]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[18:28:34] [main/INFO]: [OptiFine] OpenGL: GeForce GTX 750 Ti/PCIe/SSE2, version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
[18:28:34] [main/INFO]: [OptiFine] OpenGL Version: 4.6.0
[18:28:35] [main/INFO]: [OptiFine] Maximum texture size: 16384x16384
[18:28:35] [VersionCheck/INFO]: [OptiFine] Checking for new version
[18:28:35] [main/INFO]: [Shaders] OpenGL Version: 4.6.0 NVIDIA 430.64
[18:28:35] [main/INFO]: [Shaders] Vendor:  NVIDIA Corporation
[18:28:35] [main/INFO]: [Shaders] Renderer: GeForce GTX 750 Ti/PCIe/SSE2
[18:28:35] [main/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 
[18:28:35] [main/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[18:28:35] [main/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[18:28:35] [main/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[18:28:35] [main/INFO]: [Shaders] Load shaders configuration.
[18:28:35] [main/INFO]: [Shaders] No shaderpack loaded.
[18:28:39] [main/INFO]: Narrator library for x64 successfully loaded
[18:28:40] [main/INFO]: Built for minecraft version 1.14.3
[18:28:40] [main/INFO]: [OptiFine] *** Reloading textures ***
[18:28:40] [main/INFO]: [OptiFine] Resource packs: 1.14-r3.zip
[18:28:41] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Multitexture: false
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Multipass connected textures: false
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Multipass connected textures: false
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Sprite size: 32
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Mipmap levels: 5
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Scaled too small texture: minecraft:block/campfire_fire, 16 -> 32
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Scaled too small texture: minecraft:item/leather_horse_armor, 16 -> 32
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Scaled too small texture: minecraft:block/tripwire, 16 -> 32
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Scaled too small texture: minecraft:block/jigsaw_top, 16 -> 32
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Scaled too small texture: minecraft:block/campfire_log_lit, 16 -> 32
[18:28:44] [Server-Worker-2/INFO]: [OptiFine] Scaled too small texture: minecraft:optifine/ctm/default/empty, 16 -> 32
[18:28:45] [main/INFO]: OpenAL initialized.
[18:28:45] [main/INFO]: Sound engine started
[18:28:45] [main/INFO]: Created: 2048x1024 textures-atlas
[18:28:45] [main/INFO]: [OptiFine] Animated sprites: 33
[18:28:46] [main/INFO]: Created: 512x512 textures/particle-atlas
[18:28:46] [main/INFO]: Created: 512x512 textures/painting-atlas
[18:28:46] [main/INFO]: Created: 256x256 textures/mob_effect-atlas
[18:28:46] [main/INFO]: [OptiFine] *** Reloading custom textures ***
[18:28:47] [main/INFO]: [STDOUT]: CATEGORY ORDER IS 9
[18:28:47] [main/INFO]: Created: 256x256 waypoints-atlas
[18:28:47] [main/INFO]: Created: 256x128 chooser-atlas
[18:28:47] [main/INFO]: Created: 512x512 mobs-atlas
[18:28:48] [main/INFO]: Created: 64x64 pings-atlas
[18:28:51] [main/INFO]: Connecting to rekryt.ru, 25565
[18:28:52] [REI-SyncRecipes/INFO]: [REI] Loading 1 plugins: roughlyenoughitems:default_plugin
[18:28:52] [main/INFO]: [CHAT] [Rekryt.Ru] Rekryt присоединился
[18:28:52] [main/INFO]: [CHAT] [HolographicDisplays] Found an update: v2.3.2. Download:
[18:28:52] [main/INFO]: [CHAT] >> http://dev.bukkit.org/bukkit-plugins/holographic-displays
[18:28:55] [REI-SyncRecipes/INFO]: [REI] Registered 1143 stack entries, 770 recipes displays, 5 bounds handler, 1 visibility handlers and 8 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Brewing, Composting) in 2713 ms.
[18:28:55] [main/INFO]: Loaded 141 advancements
[18:28:55] [main/INFO]: [CHAT] Welcome, Rekryt!
[18:28:55] [main/INFO]: [CHAT] Type /help for a list of commands.
[18:28:55] [main/INFO]: [CHAT] Type /list to see who else is online.
[18:28:55] [main/INFO]: [CHAT] Players online: 3 - World time: 4:00 PM
[18:28:55] [main/INFO]: [CHAT] Нет новых писем.
[18:28:55] [main/INFO]: [CHAT] Rekryt has the following notes:
[18:28:55] [main/INFO]: [CHAT] [xDarferdasx] топ обезьяна - 01-01-2018
[18:28:55] [main/INFO]: [CHAT] Сессия некорректна. Дождитесь, пока она закончится.
[18:28:59] [main/INFO]: [CHAT] Авторизация: /login <Пароль>
[18:28:59] [main/INFO]: [CHAT] §ENo waypoints exist for this world/server.
[18:29:03] [main/INFO]: [CHAT] Авторизация: /login <Пароль>
[18:29:06] [VersionCheck/INFO]: [OptiFine] java.io.IOException: Server returned HTTP response code: 522 for URL: http://optifine.net/version/1.14.3/HD_U.txt
[18:29:06] [main/INFO]: [CHAT] Приветствуем Rekryt на Rekryt.Ru 1.14.x-1.9 MultiVarious (Lobby) 
[18:29:06] [main/INFO]: [CHAT] 
[18:29:06] [main/INFO]: [CHAT] Приятной игры на сервере!
[18:29:21] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:928) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.3.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:954) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.3.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:411) [intermediary-fabric-loader-0.4.8+build.155-1.14.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) [intermediary-fabric-loader-0.4.8+build.155-1.14.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.155.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.155.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.155.jar:?]
Caused by: java.lang.NullPointerException
	at me.shedaniel.rei.plugin.DefaultPlugin$4.getRightBounds(DefaultPlugin.java:245) ~[RoughlyEnoughItems-2.9.6+build.135.jar:?]
	at me.shedaniel.rei.plugin.DefaultPlugin$4.getRightBounds(DefaultPlugin.java:232) ~[RoughlyEnoughItems-2.9.6+build.135.jar:?]
	at me.shedaniel.rei.gui.ContainerScreenOverlay.init(ContainerScreenOverlay.java:74) ~[RoughlyEnoughItems-2.9.6+build.135.jar:?]
	at me.shedaniel.rei.client.ScreenHelper.getLastOverlay(ScreenHelper.java:49) ~[RoughlyEnoughItems-2.9.6+build.135.jar:?]
	at me.shedaniel.rei.client.ScreenHelper.getLastOverlay(ScreenHelper.java:55) ~[RoughlyEnoughItems-2.9.6+build.135.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$11(RoughlyEnoughItemsCore.java:272) ~[RoughlyEnoughItems-2.9.6+build.135.jar:?]
	at net.minecraft.class_757.handler$renderScreen$zco000(class_757.java:1393) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.3.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:910) ~[intermediary-fabric-loader-0.4.8+build.155-1.14.3.jar:?]
	... 10 more
`

**Comment by shedaniel** [comment]
Logs deleted, please use pastebin and try without optifine.

**Comment by shedaniel** [comment]
Open another issue for that as your crash is not related to this bug.

**Comment by shedaniel** [comment]
This issue is irrelevant in REI 3.0 since the search alg changed.
