### ISSUE TITLE
[Bug] Crash on using search bar 

### ISSUE THREAD

**Issue by Aketoo** [shedaniel/RoughlyEnoughItems#1143]
### What happened?

I just wanted to look up a recipe for a certain ingot. As soon as I used the search bar and started typing the game crashed instantly. Seems like BetterEnd caused the crash, but I'm not sure. Any way to fix that?

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2022-10-06 15:56:15
Description: Rendering entry

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.model.SpriteFinder.find(net.fabricmc.fabric.api.renderer.v1.mesh.QuadView, int)" because the return value of "me.pepperbell.continuity.client.util.RenderUtil.getSpriteFinder()" is null
	at me.pepperbell.continuity.client.model.EmissiveBakedModel$EmissiveItemQuadTransform.transform(EmissiveBakedModel.java:211)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:42)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.renderQuadWithTransform(ItemRenderContext.java:294)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:281)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:267)
	at net.minecraft.class_1087.emitItemQuads(class_1087.java:550)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitItemQuads(ForwardingBakedModel.java:56)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitItemQuads(EmissiveBakedModel.java:103)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:111)
	at net.minecraft.class_918.handler$don000$hook_renderItem(class_918.java:4557)
	at net.minecraft.class_918.method_23179(class_918.java:132)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:269)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.render(ForwardingEntryRenderer.java:42)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:199)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:410)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.drawCurrentEntry(EntryListStackEntry.java:144)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:365)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:246)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:139)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:110)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:330)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:239)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:398)
	at net.minecraft.class_757.handler$zjp000$renderScreenPost(class_757.java:9597)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.client.model.EmissiveBakedModel$EmissiveItemQuadTransform.transform(EmissiveBakedModel.java:211)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:42)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.renderQuadWithTransform(ItemRenderContext.java:294)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:281)
	at link.infra.indium.renderer.render.ItemRenderContext$FallbackConsumer.accept(ItemRenderContext.java:267)
	at net.minecraft.class_1087.emitItemQuads(class_1087.java:550)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitItemQuads(ForwardingBakedModel.java:56)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitItemQuads(EmissiveBakedModel.java:103)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:111)
	at net.minecraft.class_918.handler$don000$hook_renderItem(class_918.java:4557)
	at net.minecraft.class_918.method_23179(class_918.java:132)

-- Screen details --
Details:
	Screen name: net.minecraft.class_490
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:201)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:410)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.drawCurrentEntry(EntryListStackEntry.java:144)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:365)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:246)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:139)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:110)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:330)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:239)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:398)
	at net.minecraft.class_757.handler$zjp000$renderScreenPost(class_757.java:9597)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: betterend:thallasium_bulb_lantern

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: thallasium_bulb_lantern
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.class_490

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry
	Z level: 0
	Bounds: me.shedaniel.math.Rectangle@5e5c53f0[height=18,width=18,x=469,y=82]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: betterend:thallasium_bulb_lantern

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: thallasium_bulb_lantern
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.class_490

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2708375896 bytes (2582 MiB) / 4764729344 bytes (4544 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600X Six-Core Processor           
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b80
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23486.63
	Virtual memory used (MB): 14149.41
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 65.11
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 3.6.1+1.19
		advancednetherite: Advanced Netherite 1.6.4-1.19.2
		advancementplaques: Advancement Plaques 1.4.6
		adventurez: AdventureZ 1.4.16
		ae2: Applied Energistics 2 12.5.1-beta
			noindium: No Indium? 1.1.0+1.19
			team_reborn_energy: Energy 2.0.0-beta1
		ae2wtlib: AE2WTLib 12.5.1-beta
		amethyst_core: Amethyst Core 0.3.1+1.19
		amethyst_imbuement: Amethyst Imbuement 1.19-12
			playerabilitylib: Pal 1.6.0
			structurized-reborn: Structurized Reborn 1.19-01
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		apples: Apples & Carrots 1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.2.46
		attributefix: AttributeFix 17.1.2
		auditory: Auditory 0.0.3-1.19.x
		autosmeltenchant: AutosmeltEnchant 1.1.0
		badpackets: Bad Packets 0.2.0
		balm-fabric: Balm 4.5.2+0
		bambooeverything: Bamboo Everything 2.0.0-build.23+mc1.19.2
		bclib: BCLib 2.1.0
		bedrockify: BedrockIfy 1.4.2+mc1.19.1
		bendy-lib: Bendy api 2.1.1
		better_respawn: Better Respawn 1.19.2-2.0.1
		betteradvancements: Better Advancements 0.2.2.142
		betterend: Better End 2.1.0
		betternether: Better Nether 7.1.0
		betterpingdisplay: Better Ping Display 1.1.1
		bettervillage: Better village 2.0.0
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.1.5
		byg: Oh The Biomes You'll Go 2.0.0.11
		chat_heads: Chat Heads 0.7.1
		clickthrough: ClickThrough 1.19.1-fabric0.58.5-0.4
			gbfabrictools: GBfabrictools 1.3.4+1.19
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 4.68
			fiber: fiber 0.23.0-2
		coloredglowlib: ColoredGlow Lib 1.4.0
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+6
		cosmetic-armor: Cosmetic Armor 1.4.0
		cosmetica: Cosmetica 1.2.1
			com_github_cosmetica-cc_cosmeticadotjava: CosmeticaDotJava 1.5.2
			sulphate: Sulfate 1.1.1
		craftablesaddle: Craftable Saddle 1.19.2-1.6.3-[FABRIC]
		creaturesofthesnow: Creatures Of The Snow 3.1.0+1.19.2
		creeperoverhaul: Creeper Overhaul 2.0.3
		crops_love_rain: Crops Love Rain 1.3.0
		croptopia: Croptopia 2.1.0
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cullleaves: Cull Leaves 2.3.4
		dark-enchanting: Dark Enchanting 1.0.0+1.19.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dataattributes: Data Attributes 1.2.7
		debugify: Debugify 2.7.1
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		dragonloot: DragonLoot 1.1.2
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.2
		dualwielding: Dual Wielding 1.1.2
		dungeon_difficulty: Dungeon Difficulty 1.1.1+1.19
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.0.2
		ears: Ears 1.4.6
		easymagic: Easy Magic 4.3.2
		eatinganimationid: Eating Animation 1.9
		edenring: EdenRing 0.6.4
		editsign: EditSign 2.6.0
		emotecraft: Emotecraft 2.2.5
			player-animator: Player Animator 0.3.5
		enchantment_lore: Enchantment Lore 1.2.10
		enchantmentcompat: Enchantment Compatibility 1.0.1
			roundalib: RoundaLib 0.2.1
		endportalrecipe-fabric: End Portal Recipe (Fabric) 4.0
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.3
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.4
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.3
		experiencebugfix: Experience Bug Fix 18
		extended_armor_bars: Extended Armor Bars 1.2.1
		extraalchemy: Extra Alchemy 1.8.3
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.61.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.0+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.9+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.31+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.29+4e8ca3fd90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.25+726b652090
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.0+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.0+8f88597390
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19-1.3.3
		farmingforblockheads: Farming for Blockheads 11.1.0
		feather_trampling: Feather Trampling 1.0.2-1.19
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendsandfoes: Friends&Foes 1.5.10
		ftblibrary: FTB Library 1902.3.9-build.144
		ftbquests: FTB Quests 1902.4.2-build.116
		ftbteams: FTB Teams 1902.2.9-build.61
		furnacerecycle-fabric: Furnace Recycle (Fabric) 1.6
		fwaystones: Fabric Waystones 3.0.4+mc1.19.2
		geckolib3: Geckolib 3.1.20
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		glassdoor: Glass Doors 3.0.0+1.19
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		highlighter: Highlighter 1.1.4
		ias: In-Game Account Switcher 8.0.1
		icarus: Icarus 1.13
		iceberg: Iceberg 1.0.46
		immersive_paintings: Immersive Paintings 0.2.0+1.19.2
		indium: Indium 1.0.9+mc1.19.2
		interactic: Interactic 0.1.10+1.19
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		invmove: InvMove 0.8.1
		iris: Iris 1.3.1
			org_anarres_jcpp: jcpp 1.4.14
		ironbows: Iron Bows (Fabric) 1.4-FABRIC-1.19.2
		ironchests: Iron Chests: Restocked 3.0.2
		itemfilters: Item Filters 1902.2.9-build.41
		java: OpenJDK 64-Bit Server VM 17
		jeresources: Just Enough Resources 1.1.0.179
		journeymap: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		libraryferret: Library ferret 3.0.0
		lithium: Lithium 0.8.3
		logical_zoom: Logical Zoom 0.0.17
		malilib: MaLiLib 0.13.0
		mavm: More Axolotl Variants Mod 1.1.0
		mcda: MC Dungeons Armors 2.2.0
		mcwlights: Macaw's Lights and Lamps 1.0.4
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mobscarecrow: Mob Scarecrow 2.2.1-1.19.1
		modmenu: Mod Menu 4.0.6
		moonlight: Moonlight 1.19.2-2.0.29
		morefrogs: More Frogs 1.19.x-1.2.3-fabric
		moremcmeta: MoreMcmeta 1.19-3.0.5
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		naturalist: Naturalist 2.1.1
		nicemod: NiceMod - New blocks 1.1 - 1.19.2
		no_more_purple: No More Purple 1.0.1
		notenoughanimations: NotEnoughAnimations 1.6.1
		owo: oωo 0.8.2+1.19
			blue_endless_jankson: jankson 1.2.1
		oxidized: Oxidized 1.7.2
		patchouli: Patchouli 1.19.2-76-FABRIC
		petowner: Pet Owner 1.8.3-1.19+
		phosphor: Phosphor 0.8.1
		playerex: PlayerEx 3.3.7
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		probablychests: Probably Chests 0.5.4-1.19.1
		projectiledamage: Projectile Damage Attribute 2.2.0+1.19
		puzzleslib: Puzzles Lib 4.3.4
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		qu-enchantments: Qu Enchantments 1.2.4-1.19
			mm: Manningham Mills 2.3
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		right-click-harvest: Right-Click-Harvest 1.2.0
		roughlyenoughitems: Roughly Enough Items 9.1.550
			error_notifier: Error Notifier 1.0.9
		servercore: ServerCore 1.3.1-1.19.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
		shinyhorses: Shiny Horses 1.0.0
		silk-all: Silk (All modules) 1.9.2
			silk-commands: Silk Commands 1.9.2
			silk-core: Silk Core 1.9.2
			silk-game: Silk Game 1.9.2
			silk-igui: Silk Inventory GUI 1.9.2
			silk-nbt: Silk NBT 1.9.2
			silk-network: Silk Network 1.9.2
			silk-persistence: Silk Persistence 1.9.2
		simple_backpack: SimpleBackpack 1.3.23
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		skyvillages: Sky Villages 1.0.2.1
		smoothswapping: Smooth Swapping 0.4.5
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		splatus_spellbound_weapons: Spellbound Weapons 3.4.0
		splatus_ultris: Ultris: Boss Expansion 5.6.5
		sspb: Sodium Shadowy Path Blocks 3.1.0
		statuseffecttimer: Status Effect Timer 1.1.1+1.19
		stepup: StepUp 1.19.1-fabric0.58.5-1.1
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		terrablender: TerraBlender 2.0.1.127
		toolstats: ToolStats 12.0.2
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
		totw_additions: Towers of the Wild: Additions 1.2.3
		tradingpost: Trading Post 4.2.0
		transportables: Transportables 1.2.1
		trashslot: TrashSlot 12.0.1
		trinkets: Trinkets 3.4.0
		trulytreasures: Truly Treasures 1.19-2.0.2
		variant_bookshelves: Variant Bookshelves 1.1.8
		villagernames: Villager Names 4.0.8
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
		villagerquests: Villager Quests 1.0.7
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		visuality: Visuality 0.5.1
		visualworkbench: Visual Workbench 4.2.0
		walllanterns: Lanterns Belong on Walls 1.4.0-1.19
		wandering_collector: Wandering Collector 1.1.3+mc1.19
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		wardenloot: Warden Loot 1.0.9-1.19.x
		waveycapes: WaveyCapes 1.2.1
		witherturnsskeletons: Wither turns Skeletons 1.2.0-1.19
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wondrouswilds: Wondrous Wilds 1.19-1.1.1
		woof: Woof 2.0.1-1.19
		yigd: You're in Grave Danger 1.4.4
	Loaded Shaderpack: ComplementaryShaders_v4.3.2.zip
		Profile: Custom (+7 options changed by user)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Please report to BetterEnd.
