### ISSUE TITLE
[Bug] Controllable Mod Compatibility

### ISSUE THREAD

**Issue by Loregart** [shedaniel/RoughlyEnoughItems#1147]
### What happened?

The game crashes when pressing the dpad in the menu or ingame inventory.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[20:45:42] [main/INFO]: ModLauncher running: args [--username, Geistkralle, --version, forge-40.1.80, --gameDir, C:\Users\reich\curseforge\minecraft\Instances\Testpack, --assetsDir, C:\Users\reich\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 0a692fd98272442680f723ff6e47c591, --accessToken, ????????, --clientId, NDAxMjE2NjUtZjYyMy00ZDYwLTgwMjgtYzc5MmVjZDQ0MWVh, --xuid, 2533274896638030, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.80, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[20:45:42] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[20:45:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/reich/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[20:45:42] [main/INFO]: Found mod file architectury-4.9.84-forge.jar of type MOD with provider {mods folder locator at C:\Users\reich\curseforge\minecraft\Instances\Testpack\mods}
[20:45:42] [main/INFO]: Found mod file cloth-config-6.4.90-forge.jar of type MOD with provider {mods folder locator at C:\Users\reich\curseforge\minecraft\Instances\Testpack\mods}
[20:45:42] [main/INFO]: Found mod file controllable-0.16.5-1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\reich\curseforge\minecraft\Instances\Testpack\mods}
[20:45:42] [main/INFO]: Found mod file notenoughcrashes-4.1.4+1.18.2-forge.jar of type MOD with provider {mods folder locator at C:\Users\reich\curseforge\minecraft\Instances\Testpack\mods}
[20:45:42] [main/INFO]: Found mod file RoughlyEnoughItems-8.3.519-server-only.jar of type MOD with provider {mods folder locator at C:\Users\reich\curseforge\minecraft\Instances\Testpack\mods}
[20:45:42] [main/INFO]: Found mod file RoughlyEnoughItems-8.3.549.jar of type MOD with provider {mods folder locator at C:\Users\reich\curseforge\minecraft\Instances\Testpack\mods}
[20:45:42] [main/INFO]: Found mod file RoughlyEnoughItems-forge-8.0.14.jar of type MOD with provider {mods folder locator at C:\Users\reich\curseforge\minecraft\Instances\Testpack\mods}
[20:45:42] [main/WARN]: Mod file C:\Users\reich\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.18.2-40.1.80\fmlcore-1.18.2-40.1.80.jar is missing mods.toml file
[20:45:42] [main/WARN]: Mod file C:\Users\reich\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.1.80\javafmllanguage-1.18.2-40.1.80.jar is missing mods.toml file
[20:45:42] [main/WARN]: Mod file C:\Users\reich\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.1.80\lowcodelanguage-1.18.2-40.1.80.jar is missing mods.toml file
[20:45:42] [main/WARN]: Mod file C:\Users\reich\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.18.2-40.1.80\mclanguage-1.18.2-40.1.80.jar is missing mods.toml file
[20:45:42] [main/INFO]: Found mod file fmlcore-1.18.2-40.1.80.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b809711
[20:45:42] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.1.80.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b809711
[20:45:42] [main/INFO]: Found mod file lowcodelanguage-1.18.2-40.1.80.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b809711
[20:45:42] [main/INFO]: Found mod file mclanguage-1.18.2-40.1.80.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b809711
[20:45:42] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b809711
[20:45:42] [main/INFO]: Found mod file forge-1.18.2-40.1.80-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b809711
[20:45:42] [main/INFO]: No dependencies to load found. Skipping!
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Your logs is insufficient, please attach the full log.

**Comment by matteorizzello** [comment]
I have the same problem, the game doesn't crash with just REI but when JEI Plugin Compatibility gets added the bug occurs.

```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 11/14/22, 6:45 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'mezz.jei.api.runtime.IJeiRuntime me.shedaniel.rei.plugincompatibilities.jeQT2MBLgO5.TYgQHQHFUxc.getRuntime()'
	at com.mrcrayfish.controllable.integration.JustEnoughItems.getNavigationPoints(JustEnoughItems.java:28) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.client.ControllerInput.gatherNavigationPoints(ControllerInput.java:1123) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.client.ControllerInput.navigateMouse(ControllerInput.java:998) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.client.ControllerInput.handleButtonInput(ControllerInput.java:855) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.processButton(Controllable.java:284) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.processButtonStates(Controllable.java:239) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.gatherAndQueueControllerInput(Controllable.java:231) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.controllerTick(Controllable.java:204) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:902) ~[forge-1.18.2-40.1.14-universal.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1614) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.14.jar%2350!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?] {}
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.controllable.integration.JustEnoughItems.getNavigationPoints(JustEnoughItems.java:28) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.client.ControllerInput.gatherNavigationPoints(ControllerInput.java:1123) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.client.ControllerInput.navigateMouse(ControllerInput.java:998) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.client.ControllerInput.handleButtonInput(ControllerInput.java:855) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.processButton(Controllable.java:284) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.processButtonStates(Controllable.java:239) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.gatherAndQueueControllerInput(Controllable.java:231) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.controllable.Controllable.controllerTick(Controllable.java:204) ~[controllable-0.16.5-1.18.2.jar%2354!/:0.16.5-1.18.2] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:902) ~[forge-1.18.2-40.1.14-universal.jar%2361!/:?] {re:classloading,pl:epic_rei_lmao:B}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2262) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.14.jar%2350!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?] {}
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 6.0.6-1-MANJARO
	Java Version: 17.0.5, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1424619264 bytes (1358 MiB) / 2422210560 bytes (2310 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TU116 [GeForce GTX 1660]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 28120.49
	Virtual memory used (MB): 9199.95
	Swap memory total (MB): 20151.00
	Swap memory used (MB): 788.75
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 3.2.0 NVIDIA 520.56.06, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		RoughlyEnoughItems-8.3.571.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |8.3.571             |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.14-universal.jar                |Forge                         |forge                         |40.1.14             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		controllable-0.16.5-1.18.2.jar                    |Controllable                  |controllable                  |0.16.5              |DONE      |Manifest: NOSIGNATURE
		architectury-4.10.86-forge.jar                    |Architectury                  |architectury                  |4.10.86             |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-forge-8.0.27.jar               |REI Plugin Compatibilities    |rei_plugin_compatibilities    |8.0.27              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: df6ca6e9-42f8-4fa9-9534-5357061c3cdf
	FML: 40.1
	Forge: net.minecraftforge:40.1.14
```

**Comment by AlexUnknown37** [comment]
Would love to see a fix, The controllable mod wants a higher (jei)version then what REI creates.

**Comment by shedaniel** [comment]
Can you try with the latest REI Plugin Compat? I believe this is fixed.

**Comment by ParasiticSquid** [comment]
It appears to still be happening. At least on the terrafirmagreg modpack, same menu crash and everything. I don't know why but im guessing something updated recently
