### ISSUE TITLE
[Bug] Crashes in Dev environment

### ISSUE THREAD

**Issue by onyxromero** [shedaniel/RoughlyEnoughItems#1150]
### What happened?

I'm trying to add integration for REI back into this mod I am trying to port and every time I go to run it with this mod installed, the game refuses to load in my dev environment.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
"C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\java.exe" -Dfabric.dli.config=C:\Users\wilki\IdeaProjects\the-big-bench-theory-resumed\.gradle\loom-cache\launch.cfg -Dfabric.dli.env=client -Dfabric.dli.main=net.fabricmc.loader.impl.launch.knot.KnotClient "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\lib\idea_rt.jar=50912:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\bin" -Dfile.encoding=UTF-8 @C:\Users\wilki\AppData\Local\Temp\idea_arg_file817360823 net.fabricmc.devlaunchinjector.Main
[18:48:24] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[18:48:24] [main/INFO] (FabricLoader) Loading 52 mods:
	- architectury 6.2.46
	- bigbenchtheory 1.3.0
	- fabric-api 0.62.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290
	- fabric-api-lookup-api-v1 1.6.10+93d8cb8290
	- fabric-biome-api-v1 9.0.18+c6af733c90
	- fabric-blockrenderlayer-v1 1.1.21+c6af733c90
	- fabric-client-tags-api-v1 1.0.2+b35fea8390
	- fabric-command-api-v2 2.1.8+93d8cb8290
	- fabric-content-registries-v0 3.3.1+624e468e90
	- fabric-convention-tags-v1 1.1.2+93d8cb8290
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90
	- fabric-data-generation-api-v1 5.2.0+b598f4ac90
	- fabric-dimensions-v1 2.1.32+0dd10df690
	- fabric-entity-events-v1 1.4.19+9ff28f4090
	- fabric-events-interaction-v0 0.4.29+c6af733c90
	- fabric-game-rule-api-v1 1.0.22+c6af733c90
	- fabric-gametest-api-v1 1.0.36+e62f51a390
	- fabric-item-api-v1 1.5.8+93d8cb8290
	- fabric-item-groups-v0 0.3.30+93d8cb8290
	- fabric-key-binding-api-v1 1.0.21+93d8cb8290
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90
	- fabric-loot-api-v2 1.1.4+83a8659290
	- fabric-message-api-v1 5.0.4+93d8cb8290
	- fabric-mining-level-api-v1 2.1.15+33fbc73890
	- fabric-models-v0 0.3.18+c6af733c90
	- fabric-networking-api-v1 1.2.5+c6af733c90
	- fabric-object-builder-api-v1 4.0.12+93d8cb8290
	- fabric-particles-v1 1.0.11+79adfe0a90
	- fabric-registry-sync-v0 0.9.26+c6af733c90
	- fabric-renderer-api-v1 1.0.11+c6af733c90
	- fabric-renderer-indigo 0.6.13+aeb40ebe90
	- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90
	- fabric-rendering-v1 1.11.0+73145abb90
	- fabric-resource-conditions-api-v1 2.0.12+a29562c890
	- fabric-resource-loader-v0 0.7.0+93d8cb8290
	- fabric-screen-api-v1 1.0.27+93d8cb8290
	- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90
	- fabric-textures-v0 1.0.21+aeb40ebe90
	- fabric-transfer-api-v1 2.1.1+93d8cb8290
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290
	- fabricloader 0.14.9
	- ingredient-extension-api 3.0.5
	- java 17
	- kubejs 1902.6.0-build.86
	- lazydfu 0.1.3-SNAPSHOT
	- minecraft 1.19.2
	- modmenu 4.0.6
	- nbtcrafting 2.2.0+mc1.19
	- rhino 1902.2.1-build.242
	- roughlyenoughitems 9.1.550
[18:48:24] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/wilki/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/c1dc27696aa4006e492c2485c9ccbcb26045a971/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:48:25] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[18:48:25] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16
[18:48:25] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[18:48:26] [main/WARN] (FileUtil) Configuration conflict: there is more than one oshi.properties file on the classpath
[18:48:26] [main/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[18:48:29] [main/INFO] (Minecraft) Building optimized datafixer
[18:48:33] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:48:34] [Render thread/ERROR] (fabric-screen-api-v1) Failed to verify authentication
 com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.jar:?]
	at net.minecraft.client.Minecraft.createUserApiService(Minecraft.java:711) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:431) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.run(Main.java:205) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.jar:?]
	... 10 more
[18:48:34] [Render thread/INFO] (fabric-screen-api-v1) Setting user: Player252
[18:48:34] [Render thread/INFO] (KubeJS) Looking for KubeJS plugins...
[18:48:34] [Render thread/INFO] (KubeJS) Found plugin source kubejs
[18:48:34] [Render thread/WARN] (KubeJS) Plugin dev.latvian.mods.kubejs.integration.fabric.techreborn.TechRebornKubeJSPlugin does not have required mod techreborn loaded, skipping
[18:48:35] [Render thread/INFO] (KubeJS) Done in 598.6 ms
[18:48:35] [Render thread/INFO] (KubeJS) Loaded common.properties
[18:48:35] [Render thread/INFO] (Rhino Script Remapper) Loading Rhino Minecraft remapper...
[18:48:35] [Render thread/INFO] (RhinoProperties) Rhino properties loaded.
[18:48:35] [Render thread/INFO] (Rhino Script Remapper) Loading mappings for 1.19.2
[18:48:40] [Render thread/INFO] (Rhino Script Remapper) Done in 4.555 s
[18:48:40] [Render thread/INFO] (KubeJS Startup) Hello, World! (You will only see this line once in console, during startup)
[18:48:40] [Render thread/INFO] (KubeJS Startup) Loaded script startup_scripts:script.js in 0.111 s
[18:48:40] [Render thread/INFO] (KubeJS Startup) Loaded 1/1 KubeJS startup scripts in 5.341 s
[18:48:40] [Render thread/INFO] (KubeJS Client) Hello, World! (You will see this line every time client resources reload)
[18:48:41] [Render thread/ERROR] (KubeJS Client) Error loading KubeJS script: ReferenceError: "JEIEvents" is not defined. (client_scripts:script.js#5)
[18:48:41] [Render thread/INFO] (KubeJS Client) Loaded 0/1 KubeJS client scripts in 0.037 s
[18:48:41] [Render thread/INFO] (NetworkManagerImpl) Registering C2S receiver with id kubejs:send_data_from_client
[18:48:41] [Render thread/INFO] (NetworkManagerImpl) Registering S2C receiver with id kubejs:send_data_from_server
[18:48:41] [Render thread/INFO] (NetworkManagerImpl) Registering S2C receiver with id kubejs:paint
[18:48:41] [Render thread/INFO] (NetworkManagerImpl) Registering S2C receiver with id kubejs:add_stage
[18:48:41] [Render thread/INFO] (NetworkManagerImpl) Registering S2C receiver with id kubejs:remove_stage
[18:48:41] [Render thread/INFO] (NetworkManagerImpl) Registering S2C receiver with id kubejs:sync_stages
[18:48:41] [Render thread/INFO] (bigbenchtheory) Initializing Big Bench Theory - Reborn
[18:48:41] [Render thread/INFO] (bigbenchtheory) Initializing screen handlers
[18:48:41] [Render thread/INFO] (bigbenchtheory) Initializing blocks
[18:48:41] [Render thread/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2022-10-11 18:48:41
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:459)
	at net.minecraft.client.main.Main.run(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88)
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy31.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/math/Point
	at me.shedaniel.rei.impl.ClientInternals.<clinit>(ClientInternals.java:74)
	at me.shedaniel.rei.impl.client.gui.widget.InternalWidgets.attach(InternalWidgets.java:163)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.attachClientInternals(RoughlyEnoughItemsCoreClient.java:135)
	at dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:35)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.<clinit>(RoughlyEnoughItemsCore.java:84)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:65)
	... 13 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.math.Point
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:459)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22000.832 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2207.7 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22000.593 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22000.778 (WinBuild.160101.0800):Microsoft Corporation
		breakgen64.dll
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22000.258 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22000.832 (WinBuild.160101.0800):Microsoft Corporation
		iertutil.dll:Run time utility for Internet Explorer:11.00.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		instrument.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		java.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		java.exe:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		jli.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		jna1605687231538807536.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		jvm.dll:OpenJDK 64-Bit server VM:17.0.4.1:Eclipse Adoptium
		kernel.appcore.dll:AppModel API Host:10.0.22000.71 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		management_ext.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		msvcp140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		netutils.dll:Net Win32 API Helpers DLL:10.0.22000.434 (WinBuild.160101.0800):Microsoft Corporation
		nio.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:Power Profile Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		srvcli.dll:Server Service Client DLL:10.0.22000.613 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		urlmon.dll:OLE32 Extensions for Win32:11.00.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
		win32u.dll:Win32u:10.0.22000.856 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22000.184 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.4.1:Eclipse Adoptium
Stacktrace:
	at net.minecraft.client.main.Main.run(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 359143344 bytes (342 MiB) / 1203765248 bytes (1148 MiB) up to 4253024256 bytes (4056 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f99
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1289
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1368
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21342.19
	Virtual memory used (MB): 12285.92
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 203.72
	JVM Flags: 0 total; 
	Fabric Mods: 
		architectury: Architectury 6.2.46
		bigbenchtheory: The Big Bench Theory - Resumed 1.3.0
		fabric-api: Fabric API 0.62.0+1.19.2
		fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
		fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
		fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
		fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
		fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.0.36+e62f51a390
		fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
		fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
		fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
		fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
		fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
		fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
		fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
		fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
		fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
		fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		ingredient-extension-api: Ingredient Extension API 3.0.5
		java: OpenJDK 64-Bit Server VM 17
		kubejs: KubeJS 1902.6.0-build.86
		lazydfu: LazyDFU 0.1.3-SNAPSHOT
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		nbtcrafting: NBT Crafting 2.2.0+mc1.19
		rhino: Rhino 1902.2.1-build.242
		roughlyenoughitems: Roughly Enough Items 9.1.550
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\wilki\IdeaProjects\the-big-bench-theory-resumed\run\crash-reports\crash-2022-10-11_18.48.41-client.txt

Process finished with exit code -1
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
You lack Cloth Config
