### ISSUE TITLE
[Compat] Search does not work if Malum 1.4+ is installed

### ISSUE THREAD

**Issue by Raidobw2** [shedaniel/RoughlyEnoughItems#1159]
### What happened?

Hi, first of all I have already made an issue to Malum about this at: https://github.com/SammySemicolon/Malum-Mod/issues/145

When Malum 1.4 https://www.curseforge.com/minecraft/mc-mods/malum/files/3961432 or more is installed with REI, the search no longer works.

Notice how "cobblestone" is written but nothing is "moving" or showing results:
![image](https://user-images.githubusercontent.com/17010632/196827532-df0ddf01-a049-4c59-98bd-a031aeb81fad.png)

Versions:
`RoughlyEnoughItems-8.3.549.jar`
`RoughlyEnoughItems-forge-8.0.14.jar` (REI Compat)
`architectury-4.9.84-forge.jar`
`malum-1.18.2-1.4.3.1.jar`
`lodestone-1.18.2-1.2.jar`
Forge 40.1.84

This was an issue before REI had a major refactor/rewrite, as soon as Malum 1.4+ came out this was an issue ( I had tested this way back then thinking Malum's beta version was to blame, since it's a beta).

There are some items that Malum added which seem to have a description and I'm not sure but I think it has to do with this.
Here is a relevant log snippet: https://paste.feed-the-beast.com/view/6362ee22
There are 3 necklace images in https://github.com/SammySemicolon/Malum-Mod/issues/145, you can check them with the relevant log kept in mind, I think it will help.

I don't know if this is a compat change needed by REI or an issue caused by Malum, so I made reports on both sides with as much info as possible!

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[19Oct2022 20:06:53.487] [ForkJoinPool.commonPool-worker-10/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent net/minecraft/world/entity/ai/attributes/AttributeModifier for class com/sammy/malum/common/item/equipment/curios/CurioWaterNecklace$1 in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@16c0663d on thread Thread[ForkJoinPool.commonPool-worker-10,5,main]
[19Oct2022 20:06:53.488] [ForkJoinPool.commonPool-worker-10/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: net.minecraft.world.entity.ai.attributes.AttributeModifier
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
        at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.sammy.malum.common.item.equipment.curios.CurioWaterNecklace.getAttributeModifiers(CurioWaterNecklace.java:32) ~[?:?]
        at top.theillusivec4.curios.common.capability.ItemizedCurioCapability.getAttributeModifiers(ItemizedCurioCapability.java:122) ~[?:?]
        at top.theillusivec4.curios.common.CuriosHelper.lambda$getAttributeModifiers$9(CuriosHelper.java:287) ~[?:?]
        at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[?:?]
        at top.theillusivec4.curios.common.CuriosHelper.getAttributeModifiers(CuriosHelper.java:287) ~[?:?]
        at top.theillusivec4.curios.client.ClientEventHandler.onTooltip(ClientEventHandler.java:130) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler_215_ClientEventHandler_onTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar:?]
        at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:275) ~[?:?]
        at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:768) ~[?:?]
        at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:226) ~[?:?]
        at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:371) ~[?:?]
        at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:211) ~[?:?]
        at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:90) ~[?:?]
        at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:75) ~[?:?]
        at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:45) ~[?:?]
        at me.shedaniel.rei.impl.client.search.argument.Argument.lambda$prepareFilter$0(Argument.java:302) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

### Anything else?

This might be yet another compat issue, empty lines in REI item description/lore usually meant a mod wasn't implementing REI's code by default, but JEI's code:
![image](https://user-images.githubusercontent.com/17010632/196828466-fda05a8e-074c-49a1-a7e8-96994eb53b3b.png)

I used FTB Paste and pasted relevant output as raw text as a failsafe, I assume it should be fine instead of Gists

Also, thanks a lot in advance

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Raidobw2** [comment]
I'll continue with Malum, thanks for the help the other day Shedaniel
