### ISSUE TITLE
[Bug] AE2 compatibility for `appliedenergistics2-forge-11.6.1-beta` and up

### ISSUE THREAD

**Issue by Raidobw2** [shedaniel/RoughlyEnoughItems#1171]
### What happened?

It's not possible to craft stone bricks using the "!" button in REI, to place the items in the Crafting Terminal from AE2.

Versions
```
appliedenergistics2-forge-11.6.1-beta.jar
architectury-4.10.86-forge.jar
RoughlyEnoughItems-8.3.556.jar
RoughlyEnoughItems-forge-8.0.18.jar
```

Forge is on 40.1.84
Minecraft is 1.18.2
Modpack is Plexiglass Mountain in-dev 1.2.1

https://user-images.githubusercontent.com/17010632/197984012-bbfe17a2-1a1f-43a6-965d-607ee95538ce.mp4

I believe you had fixed this issue before, though it looks like the newer versions of AE might have broke it again

Thanks for looking into it when you have the time

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[05:02:06] [REI-ReloadPlugins/ERROR] [REI] REI Plugin Compatibilities Adapter [rei_plugin_compatibilities, jei] plugin failed to post-register/!
java.lang.NullPointerException: Cannot invoke "me.shedaniel.rei.api.common.entry.EntryStack.getType()" because "<parameter2>" is null
	at TRANSFORMER/rei_plugin_compatibilities@8.0.18/me.shedaniel.rei.plugincompatibilities.SWGX1UbiMnt.XIHjXCUrWFL.OV6JVqz2RbO(JEIIngredientManager.java:59)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at TRANSFORMER/rei_plugin_compatibilities@8.0.18/me.shedaniel.rei.plugincompatibilities.SWGX1UbiMnt.XIHjXCUrWFL.getAllIngredients(JEIIngredientManager.java:62)
	at TRANSFORMER/kubejs@1802.5.4-build.541/dev.latvian.mods.kubejs.integration.forge.jei.HideJEIEventJS.<init>(HideJEIEventJS.java:30)
	at TRANSFORMER/kubejs@1802.5.4-build.541/dev.latvian.mods.kubejs.integration.forge.jei.JEIPlugin.onRuntimeAvailable(JEIPlugin.java:38)
	at TRANSFORMER/rei_plugin_compatibilities@8.0.18/me.shedaniel.rei.plugincompatibilities.SWGX1UbiMnt.HfZTWHDeAMz.postStage(JEIPluginDetector.java:627)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$post$7(PluginManagerImpl.java:257)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:188)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$post$8(PluginManagerImpl.java:256)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:186)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.post(PluginManagerImpl.java:254)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.api.common.plugins.PluginView$1.post(PluginView.java:71)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:126)
	at TRANSFORMER/roughlyenoughitems@8.3.556/me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:465)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[05:02:06] [REI-ReloadPlugins/DEBUG] [REI] Running post-register for JEI Plugin [REI:ae2things:plugin] with 0 post tasks
[05:02:07] [REI-ReloadPlugins/DEBUG] [REI] Running post-register for JEI Plugin [JEIPlugin:ae2:core] with 10 post tasks
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
This should be resolved now.

**Comment by Raidobw2** [comment]
Thank you very much!
