### ISSUE TITLE
[Bug] Crash when openning SP world and checking first page of recipe

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1176]
### What happened?

I just updated REI for fabric 1.18.2 to latest, launched game, created new creative world, opened menu and crash

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// There are four lights!

Time: 10/28/22, 2:59 PM
Description: Rendering entry extra

java.lang.NullPointerException: indrev:distiller
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at me.shedaniel.rei.impl.client.registry.category.CategoryRegistryImpl.get(CategoryRegistryImpl.java:89)
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.isDisplayVisible(DisplayRegistryImpl.java:211)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget._getTransferHandler(EntryWidget.java:321)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getTransferHandler(EntryWidget.java:363)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:441)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.getCurrentTooltip(EntryListStackEntry.java:194)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.queueTooltip(EntryWidget.java:418)
	at me.shedaniel.rei.impl.client.gui.widget.DisplayedEntryWidget.queueTooltip(DisplayedEntryWidget.java:60)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:218)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:123)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:112)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:197)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:333)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:242)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:405)
	at net.minecraft.class_757.handler$zfa000$renderScreenPost(class_757.java:5057)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at me.shedaniel.rei.impl.client.registry.category.CategoryRegistryImpl.get(CategoryRegistryImpl.java:89)
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.isDisplayVisible(DisplayRegistryImpl.java:211)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget._getTransferHandler(EntryWidget.java:321)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getTransferHandler(EntryWidget.java:363)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:441)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.getCurrentTooltip(EntryListStackEntry.java:194)

-- Screen details --
Details:
	Screen name: net.minecraft.class_481
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:226)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:123)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:112)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:197)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:333)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:242)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:405)
	at net.minecraft.class_757.handler$zfa000$renderScreenPost(class_757.java:5057)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry
	Z level: 0
	Bounds: me.shedaniel.math.Rectangle@3f17f4d4[height=18,width=18,x=509,y=136]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: minecraft:exposed_cut_copper_stairs

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: exposed_cut_copper_stairs
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.class_481

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1672204128 bytes (1594 MiB) / 3355443200 bytes (3200 MiB) up to 10502537216 bytes (10016 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e81
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34742.23
	Virtual memory used (MB): 12925.52
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 6.34
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10016m -Xms256m
	Fabric Mods: 
		ae2: Applied Energistics 2 11.5.0
			noindium: No Indium? 1.0.2+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
		agape_space: Space Dimensions 0.5.17
		architectury: Architectury 4.10.86
		balm-fabric: Balm 3.2.0+0
		betteradvancements: Better Advancements 0.2.1.132
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		dehydration: Dehydration 1.2.8
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		enderchests: EnderChests 1.0.10
		experiencebugfix: Experience Bug Fix 18
		fabric-api: Fabric API 0.59.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.2+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.11+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.14+5d58937860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.4+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.9
		ferritecore: FerriteCore 4.2.1
		indium: Indium 1.0.7+mc1.18.2
		indrev: Industrial Revolution 1.14.0-BETA
			fake-player-api: Fake Player API 0.3.0
			libblockattributes_core: LibBlockAttributes (Core) 0.10.0
			libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
			libblockattributes_items: LibBlockAttributes (Items) 0.10.0
			magna: Magna 1.7.0-1.18-pre1
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		ironchests: Iron Chests 1.7.4
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		jade: Jade 5.99.9
		java: OpenJDK 64-Bit Server VM 17
		journeymap-fabric: Journeymap 5.8.5
			journeymap-api-fabric: JourneyMap API 1.18.2-1.8-fabric-SNAPSHOT
		lightoverlay: Light Overlay 6.1.0
			org_javassist_javassist: javassist 3.26.0-GA
			org_reflections_reflections: reflections 0.9.12
		lithium: Lithium 0.7.10
		minecraft: Minecraft 1.18.2
		modern_industrialization: Modern Industrialization 1.2.2
			patchouli: Patchouli 1.18.2-66-FABRIC-SNAPSHOT
				fiber: fiber 0.23.0-2
			playerabilitylib: Pal 1.5.0
			team_reborn_energy: Energy 2.2.0
		modmenu: Mod Menu 3.2.3
		mousetweaks: Mouse Tweaks 2.22
		netherportalfix: NetherPortalFix 9.0.0
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		reborncore: Reborn Core 5.2.0
		roughlyenoughitems: Roughly Enough Items 8.3.557
			error_notifier: Error Notifier 1.0.9
		shetiphiancore: ShetiPhianCore 1.2.15
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		techreborn: Tech Reborn 5.2.0
		upc: UPC 0.0.2
		waystones: Waystones 2.5.5+mc1.18.2
		wirelessnetworks: Wireless Networks 1.5.1
		yigd: You're in Grave Danger 1.3.10
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I believe this is now fixed
