### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by Sunekaer** [shedaniel/RoughlyEnoughItems#1196]
### What happened?

_When searching for "grass" in the RS system with jei sync on, as soon as the A key is pressed the game crashes to desktop._

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/tyler489/e01bb3af8f2d99f6bf92bdeebf47fdd8
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Raidobw2** [comment]
Here's a similar stacktrace, but with Applied Energistics 2 instead
[crash-2022-11-06_17.54.13-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9947899/crash-2022-11-06_17.54.13-client.txt)

**Comment by Raidobw2** [comment]
Seems to happen without AE2 or RS as well, see https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1601#issuecomment-1304848816 where it's the same crash but in the REI search box

**Comment by Raidobw2** [comment]
More info with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1691
1. Open REI
2. search mod
3. hover over an item. <-- this is typically when it freezes and crashes

![image](https://user-images.githubusercontent.com/16984021/200187723-eef9d1c8-042a-4a16-8317-7160aded60b3.png)

Notes:
Typically when hovering over an item like I did in screenshot above, it wouldn't show the item name in the pop up, it would just freeze and save world and crash instance.

Log: https://paste.ee/p/10EAy

It _looks_ like Emojiful is to blame here, but if you remove Emojiful, you still get crashes, and those crashes are the exact same as in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1601#issuecomment-1304848816

```
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@729313ab rejected from java.util.concurrent.ThreadPoolExecutor@23b437d0[Running, pool size = 80, active threads = 80, queued tasks = 0, completed tasks = 362]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.get(AsyncSearchManager.java:165) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.get(AsyncSearchManager.java:124) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.getAsync(AsyncSearchManager.java:96) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListSearchManager.update(EntryListSearchManager.java:81) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateSearch(EntryListWidget.java:281) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$init$0(ScreenOverlayImpl.java:179) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:?]
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget.onChanged(TextFieldWidget.java:164) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget.eraseCharacters(TextFieldWidget.java:201) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget.erase(TextFieldWidget.java:172) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget.m_7933_(TextFieldWidget.java:299) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.search.OverlaySearchField.m_7933_(OverlaySearchField.java:339) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_7933_(ScreenOverlayImpl.java:368) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$22(RoughlyEnoughItemsCoreClient.java:432) ~[RoughlyEnoughItems-8.3.563.jar%23219!/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:731) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.10.86-forge.jar%2359!/:?]
	at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-4.10.86-forge.jar%2359!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2329!/:?]
	at jdk.proxy3.$Proxy167.keyPressed(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:284) ~[architectury-4.10.86-forge.jar%2359!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler_471_EventHandlerImplClient_event_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.client.ForgeHooksClient.onScreenKeyPressedPre(ForgeHooksClient.java:681) ~[forge-1.18.2-40.1.84-universal.jar%23267!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:362) ~[client-1.18.2-20220404.173914-srg.jar%23262!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23262!/:?]
```

**Comment by shedaniel** [comment]
I have pushed an update that should hopefully alleviate this issue.

**Comment by tyler489** [comment]
Weirdly Enough, if I disable the MineTogether mod, the crash does not happen... Might be a cross mod interaction thing?
