### ISSUE TITLE
[Bug] CRASH. Unable to open Alloy Forgery blocks!

### ISSUE THREAD

**Issue by lithospace** [shedaniel/RoughlyEnoughItems#1204]
### What happened?

How does this relate to REI? Well here's the crash report.
[crash-2022-11-09_14.07.50-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9974385/crash-2022-11-09_14.07.50-client.txt)
Alloy Forgery has integrations with REI where a screen with recipes pops up to the side. Alloy Forgery runs fine without REI but whenever REI is installed, opening a forge block, the game crashes. 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[14:19:53] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
[14:19:53] [VoiceChatConnectionThread/INFO]: Server acknowledged authentication
[14:19:53] [NativeInitializationThread/INFO]: Using Opus version 'libopus 1.3.1'
[14:19:54] [Render thread/WARN]: Received passengers for unknown entity
[14:20:43] [Render thread/ERROR]: ########## GL ERROR ##########
[14:20:43] [Render thread/ERROR]: @ Render
[14:20:43] [Render thread/ERROR]: 65540: Invalid scancode -1
[14:20:54] [Render thread/WARN]: @Final field field_25883:Lnet/minecraft/class_4970$class_4973; in charm.mixins.json:more_portal_frames.AddValidPortalFrameBlocksMixin from mod charm should be final
[14:20:55] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[14:20:56] [Render thread/INFO]: Clearing audio channels
[14:20:56] [Render thread/INFO]: Stopping microphone thread
[14:20:56] [Render thread/INFO]: Disconnecting voicechat
[14:20:56] [Render thread/INFO]: Minimap session finalized.
[14:20:56] [Render thread/INFO]: Finalizing world map session...
[14:20:56] [Thread-20/INFO]: World map force-cleaned!
[14:20:56] [Render thread/INFO]: World map session finalized.
[14:20:56] [Render thread/INFO]: Unloading server config for easymagic
[14:20:56] [Render thread/INFO]: Unloading server config for enchantinginfuser
[14:20:56] [Render thread/INFO]: Unloading server config for pickupnotifier
[14:20:57] [Render thread/INFO]: Stopping worker threads
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266803)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266820)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266805)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2626.redirect$fbj001$polymer_replaceState(class_2626.java:533)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266801)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266801)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at net.minecraft.class_437.method_25394(class_437.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:104) ~[client-intermediary.jar:?]
	at io.wispforest.owo.ui.base.BaseOwoHandledScreen.method_25394(BaseOwoHandledScreen.java:156) ~[owo-lib-0.8.5+1.19.jar:?]
	at wraith.alloyforgery.client.AlloyForgeScreen.method_25394(AlloyForgeScreen.java:39) ~[wraith-alloy-forgery-2.0.17+1.19.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	... 7 more
Bottom of latest.log
```

### Anything else?

RoughlyEnoughItems-9.1.568
wraith-alloy-forgery-2.0.17+1.19
fabric 0.14.10
fabric-api-0.66.0+1.19.2

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by lithospace** [comment]
Not an issue via REI
