### ISSUE TITLE
[Bug]Use composting option, causes the game to crash

### ISSUE THREAD

**Issue by nicklly** [shedaniel/RoughlyEnoughItems#121]
I install REIAddon and REI. but I use my own composting for REI, cause the game to crash.... REIAddon it won't crash the game.

I have crash file....

Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at uk.me.desert_island.rer.WorldGenState.byDimension(WorldGenState.java:39)
	at uk.me.desert_island.rer.rei_stuff.WorldGenCategory$1.render(WorldGenCategory.java:67)
	at me.shedaniel.rei.gui.VillagerRecipeViewingScreen.lambda$render$3(VillagerRecipeViewingScreen.java:325)
	at java.util.ArrayList.forEach(Unknown Source)
	at me.shedaniel.rei.gui.VillagerRecipeViewingScreen.render(VillagerRecipeViewingScreen.java:323)
	at net.minecraft.class_757.method_3192(class_757.java:910)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:411)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at uk.me.desert_island.rer.WorldGenState.byDimension(WorldGenState.java:39)
	at uk.me.desert_island.rer.rei_stuff.WorldGenCategory$1.render(WorldGenCategory.java:67)
	at me.shedaniel.rei.gui.VillagerRecipeViewingScreen.lambda$render$3(VillagerRecipeViewingScreen.java:325)
	at java.util.ArrayList.forEach(Unknown Source)
	at me.shedaniel.rei.gui.VillagerRecipeViewingScreen.render(VillagerRecipeViewingScreen.java:323)

-- Screen render details --
Details:
	Screen name: me.shedaniel.rei.gui.VillagerRecipeViewingScreen
	Mouse location: Scaled: (498, 213). Absolute: (996.000000, 427.000000)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['nicky123'/16552630, l='MpServer', x=-1667.47, y=70.00, z=2561.20]]
	Chunk stats: Client Chunk Cache: 225, 81
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (256,96,-206), Chunk: (at 0,6,2 in 16,-13; contains blocks 256,0,-208 to 271,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 87018 game time, 95384354 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:548)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:426)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

mod version: RoughlyEnoughItems-2.9.6+build.138
fabric version: fabric-api-0.3.0+build.191
Minecraft version: 1.14.3

**Comment by shedaniel** [comment]
Ugh remove REIAddon, it is no longer supported.
Also, the crash seems to be caused by RER (Roughly Enough Resources)
