### ISSUE TITLE
[Bug] REI Sometimes Forces 100% CPU Usage, Locking Computer

### ISSUE THREAD

**Issue by RobertHDPotatoes** [shedaniel/RoughlyEnoughItems#1225]
### What happened?

In my private custom modpack (fabric - 0.14.10), occasionally REI (RoughlyEnoughItems-9.1.572) will cause an insane hang at the "Joining World" screen, where my CPU is forced to 100% usage and my whole computer locks up and lags. I then have to force exit Minecraft (I have let it go for several minutes before, and it refuses to load any further) and am left with incomplete logs and no crash report. It only crashes like this roughly 75% of the time. REI does not do this on my machine on a clean profile with only REI installed. I have never experienced an issue as rough as this one, especially since my machine is pretty okay (Ryzen 5 5600x and RTX 3070). The only reason I know it is REI is simply because the crash happens directly after REI reloads in my logs, which is the last thing my logs show. Disabling/removing REI causes my game to function normally again. The few times I don't crash while using REI, REI takes extra time to initialize in game.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Check below, log was too long to paste here
```

### Anything else?

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10044415/rei.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10044479/latest.log)

I'm pretty sure my logs will not be very sufficient in helping you figure out the problem, but I do not really know what else to do to troubleshoot this problem further. Any advice is welcome. As a side note, I also get the crash with or without the RER and REP plugins.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Orygeunik** [comment]
Hello!
I have same problem, but have small thing, on version 9.1.572- i couldn't successfully entered into world (never). I was downgraded version to 9.1.570, and in logs i found next error:
```
[18:36:46] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 13054ms or 261 ticks behind
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: java.util.concurrent.TimeoutException
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.prepareFilter(Argument.java:376)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.resetCache(Argument.java:98)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.REIRuntimeImpl.endReload(REIRuntimeImpl.java:275)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:373)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$27(RoughlyEnoughItemsCoreClient.java:506)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:37:02] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

So, at this moment, i have a temporary solution - in config reduce `asyncSearchPartitionSize` to 25

**Comment by RobertHDPotatoes** [comment]
Just looked through some of my past logs and found some that are very similar to that one. I tried your temporary solution but it does not work for me unfortunately

**Comment by Orygeunik** [comment]
@RobertHDPotatoes tried to downgrade mod to `9.1.570`?

**Comment by RobertHDPotatoes** [comment]
I did not, but I just changed asyncSearch to false and I can load into worlds without crashing now, on version 9.1.572.

**Comment by chorbintime** [comment]
I'd like to add that this same issue was present on one of our modpacks (https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric). It only happens on the latest version of RoughlyEnoughItems. Using the same version of REI on a similar modpack with less mods (https://www.curseforge.com/minecraft/modpacks/better-mc-fabric) does not have this issue. 

You can compare the two modpacks here: https://www.modpackindex.com/modpacks/compare?modpacks=28903,32754

One of the mods that is only present in Medieval MC and not in Better MC is causing this issue.

**Comment by samos667** [comment]
Same issue with this [mod list](https://mclo.gs/KRdvLaS) on my 1.18.2 modpack with REI 8.3.576.



> I did not, but I just changed asyncSearch to false and I can load into worlds without crashing now, on version 9.1.572.

Tested 2 times this trick work greatly !

**Comment by INSANEMODE** [comment]
This also affects this [fabric 0.14.11 modpack](https://www.curseforge.com/minecraft/modpacks/e3vls-rat-pack). downgrading REI or setting async search to false gets around the issue.
