### ISSUE TITLE
Game Breaking crash does not let you back in on server

### ISSUE THREAD

**Issue by garrettj1220** [shedaniel/RoughlyEnoughItems#1244]
### What happened?

Running through multiple world attempts we will randomly crash and get this crash error. When trying to rejoin it will just crash again and display the same message. We even tried tping to another location and you can move around for a couple minutes and then crash again.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[21:22:34] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry java.lang.IllegalStateException: indrev:distiller 	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:309) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:373) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$27(RoughlyEnoughItemsCoreClient.java:506) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] 	at java.lang.Thread.run(Thread.java:833) [?:?] [21:22:34] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry java.lang.IllegalStateException: indrev:laser 	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:309) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:373) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$27(RoughlyEnoughItemsCoreClient.java:506) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] 	at java.lang.Thread.run(Thread.java:833) [?:?] [21:22:34] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry java.lang.IllegalStateException: indrev:electrolysis 	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:309) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:373) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$27(RoughlyEnoughItemsCoreClient.java:506) ~[RoughlyEnoughItems-9.1.572.jar:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] 	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by rozbrajaczpoziomow** [comment]
```
[REI] Found displays registered for unknown registry
java.lang.IllegalStateException: indrev:distiller
```

Sounds like an Industrial Revolution issue to me, especially that they have their own REI plugin: https://github.com/GabrielOlvH/Industrial-Revolution/tree/master/src/main/kotlin/me/steven/indrev/compat/rei

**Comment by shedaniel** [comment]
Found displays registered for unknown registry is a warning not a crash

**Comment by rozbrajaczpoziomow** [comment]
The newest beta release of Industrial Revolution mentions that it fixes a REI crash on servers; so you should update if you're not on newest
![Changelog](https://user-images.githubusercontent.com/58668179/204081283-ced5a5ae-e2eb-4f95-b87f-ac50f1387731.png)
