### ISSUE TITLE
[Bug] Not installing architectury api causes intense log spam

### ISSUE THREAD

**Issue by TheArcaneBrony** [shedaniel/RoughlyEnoughItems#1248]
### What happened?

mod spams console output at an alarming rate 
architectury api is also not correctly declared as a dependency.

### What mod loaders are you seeing the problem on?

Quilt

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Found 1 error(s) during startup:
- Architectury API is a required dependency of Roughly Enough Items 9.1.572 but it is not installed!
https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
java.lang.RuntimeException: Resource not found: /assets/minecraft/textures/font/ascii.png
	at me.shedaniel.errornotifier.fabric.ErrorNotifierPlatformImpl.lambda$getResourceResolver$0(ErrorNotifierPlatformImpl.java:30)
	at me.shedaniel.errornotifier.launch.early.FontLoader.<init>(FontLoader.java:33)
	at me.shedaniel.errornotifier.launch.early.FontLoader.fromJson(FontLoader.java:64)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.getFont(EarlyGraphics.java:33)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.splitString(EarlyGraphics.java:149)
	at me.shedaniel.errornotifier.client.ErrorRenderer.render(ErrorRenderer.java:25)
	at me.shedaniel.errornotifier.launch.EarlyWindow.render(EarlyWindow.java:235)
	at me.shedaniel.errornotifier.launch.EarlyWindow.renderWindow(EarlyWindow.java:226)
	at me.shedaniel.errornotifier.launch.EarlyWindow.start(EarlyWindow.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at me.shedaniel.errornotifier.ErrorNotifier.init(ErrorNotifier.java:43)
	at me.shedaniel.errornotifier.fabric.ErrorNotifierFabric.onPreLaunch(ErrorNotifierFabric.java:11)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:169)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

... (cut off because the game reached 100k lines in a few seconds with this stacktrace repeating)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by AlexIIL** [comment]
AFAIK this is caused by older versions of quilt loader not exposing minecrafts assets via its mod container - so what version of quilt loader are you using? *(edit: I think only the 0.18.1 betas have fixed this actually)*

**Comment by kaylendog** [comment]
Couldn't this just be fixed by declaring the architectury API as a dependency in fabric.mod.json?

**Comment by shedaniel** [comment]
@kaylendog Neither Quilt or Fabric's error gui is user friendly enough, I don't want to go back to the old days where people will screenshot the error screen and ask me what it is

Plus this is a Quilt Loader bug anyways, it needs to be fixed

**Comment by kaylendog** [comment]
> @kaylendog Neither Quilt or Fabric's error gui is user friendly enough, I don't want to go back to the old days where people will screenshot the error screen and ask me what it is
> 
> Plus this is a Quilt Loader bug anyways, it needs to be fixed

That's fair - do you think it'd be worthwhile dropping a warning in console if the mod can't find the APIs? At least until the bug gets fixed in Quilt. I spent like 20 minutes enabling and disabling mods to find the issue...

**Comment by shedaniel** [comment]
A warning is in the console but it could be overwhelmed by the constant errors or it could be crashing before it gets to print to the console

**Comment by shedaniel** [comment]
@AlexIIL Are there any updates to this issue? Is the fix released in a release?

**Comment by AlexIIL** [comment]
erm, isn't this the warning in console?
> Found 1 error(s) during startup:
> - Architectury API is a required dependency of Roughly Enough Items 9.1.572 but it is not installed!

and yes, this is fixed in quilt-loader 0.18.1-beta.22 - however since it sadly only is in the loader-plugins betas it's not a full release quite yet. It's getting quite stable now though, so it will hit release soon.
