### ISSUE TITLE
[Bug] The string for a recipe is too long, which breaks REI and other recipe books.

### ISSUE THREAD

**Issue by ZeroOnexD** [shedaniel/RoughlyEnoughItems#1266]
### What happened?

I created a mc server and added next to the medieval mc 1.19.2 fabric modpack some mods, 2nd picture. Techreborn though crashes REI everytime a player gets synchronized with the server/recipe files.
Everytime i or anyone else joins the server it cant read the recipes bc the string is too big. The thing is though that in singleplayer everything works, do i need to change settings in the REI config or in the server config or somewhere else like the techreborn config? I would like to not deinstall techreborn, if possible.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[20:03:18] [Netty Epoll Server IO #14/INFO]: Receiving client config
[20:03:19] [Server thread/INFO]: ****** joined the game
[20:03:19] [Netty Epoll Server IO #14/ERROR]: Recipe output string is too big. This breaks recipe books!
[20:03:19] [Netty Epoll Server IO #14/ERROR]: Recipe is:techreborn:industrial_sawmill/saw_dust_from_wooden_doors
[20:03:19] [Netty Epoll Server IO #14/ERROR]: Output is:{"type":"techreborn:industrial_sawmill","power":30,"time":200,"ingredients":[{"tag_server_sync":true,"items":1960,"item_0":"minecraft:oak_door","item_1":"minecraft:spruce_door","item_2":"minecraft:birch_door","item_3":"minecraft:jungle_door","item_4":"minecraft:acacia_door","item_5":"minecraft:dark_oak_door","item_6":"minecraft:crimson_door","item_7":"minecraft:warped_door","item_8":"minecraft:mangrove_door","item_9":"architects_palette:twisted_door","item_10":"bewitchment:juniper_door","item_11":"bewitchment:cypress_door","item_12":"bewitchment:elder_door","item_13":"bewitchment:dragons_blood_door","item_14":"biomemakeover:blighted_balsa_door","item_15":"biomemakeover:willow_door","item_16":"biomemakeover:swamp_cypress_door","item_17":"biomemakeover:ancient_oak_door","item_18":"bwplus:yew_door","item_19":"byg:aspen_door","item_20":"byg:baobab_door","item_21":"byg:blue_enchanted_door","item_22":"byg:bulbis_door","item_23":"byg:cherry_door","item_24":"byg:cika_door","item_25":"byg:cypress_door","item_26":"byg:ebony_door","item_27":"byg:embur_door","item_28":"byg:ether_door","item_29":"byg:fir_door","item_30":"byg:green_enchanted_door","item_31":"byg:holly_door","item_32":"byg:imparius_door","item_33":"byg:jacaranda_door","item_34":"byg:lament_door","item_35":"byg:mahogany_door","item_36":"byg:maple_door","item_37":"byg:nightshade_door","item_38":"byg:palm_door","item_39":"byg:pine_door","item_40":"byg:rainbow_eucalyptus_door","item_41":"byg:redwood_door","item_42":"byg:skyris_door","item_43":"byg:sythian_door","item_44":"byg:white_mangrove_door","item_45":"byg:willow_door","item_46":"byg:witch_hazel_door","item_47":"byg:zelkova_door","item_48":"charm:azalea_door","item_49":"charm:ebony_door","item_50":"cinderscapes:scorched_door","item_51":"cinderscapes:umbral_door","item_52":"deeperdarker:echo_door","item_53":"ecologics:coconut_door","item_54":"ecologics:walnut_door","item_55":"ecologics:azalea_door","item_56":"ecologics:flowering_azalea_door","item_57":"mcwdoors:oak_japanese_door","item_58":"mcwdoors:spruce_japanese_door","item_59":"mcwdoors:birch_japanese_door","item_60":"mcwdoors:jungle_japanese_door","item_61":"mcwdoors:acacia_japanese_door","item_62":"mcwdoors:dark_oak_japanese_door","item_63":"mcwdoors:crimson_japanese_door","item_64":"mcwdoors:warped_japanese_door","item_65":"mcwdoors:mangrove_japanese_door","item_66":"mcwdoors:oak_japanese2_door","item_67":"mcwdoors:spruce_japanese2_door","item_68":"mcwdoors:birch_japanese2_door","item_69":"mcwdoors:jungle_japanese2_door","item_70":"mcwdoors:acacia_japanese2_door","item_71":"mcwdoors:dark_oak_japanese2_door","item_72":"mcwdoors:crimson_japanese2_door","item_73":"mcwdoors:warped_japanese2_door","item_74":"mcwdoors:mangrove_japanese2_door","item_75":"mcwdoors:oak_barn_door","item_76":"mcwdoors:spruce_barn_door","item_77":"mcwdoors:birch_barn_door","item_78":"mcwdoors:jungle_barn_door","item_79":"mcwdoors:acacia_barn_door","item_80":"mcwdoors:dark_oak_barn_door","item_81":"mcwdoors:crimson_barn_door","item_82":"mcwdoors:warped_barn_door","item_83":"mcwdoors:mangrove_barn_door","item_84":"mcwdoors:oak_barn_glass_door","item_85":"mcwdoors:spruce_barn_glass_door","item_86":"mcwdoors:birch_barn_glass_door","item_87":"mcwdoors:jungle_barn_glass_door","item_88":"mcwdoors:acacia_barn_glass_door","item_89":"mcwdoors:dark_oak_barn_glass_door","item_90":"mcwdoors:crimson_barn_glass_door","item_91":"mcwdoors:warped_barn_glass_door","item_92":"mcwdoors:mangrove_barn_glass_door","item_93":"mcwdoors:oak_modern_door","item_94":"mcwdoors:spruce_modern_door","item_95":"mcwdoors:birch_modern_door","item_96":"mcwdoors:jungle_modern_door","item_97":"mcwdoors:acacia_modern_door","item_98":"mcwdoors:dark_oak_modern_door","item_99":"mcwdoors:crimson_modern_door","item_100":"mcwdoors:warped_modern_door","item_101":"mcwdoors:mangrove_modern_door","item_102":"mcwdoors:oak_cottage_door","item_103":"mcwdoors:birch_cottage_door","item_104":"mcwdoors:jungle_cottage_door", ..... (there is more but its not pastable)
[20:03:19] [Netty Epoll Server IO #14/ERROR]: Error receiving packet 106
io.netty.handler.codec.EncoderException: String too big (was 111849 characters, max 32767)
	at net.minecraft.class_2540.method_10788(class_2540.java:2265) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_10814(class_2540.java:612) ~[server-intermediary.jar:?]
	at reborncore.common.crafting.RebornRecipeType.write(RebornRecipeType.java:88) ~[reborncore-5.3.4-baba51d8b60241b3.jar:?]
	at reborncore.common.crafting.RebornRecipeType.method_8124(RebornRecipeType.java:41) ~[reborncore-5.3.4-baba51d8b60241b3.jar:?]
	at net.minecraft.class_2788.method_17816(class_2788.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_34062(class_2540.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_11052(class_2788.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) [server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) [server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:03:19] [Netty Epoll Server IO #14/INFO]: [STDOUT]: REI: Server failed to synchronize recipe data with the client! Please check the server console log for errors, this breaks REI and vanilla recipe books!
```

### Anything else?

![sw](https://user-images.githubusercontent.com/61319822/206788307-bf8bfcc6-efca-448a-8f79-e56c6aa2601b.png)
![mods png](https://user-images.githubusercontent.com/61319822/206789678-d64943ad-d936-46c1-af3a-e672bcfb1806.PNG)
[config.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10197913/config.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ZeroOnexD** [comment]
Just download a techreborn version after 5.3.4 and its fixed
