### ISSUE TITLE
[Bug] Fabric Mod Conflict with Vinery (Let's Do Wine) 1.1.2 for MC 1.18.2

### ISSUE THREAD

**Issue by EvionFox** [shedaniel/RoughlyEnoughItems#1284]
### What happened?

After completing the loading screen, before reaching the main menu, the game pops up with the message:
"Errors during Roughly Enough Items' initialization
Errors:
Could not create REI Plugin [REIPlugin] due to errors, provided by 'vinery'!
Could not create REI Plugin [REIServerPlugin] due to errors, provided by 'vinery'!"
The only option it gives it to Exit the game.

This is on Minecraft 1.18.2 singleplayer, using REI version 8.3.583 and Vinery 1.1.2
I can also submit this issue to Vinery, as I don't know which end of the combo is causing the issue.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[03:47:41] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException: Could not create REI Plugin [REIPlugin] due to errors, provided by 'vinery'!
[03:47:41] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:114)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:139)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:172)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy48.onInitialize(Unknown Source)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:452)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:197)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[03:47:41] [Render thread/INFO]: [STDERR]: Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'rei_client' provided by 'vinery'
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:85)
[03:47:41] [Render thread/INFO]: [STDERR]: 	... 14 more
[03:47:41] [Render thread/INFO]: [STDERR]: Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: daniking.vinery.compat.rei.VineryReiClientPlugin
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
[03:47:41] [Render thread/INFO]: [STDERR]: 	... 15 more
[03:47:41] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: daniking.vinery.compat.rei.VineryReiClientPlugin
[03:47:41] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName0(Native Method)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName(Class.java:467)
[03:47:41] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
[03:47:41] [Render thread/INFO]: [STDERR]: 	... 17 more
[03:47:41] [Render thread/ERROR]: Could not create REI Plugin [REIPlugin] due to errors, provided by 'vinery'!
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
This is caused by Vinery, please report the issue to them
