### ISSUE TITLE
[Bug] Timeout on Search Preparation

### ISSUE THREAD

**Issue by briarss** [shedaniel/RoughlyEnoughItems#1317]
### What happened?

Trying to connect to a server but get timed out when REI is loading plugins.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: java.util.concurrent.TimeoutException
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.prepareFilter(Argument.java:376)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.resetCache(Argument.java:98)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.REIRuntimeImpl.endReload(REIRuntimeImpl.java:275)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:373)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$28(RoughlyEnoughItemsCoreClient.java:525)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Getting tooltips
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Getting tooltips
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.util.CrashReportUtils.throwReport(CrashReportUtils.java:68)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:236)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:90)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:75)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:45)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.lambda$prepareFilter$4(Argument.java:343)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	... 3 more
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 5
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at it.unimi.dsi.fastutil.objects.ReferenceOpenHashSet.rehash(ReferenceOpenHashSet.java:844)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at it.unimi.dsi.fastutil.objects.ReferenceOpenHashSet.add(ReferenceOpenHashSet.java:405)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_5131.method_26845(class_5131.java:34)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_1324.method_26838(class_1324.java:91)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_1324.method_26831(class_1324.java:169)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_5132.method_26863(class_5132.java:50)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_5131.md4c3dc9$lambda$data_getCustomInstance$0$2(class_5131.java:1557)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_5131.handler$fpn000$data_getCustomInstance(class_5131.java:1557)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_5131.method_26842(class_5131.java)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_1309.method_5996(class_1309.java:1894)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_1799.playerex_modifyValue(class_1799.java:18673)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_1799.localvar$gop000$playerex_modifyAttackDamage(class_1799.java:18699)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7950(class_1799.java:750)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:225)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:370)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:211)
[14:27:43] [REI-ReloadPlugins/INFO]: [STDERR]: 	... 8 more
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by firyy** [comment]
I'm having exactly the same error, any ideas?
