### ISSUE TITLE
[Bug][1.18.2Fabric]Failed to prepare input method

### ISSUE THREAD

**Issue by Xiepohe** [shedaniel/RoughlyEnoughItems#1320]
### What happened?

When changing the IME to Pingying or others,the loding screen of initializing IME shows up less than a second then back to game

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[01:21:21] [pool-72-thread-1/ERROR]: [REI] Failed to prepare input method
java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.io.EOFException: Unexpected end of ZLIB input stream
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) [?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: java.io.EOFException: Unexpected end of ZLIB input stream
	at org.apache.commons.io.LineIterator.hasNext(LineIterator.java:108) ~[commons-io-2.11.0.jar:?]
	at me.shedaniel.rei.impl.client.search.method.unihan.UniHanManager.read(UniHanManager.java:112) ~[RoughlyEnoughItems-8.3.583.jar:?]
	at me.shedaniel.rei.impl.client.search.method.unihan.UniHanManager.load(UniHanManager.java:105) ~[RoughlyEnoughItems-8.3.583.jar:?]
	at me.shedaniel.rei.impl.client.search.method.unihan.UniHanInputMethod.load(UniHanInputMethod.java:66) ~[RoughlyEnoughItems-8.3.583.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 4 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244) ~[?:?]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:?]
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
	at org.apache.commons.io.LineIterator.hasNext(LineIterator.java:96) ~[commons-io-2.11.0.jar:?]
	at me.shedaniel.rei.impl.client.search.method.unihan.UniHanManager.read(UniHanManager.java:112) ~[RoughlyEnoughItems-8.3.583.jar:?]
	at me.shedaniel.rei.impl.client.search.method.unihan.UniHanManager.load(UniHanManager.java:105) ~[RoughlyEnoughItems-8.3.583.jar:?]
	at me.shedaniel.rei.impl.client.search.method.unihan.UniHanInputMethod.load(UniHanInputMethod.java:66) ~[RoughlyEnoughItems-8.3.583.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 4 more
```

### Anything else?

[minecraft-exported-logs-2023-01-12T01-22-23.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10394635/minecraft-exported-logs-2023-01-12T01-22-23.log)

https://user-images.githubusercontent.com/103975855/211876886-783d0704-5e64-44b0-ad1d-e9f8560442b5.mp4

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Can you see if you can [download this zip](https://shedaniel.moe/qntrML0EraNB.zip)?

**Comment by shedaniel** [comment]
I am closing the issue because the question was not answered and this issue has became stale. Please re-open this issue if it persists.
