### ISSUE TITLE
[Bug] Crash randomly after adding REI.

### ISSUE THREAD

**Issue by HySand** [shedaniel/RoughlyEnoughItems#1326]
### What happened?

Crash randomly after joining world.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 257
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1334)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:279)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:500)
	at net.minecraft.class_377.method_2011(class_377.java:137)
	at net.minecraft.class_327.method_27516(class_327.java:57)
	at net.minecraft.class_5225.method_27492(class_5225.java:50)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27473(class_5223.java:120)
	at net.minecraft.class_5223.method_27472(class_5223.java:84)
	at net.minecraft.class_5223.method_27470(class_5223.java:128)
	at net.minecraft.class_5348$2.method_27658(class_5348.java:37)
	at net.minecraft.class_2588.method_27660(class_2588.java:135)
	at net.minecraft.class_2561.method_27658(class_2561.java:95)
	at net.minecraft.class_5223.method_27476(class_5223.java:128)
	at net.minecraft.class_5225.method_27488(class_5225.java:49)
	at net.minecraft.class_327.method_27525(class_327.java:368)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderer.renderText(TitleRenderer.java:92)
	at com.yungnickyoung.minecraft.travelerstitles.render.TitleRenderManager.renderTitles(TitleRenderManager.java:71)
	at net.minecraft.class_329.handler$fdh000$onClientTick(class_329.java:9977)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
```

### Anything else?

Some Mod textures aren't rendered correctly.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by HySand** [comment]
#https://github.com/FTBTeam/FTB-Mods-Issues/issues/630
