### ISSUE TITLE
[Bug] Game not starting in the latest REI version for 1.19.2

### ISSUE THREAD

**Issue by itsMarkiS** [shedaniel/RoughlyEnoughItems#1338]
### What happened?

basically the game is not starting and it says it cause of REI,
im using "RoughlyEnoughItems-9.1.585" for 1.19.2 in Fabric

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.shedaniel.rei.impl.client.REIRuntimeImpl.getOverlay(REIRuntimeImpl.java:162)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$16(RoughlyEnoughItemsCoreClient.java:343)
	at net.minecraft.class_437.handler$zfj000$postInit(class_437.java:1272)
	at net.minecraft.class_437.method_25423(class_437.java:384)
	at net.minecraft.class_310.method_1507(class_310.java:1035)
	at net.minecraft.class_310.<init>(class_310.java:668)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at me.shedaniel.rei.impl.client.REIRuntimeImpl.getOverlay(REIRuntimeImpl.java:160)
	... 10 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:901)
	at me.shedaniel.rei.impl.client.gui.widget.hint.HintsContainerWidget.read(HintsContainerWidget.java:84)
	at me.shedaniel.rei.impl.client.gui.widget.hint.HintsContainerWidget.<init>(HintsContainerWidget.java:52)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.<init>(ScreenOverlayImpl.java:94)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplFabric.<init>(ScreenOverlayImplFabric.java:43)
	... 16 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 22 more
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by itsMarkiS** [comment]
removing the mod, the game starts well and everything works fine...

**Comment by shedaniel** [comment]
Can you try deleting your config/roughlyenoughitems folder

**Comment by itsMarkiS** [comment]
seems it have worked.. which is weird
