### ISSUE TITLE
[Bug] Freezing 

### ISSUE THREAD

**Issue by scully06** [shedaniel/RoughlyEnoughItems#1358]
### What happened?

When I open Inventory with REI on, game get freeze.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
latest.log
[14:25:36] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.13
[14:25:36] [main/INFO]: Loading 75 mods:
	- architectury 4.11.89
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.4.90
	- error_notifier 1.0.9 via roughlyenoughitems
	- fabric-api 0.67.1+1.18.2
	- fabric-api-base 0.4.5+64b7c69360 via fabric-api
	- fabric-api-lookup-api-v1 1.6.3+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.10+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.9+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.24+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.2+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.2+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.3+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.21+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.9+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.20+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.21+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.1+a6f01b2660 via fabric-api
	- fabric-item-groups-v0 0.3.15+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-lifecycle-events-v1 2.1.1+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.1+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.3+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.5+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.7+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.24+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.11+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.4+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.13+526dc1ac60 via fabric-api
	- fabric-registry-sync-v0 0.9.12+bb2e047760 via fabric-api
	- fabric-renderer-api-v1 0.4.16+ee3621fc60 via fabric-api
	- fabric-renderer-indigo 0.5.6+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.14+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.8+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.11+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.3+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.13+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.4+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.13
	- java 17
	- minecraft 1.18.2
	- org_joml_joml 1.10.4 via vulkanmod
	- org_lwjgl_lwjgl 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-glfw 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-glfw_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-glfw_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-openal 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-openal_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-openal_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-shaderc 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-stb 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-stb_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-stb_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vma 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vma_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vma_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vulkan 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl_natives-windows 3.3.1 via vulkanmod
	- roughlyenoughitems 8.3.588
	- vulkanmod 0.2.2
[14:25:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/morob/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:25:37] [main/INFO]: Compatibility level set to JAVA_16
[14:25:37] [main/INFO]: Compatibility level set to JAVA_17
[14:25:52] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[14:25:54] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:25:57] [Render thread/INFO]: Setting user: scully05
[14:26:03] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[14:26:03] [Render thread/INFO]: [REI] Config loaded
[14:26:04] [Render thread/INFO]: Registering S2C receiver with id roughlyenoughitems:request_tags_s2c
[14:26:04] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider HideIngredientsFromTagsPlugin [roughlyenoughitems] for REIPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[14:26:04] [Render thread/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[14:26:04] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[14:26:04] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[14:26:04] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[14:26:04] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[14:26:04] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[14:26:04] [Render thread/INFO]: == VulkanMod ==
[14:26:05] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[14:26:05] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[14:26:06] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIClientPlugin
[14:26:06] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIClientPlugin
[14:26:06] [Render thread/INFO]: [REI] Registered plugin provider HideIngredientsFromTagsPlugin [roughlyenoughitems] for REIClientPlugin
[14:26:06] [Render thread/INFO]: Registering S2C receiver with id roughlyenoughitems:ci_msg
[14:26:06] [Render thread/INFO]: Registering S2C receiver with id roughlyenoughitems:og_not_enough
[14:26:07] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[14:26:08] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[14:26:15] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[14:26:20] [Render thread/INFO]: Narrator library for x64 successfully loaded
[14:26:20] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Cloth Config v6, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Roughly Enough Items, VulkanMod)
[14:26:22] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on スピーカー (Realtek USB2.0 Audio)
[14:26:22] [Render thread/INFO]: Sound engine started
[14:26:22] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[14:26:22] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[14:26:22] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[14:26:22] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[14:26:22] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[14:26:22] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[14:26:22] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:26:23] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:26:23] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:26:23] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:26:29] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:26:29] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:26:29] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:26:29] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:26:29] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:26:29] [Render thread/INFO]: Loaded 7 recipes
[14:26:29] [Render thread/INFO]: Loaded 1141 advancements
[14:26:30] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:26:30] [Render thread/INFO]: Applied 0 biome modifications to 0 of 61 new biomes in 1.764 ms
[14:26:30] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[14:26:30] [Server thread/INFO]: Generating keypair
[14:26:30] [Render thread/INFO]: [STDOUT]: resized DescriptorPool to: 1000
[14:26:30] [Render thread/INFO]: [STDOUT]: resized DescriptorPool to: 2000
[14:26:30] [Render thread/INFO]: [STDOUT]: resized UniformBuffer to: 400128
[14:26:30] [Render thread/INFO]: [STDOUT]: resized DescriptorPool to: 4000
[14:26:30] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:26:31] [Render thread/INFO]: スポーン地点を準備中：0%
[14:26:31] [Render thread/INFO]: スポーン地点を準備中：0%
[14:26:31] [Render thread/INFO]: スポーン地点を準備中：0%
[14:26:32] [Render thread/INFO]: スポーン地点を準備中：0%
[14:26:32] [Render thread/INFO]: スポーン地点を準備中：0%
[14:26:33] [Render thread/INFO]: スポーン地点を準備中：2%
[14:26:33] [Render thread/INFO]: スポーン地点を準備中：2%
[14:26:34] [Render thread/INFO]: スポーン地点を準備中：10%
[14:26:34] [Render thread/INFO]: スポーン地点を準備中：10%
[14:26:35] [Render thread/INFO]: スポーン地点を準備中：34%
[14:26:35] [Render thread/INFO]: スポーン地点を準備中：41%
[14:26:36] [Render thread/INFO]: スポーン地点を準備中：48%
[14:26:36] [Render thread/INFO]: スポーン地点を準備中：53%
[14:26:37] [Render thread/INFO]: スポーン地点を準備中：58%
[14:26:37] [Render thread/INFO]: スポーン地点を準備中：62%
[14:26:38] [Render thread/INFO]: スポーン地点を準備中：67%
[14:26:38] [Render thread/INFO]: スポーン地点を準備中：76%
[14:26:39] [Render thread/INFO]: スポーン地点を準備中：85%
[14:26:39] [Render thread/INFO]: Time elapsed: 8908 ms
[14:26:39] [Server thread/INFO]: Changing view distance to 12, from 10
[14:26:39] [Server thread/INFO]: Changing simulation distance to 12, from 0
[14:26:40] [Server thread/INFO]: scully05[local:E:b17ad46e] logged in with entity id 125 at (1498.2527360339268, 92.0, -108.17419830489989)
[14:26:40] [Server thread/INFO]: scully05がゲームに参加しました
[14:26:40] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [START], registered 6 plugins: DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:26:40] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [START], registered 3 plugins: DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:26:41] [Render thread/INFO]: [REI] Refreshing cached entry list texture...
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [START], registered 3 plugins: DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 6 plugins in 109.8 ms.
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 3 plugins in 337.0 ms.
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 3 plugins in 3.128 ms.
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [END], registered 6 plugins: DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [END], registered 3 plugins: DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems], HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems], DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[14:26:41] [Render thread/INFO]: [REI] Refreshing cached entry list texture...
[14:26:41] [Render thread/INFO]: Loaded 26 advancements
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [END], registered 3 plugins: DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 6 plugins in 83.90 ms.
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 3 plugins in 427.0 ms.
[14:26:41] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 3 plugins in 20.13 ms.
[14:26:43] [Render thread/INFO]: [REI] Preparing cached texture with size 2432x2432 for 38x38 entries
[14:26:43] [Render thread/INFO]: [STDOUT]: resized DescriptorPool to: 1000
[14:26:44] [Render thread/INFO]: [STDOUT]: resized DescriptorPool to: 1000
[14:26:44] [Render thread/INFO]: [STDOUT]: resized UniformBuffer to: 800640
[14:26:44] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: Failed to submit draw command buffer: -4
	at net.vulkanmod.vulkan.Drawer.drawFrame(Drawer.java:339) ~[VulkanMod_1.18.2-0.2.2.jar:?]
	at net.vulkanmod.vulkan.Drawer.submitDraw(Drawer.java:127) ~[VulkanMod_1.18.2-0.2.2.jar:?]
	at net.minecraft.class_310.handler$znc000$submitRender(class_310.java:7004) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1147) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.13.jar:?]
```

### Anything else?

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10703967/rei.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Incompatibilities with vulkanmod
