### ISSUE TITLE
[Bug] Index out of bounds in Rendering Screen

### ISSUE THREAD

**Issue by Tiefseetauchner** [shedaniel/RoughlyEnoughItems#1360]
### What happened?

Random occasional crashes, most often when opening an inventory (but not consistently)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I just don't know what went wrong :(
Time: 2023-02-12 12:57:33
Description: Rendering screen
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1334)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:279)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:500)
	at net.minecraft.class_377.method_2011(class_377.java:137)
	at net.minecraft.class_327.method_27516(class_327.java:57)
	at net.minecraft.class_5225$class_5227.accept(class_5225.java:256)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27473(class_5223.java:120)
	at net.minecraft.class_5225.method_29971(class_5225.java:491)
	at net.minecraft.class_5225.method_27495(class_5225.java:463)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplFabric.lambda$renderTooltipInner$0(ScreenOverlayImplFabric.java:49)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplFabric.renderTooltipInner(ScreenOverlayImplFabric.java:57)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:327)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$lateRender$3(ScreenOverlayImpl.java:318)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:318)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$24(RoughlyEnoughItemsCoreClient.java:454)
	at net.minecraft.class_757.handler$zkh000$renderScreenPost(class_757.java:16611)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1334)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:279)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:500)
	at net.minecraft.class_377.method_2011(class_377.java:137)
	at net.minecraft.class_327.method_27516(class_327.java:57)
	at net.minecraft.class_5225$class_5227.accept(class_5225.java:256)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27473(class_5223.java:120)
	at net.minecraft.class_5225.method_29971(class_5225.java:491)
	at net.minecraft.class_5225.method_27495(class_5225.java:463)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplFabric.lambda$renderTooltipInner$0(ScreenOverlayImplFabric.java:49)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplFabric.renderTooltipInner(ScreenOverlayImplFabric.java:57)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:327)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$lateRender$3(ScreenOverlayImpl.java:318)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:318)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$24(RoughlyEnoughItemsCoreClient.java:454)
	at net.minecraft.class_757.handler$zkh000$renderScreenPost(class_757.java:16611)
-- Screen render details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
	Mouse location: Scaled: (527, 113). Absolute: (1582.000000, 339.000000)
	Screen size: Scaled: (683, 360). Absolute: (2048, 1079). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Affected level --
Details:
	All players: Never mind this :)
	Chunk stats: 1024, 472 F: 591 L: 0 U: 33
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,70,16), Section: (at 0,6,0 in 3,4,1; chunk contains blocks 48,-64,16 to 63,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1754888 game time, 1880252 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, VanillaTweaks_r179796.zip, Fabric Mods, replaymod_lang
-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.19.0-31-generic
	Java Version: 17.0.4.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 2721480664 bytes (2595 MiB) / 5721030656 bytes (5456 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD (No, what, it's authentic?! I didn't know there's unauthentic AMDs as well, gotta look out for those now!)
	Processor Name: AMD Ryzen Threadripper 2950X 16-Core Processor
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 32
	Graphics card #0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 46492.71
	Virtual memory used (MB): 14918.81
	Swap memory total (MB): 30517.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Fabric Mods: 
		alternate-current: Alternate Current 1.4.0
		architectury: Architectury 6.5.69
		betterf3: BetterF3 4.0.0
		bobby: Bobby 4.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		capes: Capes 1.4.5+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		clickthrough: ClickThrough 1.19.1-fabric0.58.5-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.1+1.19
		create: Create 0.5.0.i-946+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-4
			forgeconfigapiport: Forge Config API Port 4.2.9
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.766+1.19.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				forge_tags: Porting Lib Tags 3.0
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 2.1.766+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.766+1.19.2
				porting_lib_base: Porting Lib Base 2.1.766+1.19.2
				porting_lib_common: Porting Lib Common 2.1.766+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.766+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.766+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.766+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.766+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.766+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.766+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.766+1.19.2
				porting_lib_models: Porting Lib Models 2.1.766+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.766+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.766+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.766+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.50-MC1.19.2
		cullleaves: Cull Leaves 3.0.1
			midnightlib: MidnightLib 1.0.0
		dcch: DCCH 2.0+1.17
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easiervillagertrading: EasierVillagerTrading 1.19.1-fabric0.58.5-1.5.4
			gbfabrictools: GBfabrictools 1.3.4+1.19
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.24+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		fabrizoom: FabriZoom 1.2.1
			com_google_guava_guava: guava 31.1-jre
			org_spongepowered_configurate-extra-kotlin: configurate-extra-kotlin 4.1.2
			yet-another-config-lib: YetAnotherConfigLib 1.5.0
		ferritecore: FerriteCore 5.0.3
		indium: Indium 1.0.9+mc1.19.2
		inventoryhud: Inventory HUD + 3.4.7
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.3
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.12.6
		lithium: Lithium 0.10.4
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.1.2
		mousewheelie: Mouse Wheelie 1.10.7+mc1.19.2
			amecsapi: Amecs API 1.3.7+mc22w17a
			coat: Coat 1.0.0-beta.19+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc22w17a
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		puzzle: Puzzle 1.4.2-1.19
			puzzle-base: Puzzle Base 1.4.2-1.19
			puzzle-gui: Puzzle GUI 1.4.2-1.19
			puzzle-models: Puzzle Models 1.4.2-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		replaymod: Replay Mod 1.19.2-2.6.9
		roughlyenoughitems: Roughly Enough Items 9.1.587
			error_notifier: Error Notifier 1.0.9
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		tweakeroo: Tweakeroo 0.14.3
		visuality: Visuality 0.5.5
		voicechat: Simple Voice Chat 1.19.2-2.3.28
		waveycapes: WaveyCapes 1.3.0
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		worldeditcui: WorldEditCUI 1.19.2+01
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 580 Series (polaris10, LLVM 14.0.6, DRM 3.47, 5.19.0-31-generic) GL version 4.6 (Core Profile) Mesa 22.3.2 (git-a09d5e2747), AMD
	Window size: 2048x1079
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=2, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='0:22(24): warning: `FragDistance' used uninitialized' x 1
id=3, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='0:21(24): warning: `FragDistance' used uninitialized' x 1
	Using VBOs: Yes
	Is Modded: Definitely (No shit!); Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy - No you're fancy :3
	Resource Packs: vanilla, file/VanillaTweaks_r179796.zip, Fabric Mods
	Current Language: English (US)
	CPU: 32x AMD Ryzen Threadripper 2950X 16-Core Processor
```

### Anything else?

Randomly occuring, can't find a pattern...

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Noaaan** [comment]
Players on my server have been experiencing this same issue. Turns out it is a vanilla bug with FastUtil. There are some mods out there to fix this, like BugJump: https://modrinth.com/mod/bugjump
