### ISSUE TITLE
[Bug] Rei doesn't show up on a server unless you load a single player world first

### ISSUE THREAD

**Issue by Trinsdar** [shedaniel/RoughlyEnoughItems#1395]
### What happened?

Whenver I load into a server, it is hidden till you load a single player world, then if you log back into the server it shows up

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [x] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[20:22:05] [Render thread/WARN] [ModernFix/]: Game took 16.407 seconds to start
[20:22:05] [Render thread/WARN] [AE2:C/]: Unable to find class com.simibubi.create.foundation.ponder.PonderWorld. Integration with PonderJS disabled.
[20:22:05] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [fastleafdecay] Found status: UP_TO_DATE Current: 28 Target: null
[20:22:05] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [twilightforest] Starting version check at https://gh.tamaized.com/TeamTwilight/twilightforest/update.json
[20:22:05] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [twilightforest] Found status: UP_TO_DATE Current: 4.1.1494 Target: null
[20:22:42] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:22:42] [Render thread/INFO] [mojang/YggdrasilUserAuthentication]: Environment: PROD
[20:22:42] [Netty Client IO #0/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Server has additional mods that may be needed on the client: notenoughcrashes@4.2.0+1.18.2, connectivity@, jei@9.9999, rei_plugin_compatibilities@8.0.46
[20:22:42] [Netty Client IO #0/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [ftbchunks]
[20:22:42] [Netty Client IO #1/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Server has additional mods that may be needed on the client: jei@9.9999, rei_plugin_compatibilities@8.0.46
[20:22:42] [Netty Client IO #1/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [ftbchunks]
[20:22:44] [Render thread/INFO] [minecraft/ConnectScreen]: Connecting to localhost, 25565
[20:22:46] [Netty Epoll Client IO #0/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[20:22:46] [Netty Epoll Client IO #0/INFO] [ne.mi.ne.NetworkHooks/]: Connected to a modded server.
[20:22:46] [Render thread/INFO] [ChunkBuilder/]: Started 6 worker threads
[20:22:46] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:22:47] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client
java.lang.IllegalArgumentException: initialArraySize cannot be negative but was: -1
	at com.google.common.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:40) ~[guava-31.0.1-jre.jar%2318!/:?] {}
	at com.google.common.collect.Lists.newArrayListWithCapacity(Lists.java:178) ~[guava-31.0.1-jre.jar%2318!/:?] {re:mixin}
	at net.minecraft.network.FriendlyByteBuf.m_178371_(FriendlyByteBuf.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading,re:mixin}
	at net.minecraft.network.FriendlyByteBuf.m_178366_(FriendlyByteBuf.java:135) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading,re:mixin}
	at muramasa.antimatter.recipe.ingredient.RecipeIngredient.fromNetwork(RecipeIngredient.java:117) ~[AntimatterAPI-forge-0.2-rc3-1.18.2.jar%2355!/:0.2-rc3-1.18.2] {re:mixin,re:classloading,pl:mixin:APP:antimatter-forge.mixins.json:RecipeIngredientMixin,pl:mixin:A}
	at muramasa.antimatter.recipe.serializer.AntimatterRecipeSerializer.fromNetwork(AntimatterRecipeSerializer.java:148) ~[AntimatterAPI-forge-0.2-rc3-1.18.2.jar%2355!/:0.2-rc3-1.18.2] {re:mixin,re:classloading,pl:mixin:APP:antimatter-forge.mixins.json:AntimatterRecipeSerializerMixin,pl:mixin:A}
	at muramasa.antimatter.recipe.serializer.AntimatterRecipeSerializer.m_8005_(AntimatterRecipeSerializer.java:38) ~[AntimatterAPI-forge-0.2-rc3-1.18.2.jar%2355!/:0.2-rc3-1.18.2] {re:mixin,re:classloading,pl:mixin:APP:antimatter-forge.mixins.json:AntimatterRecipeSerializerMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_133647_(ClientboundUpdateRecipesPacket.java:45) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading,re:mixin}
	at net.minecraft.network.FriendlyByteBuf.m_178371_(FriendlyByteBuf.java:119) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading,re:mixin}
	at net.minecraft.network.FriendlyByteBuf.m_178366_(FriendlyByteBuf.java:135) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading,re:mixin}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading,re:mixin}
	at net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:419) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading}
	at net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:471) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading}
	at net.minecraftforge.network.filters.VanillaPacketSplitter.onClientPacket(VanillaPacketSplitter.java:146) ~[forge-1.18.2-40.1.80-universal.jar%23103!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.80-universal.jar%23103!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.1.80-universal.jar%23103!/:?] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.1.80-universal.jar%23103!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1824) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rei.mixins.json:MixinClientPacketListener,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientPlayNetworkHandler,pl:mixin:APP:journeymap.mixins.json:client.ClientPacketListenerMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ClientPacketListenerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:oauth.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:core.MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:oauth.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:core.MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2398!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.80.jar%2351!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?] {}
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?] {}
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?] {}
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?] {}
[20:22:47] [Render thread/INFO] [antimatter/]: Compiling GT recipes
[20:22:47] [Render thread/INFO] [antimatter/]: Time to compile GT recipes: (ms) 0
[20:22:47] [Render thread/INFO] [antimatter/]: No. of GT recipes: 0
[20:22:47] [Render thread/INFO] [antimatter/]: Average loading time / recipe: (µs) 473
[20:22:47] [Render thread/INFO] [journeymap/]: World UID is set to: 640baf26-c9b6-4492-a6a1-e42ddab620f9
[20:22:47] [Render thread/INFO] [FTB Chunks/]: Loading FTB Chunks client data from world 6f2dbd3a-623f-4aab-bb53-e4c942f97b62
[20:22:47] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 11 advancements
[20:22:47] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Cannot modify immutable buffer.'
[20:22:47] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[20:22:47] [Render thread/INFO] [ChunkBuilder/]: Started 6 worker threads
[20:22:48] [Render thread/INFO] [journeymap/]: Loaded 0 waypoints from /home/trinsdar/.local/share/multimc/instances/mod-testing/.minecraft/journeymap/data/mp/Minecraft~Server_640baf26~c9b6~4492~a6a1~e42ddab620f9/waypoints
[20:22:48] [Render thread/INFO] [journeymap/]: Mapping started in /home/trinsdar/.local/share/multimc/instances/mod-testing/.minecraft/journeymap/data/mp/Minecraft~Server_640baf26~c9b6~4492~a6a1~e42ddab620f9/overworld. Memory: 1280MB total, 452MB free 
[20:22:49] [Render thread/INFO] [minecraft/ChatComponent]: [CHAT] JourneyMap: Press [J]
[20:22:49] [Render thread/INFO] [journeymap/]: 
[20:23:39] [Render thread/INFO] [journeymap/]: Mapping halted in /home/trinsdar/.local/share/multimc/instances/mod-testing/.minecraft/journeymap/data/mp/Minecraft~Server_640baf26~c9b6~4492~a6a1~e42ddab620f9/minecraft:overworld
[20:23:39] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Cannot modify immutable buffer.'
[20:23:39] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[20:23:39] [Netty Client IO #2/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Server has additional mods that may be needed on the client: notenoughcrashes@4.2.0+1.18.2, connectivity@, jei@9.9999, rei_plugin_compatibilities@8.0.46
[20:23:39] [Netty Client IO #2/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [ftbchunks]
[20:23:39] [Render thread/INFO] [journeymap/]: World ID has been reset.
[20:23:39] [Render thread/INFO] [journeymap/]: World UID is set to: null
[20:23:40] [Netty Client IO #3/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Server has additional mods that may be needed on the client: jei@9.9999, rei_plugin_compatibilities@8.0.46
[20:23:40] [Netty Client IO #3/INFO] [ne.mi.cl.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [ftbchunks]
```

### Anything else?

![2023-04-17_20 24 48](https://user-images.githubusercontent.com/30245301/232638159-6f6b3a34-379c-4987-8bee-f82898be80bf.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Trinsdar** [comment]
ok so update: seems it's something in antimatter causing this, not exactly sure what though, best guess is that recipe error above
