### ISSUE TITLE
[Bug] Crashed when opening the ae2 terminal

### ISSUE THREAD

**Issue by loong218-toast** [shedaniel/RoughlyEnoughItems#1452]
### What happened?

Using 1.20.1 minecraft. The game crashed when trying to open ae2 Terminal/Pattern Encoded Terminal by right clicking.

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'boolean me.shedaniel.rei.api.client.gui.widgets.TextField.isFocused()'

Able to reproduce with only these mods installed:
REI [Forge 1.20(.1)] v12.0.634
Cloth Config cloth-config-11.1.106-forge
Architechtury architectury-9.1.10-forge
AE2 appliedenergistics2-forge-15.0.5-beta.jar
Create create-1.20.1-0.5.1.d
Forge forge-47.0.35 (Later I tried the release version of forge which is forge-47.1.0, but still the same result)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
rei log: https://gist.github.com/loong218-toast/d03124d2a293ce279bb58f27e318d72a

latest log:

[04:13:59] [Server thread/INFO]: loongbreadd joined the game
[04:13:59] [Render thread/INFO]: Started 2 worker threads
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for START.
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] Plugins (6):
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for START.
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] Plugins (4):
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[04:13:59] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for START.
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] Plugins (2):
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] ++++++++++++++++++++++++++++++++++++++++
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for START in 1.986 ms, totaling 79.61 ms.
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 869.8 ?s, totaling 1.382 s.
[04:14:01] [Render thread/INFO]: Loaded 125 advancements
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for START in 463.6 ?s, totaling 4.223 ms.
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for END.
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] Plugins (6):
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] Plugins (4):
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[04:14:01] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[04:14:02] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[04:14:02] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for END.
[04:14:02] [REI-ReloadPlugins/INFO]: [REI] Plugins (2):
[04:14:02] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[04:14:02] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[04:14:02] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[04:14:02] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for END in 1.127 ms, totaling 132.7 ms.
[04:14:02] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 583.5 ?s, totaling 1.171 s.
[04:14:02] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for END in 372.6 ?s, totaling 19.03 ms.
[04:14:08] [Server thread/INFO]: Stopping server
[04:14:08] [Server thread/INFO]: Saving players
[04:14:08] [Server thread/INFO]: Saving worlds
[04:14:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[04:14:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[04:14:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[04:14:12] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/ae2:spatial_storage
[04:14:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[04:14:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[04:14:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[04:14:12] [Server thread/INFO]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[04:14:12] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[04:14:14] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.0.35.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.0.35.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.0.35.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.0.35.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoSuchMethodError: 'boolean me.shedaniel.rei.api.client.gui.widgets.TextField.isFocused()'
	at appeng.integration.modules.rei.ReiRuntimeAdapter.hasSearchFocus(ReiRuntimeAdapter.java:62) ~[appliedenergistics2-forge-15.0.5-beta.jar%23161!/:15.0.5-beta]
	at appeng.util.ExternalSearch.isExternalSearchFocused(ExternalSearch.java:38) ~[appliedenergistics2-forge-15.0.5-beta.jar%23161!/:15.0.5-beta]
	at appeng.client.gui.me.common.MEStorageScreen.updateSearch(MEStorageScreen.java:386) ~[appliedenergistics2-forge-15.0.5-beta.jar%23161!/:15.0.5-beta]
	at appeng.client.gui.me.common.MEStorageScreen.updateBeforeRender(MEStorageScreen.java:343) ~[appliedenergistics2-forge-15.0.5-beta.jar%23161!/:15.0.5-beta]
	at appeng.client.gui.me.items.PatternEncodingTermScreen.updateBeforeRender(PatternEncodingTermScreen.java:86) ~[appliedenergistics2-forge-15.0.5-beta.jar%23161!/:15.0.5-beta]
	at appeng.client.gui.AEBaseScreen.m_88315_(AEBaseScreen.java:237) ~[appliedenergistics2-forge-15.0.5-beta.jar%23161!/:15.0.5-beta]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.0.35-universal.jar%23171!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.0.35-universal.jar%23171!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?]
	... 18 more
[04:14:14] [Render thread/FATAL]: Preparing crash report with UUID 72d52341-528b-43df-b4d2-24e159992f06
[04:14:14] [Render thread/FATAL]: Preparing crash report with UUID fd31e89c-2c09-4bec-9499-4222f941fde5
```

### Anything else?

[crash-2023-07-19_04.14.14-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/12088707/crash-2023-07-19_04.14.14-client.txt)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Harveykang** [comment]
reproduced with Forge, AE2 15.0.11, REI 12.0.652, Minecraft 1.20.1.
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/46108547/ad433be3-7ff7-464a-9c8d-745bbf6b0946)
在发布的mod的class文件中，isFocused() 方法被混淆为了图中的名称，但并没有对应的混淆表，导致其他mod（比如AE2）找不到这个方法。
