### ISSUE TITLE
[Bug] REI not showing any items on server after update.  

### ISSUE THREAD

**Issue by Plisko1** [shedaniel/RoughlyEnoughItems#1464]
### What happened?

REI was working fine on my 1.19.3 Bisect Hosting server using some mod, including REI version 10.0.581 on Forge 44.1.0. 

I added some more mods and I also did a round of updates to the last versions for 1.19.3, including Forge to 44.1.23.  REI is now version 10.0.620, Architectury is 7.1.86 and Cloth config is 9.1.104.    The problem is, when anyone enters the server, there are no blocks or items in the REI interface on the right side.  If we leave the server and enter a single player game with the same modpack, the items are there in the REI interface.   When we go back into the server, the problem is corrected and we can use REI normally, but only for that game session.  if we quit the game and restart, the items are always gone when entering the server.  Everyone needs to do the single player game again to make REI work for each game session on the server.  Somehow, it is not registering ANY of the items when entering the server game world.  They need to be reached by the single player game first.

Attaching logs

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/12196119/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/12196120/rei.log)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Logs are attached
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by itsdinkd** [comment]
This issue is happening to my modpack as well on Fabric 1.19.2

**Comment by TheSnowyChickens** [comment]
Can confirm this, I was REALLY confused right now, because many recipes are just gone.
(Fabric, 1.19.2)

**Comment by Plisko1** [comment]
I have noticed that when I use my same modpack on Curseforge and log into the same server,  the problem mostly goes away.  It only happens occasionally and a simple relog clears it.  I got the modpack published on Curseforge and had one of our other members test it.  The problem went away for her as well.  Somehow this happens to modpacks set up as a custom profile through the Vanilla launcher.  I tried creating a new profile in the vanilla launcher but that didn't work.  It seems to need a whole new .minecraft folder to clear things up.

I don't know if that helps...

**Comment by Chrizzx3** [comment]
I had the same thing, though on fabric and a small amount of mods. The first time joining on a server is okay, but every log in afterwards presents the same bug. Reloading Plugins via the advanced tab solves this everytime though, so maybe some issue with either the plugin or a specific mod with the plugins?

**Comment by itsdinkd** [comment]
I think it's the newest rei version but either way can you share your
modlist

**Comment by Chrizzx3** [comment]
I can share the modlist! Minecraft 1.20.1, Fabric 0.14.22

![modlist](https://github.com/shedaniel/RoughlyEnoughItems/assets/92762855/cc4a591e-1fd1-4c18-9c77-6ceb32fa8330)

**Comment by itsdinkd** [comment]
For shedaniel..

here is the log in console that appears upon player joining server. Nothing in rei-issues unfortunately. 

```
java.lang.IllegalArgumentException: Packet too big (is 8434739, should be less than 8388608): net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket@782dd841
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:48) [server-intermediary.jar:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) [server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by itsdinkd** [comment]
> I can share the modlist! Minecraft 1.20.1, Fabric 0.14.22
> 
> ![modlist](https://user-images.githubusercontent.com/92762855/259244807-cc4a591e-1fd1-4c18-9c77-6ceb32fa8330.png)

what mods did you update when this started happening to you

Things we have in common;

architectury
lithium
sodium and sodium extra
toolstats
reeses sodium
modmenu
modernfix
xaeros
ipn
iris
ferritecore
falling leaves
cloth config
bookshelf.


The only related thing we have when i got this error is i added modern fix.

**Comment by itsdinkd** [comment]
Alright i discovered what caused it for my end at least. CC:Bridge. When in a server, it causes a huge packet breaking rei.

**Comment by waddon1** [comment]
I've also been getting this issue on Forge 1.20.1, I think I also narrowed it down to ModernFix being the cause.

**Comment by fandomaice** [comment]
Це проблема звязана скоріше завсе з шейдерами, не знаю чому но коли я видалив iris або oculus в мене rei працював стабільно

**Comment by jacklollz2** [comment]
Same thing happening to me, ModernFix is installed.

**Comment by melonacebear** [comment]
> Same thing happening to me, Quilt 1.20.1 on a server. ModernFix is installed. "Blast search trees" might be it, but I turned it off and it's still happening. I also forced it on, same thing. Empty REI and creative search not working.

Hi! idk if u still havent solved this yet, but mine were fix by unchecking the hide entries when hovering over the craftable filter icon (the crafting table icon between search bar and gear)

then reload the resource pack by f3 + t

note that everytime u disable craftable filter on the gear options, the items will disappear, u jut need to reload the resource pack with f3 + T

also turn on reduce motion if needed
