### ISSUE TITLE
[Bug] 输入法进度条一直卡在0%

### ISSUE THREAD

**Issue by 1753449579** [shedaniel/RoughlyEnoughItems#1469]
### What happened?

![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/90882660/5789993f-2f5f-4013-b8fc-7d745cc92dd2)

### What mod loaders are you seeing the problem on?

Fabric, Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[058月2023 14:23:44.951] [REI-ReloadPlugins/ERROR] [REI/]: [REI] JEI Plugin [SBPPlugin:sophisticatedbackpacks:default] of REI Plugin Compatibilities Adapter [rei_plugin_compatibilities, jei] plugin failed to reloadable-plugin/DisplayRegistryImpl/!
java.lang.NoClassDefFoundError: mezz/jei/library/util/RecipeUtil
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.copyShapedRecipe(ClientRecipeHelper.java:53) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableRecipes$0(ClientRecipeHelper.java:36) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableRecipes$1(ClientRecipeHelper.java:34) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.getAndTransformAvailableRecipes(ClientRecipeHelper.java:34) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.jei.SBPPlugin.registerRecipes(SBPPlugin.java:83) ~[%5Btest%5Dsophisticatedbackpacks-1.20.1-3.18.56.890.jar%23205!/:1.20.1-3.18.56.890]
	at me.shedaniel.rei.plugincompatibilities.wYei0QiIcjX.jhSZPBSOFea.registerDisplays(JEIPluginDetector.java:545) ~[REIPluginCompatibilities-forge-12.0.55.jar%23230!/:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:65) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:51) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:387) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:377) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:375) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:160) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:482) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: mezz.jei.library.util.RecipeUtil
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 25 more
[058月2023 14:23:45.078] [REI-ReloadPlugins/ERROR] [REI/]: [REI] JEI Plugin [CorePlugin:sophisticatedcore:default] of REI Plugin Compatibilities Adapter [rei_plugin_compatibilities, jei] plugin failed to reloadable-plugin/DisplayRegistryImpl/!
java.lang.NoClassDefFoundError: mezz/jei/library/util/RecipeUtil
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.copyShapedRecipe(ClientRecipeHelper.java:53) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableRecipes$0(ClientRecipeHelper.java:36) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableRecipes$1(ClientRecipeHelper.java:34) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.getAndTransformAvailableRecipes(ClientRecipeHelper.java:34) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.CorePlugin.registerRecipes(CorePlugin.java:22) ~[%5Btest%5Dsophisticatedcore-1.20.1-0.5.83.395.jar%23206!/:1.20.1-0.5.83.395]
	at me.shedaniel.rei.plugincompatibilities.wYei0QiIcjX.jhSZPBSOFea.registerDisplays(JEIPluginDetector.java:545) ~[REIPluginCompatibilities-forge-12.0.55.jar%23230!/:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:65) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:51) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:387) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:377) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:375) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:160) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:482) ~[RoughlyEnoughItems-12.0.634.jar%23231!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: mezz.jei.library.util.RecipeUtil
	... 25 more
[058月2023 14:23:45.328] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...
[058月2023 14:23:45.351] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[058月2023 14:23:45.698] [REI-ReloadPlugins/INFO] [REI/]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[058月2023 14:23:45.698] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIServerPlugin starting main-reload for END.
[058月2023 14:23:45.699] [REI-ReloadPlugins/INFO] [REI/]: [REI] Plugins (3):
[058月2023 14:23:45.699] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[058月2023 14:23:45.699] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) REI Plugin Compatibilities Server Handler of REI Plugin Compatibilities Server Handler [rei_plugin_compatibilities, jei]
[058月2023 14:23:45.699] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[058月2023 14:23:45.699] [REI-ReloadPlugins/INFO] [REI/]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[058月2023 14:23:45.714] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIPlugin finished post-reload for END in 1.199 ms, totaling 48.72 ms.
[058月2023 14:23:46.116] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIClientPlugin finished post-reload for END in 399.9 ms, totaling 1.435 s.
[058月2023 14:23:46.118] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIServerPlugin finished post-reload for END in 286.7 μs, totaling 14.02 ms.
[058月2023 14:23:46.128] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[058月2023 14:23:46.130] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[058月2023 14:23:55.431] [Render thread/WARN] [xaero.common.MinimapLogs/]: Render engine used for entities is not fully compatible with the minimap entity icons. Using fallback. class xaero.common.minimap.render.radar.EntityIconModelPartsRenderer$VertexConsumerWrapper cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (xaero.common.minimap.render.radar.EntityIconModelPartsRenderer$VertexConsumerWrapper is in module xaerominimap@23.6.0 of loader 'TRANSFORMER' @5cfa2ac5; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @5cfa2ac5)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
This is caused by bad Internet, the initialisation of the IME is downloading a 8MB pinyin file.
