### ISSUE TITLE
[Bug] REI Disappears due to Packet too big

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#1475]
### What happened?

I use Extra Thicc Packets so cant see how this would ever be an issue. Though, it seems like its entirely different than what Extra Thicc/XL packets does.

Randomly, when you join a server now using AQM2 modpack, you will no longer see REI until you either Reload Plugins, or join a single player session.

You are seen with a REI error in chat that says to check logs and Server cannot sync with Client.

This is what is in console

```java
[05:41:43] [Netty Epoll Server IO #3/ERROR]: Error receiving packet 106
java.lang.IllegalArgumentException: Packet too big (is 8416522, should be less than 8388608): net.minecraft.class_2788@2b21a21d
        at net.minecraft.class_2545.method_10838(class_2545.java:48) [server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:14) [server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

I've tried downgrading mods, removing mods added, downgrading REI, nothing worked. 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Server Log: https://mclo.gs/PzKaiRP 
Client Log: https://gist.github.com/itsdinkd/f5fd26b79a8a9e7f6562a99f7ebaafcf

Client REI Log: https://gist.github.com/itsdinkd/31d226befa0828590364ecdd3857f22b
Server REI Log: https://gist.github.com/itsdinkd/80f859ed3b0bbccefb85a88cf14866bf
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
There is nothing REI can do about this issue, you can try to solve this issue by using XL Packets or XL Packets Fabric.
