### ISSUE TITLE
[Bug] Game freeze for seconds when looking for a recipe

### ISSUE THREAD

**Issue by Zenthae** [shedaniel/RoughlyEnoughItems#1481]
### What happened?

Whenever I look at a recipe, (r or left click), the game hang for around 2 seconds.
Same behavior for every item.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[Render thread/ERROR]: Throwing
net.minecraft.class_148: Error while generating recipes for an entry stack
	at me.shedaniel.rei.impl.client.view.ViewsImpl$1.getRecipeFor(ViewsImpl.java:394) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.view.ViewsImpl.generateLiveDisplays(ViewsImpl.java:354) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.view.ViewsImpl._buildMapFor(ViewsImpl.java:198) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.view.ViewsImpl.buildMapFor(ViewsImpl.java:92) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.ClientHelperImpl$ViewSearchBuilderImpl.lambda$new$0(ClientHelperImpl.java:397) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar:?]
	at me.shedaniel.rei.impl.client.ClientHelperImpl$ViewSearchBuilderImpl.buildMapInternal(ClientHelperImpl.java:470) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.ClientHelperImpl.openView(ClientHelperImpl.java:329) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.api.client.view.ViewSearchBuilder.open(ViewSearchBuilder.java:228) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.keyPressedIgnoreContains(EntryWidget.java:691) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.DisplayedEntryWidget.keyPressedIgnoreContains(DisplayedEntryWidget.java:127) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25404(EntryWidget.java:664) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25404(EntryListWidget.java:236) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25404(ScreenOverlayImpl.java:387) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.gui.screen.AbstractDisplayViewingScreen.method_25404(AbstractDisplayViewingScreen.java:420) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25404(DefaultDisplayViewingScreen.java:142) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at net.minecraft.client.Keyboard.method_1454(Keyboard.java:374) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:489) ~[client-intermediary.jar:?]
	at net.minecraft.client.Keyboard.onKey(Keyboard.java:370) ~[client-intermediary.jar:?]
	at net.minecraft.client.Keyboard.method_22678(Keyboard.java:462) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.client.Keyboard.method_22676(Keyboard.java:462) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) [lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) [lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) [client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:315) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1205) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.IllegalAccessError: class dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedQuestCache tried to access private field dev.ftb.mods.ftbquests.quest.Chapter.quests (dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedQuestCache and dev.ftb.mods.ftbquests.quest.Chapter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c0f93f1)
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedQuestCache.rebuildWrappedQuestCache(WrappedQuestCache.java:44) ~[ftb-xmod-compat-fabric-1.2.1.jar:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedQuestCache.getCachedItems(WrappedQuestCache.java:22) ~[ftb-xmod-compat-fabric-1.2.1.jar:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedQuestCache.lambda$findQuestsWithOutput$4(WrappedQuestCache.java:64) ~[ftb-xmod-compat-fabric-1.2.1.jar:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.ItemStackToListCache.getList(ItemStackToListCache.java:27) ~[ftb-xmod-compat-fabric-1.2.1.jar:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedQuestCache.findQuestsWithOutput(WrappedQuestCache.java:64) ~[ftb-xmod-compat-fabric-1.2.1.jar:?]
	at dev.ftb.mods.ftbxmodcompat.ftbquests.rei.QuestDisplayGenerator.getRecipeFor(QuestDisplayGenerator.java:26) ~[ftb-xmod-compat-fabric-1.2.1.jar:?]
	at me.shedaniel.rei.impl.client.view.ViewsImpl$1.getRecipeFor(ViewsImpl.java:390) ~[RoughlyEnoughItems-9.1.643.jar:?]
	... 36 more
Log upload triggered at: 16 Aug 2023 21:01:27  0200
```

### Anything else?

Here is the full log file : 
[minecraft.log](https://github.com/shedaniel/RoughlyEnoughItems/files/12362857/minecraft.log)

I posted an issue on FTB Quests side since going back to an older rev fixed the issue, I don't know from which side the bug is.
https://github.com/FTBTeam/FTB-Mods-Issues/issues/913

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [x] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by desht** [comment]
Error is on the FTB side, not REI - this can be closed.
