### ISSUE TITLE
Crash caused by create: symmetry wand

### ISSUE THREAD

**Issue by 3OL** [shedaniel/RoughlyEnoughItems#1484]
### What happened?

Game Crashes/Rei crashes because of create item: wand of symmetry. I've got the latest version of REI and I'm playing on forge but using spark to play fabric mods like rei.

[crash-2023-08-19_17.55.23-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/12386258/crash-2023-08-19_17.55.23-client.txt)

### What mod loaders are you seeing the problem on?

Fabric, Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2023-08-19 17:55:23
Description: Rendering entry base

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
	at net.minecraft.client.renderer.ShaderInstance.redirect$zeb000$redirectGetUniformLocation(ShaderInstance.java:615) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ShaderInstance.m_173363_(ShaderInstance.java:348) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.VertexBuffer.m_166876_(VertexBuffer.java:180) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mojang.blaze3d.vertex.VertexBuffer.m_253207_(VertexBuffer.java:123) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mojang.blaze3d.vertex.BufferUploader.m_231211_(BufferUploader.java:33) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mojang.blaze3d.vertex.BufferUploader.m_231202_(BufferUploader.java:26) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.RenderType.m_276775_(RenderType.java:434) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109912_(MultiBufferSource.java:97) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorMultiBufferSource,pl:mixin:A}
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_6299_(MultiBufferSource.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorMultiBufferSource,pl:mixin:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115222_(ItemRenderer.java:183) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.item.render.PartialItemModelRenderer.render(PartialItemModelRenderer.java:67) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.simibubi.create.foundation.item.render.PartialItemModelRenderer.renderGlowing(PartialItemModelRenderer.java:56) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.simibubi.create.content.equipment.symmetryWand.SymmetryWandItemRenderer.render(SymmetryWandItemRenderer.java:32) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.simibubi.create.foundation.item.render.CustomRenderedItemModelRenderer.m_108829_(CustomRenderedItemModelRenderer.java:26) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:320) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:250) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:199) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:128) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.m_88315_(EntryListWidget.java:196) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:348) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_88315_(ScreenOverlayImpl.java:244) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.m_88315_(DefaultDisplayViewingScreen.java:333) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:APP:inventorio.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:fancymenu.general.mixin.json:IMixinScreen,pl:mixin:APP:fancymenu.general.mixin.json:MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.1-universal.jar%23329!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.1-universal.jar%23329!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:craterlib.mixins.json:events.client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:craterlib.mixins.json:events.client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.1.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.ShaderInstance.redirect$zeb000$redirectGetUniformLocation(ShaderInstance.java:615) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ShaderInstance.m_173363_(ShaderInstance.java:348) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.VertexBuffer.m_166876_(VertexBuffer.java:180) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mojang.blaze3d.vertex.VertexBuffer.m_253207_(VertexBuffer.java:123) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mojang.blaze3d.vertex.BufferUploader.m_231211_(BufferUploader.java:33) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.mojang.blaze3d.vertex.BufferUploader.m_231202_(BufferUploader.java:26) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.RenderType.m_276775_(RenderType.java:434) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109912_(MultiBufferSource.java:97) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorMultiBufferSource,pl:mixin:A}
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_6299_(MultiBufferSource.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorMultiBufferSource,pl:mixin:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115222_(ItemRenderer.java:183) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.item.render.PartialItemModelRenderer.render(PartialItemModelRenderer.java:67) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.simibubi.create.foundation.item.render.PartialItemModelRenderer.renderGlowing(PartialItemModelRenderer.java:56) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.simibubi.create.content.equipment.symmetryWand.SymmetryWandItemRenderer.render(SymmetryWandItemRenderer.java:32) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.simibubi.create.foundation.item.render.CustomRenderedItemModelRenderer.m_108829_(CustomRenderedItemModelRenderer.java:26) ~[create-1.20.1-0.5.1.d.jar%23258!/:0.5.1.d] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Screen details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:203) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:128) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.m_88315_(EntryListWidget.java:196) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:348) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_88315_(ScreenOverlayImpl.java:244) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.m_88315_(DefaultDisplayViewingScreen.java:333) ~[RoughlyEnoughItems-12.0.645.jar%23307!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:APP:inventorio.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:fancymenu.general.mixin.json:IMixinScreen,pl:mixin:APP:fancymenu.general.mixin.json:MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.1-universal.jar%23329!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.1-universal.jar%23329!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:craterlib.mixins.json:events.client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23324!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:craterlib.mixins.json:events.client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.1.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry
	Bounds: me.shedaniel.math.Rectangle@4ee5b472[height=18,width=18,x=555,y=91]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: create:wand_of_symmetry

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: wand_of_symmetry
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
```

### Anything else?

Create mod caused it because of the symmetry wand but why?

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by kahd0** [comment]
same issue here

**Comment by shedaniel** [comment]
This is unrelated to REI, this is the same issue as https://github.com/Creators-of-Create/Create/issues/5322
Please look at the comments over there
