### ISSUE TITLE
Error: cannot access class_8786class

### ISSUE THREAD

**Issue by CSMMaster** [shedaniel/RoughlyEnoughItems#1501]
### What happened?

I am developing a mod for fabric 1.20.1, and integrated the REI API Fabric and Fabric as listed on the description page of this feed. When I try to Data Regen or launch the client, I get this error:

cannot access class_8786class file for net.minecraft.class_8786 not found

It seems there is a referenced minecraft element that no longer exists in the fabric api. I am using the fabric_version=0.86.1+1.20.1 with REI API 13.0.654. Would be helpful if clarification on any compatibility issues I may need to take into consideration.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Error related to v13.0.654:
cannot access class_8786class file for net.minecraft.class_8786 not found

Attempted using an older version, 12.0.625, and got this error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
     
Replace mod 'Fabric Model Loading API (v1)' (fabric-model-loading-api-v1) 1.0.2+709a987177 with any version that is compatible with:
fabric-models-v0 0.3.35+b3afc78b27
Unmet dependency listing:
     
Mod 'Fabric Model Loading API (v1)' (fabric-model-loading-api-v1) 1.0.2+709a987177 is incompatible with any version before 0.4.0 of mod 'Fabric Models (v0)' (fabric-models-v0), but a matching version is present: 0.3.35+b3afc78b27!
  at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
  at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
  at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
  at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by CSMMaster** [comment]
Resolved the Issue. Was not aware that Minecraft and Fabric have an update to 1.20.2. Rolled back to v12.0.648 w/ Fabric v0.88.1+1.20.1. Mod works perfectly.
