### ISSUE TITLE
[Bug] Crash with Applied Energistics 2

### ISSUE THREAD

**Issue by sevenninesixthree** [shedaniel/RoughlyEnoughItems#1512]
### What happened?

Minecraft: 1.20.1
forge: 47.2.1
architectury: 9.1.12
**no** kubejs
ae2: 15.0.13
Every time I open the _ME Terminal_, the game crashes.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[23:15:40] [main/INFO]: ModLauncher running: args [--username, jiang_xin, --version, 1.20.1, --gameDir, C:\.mine\.pick, --assetsDir, C:\.mine\.pick\assets, --assetIndex, 5, --uuid, dc31362edb1e4544be36a840d6d0ffb4, --accessToken, ????????????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, HMCL 3.5.5, --width, 1280, --height, 720, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.1, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[23:15:40] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.3 by Microsoft; OS Windows 11 arch amd64 version 10.0
[23:15:40] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[23:15:40] [main/INFO]: Trying GL version 4.6
[23:15:41] [main/INFO]: Requested GL version 4.6 got version 4.6
[23:15:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/.mine/.pick/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[23:15:41] [pool-2-thread-1/INFO]: GL info: AMD Radeon (TM) Graphics GL version 4.6.0 Core Profile Context 22.20.44.221025, ATI Technologies Inc.
[23:15:41] [main/INFO]: Found mod file appliedenergistics2-forge-15.0.13.jar of type MOD with provider {mods folder locator at C:\.mine\.pick\mods}
[23:15:41] [main/INFO]: Found mod file architectury-9.1.12-forge.jar of type MOD with provider {mods folder locator at C:\.mine\.pick\mods}
[23:15:41] [main/INFO]: Found mod file cloth-config-11.1.106-forge.jar of type MOD with provider {mods folder locator at C:\.mine\.pick\mods}
[23:15:41] [main/INFO]: Found mod file Jade-1.20.1-forge-11.6.1.jar of type MOD with provider {mods folder locator at C:\.mine\.pick\mods}
[23:15:41] [main/INFO]: Found mod file jecharacters-1.20.1-4.4.2.jar of type MOD with provider {mods folder locator at C:\.mine\.pick\mods}
[23:15:41] [main/INFO]: Found mod file RoughlyEnoughItems-12.0.652.jar of type MOD with provider {mods folder locator at C:\.mine\.pick\mods}
[23:15:41] [main/WARN]: Mod file C:\.mine\.pick\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.1\fmlcore-1.20.1-47.2.1.jar is missing mods.toml file
[23:15:41] [main/WARN]: Mod file C:\.mine\.pick\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.1\javafmllanguage-1.20.1-47.2.1.jar is missing mods.toml file
[23:15:41] [main/WARN]: Mod file C:\.mine\.pick\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.1\lowcodelanguage-1.20.1-47.2.1.jar is missing mods.toml file
[23:15:41] [main/WARN]: Mod file C:\.mine\.pick\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.1\mclanguage-1.20.1-47.2.1.jar is missing mods.toml file
[23:15:41] [main/INFO]: Found mod file fmlcore-1.20.1-47.2.1.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659925f4
[23:15:41] [main/INFO]: Found mod file javafmllanguage-1.20.1-47.2.1.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659925f4
[23:15:41] [main/INFO]: Found mod file lowcodelanguage-1.20.1-47.2.1.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659925f4
[23:15:41] [main/INFO]: Found mod file mclanguage-1.20.1-47.2.1.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659925f4
[23:15:41] [main/INFO]: Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659925f4
[23:15:41] [main/INFO]: Found mod file forge-1.20.1-47.2.1-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659925f4
[23:15:41] [main/INFO]: Found 1 dependencies adding them to mods collection
[23:15:41] [main/INFO]: Found mod file PinIn-1.6.0.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@344426bf
[23:15:44] [main/ERROR]: Mixin config rei.mixins.json does not specify "minVersion" property
[23:15:44] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\.mine\.pick, --assetsDir, C:\.mine\.pick\assets, --uuid, dc31362edb1e4544be36a840d6d0ffb4, --username, jiang_xin, --assetIndex, 5, --accessToken, ????????????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, HMCL 3.5.5, --width, 1280, --height, 720]
[23:15:48] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 117 milliseconds
[23:15:49] [pool-4-thread-1/WARN]: Unable to find class com.simibubi.create.foundation.ponder.PonderWorld. Integration with PonderJS disabled.
[23:15:50] [Render thread/WARN]: Assets URL 'union:/C:/.mine/.pick/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23168!/assets/.mcassetsroot' uses unexpected schema
[23:15:50] [Render thread/WARN]: Assets URL 'union:/C:/.mine/.pick/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23168!/data/.mcassetsroot' uses unexpected schema
[23:15:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:15:51] [Render thread/INFO]: Setting user: jiang_xin
[23:15:51] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[23:15:52] [modloading-worker-0/INFO]: Forge mod loading, version 47.2.1, for MC 1.20.1 with MCP 20230612.114412
[23:15:52] [modloading-worker-0/INFO]: MinecraftForge v47.2.1 Initialized
[23:15:52] [modloading-worker-0/INFO]: Registering S2C receiver with id architectury:sync_ids
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id architectury:sync_ids
[23:15:52] [modloading-worker-0/INFO]: [REI] Config loaded
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider AE2 [ae2] for REIPlugin
[23:15:52] [modloading-worker-0/INFO]: Registering S2C receiver with id roughlyenoughitems:request_tags_s2c
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultPluginImpl [roughlyenoughitems] for REIServerPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultPluginImpl [roughlyenoughitems] for REIPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[23:15:52] [modloading-worker-0/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items_new
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultClientPluginImpl [roughlyenoughitems] for REIClientPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultClientPluginImpl [roughlyenoughitems] for REIPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIClientPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider HideIngredientsFromTagsPlugin [roughlyenoughitems] for REIClientPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider HideIngredientsFromTagsPlugin [roughlyenoughitems] for REIPlugin
[23:15:52] [modloading-worker-0/INFO]: [REI] Registered plugin provider AE2 [ae2] for REIClientPlugin
[23:15:52] [modloading-worker-0/INFO]: Registering S2C receiver with id roughlyenoughitems:ci_msg
[23:15:52] [modloading-worker-0/INFO]: Registering S2C receiver with id roughlyenoughitems:og_not_enough
[23:15:53] [Worker-Main-1/WARN]: Failed to compress event log file: C:\.mine\.pick\logs\telemetry\20231007-1.json
java.io.IOException: Compressed target file already exists: C:\.mine\.pick\logs\telemetry\20231007-1.json.gz
	at net.minecraft.util.eventlog.EventLogDirectory.m_260828_(EventLogDirectory.java:87) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at net.minecraft.util.eventlog.EventLogDirectory$RawFile.m_260857_(EventLogDirectory.java:202) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at net.minecraft.util.eventlog.EventLogDirectory$FileList.m_261127_(EventLogDirectory.java:155) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at net.minecraft.client.telemetry.TelemetryLogManager.m_261065_(TelemetryLogManager.java:36) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[23:15:53] [Render thread/INFO]: Reloading ResourceManager: vanilla, mod_resources
[23:15:53] [Worker-Main-10/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[23:15:53] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[23:15:54] [Forge Version Check/INFO]: [forge] Found status: AHEAD Current: 47.2.1 Target: null
[23:15:55] [Worker-Main-4/INFO]: Start loading plugin at snownee.jade.addon.vanilla.VanillaPlugin
[23:15:55] [Worker-Main-4/INFO]: Start loading plugin at snownee.jade.addon.universal.UniversalPlugin
[23:15:55] [Worker-Main-4/INFO]: Start loading plugin at snownee.jade.addon.core.CorePlugin
[23:15:55] [Worker-Main-4/INFO]: Start loading plugin at appeng.integration.modules.jade.JadeModule
[23:15:56] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[23:15:56] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[23:15:57] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speaker (Realtek(R) Audio)
[23:15:57] [Render thread/INFO]: Sound engine started
[23:15:57] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[23:15:57] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[23:15:57] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:15:57] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:15:57] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[23:15:57] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:15:57] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[23:15:57] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:15:57] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:15:57] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[23:15:57] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[23:15:57] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[23:15:57] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[23:16:02] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[23:16:04] [Render thread/INFO]: Loaded 12 recipes
[23:16:04] [Render thread/INFO]: Loaded 1677 advancements
[23:16:04] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[23:16:04] [Server thread/INFO]: Generating keypair
[23:16:05] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:16:08] [Render thread/INFO]: 准备生成区域中：0%
[23:16:08] [Render thread/INFO]: 准备生成区域中：0%
[23:16:08] [Render thread/INFO]: 准备生成区域中：0%
[23:16:08] [Render thread/INFO]: 准备生成区域中：0%
[23:16:08] [Render thread/INFO]: 准备生成区域中：0%
[23:16:08] [Render thread/INFO]: 准备生成区域中：0%
[23:16:08] [Render thread/INFO]: 准备生成区域中：22%
[23:16:09] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler
[23:16:09] [Render thread/INFO]: Time elapsed: 3452 ms
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.TestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.AutoCraftingTestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.InscriberTestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.P2PTestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.ItemP2PTestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.MemoryCardTestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.PatternProviderLockModePlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.SpatialTestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.QnbTestPlots for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.GuidebookPlot for plots
[23:16:09] [Server thread/INFO]: Scanning class appeng.server.testplots.SubnetPlots for plots
[23:16:09] [Server thread/INFO]: Changing view distance to 8, from 10
[23:16:09] [Server thread/INFO]: Changing simulation distance to 12, from 0
[23:16:09] [Render thread/WARN]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
[23:16:10] [Netty Local Client IO #0/INFO]: Connected to a modded server.
[23:16:10] [Server thread/INFO]: jiang_xin[local:E:0d952770] logged in with entity id 154 at (-0.20176379653518436, 89.0, -2.2839227341603334)
[23:16:10] [Server thread/INFO]: jiang_xin加入了游戏
[23:16:10] [Render thread/WARN]: Unknown recipe category: ae2:charger/ae2:charger/charged_certus_quartz_crystal
[23:16:10] [Render thread/WARN]: Unknown recipe category: ae2:charger/ae2:charger/meteorite_compass
[23:16:10] [Render thread/WARN]: Unknown recipe category: ae2:charger/ae2:charger/guide
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for START.
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] Plugins (6):
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[23:16:10] [Server thread/INFO]: Syncing config to jiang_xin (dc31362e-db1e-4544-be36-a840d6d0ffb4)
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for START.
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] Plugins (4):
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[23:16:10] [Render thread/INFO]: Received config from the server: 
[23:16:10] [Render thread/INFO]: Loaded 53 advancements
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for START.
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] Plugins (2):
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for START in 1.779 ms, totaling 49.79 ms.
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 1.698 ms, totaling 669.6 ms.
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for START in 672.7 μs, totaling 3.176 ms.
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] REIPlugin starting main-reload for END.
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] Plugins (6):
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[23:16:10] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] Plugins (4):
[23:16:11] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[23:16:11] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) AE2 of AE2 [ae2]
[23:16:11] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[23:16:11] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] ****************************************
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin starting main-reload for END.
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] Plugins (2):
[23:16:11] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[23:16:11] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] REIPlugin finished post-reload for END in 854.0 μs, totaling 84.07 ms.
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 1.485 ms, totaling 735.5 ms.
[23:16:11] [REI-ReloadPlugins/INFO]: [REI] REIServerPlugin finished post-reload for END in 54.83 ms, totaling 61.31 ms.
[23:16:30] [Server thread/INFO]: Stopping server
[23:16:30] [Server thread/INFO]: Saving players
[23:16:30] [Server thread/INFO]: Saving worlds
[23:16:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[23:16:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[23:16:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[23:16:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/ae2:spatial_storage
[23:16:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (新的世界): All chunks are saved
[23:16:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:16:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:16:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[23:16:31] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[23:16:32] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoSuchMethodError: 'boolean me.shedaniel.rei.api.client.gui.widgets.TextField.isFocused()'
	at appeng.integration.modules.rei.ReiRuntimeAdapter.hasSearchFocus(ReiRuntimeAdapter.java:62) ~[appliedenergistics2-forge-15.0.13.jar%23162!/:15.0.13]
	at appeng.util.ExternalSearch.isExternalSearchFocused(ExternalSearch.java:38) ~[appliedenergistics2-forge-15.0.13.jar%23162!/:15.0.13]
	at appeng.client.gui.me.common.MEStorageScreen.updateSearch(MEStorageScreen.java:391) ~[appliedenergistics2-forge-15.0.13.jar%23162!/:15.0.13]
	at appeng.client.gui.me.common.MEStorageScreen.updateBeforeRender(MEStorageScreen.java:348) ~[appliedenergistics2-forge-15.0.13.jar%23162!/:15.0.13]
	at appeng.client.gui.AEBaseScreen.m_88315_(AEBaseScreen.java:238) ~[appliedenergistics2-forge-15.0.13.jar%23162!/:15.0.13]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.1-universal.jar%23173!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.1-universal.jar%23173!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?]
	... 18 more
[23:16:32] [Render thread/FATAL]: Preparing crash report with UUID c73fe971-7e5e-461f-89ab-0ddeb1c1e816
[23:16:32] [Render thread/FATAL]: Preparing crash report with UUID 0d43eed5-4e1d-4a4a-a5a9-7bc92e594d26
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by sevenninesixthree** [comment]
Ok, you can just fix the problem by adding [REIPC](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks)
