### ISSUE TITLE
[Bug] REI-ReloadPlugins/ERROR

### ISSUE THREAD

**Issue by ZIDCAKE** [shedaniel/RoughlyEnoughItems#1542]
### What happened?

Getting a lot of 2 errors in the logs

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[REI-ReloadPlugins/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Rendersystem called from wrong thread
	Index: 22
	Listeners:
		0: HIGHEST
		1: ASM: class shadows.apotheosis.adventure.client.AdventureModuleClient tooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		2: HIGH
		3: ASM: class dev.architectury.event.forge.EventHandlerImplClient event(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		4: ASM: class shadows.apotheosis.adventure.client.AdventureModuleClient affixTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		5: NORMAL
		6: ASM: class com.anthonyhilyard.highlighter.Highlighter onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		7: ASM: class com.mrcrayfish.guns.item.attachment.impl.Attachment addInformationEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		8: ASM: sereneseasons.handler.season.SeasonalCropGrowthHandler@623dcefc onItemTooltipAdded(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		9: ASM: class io.github.edwinmindcraft.apoli.common.ApoliPowerEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		10: ASM: class com.mlib.itemsets.ItemSetTooltip onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		11: ASM: class io.github.edwinmindcraft.calio.common.CalioEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		12: ASM: class com.mlib.contexts.OnItemTooltip onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		13: ASM: class cofh.core.event.CoreClientEvents handleItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		14: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@58f67040 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		15: ASM: class limonblaze.originsclasses.common.event.PowerEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		16: net.minecraftforge.eventbus.EventBus$$Lambda$1504/0x00000008009c6ae8@6565be91
		17: ASM: class com.blamejared.crafttweaker.impl.event.CTClientEventHandler handleTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		18: ASM: class shadows.fastbench.ClientHandler tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		19: ASM: class twilightforest.client.TFClientEvents tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		20: ASM: class com.teamabnormals.upgrade_aquatic.core.events.ClientEvents onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		21: ASM: class net.mehvahdjukaar.supplementaries.common.events.ClientEvents onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		22: ASM: class yesman.epicfight.client.events.engine.RenderEngine$Events itemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		23: ASM: class vazkii.quark.base.client.handler.RequiredModTooltipHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		24: ASM: class io.redspace.ironsspellbooks.player.ClientPlayerEvents imbuedWeaponTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		25: ASM: class com.simibubi.create.foundation.events.ClientEvents addToItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		26: ASM: vazkii.quark.content.building.module.CelebratoryLampsModule@5f6deb8e onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		27: net.minecraftforge.eventbus.EventBus$$Lambda$1504/0x00000008009c6ae8@794b465a
		28: ASM: top.theillusivec4.curios.client.ClientEventHandler@d5579c1 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		29: net.minecraftforge.eventbus.EventBus$$Lambda$1504/0x00000008009c6ae8@4bc051cf
		30: ASM: org.infernalstudios.shieldexp.events.TooltipEvents@4e7a0d48 onTooltipCreate(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		31: ASM: shadows.apotheosis.ench.EnchModuleClient@67eefb7e tooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		32: net.minecraftforge.eventbus.EventBus$$Lambda$1504/0x00000008009c6ae8@1800b18c
		33: net.minecraftforge.eventbus.EventBus$$Lambda$1504/0x00000008009c6ae8@50d9052b
		34: LOW
		35: ASM: class com.supermartijn642.durabilitytooltip.DurabilityTooltipClient onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		36: LOWEST
		37: ASM: class com.endertech.minecraft.forge.client.DevInfo onInventoryTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		38: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@516bd6d9 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		39: ASM: class mcp.mobius.waila.WailaClient onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		40: ASM: air onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.systems.RenderSystem.m_187556_(RenderSystem.java:181)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.systems.RenderSystem.m_187554_(RenderSystem.java:170)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.platform.Window.m_85382_(Window.java:246)
	at MC-BOOTSTRAP/org.lwjgl.glfw/org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at MC-BOOTSTRAP/org.lwjgl/org.lwjgl.system.JNI.invokePI(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw/org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3409)
	at TRANSFORMER/epicfight@18.5.19/yesman.epicfight.client.events.engine.ControllEngine.isKeyDown(ControllEngine.java:428)
	at TRANSFORMER/epicfight@18.5.19/yesman.epicfight.client.events.engine.RenderEngine$Events.itemTooltip(RenderEngine.java:487)
	at net.minecraftforge.eventbus.ASMEventHandler_2411_Events_itemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.14/net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:275)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:768)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:231)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:376)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:211)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:90)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:75)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:45)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.ArgumentCache.cacheStacks(ArgumentCache.java:138)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.ArgumentCache.lambda$cache$1(ArgumentCache.java:110)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.ArgumentCache.cache(ArgumentCache.java:109)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.ArgumentCache.prepareFilter(ArgumentCache.java:90)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.argument.Argument.resetCache(Argument.java:85)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.client.search.SearchRuntime.endReload(SearchRuntime.java:44)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:454)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162)
	at TRANSFORMER/roughlyenoughitems@8.3.667/me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:488)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

-----------------------------------------------------------------------------------------

[Render thread/ERROR] [com.mojang.blaze3d.platform.Window/]: 65539: Invalid key -1
[Render thread/ERROR] [com.mojang.blaze3d.platform.Window/]: ########## GL ERROR ##########
```

### Anything else?

I think the problem is with the EpicFight-18.5.19 mod
Or one of its addons
Minecraft version 1.18.2, Forge 40.2.14

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ZIDCAKE** [comment]
![1](https://github.com/shedaniel/RoughlyEnoughItems/assets/103335436/617ba120-90f7-4463-a227-f95b42a6740c)

About the render error - it disappeared after I changed this setting (screenshot).
Except that I don't know what it affects)

About the invalid key error - I realized what the error was. It occurs if you change the control settings of Epic Fight, not related to REI
