### ISSUE TITLE
[Crash] Crashes on startup

### ISSUE THREAD

**Issue by guyperson0** [shedaniel/RoughlyEnoughItems#1545]
### What happened?

Crashes almost immediately on start-up, with the following message:
`Caused by: java.lang.module.ResolutionException: Modules roughlyenoughitems and roughlyenoughitems_servercomponent export package me.shedaniel.rei.impl.common.plugins to module [MOD]`
[MOD] has been numerous other mods, such as FTB Quests, Additional Structures, Obscure API, Alternate Current, and probably more

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[...]

Mods:
  [✔] (Forge)SculkHorn-1.20.x-1.4.5
  [✔] AdLods-1.20.1-8.1.0.0-build.0142
  [✘] AdvancementPlaques-1.20.1-forge-1.4.10.jar (disabled)
  [✔] aeroblender-1.20.1-1.0.1-neoforge
  [✔] aether_enhanced_extinguishing-1.20.1-1.0.0-neoforge
  [✔] aether-1.20.1-1.0.0-beta.2-neoforge
  [✔] aether-redux-1.3.3-1.20.1-neoforge
  [✔] AgeingSpawners-1.20.1-2.0.0
  [✔] alexscaves-1.0.8
  [✔] alexsmobs-1.22.6
  [✔] alternate_current-mc1.20-1.7.0
  [✔] apathy-forge-1.20.1-2.7.1
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] Aquaculture-1.20.1-2.5.1
  [✔] aquamirae-6.API15
  [✔] architectury-9.1.12-forge
  [✔] artifacts-forge-9.2.0
  [✔] athena-forge-1.20.1-3.1.1
  [✔] balm-forge-1.20.1-7.1.4
  [✔] beautifiedchatserver-1.20.1-2.3
  [✔] bestylewither-forge-mc1.20-1.6.0
  [✔] betterarcheology-1.1.0
  [✔] BetterF3-7.0.2-Forge-1.20.1
  [✔] BOMD-Forge-1.20.1-1.0.4
  [✔] Bookshelf-Forge-1.20.1-20.1.6
  [✔] caelus-forge-3.1.0 1.20
  [✔] carryon-forge-1.20.1-2.1.2.7
  [✔] charmofundying-forge-6.4.5 1.20.1
  [✔] chipped-forge-1.20.1-3.0.1
  [✔] Chunk Pregenerator-1.20-4.2.3
  [✔] citadel-2.4.9-1.20.1
  [✔] cloth-config-11.1.106-forge
  [✔] Clumps-forge-1.20.1-12.0.0.3
  [✔] cobblemon_quests-[1.20.1]-forge-1.1.5
  [✔] cobblemon-capturexp-1.4-forge-1.0.2
  [✔] cobblemonchallenge-forge-1.20.1-1.1.4-beta
  [✔] Cobblemon-forge-1.4.0 1.20.1
  [✔] cobblemonintegrations-1.20.1-1.0.3
  [✔] collective-1.20.1-7.13
  [✔] comforts-forge-6.3.4 1.20.1
  [✔] constructionwand-1.20.1-2.11
  [✔] Controlling-forge-1.20.1-12.0.2
  [✔] cookingforblockheads-forge-1.20-16.0.1
  [✔] craftingtweaks-forge-1.20-18.2.2
  [✔] CraftPresence-2.2.5 1.20.1
  [✔] CraftTweaker-forge-1.20.1-14.0.26
  [✔] CraftTweaker-forge-1.20.1-14.0.27
  [✔] create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7.g
  [✔] create-1.20.1-0.5.1.f
  [✔] CreateTweaker-forge-1.20.1-4.0.7
  [✔] creeperoverhaul-3.0.1-forge
  [✔] cristellib-1.1.5-forge
  [✔] ctov-3.3.6
  [✔] cupboard-1.20.1-2.1
  [✔] curios-forge-5.4.5 1.20.1
  [✔] curious_armor_stands-1.20-5.0.1
  [✔] davespotioneering-1.20.1-5
  [✔] deep_aether-1.20.1-1.0.12
  [✔] Delightful-1.20.1-3.4.2
  [✔] diet-forge-2.1.1 1.20.1
  [✔] Ding-1.20.1-Forge-1.4.1
  [✔] domesticationinnovation-1.7.1-1.20.1
  [✔] dummmmmmy-1.20-1.8.13
  [✔] Dungeon Crawl-1.20.1-2.3.14
  [✔] dungeons_enhanced-1.20.1-5.2.1
  [✔] DungeonsArise-1.20.1-2.1.57-release
  [✔] dusk-1.20.1-3.5
  [✔] dynamiclightsreforged-1.20.1_v1.6.0
  [✔] dynview-1.20.1-3.9
  [✔] e4mc-4.0.1 1.19.4-forge
  [✔] EasyAnvils-v8.0.1-1.20.1-Forge
  [✔] eccentrictome-1.20.1-1.10.2
  [✔] ecologics-forge-1.20.1-2.2.0
  [✔] embeddium-0.2.12 mc1.20.1
  [✔] EnchantingInfuser-v8.0.2-1.20.1-Forge
  [✔] EnchantmentDescriptions-Forge-1.20.1-17.0.9
  [✔] enderchests-forge-1.20.1-1.2
  [✔] endermanoverhaul-forge-1.20.1-1.0.3
  [✔] endertanks-forge-1.20.1-1.2
  [✔] EnderZoology-v8.0.1-1.20.1-Forge
  [✔] EndlessBiomes 1.4.2s - 1.20.1
  [✔] endrem_forge-5.2.3-R-1.20.X
  [✔] ends_delight-1.20.1-1.0.1
  [✔] EndsPhantasm-1.20.1-0.1
  [✔] EnhancedAI-2.0.5-mc1.20.1
  [✘] entity_model_features_forge_1.20.1-1.1.0.jar (disabled)
  [✘] entity_texture_features_forge_1.20.1-4.6.1.jar (disabled)
  [✔] everycomp-1.20-2.6.18
  [✔] expandability-9.0.0
  [✔] explorify-v1.3.0-mc1.20
  [✔] FarmersDelight-1.20.1-1.2.3
  [✔] farsight-1.20.1-3.6
  [✔] FastFurnace-1.20.1-8.0.1
  [✔] Fastload-Reforged-mc1.20.1-3.4.0
  [✔] FastSuite-1.20.1-5.0.1
  [✔] FastWorkbench-1.20.1-8.0.2
  [✔] ferritecore-6.0.1-forge
  [✔] fightorflight-forge-0.5.3
  [✔] flib-1.20.1-0.0.11
  [✔] ForgeConfigScreens-v8.0.2-1.20.1-Forge
  [✔] ForgeEndertech-1.20.1-11.1.0.0-build.0142
  [✔] formations-1.0.2-forge-mc1.20
  [✔] formationsnether-1.0.2
  [✔] formationsoverworld-1.0.1
  [✔] framework-forge-1.20.1-0.6.16
  [✔] friendsandfoes-forge-mc1.20.1-2.0.2
  [✔] ftb-chunks-forge-2001.2.4
  [✔] ftb-library-forge-2001.1.4
  [✔] ftb-quests-forge-2001.3.0
  [✔] ftb-teams-forge-2001.1.4
  [✔] ftb-xmod-compat-forge-2.1.0
  [✔] Galosphere-1.20.1-1.3.2-Forge
  [✔] galospheretrimming-1.20.1-1.0.0
  [✔] GameStages-Forge-1.20.1-15.0.1
  [✔] geckolib-forge-1.20.1-4.3.1
  [✔] geophilic-v2.1.0-mc1.20u1.20.2
  [✔] GlobalGameRules-1.20-8.0.0.11
  [✔] goblintraders-forge-1.20.1-1.9.3
  [✔] guardvillagers-1.20.1-1.6.3
  [✔] handcrafted-forge-1.20.1-3.0.5
  [✔] hearths-v1.0.0-mc1.20u1.20.1
  [✔] Highlighter-1.20.1-forge-1.1.8
  [✔] Iceberg-1.20.1-forge-1.1.16
  [✔] IllagerInvasion-v8.0.3-1.20.1-Forge
  [✔] immersive_armors-1.6.1 1.20.1-forge
  [✔] incontrol-1.20-9.1.2
  [✔] InsaneLib-1.12.1-mc1.20.1
  [✔] invhud.forge.1.20.1-3.4.18
  [✔] ironchest-1.20.1-14.4.4
  [✔] irons_spellbooks-1.20.1-2.1.1.1
  [✔] item-filters-forge-2001.1.0-build.59
  [✔] ItemStages-Forge-1.20.1-8.0.1
  [✘] jearchaeology-1.20.1-1.0.3.jar (disabled)
  [✘] jeed-1.20-2.1.6.jar (disabled)
  [✘] jei-1.20.1-forge-15.2.0.27.jar (disabled)
  [✘] JeiTweaker-forge-1.20.1-8.0.6.jar (disabled)
  [✔] jmi-forge-1.20.1-0.14-45
  [✔] journeymap-1.20.1-5.9.18-forge
  [✘] JustEnoughProfessions-forge-1.20.1-3.0.1.jar (disabled)
  [✘] JustEnoughResources-1.20.1-1.4.0.238.jar (disabled)
  [✔] kotlinforforge-4.8.0-all
  [✔] KryptonReforged-0.2.3
  [✔] Ksyxis-Forge1.17-1.1
  [✔] kubejs-forge-2001.6.4-build.111
  [✔] L_Enders_Cataclysm-1.39 -1.20.1
  [✔] LeavesBeGone-v8.0.0-1.20.1-Forge
  [✔] LegendaryTooltips-1.20.1-forge-1.4.5
  [✔] letmedespawn-forge-1.20.x-1.2.0
  [✔] Log-Begone-Forge-1.20.1-1.0.8
  [✔] lootjs-forge-1.20.1-2.10.4
  [✔] lootr-1.20-0.7.30.73
  [✔] lost_aether_content-1.20.1-1.2.3
  [✔] majrusz-library-forge-1.20.1-7.0.1
  [✔] majruszs-difficulty-forge-1.20.1-1.9.2
  [✔] majruszs-enchantments-forge-1.20.1-1.10.4
  [✔] mavapi-1.1.3-mc1.20.1
  [✔] mavm-1.2.4-mc1.20
  [✔] memoryleakfix-forge-1.17 -1.1.2
  [✔] mes-1.3-1.20-forge
  [✔] modernfix-forge-5.10.0 mc1.20.1
  [✔] moonlight-1.20-2.8.67-forge
  [✔] MouseTweaks-forge-mc1.20-2.25
  [✔] mvs-4.1.1-1.20-forge
  [✔] Nameless Trinkets-1.20.1-1.7.8
  [✔] NaturesCompass-1.20.1-1.11.2-forge
  [✔] Neat-1.20-35-FORGE
  [✔] neruina-1.3.0-forge 1.18.2-1.20.1
  [✔] netherdungeons-1.1.0-alpha2
  [✔] netherportalfix-forge-1.20-13.0.1
  [✔] nethersdelight-1.20.1-4.0
  [✔] Nullscape_1.20.4_v1.2.4
  [✔] obscure_api-15
  [✔] oceansdelight-1.0.2-1.20
  [✘] oculus-flywheel-compat-1.20.1-0.2.0.jar (disabled)
  [✘] oculus-mc1.20.1-1.6.9.jar (disabled)
  [✔] OverflowingBars-v8.0.0-1.20.1-Forge
  [✔] Patchouli-1.20.1-83-FORGE
  [✔] Paxi-1.20-Forge-4.0
  [✔] Placebo-1.20.1-8.6.0
  [✔] player-animation-lib-forge-1.0.2-rc1 1.20
  [✔] polymorph-forge-0.49.2 1.20.1
  [✔] Prism-1.20.1-forge-1.0.5
  [✔] PuzzlesLib-v8.1.11-1.20.1-Forge
  [✔] radium-mc1.20.1-0.12.2 git.5f80f74
  [✔] RegionsUnexploredForge-0.5.3 1.20.1
  [✔] REIPluginCompatibilities-forge-12.0.93
  [✔] rer-2.9.0
  [✔] resourcefulconfig-forge-1.20.1-2.1.0
  [✔] resourcefullib-forge-1.20.1-2.1.19
  [✔] Rex's-AdditionalStructures-1.20.x-(v.4.2.1)
  [✔] rhino-forge-2001.2.2-build.13
  [✔] RoughlyEnoughItems-12.0.684-forge
  [✔] RoughlyEnoughItems-12.0.684-server-only
  [✔] RoughlyEnoughProfessions-forge-1.20.1-2.0.2
  [✔] rubidium_extras-1.20.1_v1.4.3
  [✔] Searchables-forge-1.20.1-1.0.2
  [✔] shetiphiancore-forge-1.20.1-1.2
  [✔] SimpleStorageNetwork-1.20.1-1.10.0
  [✔] simplysteel-1.20.1-2.3.1
  [✔] SkyVillages-1.0.3-1.19.2-1.20.x-forge-release
  [✔] sliceanddice-forge-3.2.0
  [✔] smoothboot-mc1.20.1-0.0.3
  [✔] smoothchunk-1.20.1-3.5
  [✔] snifferent-1.0.3-1.20.1
  [✔] sophisticatedbackpacks-1.20.1-3.19.1.962
  [✔] sophisticatedcore-1.20.1-0.5.108.504
  [✔] spacecatasb-forge-20.10.1
  [✔] spark-1.10.53-forge
  [✔] sparsestructuresreforged-1.19.2-1.20.1-0.0.3
  [✔] starlight-1.1.2 forge.1cda73c
  [✔] Steam_Rails-1.5.3 forge-mc1.20.1
  [✔] Stoneworks-v8.0.0-1.20.1-Forge
  [✔] storagedrawers-1.20.1-12.0.2
  [✔] structure_gel-1.20.1-2.15.1
  [✔] supermartijn642configlib-1.1.8-forge-mc1.20
  [✔] supermartijn642corelib-1.1.16-forge-mc1.20.1
  [✔] supplementaries-1.20-2.7.4
  [✔] tact-1.0.6 1.20.1
  [✔] tectonic-mod-mc1.19.3 -v2.1.1
  [✔] TerraBlender-forge-1.20.1-3.0.0.169
  [✔] The_Undergarden-1.20.1-0.8.9
  [✔] the-conjurer-1.20.1-1.1.6
  [✔] theoneprobe-1.20.1-10.0.1
  [✔] TinySkeletons-v8.0.1-1.20.1-Forge
  [✔] tlc_forge-1.0.3-R-1.20.X
  [✔] Tomtaru's Cobblemon  Farmer's Delight Tweaks - 1.20.1 - B.1.1
  [✔] toofast-1.20-0.4.3.5
  [✔] torchmaster-20.1.5
  [✔] Towns-and-Towers-1.12-Fabric Forge
  [✔] TradingPost-v8.0.1-1.20.1-Forge
  [✔] trashcans-1.0.18b-forge-mc1.20
  [✔] trofers-forge-5.0.0
  [✔] twigs-1.20.1-3.1.0-forge
  [✔] undergroundjungle-1.20-2.1.2-forge
  [✔] veinmining-forge-1.2.1 1.20.1
  [✔] villagertools-1.20.1-1.0.3
  [✔] visuality-forge-2.0.2
  [✔] VisualWorkbench-v8.0.0-1.20.1-Forge
  [✔] voicechat-forge-1.20.1-2.4.29
  [✔] Voidscape-1.20.1-1.5.310
  [✔] waystones-forge-1.20-14.0.2
  [✔] YungsApi-1.20-Forge-4.0.2
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
  [✔] YungsBetterDungeons-1.20-Forge-4.0.3
  [✔] YungsBetterEndIsland-1.20-Forge-2.0.4
  [✔] YungsBetterJungleTemples-1.20-Forge-2.0.4
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.5
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4
  [✔] YungsBetterWitchHuts-1.20-Forge-3.0.3
  [✔] YungsExtras-1.20-Forge-4.0.3

[...]

[12:58:03] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.17, NVIDIA Corporation
[12:58:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.0\fmlcore-1.20.1-47.2.0.jar is missing mods.toml file
[12:58:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.0\javafmllanguage-1.20.1-47.2.0.jar is missing mods.toml file
[12:58:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.0\lowcodelanguage-1.20.1-47.2.0.jar is missing mods.toml file
[12:58:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\********\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.0\mclanguage-1.20.1-47.2.0.jar is missing mods.toml file
[12:58:05] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[12:58:05] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: curios. Using Mod File: C:\Users\********\AppData\Roaming\PrismLauncher\instances\********\.minecraft\mods\curios-forge-5.4.5 1.20.1.jar
[12:58:05] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: C:\Users\********\AppData\Roaming\PrismLauncher\instances\********\.minecraft\mods\resourcefullib-forge-1.20.1-2.1.19.jar
[12:58:05] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: cloth_config. Using Mod File: C:\Users\********\AppData\Roaming\PrismLauncher\instances\********\.minecraft\mods\cloth-config-11.1.106-forge.jar
[12:58:05] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: expandability. Using Mod File: C:\Users\********\AppData\Roaming\PrismLauncher\instances\********\.minecraft\mods\expandability-9.0.0.jar
[12:58:05] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 20 dependencies adding them to mods collection
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.module.ResolutionException: Modules roughlyenoughitems and roughlyenoughitems_servercomponent export package me.shedaniel.rei.impl.common.plugins to module additionalstructures
	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.finish(Unknown Source)
	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Process exited with code 2.
```

### Anything else?

Version 1.20.1
REI v12.0.684
REIPC v12.0.93

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by guyperson0** [comment]
Figured it out; it was because I had REI and REI Server Component installed together. Probably.
