### ISSUE TITLE
"Duplicate Mod" crash with both REI and compats

### ISSUE THREAD

**Issue by Aceplante** [shedaniel/RoughlyEnoughItems#1551]
### What happened?

When I have both REI and REIPC enabled, it crashes due to "duplicate mod".

Forge 1.18.2

### What mod loaders are you seeing the problem on?

Forge

### Relevant log output

```shell
I can get this later
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by rozbrajaczpoziomow** [comment]
That sounds impossible. could be with JEI+REIPC, or possibly REI+REI-SC? but not with REI+REIPC.
also you removed a section from your issue.

**Comment by Aceplante** [comment]
```
Failed to build unique mod list after mod discovery.
net.minecraftforge.fml.loading.EarlyLoadingException: Duplicate mods found
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.UniqueModListBuilder.buildUniqueList(UniqueModListBuilder.java:78)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:76)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
18:06:24.410
net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer
main
Mod Discovery failed. Skipping dependency discovery.
```

**Comment by Aceplante** [comment]
The two I mentioned, REI and REIPC seem to be dependent on each other. Disabling one also disables the other, and enabling one likewise enables the other, so I cannot test them individually. With both of them, I get that error, without them I do not

**Comment by rozbrajaczpoziomow** [comment]
please send the full log

**Comment by Aceplante** [comment]
It doesnt even seem to be making a crash log file, so other than that^ which I was able to copy from the debug screen, the only other thing might be this (which comes right after the previous message):
```
Exception in thread "main" java.lang.IllegalStateException: Failed to find system mod: minecraft
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.ModSorter.detectSystemMods(ModSorter.java:180)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.ModSorter.buildUniqueList(ModSorter.java:145)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.ModSorter.sort(ModSorter.java:52)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.moddiscovery.ModValidator.stage2Validation(ModValidator.java:93)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.FMLLoader.completeScan(FMLLoader.java:175)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.FMLServiceProvider.completeScan(FMLServiceProvider.java:91)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServiceDecorator.onCompleteScan(TransformationServiceDecorator.java:174)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.lambda$triggerScanCompletion$23(TransformationServicesHandler.java:142)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.triggerScanCompletion(TransformationServicesHandler.java:144)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:94)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
21:22:21.249
monitor
Process Monitor
Process crashed with exit code 1
```

**Comment by Aceplante** [comment]
wait are you supposed to use yours INSTEAD of jei? not in addition to? Because yea I have jei

**Comment by Aceplante** [comment]
I swear I used them both just fine before, not sure what changed
