### ISSUE TITLE
[Bug] Game crashes when initializing game

### ISSUE THREAD

**Issue by m4tzzz** [shedaniel/RoughlyEnoughItems#1555]
### What happened?

My game wont get past the loading screen and crashes and gives me this error.
[crash-2023-12-23_14.30.40-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/13760182/crash-2023-12-23_14.30.40-client.txt)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[23Dec2023 14:30:12.756] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, _m4tz_, --version, 1.20.2-forge-48.1.0, --gameDir, /Users/maximilianohernandez/Library/Application Support/minecraft, --assetsDir, /Users/maximilianohernandez/Library/Application Support/minecraft/assets, --assetIndex, 8, --uuid, 417f673013ec4ad083cfabd6ef1ef9a9, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, QkUwNjNGQjQwRTIzNDkyQkI3NDg2NDZBQjBEMTczOTQ=, --xuid, 2535412862894491, --userType, msa, --versionType, release, --quickPlayPath, /Users/maximilianohernandez/Library/Application Support/minecraft/quickPlay/java/1703363406839.json, --launchTarget, forge_client, --fml.forgeVersion, 48.1.0, --fml.mcVersion, 1.20.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230921.100330]
[23Dec2023 14:30:12.762] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 17.0.8+7-LTS
[23Dec2023 14:30:12.766] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.1.1 starting: java version 17.0.8 by Microsoft; OS Mac OS X arch x86_64 version 12.7.1
[23Dec2023 14:30:14.684] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[23Dec2023 14:30:15.442] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[23Dec2023 14:30:15.570] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.5
[23Dec2023 14:30:15.605] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.4
[23Dec2023 14:30:15.641] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.3
[23Dec2023 14:30:15.685] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.2
[23Dec2023 14:30:15.728] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.1
[23Dec2023 14:30:15.770] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.1 got version 4.1
[23Dec2023 14:30:16.389] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Users/maximilianohernandez/Library/Application%20Support/minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[23Dec2023 14:30:16.532] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: Intel(R) HD Graphics 6000 GL version 4.1 INTEL-18.8.6, Intel Inc.
[23Dec2023 14:30:17.600] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/maximilianohernandez/Library/Application Support/minecraft/libraries/net/minecraftforge/fmlcore/1.20.2-48.1.0/fmlcore-1.20.2-48.1.0.jar is missing mods.toml file
[23Dec2023 14:30:17.606] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/maximilianohernandez/Library/Application Support/minecraft/libraries/net/minecraftforge/javafmllanguage/1.20.2-48.1.0/javafmllanguage-1.20.2-48.1.0.jar is missing mods.toml file
[23Dec2023 14:30:17.610] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/maximilianohernandez/Library/Application Support/minecraft/libraries/net/minecraftforge/lowcodelanguage/1.20.2-48.1.0/lowcodelanguage-1.20.2-48.1.0.jar is missing mods.toml file
[23Dec2023 14:30:17.614] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/maximilianohernandez/Library/Application Support/minecraft/libraries/net/minecraftforge/mclanguage/1.20.2-48.1.0/mclanguage-1.20.2-48.1.0.jar is missing mods.toml file
[23Dec2023 14:30:18.375] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
[23Dec2023 14:30:18.592] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'neoforge', Requested by: 'balm', Expected range: '[20.2,)', Actual version: '[MISSING]'
	Mod ID: 'neoforge', Requested by: 'twilightforest', Expected range: '[20.2.0,)', Actual version: '[MISSING]'
[23Dec2023 14:30:21.887] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[23Dec2023 14:30:21.894] [main/ERROR] [mixin/]: Mixin config rei.mixins.json does not specify "minVersion" property
[23Dec2023 14:30:21.908] [main/ERROR] [mixin/]: Mixin config rei-jei-internals-workaround.mixins.json does not specify "minVersion" property
[23Dec2023 14:30:21.937] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forge_client' with arguments [--version, 1.20.2-forge-48.1.0, --gameDir, /Users/maximilianohernandez/Library/Application Support/minecraft, --assetsDir, /Users/maximilianohernandez/Library/Application Support/minecraft/assets, --uuid, 417f673013ec4ad083cfabd6ef1ef9a9, --username, _m4tz_, --assetIndex, 8, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, QkUwNjNGQjQwRTIzNDkyQkI3NDg2NDZBQjBEMTczOTQ=, --xuid, 2535412862894491, --userType, msa, --versionType, release, --quickPlayPath, /Users/maximilianohernandez/Library/Application Support/minecraft/quickPlay/java/1703363406839.json]
[23Dec2023 14:30:22.044] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 41 options available, 0 override(s) found
[23Dec2023 14:30:22.377] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher (java.lang.ClassNotFoundException: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher)
[23Dec2023 14:30:22.377] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.chunk.ChunkRenderDispatcher was not found rubidium.mixins.json:core.render.world.ChunkBuilderMixin
[23Dec2023 14:30:33.343] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 192 Datafixer optimizations took 371 milliseconds
[23Dec2023 14:30:37.696] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/Users/maximilianohernandez/Library/Application%20Support/minecraft/libraries/net/minecraft/client/1.20.2-20230921.100330/client-1.20.2-20230921.100330-srg.jar%23189!/assets/.mcassetsroot' uses unexpected schema
[23Dec2023 14:30:37.697] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/Users/maximilianohernandez/Library/Application%20Support/minecraft/libraries/net/minecraft/client/1.20.2-20230921.100330/client-1.20.2-20230921.100330-srg.jar%23189!/data/.mcassetsroot' uses unexpected schema
[23Dec2023 14:30:37.726] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[23Dec2023 14:30:38.373] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: _m4tz_
[23Dec2023 14:30:38.622] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.2+13
[23Dec2023 14:30:38.743] [Render thread/INFO] [Rubidium-PostlaunchChecks/]: OpenGL Vendor: Intel Inc.
[23Dec2023 14:30:38.744] [Render thread/INFO] [Rubidium-PostlaunchChecks/]: OpenGL Renderer: Intel(R) HD Graphics 6000
[23Dec2023 14:30:38.744] [Render thread/INFO] [Rubidium-PostlaunchChecks/]: OpenGL Version: 4.1 INTEL-18.8.6
[23Dec2023 14:30:39.075] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §ebalm§r requires §6neoforge§r §o20.2 or above§r
§7Currently, §6neoforge§r§7 is §o§nnot installed
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.20.2-48.1.0.jar%23190!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:96) ~[fmlcore-1.20.2-48.1.0.jar%23190!/:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:128) ~[fmlcore-1.20.2-48.1.0.jar%23190!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:73) ~[forge-1.20.2-48.1.0-universal.jar%23194!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:93) ~[forge-1.20.2-48.1.0-universal.jar%23194!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:73) ~[forge-1.20.2-48.1.0-universal.jar%23194!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:468) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.main.Main.main(Main.java:185) ~[1.20.2-forge-48.1.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?]
	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?]
[23Dec2023 14:30:39.144] [Render thread/INFO] [net.minecraft.server.packs.repository.FolderRepositorySource/]: Found non-pack entry '/Users/maximilianohernandez/Library/Application Support/minecraft/resourcepacks/.DS_Store', ignoring
[23Dec2023 14:30:39.289] [Render thread/WARN] [net.minecraft.client.Options/]: Removed resource pack mod_resources from options because it doesn't seem to exist anymore
[23Dec2023 14:30:39.445] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Ghastly13** [comment]
You're not using NeoForge

**Comment by Ghastly13** [comment]
Definitely not a bug
