### ISSUE TITLE
[Bug] Game crash when looking at recipes added by Create 0.5.1-f

### ISSUE THREAD

**Issue by SageofTurtles** [shedaniel/RoughlyEnoughItems#1600]
### What happened?

Kind of difficult to explain, since I'm struggling to find the exact cause of the crashes.  As best I can tell, when hovering the mouse over certain recipes, there is some bug with the tooltip that causes the game to crash.  I've only found this bug occurring with recipes added by the Create mod (I've seen it with recipes using the 'mixing', 'splashing', and 'deploying' crafting methods so far, but it would take considerably more testing for me to rule out any others).  I am also using Farmer's Delight and Create: Slice & Dice, but recipes from these mods don't seem to be causing crashes.  It only happens when hovering over certain items when viewing these Create mod recipes (both standard and some custom recipes I added via datapack which have never caused me issues before), and there seems to be consistency with which recipe slots trigger the crashes (e.g. with 'mixing' recipes, the second input ingredient always seems to cause a crash when hovered over it, even for different mixing recipes it is always the same ingredient slot that does it).  Hopefully this can be resolved, but please let me know if I can provide any more information to assist with this issue!

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2024-03-23 21:27:06
Description: Getting tooltips

java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at com.simibubi.create.compat.rei.category.CreateRecipeCategory.lambda$addStochasticTooltip$2(CreateRecipeCategory.java:137)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:199)
	at me.shedaniel.rei.api.common.entry.EntryStack.getTooltip(EntryStack.java:225)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:444)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.queueTooltip(EntryWidget.java:432)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:387)
	at me.shedaniel.rei.impl.client.gui.widget.MergedWidget.method_25394(MergedWidget.java:50)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25394(DelegateWidgetWithTranslate.java:58)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:336)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)

-- Screen details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:219)
	at me.shedaniel.rei.api.common.entry.EntryStack.getTooltip(EntryStack.java:225)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:444)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.queueTooltip(EntryWidget.java:432)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:387)
	at me.shedaniel.rei.impl.client.gui.widget.MergedWidget.method_25394(MergedWidget.java:50)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25394(DelegateWidgetWithTranslate.java:58)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:336)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: create:zinc_nugget

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: zinc_nugget
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen render details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
	Mouse location: Scaled: (370, 145). Absolute: (1110.000000, 436.000000)
	Screen size: Scaled: (640, 337). Absolute: (1920, 1009). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['SageofTurtles'/4, l='ClientLevel', x=1.38, y=41.00, z=-12.82]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,41,0), Section: (at 0,9,0 in 0,2,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 20400 game time, 1 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Standard Vanilla Tweaks.zip, file/v2_[Darkmode]Enhanched_Travelers_Backpack_GUI.zip, railways:green_signals

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 591813160 bytes (564 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 4800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.89
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: DriverVersion=31.0.12014.6
	Graphics card #1 name: NVIDIA GeForce RTX 2060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f15
	Graphics card #1 versionInfo: DriverVersion=31.0.15.5186
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26029.60
	Virtual memory used (MB): 17815.47
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 102.80
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 9.2.14
		athena: Athena 3.1.2
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chipped: Chipped 3.0.4
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		copycats: Create: Copycats+ 1.20.1-1.2.2
		create: Create 0.5.1-f-build.1335+mc1.20.1
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
			porting_lib_base: Porting Lib Base 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.0+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.0+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.0+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.0+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.0+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
			porting_lib_models: Porting Lib Models 2.3.0+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.0+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_enchantment_industry: Create Enchantment Industry 1.2.16
			create_dragon_lib: Create Dragon Lib 1.4.2
		create_jetpack: Create Jetpack 4.2.0
			flightlib: Flight Lib 2.1.0
		createdeco: Create Deco 2.0.1-1.20.1-fabric
		decorative_blocks: Decorative Blocks 4.1.3
		doapi: [Let's Do] API 1.2.9
			blue_endless_jankson: jankson 1.2.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		extended_drawers: Extended Drawers 2.1.1+mc.1.20.1
			config_toolkit: ConfigToolkit 1.0.0
				io_determann_shadow-api-17: shadow-api-17 0.1.1
				net_fabricmc_javapoet: javapoet 0.1.0
			graphlib: Graph Lib 1.4.0+1.20
				kmodlib-overlay: KModLib Overlay 0.2.12+1.20
				libnetworkstack: Lib Network Stack 0.10.0
			noindium: No Indium? 1.1.0+1.20
			yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
				com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		gravestones: Gravestones 1.0.3-1.20.1
		indium: Indium 1.0.30+mc1.20.4
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20.1
		pneumonocore: PneumonoCore 1.1.3+1.20.1
		railways: Create: Steam 'n' Rails 1.5.3+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		resourcefullib: Resourceful Lib 2.1.23
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		sliceanddice: Create Slice & Dice 3.1.0
		sodium: Sodium 0.5.8+mc1.20.1
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		vinery: [Let's Do] Vinery 1.4.12-1
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.15.7-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.86, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/Standard Vanilla Tweaks.zip, file/v2_[Darkmode]Enhanched_Travelers_Backpack_GUI.zip (incompatible), railways:green_signals
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 4800H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['SageofTurtles'/4, l='ServerLevel[Create 0.5.1.f Modpack Testing]', x=1.38, y=41.00, z=-12.82]]
	Data Packs: vanilla, fabric, file/Compression Drawers v0.2.zip, file/Crafting Tweaks.zip, file/Custom Recipes v1.4.zip, file/afk display v1.1.6 (MC 1.20-1.20.4).zip, file/anti enderman grief v1.1.6 (MC 1.20-1.20.4).zip, file/cauldron concrete v2.0.9 (MC 1.20-1.20.4).zip, file/custom nether portals v2.3.9 (MC 1.20-1.20.4).zip, file/custom villager shops v1.2.6 (MC 1.20-1.20.4).zip, file/double shulker shells v1.3.6 (MC 1.20-1.20.4).zip, file/dragon drops v1.3.6 (MC 1.20-1.20.4).zip, file/fxnt_create_chipped.zip, file/item averages v1.3.7 (MC 1.20-1.20.4).zip, file/multiplayer sleep v2.6.6 (MC 1.20-1.20.4).zip, file/pillager tools v1.1.6 (MC 1.20-1.20.4).zip, file/silence mobs v1.2.1 (MC 1.20-1.20.4).zip, file/unlock all recipes v2.0.7 (MC 1.20-1.20.4).zip, file/villager death messages v1.2.7 (MC 1.20-1.20.4).zip, file/villager workstation highlights v1.1.6 (MC 1.20-1.20.4).zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by SageofTurtles** [comment]
Probably worth noting also, but I only began running into this bug when updating my modpack for Create 0.5.1.f (was previously using 0.5.1.d for Fabric).  This issue didn't occur before updating, but I've also had to update a number of other mods as well as Fabric itself for the sake of compatibility, so I can't be sure if any other changes may have been the cause of this error.

**Comment by Hyperbuss** [comment]
I'm getting this as well, with both REI and JEI, so I think it's an issue on Create's end

**Comment by SageofTurtles** [comment]
> I'm getting this as well, with both REI and JEI, so I think it's an issue on Create's end

Could be, I'll report it to them too. Gave EMI a try as an alternative, and that one seems to work just fine for me (in case anyone is looking for an alternative).

**Comment by Poopooracoocoo** [comment]
> so I think it's an issue on Create's end

Yes. It's been fixed but a release has yet to be made. https://github.com/Fabricators-of-Create/Create/issues/1380#issuecomment-2002030992
