### ISSUE TITLE
[Bug] java.lang.AssertionError: REI Internals have not been initialized!

### ISSUE THREAD

**Issue by WestPrime** [shedaniel/RoughlyEnoughItems#1607]
### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2024-04-04 20:20:09
Description: mouseClicked event handler

java.lang.AssertionError: REI Internals have not been initialized!
	at me.shedaniel.rei.impl.Internals.throwNotSetup(Internals.java:60) ~[RoughlyEnoughItems-9.1.682-forge.jar%23290!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.Internals.getInternalLogger(Internals.java:117) ~[RoughlyEnoughItems-9.1.682-forge.jar%23290!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.impl.common.InternalLogger.getInstance(InternalLogger.java:33) ~[RoughlyEnoughItems-9.1.682-forge.jar%23290!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.tags.TagLoader.handler$zli000$loadPost(TagLoader.java:599) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinTagLoader,pl:mixin:APP:almostunified-common.mixins.json:runtime.TagLoaderMixin,pl:mixin:A}
	at net.minecraft.tags.TagLoader.m_203898_(TagLoader.java:173) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinTagLoader,pl:mixin:APP:almostunified-common.mixins.json:runtime.TagLoaderMixin,pl:mixin:A}
	at net.minecraft.tags.TagLoader.m_203900_(TagLoader.java:177) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinTagLoader,pl:mixin:APP:almostunified-common.mixins.json:runtime.TagLoaderMixin,pl:mixin:A}
	at net.minecraft.tags.TagManager.m_203920_(TagManager.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rei.mixins.json:MixinTagManager,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Roughly Enough Items (REI) (roughlyenoughitems), Version: 9.1.682
		Issue tracker URL: https://github.com/shedaniel/RoughlyEnoughItems/issues
		at TRANSFORMER/roughlyenoughitems@9.1.682/me.shedaniel.rei.impl.Internals.throwNotSetup(Internals.java:60)
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screens.TitleScreen
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7] {re:mixin}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:mixins.oculus.json:MixinGlStateManager,pl:mixin:APP:mixins.oculus.json:MixinRenderSystem,pl:mixin:APP:mixins.oculus.json:statelisteners.MixinRenderSystem,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:core.MixinWindow,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.MainWindowAccessor,pl:mixin:APP:rubidium_extras.mixins.json:BorderlessFullscreen.WindowMixin,pl:mixin:APP:mixins.oculus.json:MixinWindow,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:xaeroplus.mixins.json:mc.MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:xaeroplus.mixins.json:mc.MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23303!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.9.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, ic2loader, , Supplementaries Generated Pack, quark-emote-pack, SmoothFont_1.19.X.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1409959160 bytes (1344 MiB) / 3061841920 bytes (2920 MiB) up to 9093251072 bytes (8672 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2187
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5186
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28109.75
	Virtual memory used (MB): 15614.34
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 54.25
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8672m -Xms256m
	Loaded Shaderpack: ComplementaryUnbound_r5.1.1.zip
		Profile: HIGH (+0 options changed by user)
	Launched Version: forge-43.3.9
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.86, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, mod:ic2loader, mod:ic2c (incompatible), Supplementaries Generated Pack, quark:emote_resources (incompatible), file/SmoothFont_1.19.X.zip
	Current Language: Русский (Россия)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.9.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.9.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.9.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.9.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.9.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		rsrequestify-1.19.2-2.3.1.jar                     |RSRequestify                  |rsrequestify                  |2.3.1               |DONE      |Manifest: NOSIGNATURE
		dynamiclightsreforged-1.19.2_v1.4.0.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.19.2_v1.4.0       |DONE      |Manifest: NOSIGNATURE
		CyclopsCore-1.19.2-1.19.0.jar                     |Cyclops Core                  |cyclopscore                   |1.19.0              |DONE      |Manifest: NOSIGNATURE
		caveore-1.19.2-2.3.jar                            |CaveOre Mod                   |caveore                       |1.19.2-2.3          |DONE      |Manifest: NOSIGNATURE
		IntegratedTerminals-1.19.2-1.4.11.jar             |IntegratedTerminals           |integratedterminals           |1.4.11              |DONE      |Manifest: NOSIGNATURE
		connectivity-1.19.2-4.6.jar                       |Connectivity Mod              |connectivity                  |1.19.2-4.6          |DONE      |Manifest: NOSIGNATURE
		rubidium-mc1.19.2-0.6.2c.jar                      |Rubidium                      |rubidium                      |0.6.2c              |DONE      |Manifest: NOSIGNATURE
		gpumemleakfix-1.19.2-1.6.jar                      |Gpu memory leak fix           |gpumemleakfix                 |1.19.2-1.6          |DONE      |Manifest: NOSIGNATURE
		[1.19.2] Armor Status HUD-1.5.1.jar               |Armor Status HUD              |armorstatushud                |1.5.1               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+14.jar                  |Clumps                        |clumps                        |9.0.0+14            |DONE      |Manifest: NOSIGNATURE
		fastasyncworldsave-1.19.2-1.2.jar                 |fastasyncworldsave mod        |fastasyncworldsave            |1.19.2-1.2          |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.19.2-10.0+7.jar               |Controlling                   |controlling                   |10.0+7              |DONE      |Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-9.0.90.jar         |REI Plugin Compatibilities    |rei_plugin_compatibilities    |9.0.90              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.19.2-1.10.0-forge.jar            |Nature's Compass              |naturescompass                |1.19.2-1.10.0-forge |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		universalgrid-1.19.2-1.1.jar                      |Universal Grid                |universalgrid                 |1.19.2-1.1          |DONE      |Manifest: NOSIGNATURE
		farsight-1.19.2-3.6.jar                           |Farsight mod                  |farsight_view                 |1.19.2-3.6          |DONE      |Manifest: NOSIGNATURE
		Terralith_1.19.3_v2.3.12.jar                      |Terralith                     |terralith                     |2.3.12              |DONE      |Manifest: NOSIGNATURE
		dynview-1.19.1-2.9.jar                            |Dynamic view distance         |dynview                       |2.3                 |DONE      |Manifest: NOSIGNATURE
		rubidium_extras-1.19.2_v1.4.3.jar                 |Rubidium Extras               |rubidium_extras               |1.19.2_v1.4.3       |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.3.115-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.115             |DONE      |Manifest: NOSIGNATURE
		[1.19.2] BobLib-0.3.2.jar                         |BobLib                        |boblib                        |0.3.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.3.9-universal.jar                 |Forge                         |forge                         |43.3.9              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		refinedstorage-1.11.7.jar                         |Refined Storage               |refinedstorage                |1.11.7              |DONE      |Manifest: NOSIGNATURE
		easy_piglins-1.19.2-1.0.0.jar                     |Easy Piglins                  |easy_piglins                  |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		PlayerAbilityLib-forge-b2d633b0ae.jar             |Pal                           |playerabilitylib              |1.6.0               |DONE      |Manifest: NOSIGNATURE
		smoothchunk-1.19.2-3.5.jar                        |Smoothchunk mod               |smoothchunk                   |1.19.2-3.5          |DONE      |Manifest: NOSIGNATURE
		logprot-1.19.2-1.9.jar                            |Logprot                       |logprot                       |1.4                 |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19.2-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.4        |DONE      |Manifest: NOSIGNATURE
		endsdelight-1.19.2-1.2.1.jar                      |End's Delight                 |ends_delight                  |1.19.2-1.2.1        |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.19-6.2.2.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.2          |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.3.6-forge.jar                  |Moonlight Library             |moonlight                     |1.19.2-2.3.6        |DONE      |Manifest: NOSIGNATURE
		CommonCapabilities-1.19.2-2.9.1.jar               |CommonCapabilities            |commoncapabilities            |2.9.1               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |DONE      |Manifest: NOSIGNATURE
		mysterious_mountain_lib-1.2.3-1.19.2.jar          |Mysterious Mountain Lib       |mysterious_mountain_lib       |1.2.3-1.19.2        |DONE      |Manifest: NOSIGNATURE
		endersdelight-1.19-1.2.2.jar                      |Ender's Delight               |endersdelight                 |1.19-1.2.2          |DONE      |Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.9.1.jar                       |Jade                          |jade                          |8.9.1               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.12.8+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.8+1.19.2       |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.19-3.1.jar                       |Nether's Delight              |nethersdelight                |1.19-3.1            |DONE      |Manifest: NOSIGNATURE
		IntegratedScripting-1.19.2-1.0.1.jar              |IntegratedScripting           |integratedscripting           |1.0.1               |DONE      |Manifest: NOSIGNATURE
		TextruesRubidiumOptions-1.0.7-mc1.19.2.jar        |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.7-mc1.19.2      |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.19.2-4.1.jar                      |betterfpsdist mod             |betterfpsdist                 |1.19.2-4.1          |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.19.2-1.0.17.jar                  |Easy Villagers                |easy_villagers                |1.19.2-1.0.17       |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.6.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.6.1      |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.9.13.jar                     |Mekanism                      |mekanism                      |10.3.9              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.9.13.jar           |Mekanism: Generators          |mekanismgenerators            |10.3.9              |DONE      |Manifest: NOSIGNATURE
		IC2Classic-1.19.2-2.0.9.2.jar                     |IC2 Classic                   |ic2                           |1.19.2-2.0.9.2      |DONE      |Manifest: NOSIGNATURE
		advancedsolars-2.0.5.jar                          |Advanced Solars Classic       |advanced_solars               |2.0.5               |DONE      |Manifest: NOSIGNATURE
		jadexic2c-1.19.2-1.0.8.jar                        |IC2Classic Jade Plugin        |jadexic2c                     |1.19.2-1.0.8        |DONE      |Manifest: NOSIGNATURE
		IC2CExtras-2.0.2.jar                              |IC2C Extras                   |ic2c_extras                   |2.0.2               |DONE      |Manifest: NOSIGNATURE
		ic2c-additions-1.19.2-1.0.1.jar                   |IC2C Additions                |ic2cadditions                 |1.19.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.19.2-1.6.9.jar                         |Oculus                        |oculus                        |1.6.9               |DONE      |Manifest: NOSIGNATURE
		IntegratedDynamics-1.19.2-1.21.2.jar              |IntegratedDynamics            |integrateddynamics            |1.21.2              |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.46.6+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.6+1.19.2       |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |DONE      |Manifest: NOSIGNATURE
		Quark-3.4-418.jar                                 |Quark                         |quark                         |3.4-418             |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.4.20.jar                 |Supplementaries               |supplementaries               |1.19.2-2.4.20       |DONE      |Manifest: NOSIGNATURE
		almostunified-forge-1.19.2-0.8.1.jar              |AlmostUnified                 |almostunified                 |1.19.2-0.8.1        |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-9.1.682-forge.jar              |Roughly Enough Items (REI)    |roughlyenoughitems            |9.1.682             |DONE      |Manifest: NOSIGNATURE
		IC2ClassicREICompat-1.19.2-1.0.2.jar              |IC2 - REI Plugin              |ic2rei                        |1.19.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		IntegratedTunnels-1.19.2-1.8.24.jar               |IntegratedTunnels             |integratedtunnels             |1.8.24              |DONE      |Manifest: NOSIGNATURE
		betterchunkloading-1.19.2-2.5.jar                 |betterchunkloading mod        |betterchunkloading            |1.19.2-2.5          |DONE      |Manifest: NOSIGNATURE
		integratednbt-1.19.2-1.6.0.jar                    |Integrated NBT                |integratednbt                 |1.6.0               |DONE      |Manifest: NOSIGNATURE
		XaeroPlus-2.6+forge-1.19.2-WM1.38.1-MM24.0.3.jar  |XaeroPlus                     |xaeroplus                     |2.6                 |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.38.1_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.38.1              |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_24.0.3_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |24.0.3              |DONE      |Manifest: NOSIGNATURE
		oceansdelight-1.0.2-1.19.2.jar                    |Ocean's Delight               |oceansdelight                 |1.0.2-1.19.2        |DONE      |Manifest: NOSIGNATURE
		architectury-6.6.92-forge.jar                     |Architectury                  |architectury                  |6.6.92              |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		moreoverlays-1.21.9-mc1.19.2.jar                  |More Overlays Updated         |moreoverlays                  |1.21.9-mc1.19.2     |DONE      |Manifest: NOSIGNATURE
		cupboard-1.19.2-2.6.jar                           |Cupboard utilities            |cupboard                      |1.19.2-2.6          |DONE      |Manifest: NOSIGNATURE
		corn_delight-1.0.3-1.19.2.jar                     |Corn Delight                  |corn_delight                  |1.0.3-1.19.2        |DONE      |Manifest: NOSIGNATURE
		gravisuit-2.3.jar                                 |Gravisuit Classic             |gravisuit                     |2.3                 |DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.19.2-forge-3.6.0.jar                 |Jade Addons                   |jadeaddons                    |3.6.0               |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.9.0.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.9.0               |DONE      |Manifest: NOSIGNATURE
		refinedpolymorph-0.1.1-1.19.2.jar                 |Refined Polymorphism          |refinedpolymorph              |0.1.1-1.19.2        |DONE      |Manifest: NOSIGNATURE
		extremesoundmuffler-3.39-forge-1.19.2.jar         |Extreme Sound Muffler         |extremesoundmuffler           |3.39-forge-1.19.2   |DONE      |Manifest: NOSIGNATURE
		Delightful-1.19.2-3.4.1.jar                       |Delightful                    |delightful                    |3.4.1               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19.2-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19.2-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		chunksending-1.19.2-2.8.jar                       |chunksending mod              |chunksending                  |1.19.2-2.8          |DONE      |Manifest: NOSIGNATURE
		carbon-config-92RIAvni.jar                        |Carbon Config Library         |carbonconfig                  |1.19.2-1.1.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f671c7b0-a6a4-44af-86a7-72bb25790860
	FML: 43.3
	Forge: net.minecraftforge:43.3.9
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
REI Forge is incompatible with More Overlays because it already provides parts of that mod. Use Light Overlay or any other similar mods.
