### ISSUE TITLE
[Bug] On Fabric 0.15.10 for Minecraft Version 1.20.6, REI Pretends it Doesn't have any Dependencies (Formerly "Minecraft Won't Launch w/ REI")

### ISSUE THREAD

**Issue by CaptainAdams** [shedaniel/RoughlyEnoughItems#1624]
### What happened?
Sorry about that. NOW it's exactly what it says in the title. Instead of telling you about the required dependencies, the game just gets itself stuck on "Compatibility level set to JAVA_17," leading to the possibility of people new to the whole modded minecraft thing (and people who have piss-poor reading skills[me]) thinking REI's mere existence is causing their game to be unable to launch.

(Formerly "Exactly what the title says. Only other mod installed is Fabric API and the log never gets past 'Compatibility level set to JAVA_17'")

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
null[21:28:32] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.10
[21:28:32] [main/INFO]: Loading 55 mods:
	- fabric-api 0.97.8+1.20.6
	   |-- fabric-api-base 0.4.40+80f8cf51ff
	   |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72bff
	   |-- fabric-biome-api-v1 13.0.25+be5d88beff
	   |-- fabric-block-api-v1 1.0.20+6dfe4c9bff
	   |-- fabric-block-view-api-v2 1.0.8+80f8cf51ff
	   |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf51ff
	   |-- fabric-client-tags-api-v1 1.1.12+7f945d5bff
	   |-- fabric-command-api-v1 1.2.45+f71b366fff
	   |-- fabric-command-api-v2 2.2.24+80f8cf51ff
	   |-- fabric-commands-v0 0.2.62+df3654b3ff
	   |-- fabric-content-registries-v0 8.0.4+b82b2392ff
	   |-- fabric-convention-tags-v1 2.0.3+7f945d5bff
	   |-- fabric-convention-tags-v2 2.0.0+2b43c5c8ff
	   |-- fabric-crash-report-info-v1 0.2.27+80f8cf51ff
	   |-- fabric-data-attachment-api-v1 1.1.15+2a2c66b6ff
	   |-- fabric-data-generation-api-v1 19.0.6+7f945d5bff
	   |-- fabric-dimensions-v1 2.1.68+94793913ff
	   |-- fabric-entity-events-v1 1.6.8+e9d2a72bff
	   |-- fabric-events-interaction-v0 0.7.6+c5fc38b3ff
	   |-- fabric-game-rule-api-v1 1.0.50+80f8cf51ff
	   |-- fabric-item-api-v1 8.1.1+17e985d6ff
	   |-- fabric-item-group-api-v1 4.0.38+aae0949aff
	   |-- fabric-key-binding-api-v1 1.0.45+80f8cf51ff
	   |-- fabric-keybindings-v0 0.2.43+df3654b3ff
	   |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b3ff
	   |-- fabric-loot-api-v2 3.0.4+97f703daff
	   |-- fabric-message-api-v1 6.0.10+109a837cff
	   |-- fabric-model-loading-api-v1 1.0.12+80f8cf51ff
	   |-- fabric-models-v0 0.4.11+9386d8a7ff
	   |-- fabric-networking-api-v1 4.0.8+0dca0349ff
	   |-- fabric-object-builder-api-v1 15.1.3+c5fc38b3ff
	   |-- fabric-particles-v1 4.0.0+c5fc38b3ff
	   |-- fabric-recipe-api-v1 5.0.3+c5fc38b3ff
	   |-- fabric-registry-sync-v0 5.0.15+f1240ba7ff
	   |-- fabric-renderer-api-v1 3.2.12+97f703daff
	   |-- fabric-renderer-indigo 1.5.12+80f8cf51ff
	   |-- fabric-renderer-registries-v1 3.2.61+df3654b3ff
	   |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eff
	   |-- fabric-rendering-fluids-v1 3.1.3+2c869dedff
	   |-- fabric-rendering-v0 1.1.64+df3654b3ff
	   |-- fabric-rendering-v1 4.2.4+b21c00cbff
	   |-- fabric-resource-conditions-api-v1 4.0.1+74e2f560ff
	   |-- fabric-resource-loader-v0 1.0.5+c5f2432cff
	   |-- fabric-screen-api-v1 2.0.21+7b70ea8aff
	   |-- fabric-screen-handler-api-v1 1.3.72+b21c00cbff
	   |-- fabric-sound-api-v1 1.0.21+c5fc38b3ff
	   |-- fabric-transfer-api-v1 5.1.6+c5fc38b3ff
	   \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f560ff
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.20.6
	- roughlyenoughitems 15.0.728
	   \-- error_notifier 1.0.9
[21:28:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:28:32] [main/INFO]: Compatibility level set to JAVA_17
```

### Anything else?

Again, sorry about being an idiot and not double checking my dependencies despite the fact that part of the issue opening process asks you to check your dependencies. Updated this Issue instead of opening a new one because the thread can be helpful to people like me and the underlying issue is still technically the same.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes [but actually this time]

**Comment by FoketzoRAI** [comment]
Have the same issue. Game is just black window and freezes.

**Comment by davepusey** [comment]
Same here. Black frozen window. Have to kill off the java process via task manager. Removing REI mod jar clears the issue.

**Comment by DasBabyPixel** [comment]
Following error is getting spammed in console (in dev environment) (v15.0.728)
```
java.lang.RuntimeException: Resource not found: /assets/minecraft/textures/gui/options_background.png
	at me.shedaniel.errornotifier.fabric.ErrorNotifierPlatformImpl.lambda$getResourceResolver$0(ErrorNotifierPlatformImpl.java:30)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.lambda$registerTexture$0(EarlyGraphics.java:178)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.registerTexture(EarlyGraphics.java:185)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.registerTexture(EarlyGraphics.java:178)
	at me.shedaniel.errornotifier.launch.EarlyGraphics._bindTexture(EarlyGraphics.java:204)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.bindTexture(EarlyGraphics.java:106)
	at me.shedaniel.errornotifier.client.DynamicErrorFreeEntryListWidget.renderBackBackground(DynamicErrorFreeEntryListWidget.java:122)
	at me.shedaniel.errornotifier.client.DynamicErrorFreeEntryListWidget.render(DynamicErrorFreeEntryListWidget.java:132)
	at me.shedaniel.errornotifier.client.ErrorRenderer.render(ErrorRenderer.java:42)
	at me.shedaniel.errornotifier.launch.EarlyWindow.render(EarlyWindow.java:235)
	at me.shedaniel.errornotifier.launch.EarlyWindow.renderWindow(EarlyWindow.java:226)
	at me.shedaniel.errornotifier.launch.EarlyWindow.start(EarlyWindow.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at me.shedaniel.errornotifier.ErrorNotifier.init(ErrorNotifier.java:43)
	at me.shedaniel.errornotifier.fabric.ErrorNotifierFabric.onPreLaunch(ErrorNotifierFabric.java:11)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by a89792** [comment]
> Following error is getting spammed in console (in dev environment) (v15.0.728)
> 
> ```
> java.lang.RuntimeException: Resource not found: /assets/minecraft/textures/gui/options_background.png
> 	at me.shedaniel.errornotifier.fabric.ErrorNotifierPlatformImpl.lambda$getResourceResolver$0(ErrorNotifierPlatformImpl.java:30)
> 	at me.shedaniel.errornotifier.launch.EarlyGraphics.lambda$registerTexture$0(EarlyGraphics.java:178)
> ```

this file removed in 24w09a

**Comment by Jab125** [comment]
You may need **Cloth Config** to get REI to work.

**Comment by davepusey** [comment]
> You may need **Cloth Config** to get REI to work.

Already had that, and still issue persists.

**Comment by Jab125** [comment]
> > You may need **Cloth Config** to get REI to work.
> 
> Already had that, and still issue persists.

could you send the logs of that as well?

**Comment by davepusey** [comment]
I get the same repeating message that DasBabyPixel posted above.

**Comment by davepusey** [comment]
Hmm, I just tried it again and this list appears to actually work now. Not sure what changed.

![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/787745/eec22a30-5aa9-4bee-aa19-2a1deb597197)

**Comment by davepusey** [comment]
Looks like adding "architectury-12.0.27-fabric.jar" is the key to fixing it. Prism shows it as a dependency, but the game doesn't complain with the usual "Unmet Dependency Listing" if it is missing and just hangs instead.

**Comment by davepusey** [comment]
Confirming REI on 1.20.6

![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/787745/d7090f9a-37b6-4075-9469-cd3b5793a7b7)

**Comment by CompaqDisc** [comment]
> Looks like adding "architectury-12.0.27-fabric.jar" is the key to fixing it. Prism shows it as a dependency, but the game doesn't complain with the usual "Unmet Dependency Listing" if it is missing and just hangs instead.

This is what fixed it for me, thanks!

**Comment by Poopooracoocoo** [comment]
https://github.com/shedaniel/error-notifier/issues/3
