### ISSUE TITLE
[Bug] Trying to look up custom recipes in 1.20.5 doesn't work (Fabric)

### ISSUE THREAD

**Issue by regfunkid** [shedaniel/RoughlyEnoughItems#1627]
### What happened?

**What happened:** I installed version 1.20.5, tried to look up the name of a recipe I've added, and nothing came up.
The recipe in question is for a custom item I added using a datapack, and a resourcepack. 

**What I expected to happen:** It shows up in the Recipe Book, so I thought it would appear in the REI menu. 
(That being said, you can't disable the recipe book with REI which seems to be a bug as well?) 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[04:06:46] [REI-ReloadPlugins/ERROR]:
 [REI] Failed to collect creative tab: net.minecraft.class_1761@15995647
java.lang.IllegalStateException: Registry minecraft:banner_pattern not found
	at net.minecraft.class_7225$class_7874.method_46763(class_7225.java:107) ~[client-intermediary.jar:?]
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraft.class_7225$class_7874.method_46762(class_7225.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_7706.method_51332(class_7706.java:1261) ~[client-intermediary.jar:?]
	at me.shedaniel.rei.impl.client.fabric.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:56) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:193) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:154) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:417) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:407) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:405) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:483) ~[RoughlyEnoughItems-15.0.728-fabric.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

### Anything else?

I saw another report about custom items that i think you've already seen, but that was about server-side plugin items. This report is about datapacks adding recipes, specifically utilizing the new Components added by 1.20.5 to effectively change the resulting item.
Although all the items are technically just 1 item (a firework star, in my case), they all have unique names, textures, and data.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by regfunkid** [comment]
I'm also unsure if that log data is at all related to my issue, I just saw it in the server logs for my world. Nothing else related to my issue came up there.
