### ISSUE TITLE
[Bug] Unable to use Fabric Data Generation on 1.20.5+ (15.0.728)

### ISSUE THREAD

**Issue by A5ho9999** [shedaniel/RoughlyEnoughItems#1632]
### What happened?

When trying to run Data Generation the mod causes an error preventing the data generation from completing. It also fails when attempting to runServer but works fine when loading client.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[11:42:33] [main/ERROR] (Minecraft) Failed to start the minecraft server
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:117) [minecraft-merged-4b736d393f-1.20.6-net.fabricmc.yarn.1_20_6.1.20.6+build.1-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore

	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy32.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Roughly Enough Items. Please use "rei_server", "rei_client" or "rei_common" instead.
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Roughly Enough Items. Please use "rei_server", "rei_client" or "rei_common" instead.

	at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:52) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:108) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:139) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:174) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy32.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Sir-Antonic** [comment]
I am also having this issue with V. 15.0.728

While doing some more testing, It would seem (at least on my end) that the Data Generation will only error out when I add the REI dependencies to my build.gradle file. If I comment those out but leave my fabric.mod.json alone it lets me Generate my data. If I just remove the portion in fabric.mod.json for rei_client but leave the dependencies it still crashes for some reason.

So for some reason having the REI dependencies in my mod stops Data Generation from performing with the error mentioned above.

For debug reference, here is what my dependencies look like (because I may have it set up incorrectly.)

BUILD.GRADLE
```
// REI Compatibility Dependency
	modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${project.rei_version}"
	modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"

	modApi("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}

	modApi "dev.architectury:architectury-fabric:${project.architectury_version}"
```

then in my gradle.properties, I have rei_version setup like so

GRADLE.PROPERTIES
```
# REI mod for adding compatibility and also being used during gameplay test
rei_version=15.0.728
# Cloth Config to add compatibility for your mod
cloth_version=14.0.126
# Architectury is needed for REI mod compatibility development
architectury_version=12.0.1
```

**Comment by SHsuperCM** [comment]
Can confirm, having this issue as well. However this is not really to do with datagen and more with the server run. Datagen uses server instead of client to generate(to save resources and make it faster) but it seems that whenever rei is just in the runtime, server run configuration cannot be used.

Dependency used:
```groovy
modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${property('deps.rei')}"
```

Crash appears to be the same:
```
[09:37:44] [main/INFO] (FabricLoader/MixinExtras|Service) Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
EXCEPTION IN ENTRYPOINT: roughlyenoughitems->(0.3.x)me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer::onInitialize  (I have this log message set for entrypoint crashes using a breakpoint)
[09:37:58] [main/ERROR] (Minecraft) Failed to start the minecraft server
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:117) [minecraft-merged-d46619f804-1.20.6-net.fabricmc.yarn.1_20_6.1.20.6+build.3-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy32.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Roughly Enough Items. Please use "rei_server", "rei_client" or "rei_common" instead.
	at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:52) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:108) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:139) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:174) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-fabric-15.0.728.jar:?]
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy32.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
Disconnected from the target VM, address: '127.0.0.1:21238', transport: 'socket'

Process finished with exit code 0
```
