### ISSUE TITLE
[Bug] fromIndex(819) > toIndex(625)

### ISSUE THREAD

**Issue by seriousfreezing** [shedaniel/RoughlyEnoughItems#1641]
### What happened?

I have almost 100 crash-reports of the same bug, it always crashes when using REI.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 5/12/24, 6:05 PM
Description: Rendering screen

java.lang.IllegalArgumentException: fromIndex(819) > toIndex(625)
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.updateEntries(PaginatedEntryListWidget.java:140)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateEntriesPosition(EntryListWidget.java:266)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.CollapsingEntryListWidget.updateEntriesPosition(CollapsingEntryListWidget.java:67)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateArea(EntryListWidget.java:251)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.init(ScreenOverlayImpl.java:177)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:225)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:345)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.updateEntries(PaginatedEntryListWidget.java:140)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateEntriesPosition(EntryListWidget.java:266)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.CollapsingEntryListWidget.updateEntriesPosition(CollapsingEntryListWidget.java:67)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateArea(EntryListWidget.java:251)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.init(ScreenOverlayImpl.java:177)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:225)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:345)

-- Screen render details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
	Mouse location: Scaled: (432, 146). Absolute: (1298.000000, 439.000000)
	Screen size: Scaled: (640, 337). Absolute: (1920, 1009). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['SeriousFreezing'/20729, l='ClientLevel', x=11741.73, y=63.00, z=-12708.29]]
	Chunk stats: 1024, 249
	Level dimension: minecraft:overworld
	Level spawn location: World: (81,64,6), Section: (at 1,0,6 in 5,4,0; chunk contains blocks 80,-64,0 to 95,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 110032395 game time, 110282939 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: PFM-Runtime-RP, Default, Fabric Mods, VanillaTweaks.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4142100704 bytes (3950 MiB) / 6106906624 bytes (5824 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.45.0.0
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a2
	Graphics card #1 versionInfo: DriverVersion=31.0.15.5186
	Graphics card #2 name: Intel(R) UHD Graphics
	Graphics card #2 vendor: Intel Corporation (0x8086)
	Graphics card #2 VRAM (MB): 1024.00
	Graphics card #2 deviceId: 0x9a68
	Graphics card #2 versionInfo: DriverVersion=30.0.101.1273
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 42787.30
	Virtual memory used (MB): 26921.21
	Swap memory total (MB): 26624.00
	Swap memory used (MB): 1083.65
	JVM Flags: 58 total; -Xmx8096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseVectorCmov -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:AllocatePrefetchStyle=3 -XX:+UseG1GC -XX:MaxGCPauseMillis=37 -XX:+PerfDisableSharedMem -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:GCTimeRatio=99 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		ad_astra: Ad Astra 1.0.9
			team_reborn_energy: Energy 2.2.0
		advanced_reborn: Advanced Reborn 1.2.8
		ae2: Applied Energistics 2 11.7.6
			noindium: No Indium? 1.0.2+1.18.2
		ae2wtlib: AE2WTLib 11.6.3
		arcanus: Arcanus 1.29.2
		architectury: Architectury 4.12.94
		attributefix: AttributeFix 14.0.2
		autoconfig1u: Auto Config v1 Updated 3.4.0
		betterbeds: Better Beds 1.2.0
		bookshelf: Bookshelf 13.3.56
		botania: Botania 1.18.2-435-FABRIC
			fiber: fiber 0.23.0-2
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		botanypots: BotanyPots 8.1.32
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chipped: Chipped 2.0.1
		create: Create 0.5.1-f-build.1415+mc1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-39
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.4
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.1304-beta+1.18.2
				serialization_hooks: Serialization Hooks 0.3.23
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.11
		createaddition: Create Crafts & Additions 20230704a
		ctm: ConnectedTexturesMod for Fabric 1.0.0+1.18
		dankstorage: Dank Storage 1.18.2-3.9
		debugify: Debugify 1.11.0
		dynamic_fps: Dynamic FPS 3.4.3
		enchdesc: EnchantmentDescriptions 10.0.17
		explorerscompass: Explorer's Compass 1.18.2-2.2.0-fabric
		extended_drawers: Extended Drawers 1.3.7+mc.1.18.2
			graphlib: Graph Lib 0.2.4+1.18.2
			mconfig: Mconfig 1.2.0
				de_poiu_apron_apron: apron 2.1.1
		fabric-api: Fabric API 0.77.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.13+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.15+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+b7f3cf3460
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-furnaces: Fabric Furnaces 2.1.1-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 4.2.1
		freecam: Freecam (Modrinth Edition) 1.2.3
		fwaystones: Fabric Waystones 3.0.0+mc1.18.2
		gardenarsenal: Garden Arsenal 0.4.2
		geckolib3: Geckolib 3.0.80
			com_eliotlash_mclib_mclib: mclib 20
		gobber2: Gobber2 2.5.81
			pugh_lib: Pugh Lib 1.3.2
			pugh_tools: Pugh Tools 1.2.7
		haema: Haema 1.10.1+1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			patchouli: Patchouli 1.18.2-67-FABRIC
			pehkui: Pehkui 3.2.2+1.14.4-1.19
				kanos_config: Kanos Config 0.2.0+1.14.4-1.19
			satin: Satin 1.7.2
		hwg: Happiness is a Warm Gun 1.1.12
		immediatelyfast: ImmediatelyFast 1.1.12
			net_lenni0451_reflect: Reflect 1.1.0
		indium: Indium 1.0.7+mc1.18.2
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		iron-jetpacks: Iron Jetpacks 0.4.3
		jade: Jade 5.100.0
		java: OpenJDK 64-Bit Server VM 17
		kibe: Kibe 1.9.11-BETA+1.18
			playerabilitylib: Pal 1.5.0
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		lazydfu: LazyDFU 0.1.2
		led: Light Emitting Diode 1.2.4
			jmxl: JMXL 1.0
		lithium: Lithium 0.10.3
		lootr: Lootr 0.3.28.65
		mcpitanlib: MCPitanLib 2.2.4-1.18.2-fabric
			cloth-config: Cloth Config v6 6.5.116
				cloth-basic-math: cloth-basic-math 0.6.1
			org_yaml_snakeyaml: snakeyaml 2.0
		minecraft: Minecraft 1.18.2
		modern_industrialization: Modern Industrialization 1.2.3
			magna: Magna 1.7.0-1.18-pre1
		modernfix: ModernFix 5.17.0+mc1.18.2
		moreculling: More Culling 1.18.2-0.8.2
			conditional-mixin: conditional mixin 0.3.0
		mousetweaks: Mouse Tweaks 2.22
		mysticalcrops: Mystical Nature 1.8.5-1.18.2
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nerb: Not Enough Recipe Book 0.3
		offlineskins: OfflineSkins 1.18.2-v2-fabric
		opchanter: OPChanter 1.18.2-1.0.0-fabric
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				calio: Calio 1.5.1
		origins-plus-plus: Origins++ 2.2
		pfm: Paladin's Furniture 1.2.1
		powah: Powah! 3.0.8
		presencefootsteps: Presence Footsteps 1.5.1
			kirin: Kirin UI 1.10.0
		reinfchest: Reinforced Chests 2.2.0+1.18
			reinfcore: Reinforced Core 3.0.3+1.18
		replaymod: Replay Mod 1.18.2-2.6.15
		retraining: Retraining 1.1.0
		roughlyenoughitems: Roughly Enough Items 8.4.709
			error_notifier: Error Notifier 1.0.9
		securityforfabric: Security For Fabric 1.2.0-1.18.2
		shrink_rays: ShrinkRays 1.0
		simplevoidworld: Simple Void World 4.0.0
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		starlight: Starlight 1.0.2+fabric.89b8d9f
		stylish_occult: Stylish Occult 0.12.2
			interference: Interference API 1.5.0
			loot_boxes: Loot Boxes 0.1.5
		techreborn: Tech Reborn 5.2.1
			reborncore: Reborn Core 5.2.1
		the_aether: Paradise Lost 1.6.9+1.18.2
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.6.6+1.18.2
			moretags: More Tags 3.0.4
			trinkets: Trinkets 3.3.0
		tiered: Tiered 1.1.1
			additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
			autotag: AutoTag 1.1.0
		toolstats: ToolStats 9.0.3
		travelersbackpack: Traveler's Backpack fabric-1.18.2-7.1.39
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		twilightforest: The Twilight Forest 4.1.313
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
		wands: Building Wands 2.6.9-release
		wirelessnetworks: Wireless Networks 1.5.1
		xaerominimap: Xaero's Minimap 24.1.1
		xaeroworldmap: Xaero's World Map 1.38.4
		zenith: Zenith 0.3.0
			fake-player-api: Fake Player API 0.3.0
		zoomify: Zoomify 1.6.0+build.2
			dev_isxander_settxi_settxi-core: settxi-core 2.10.2
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.2
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.2
	Loaded Shaderpack: (off)
	Flywheel Backend: Parallel Batching
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.86, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: pfm-asset-resources, vanilla, Fabric Mods, file/VanillaTweaks.zip
	Current Language: English (US)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by seriousfreezing** [comment]
I've reinstalled the mod to see if it's a configuration problem. If it is, I'll open it again.
