### ISSUE TITLE
[Bug] Very odd loading issue

### ISSUE THREAD

**Issue by vizthex123** [shedaniel/RoughlyEnoughItems#1653]
### What happened?

I added some custom composting values with [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs), and had my game fail to load due to an error with REI. Tried it with [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker) and that didn't fix it. Removed both and that still didn't fix it.

Afterward, I deleted the mod's config folder and that fixed it.

I've heavily customized REI in this pack (added a couple dozen collapsible entries, hidden a hundred or so items, etc.), but I used a [JSON5 validator](https://jsonformatter.org/json5-validator) to check on the rare occasion I edited the file itself. Haven't had anything like this happen before trying to add my composter recipes.

Here's the full log from after I removed the compost scripts:
[latest.log](https://github.com/user-attachments/files/15541305/latest.log)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[19:56:15] [modloading-worker-0/ERROR]: Failed to load plugin: dev.yurisuika.compost.integration.roughlyenoughitems.CompostClientPlugin
java.lang.InstantiationException: null
	at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at me.shedaniel.rei.forge.AnnotationUtils.lambda$scanAnnotation$4(AnnotationUtils.java:92) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.PluginDetectorImpl.lambda$detectCommonPlugins$11(PluginDetectorImpl.java:156) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.AnnotationUtils.scanAnnotation(AnnotationUtils.java:116) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.AnnotationUtils.scanAnnotation(AnnotationUtils.java:52) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:155) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:174) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.RoughlyEnoughItemsForge.<init>(RoughlyEnoughItemsForge.java:41) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.6.jar%23624!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.6.jar%23623!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[19:56:15] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: roughlyenoughitems, class me.shedaniel.rei.forge.RoughlyEnoughItemsForge
java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.RoughlyEnoughItemsForge.<init>(RoughlyEnoughItemsForge.java:41) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.6.jar%23624!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.6.jar%23623!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.rei.api.common.plugins.REIPluginProvider.getPluginProviderName()" because "this.val$plugin" is null
	at me.shedaniel.rei.forge.PluginDetectorImpl$1.getPluginProviderName(PluginDetectorImpl.java:67) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.registerPlugin(PluginManagerImpl.java:117) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.PluginDetectorImpl.lambda$detectCommonPlugins$11(PluginDetectorImpl.java:156) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.AnnotationUtils.scanAnnotation(AnnotationUtils.java:116) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.AnnotationUtils.scanAnnotation(AnnotationUtils.java:52) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.forge.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:155) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:174) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-12.1.725-forge.jar%23570!/:?]
	... 16 more
```

### Anything else?

Reinstalling the mod after deleting the config still didn't allow it to load.

I don't know for sure, but I think Masterful Machinery might be causing it? The mod doesn't have REI support (although I did request it https://github.com/ticticboooomer/MasterfulMachinery/issues/69), but I still get the error message if I disable the mod.

**Edit:** I updated Forge (from 47.2.6 to 47.3.0) and that didn't fix it.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by vizthex123** [comment]
**Update:** I updated Forge (from 47.2.6 to 47.3.0) and that didn't fix it.

**Comment by vizthex123** [comment]
**Update:** I found out that the [Compost](https://www.curseforge.com/minecraft/mc-mods/compost) mod is what's causing it!

**Comment by ticticboooomer** [comment]
The error you showed along with the full log file clearly show that the error is 
`Failed to load plugin: dev.yurisuika.compost.integration.roughlyenoughitems.CompostClientPlugin`

I'm very sure this issue is far away from being even remotely related to Masterful Machinery.

If it is somehow related to MM, REI is not currently supported in any capacity, thus any issues will not be handled as it is not an issue with MM.
