### ISSUE TITLE
[Bug] Items do not appear in menu (NeoForge v16.0.729)

### ISSUE THREAD

**Issue by Shoes4Clues** [shedaniel/RoughlyEnoughItems#1662]
### What happened?

Items do not appear in the menu, and all pages are empty.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[16Jun2024 13:21:22.974] [REI-ReloadPlugins/INFO] [REI/]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[16Jun2024 13:21:22.975] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIPlugin starting main-reload for START.
[16Jun2024 13:21:22.976] [REI-ReloadPlugins/INFO] [REI/]: [REI] Plugins (5):
[16Jun2024 13:21:22.976] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:22.976] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:22.976] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[16Jun2024 13:21:22.976] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:22.976] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:22.977] [REI-ReloadPlugins/INFO] [REI/]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[16Jun2024 13:21:23.030] [REI-ReloadPlugins/INFO] [REI/]: [REI] ########################################
[16Jun2024 13:21:23.030] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIClientPlugin starting main-reload for START.
[16Jun2024 13:21:23.031] [REI-ReloadPlugins/INFO] [REI/]: [REI] Plugins (3):
[16Jun2024 13:21:23.031] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:23.031] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[16Jun2024 13:21:23.031] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:23.031] [REI-ReloadPlugins/INFO] [REI/]: [REI] ########################################
[16Jun2024 13:21:23.056] [REI-ReloadPlugins/ERROR] [REI/]: [REI] DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems] plugin failed to reloadable-plugin/EntryRegistryImpl/!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:197) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:156) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:417) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:407) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:405) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:483) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:195) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	... 18 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.level()" because "dev.architectury.utils.GameInstance.getClient().player" is null
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.api.common.display.basic.BasicDisplay.lambda$static$0(BasicDisplay.java:49) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.api.common.display.basic.BasicDisplay.registryAccess(BasicDisplay.java:67) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.impl.client.forge.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:48) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at TRANSFORMER/roughlyenoughitems@16.0.729/me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:195) ~[RoughlyEnoughItems-16.0.729-neoforge.jar%23272!/:?]
	... 18 more
[16Jun2024 13:21:23.147] [REI-ReloadPlugins/INFO] [REI/]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[16Jun2024 13:21:23.147] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIServerPlugin starting main-reload for START.
[16Jun2024 13:21:23.148] [REI-ReloadPlugins/INFO] [REI/]: [REI] Plugins (2):
[16Jun2024 13:21:23.148] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:23.148] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:23.148] [REI-ReloadPlugins/INFO] [REI/]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[16Jun2024 13:21:23.155] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIPlugin finished post-reload for START in 2.441 ms, totaling 85.61 ms.
[16Jun2024 13:21:23.159] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIClientPlugin finished post-reload for START in 2.435 ms, totaling 122.1 ms.
[16Jun2024 13:21:23.160] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIServerPlugin finished post-reload for START in 644.4 μs, totaling 5.137 ms.
[16Jun2024 13:21:23.787] [Render thread/WARN] [REI/]: [REI] Suppressing Reload Plugins of stage START
[16Jun2024 13:21:23.834] [REI-ReloadPlugins/INFO] [REI/]: [REI] ----------------------------------------
[16Jun2024 13:21:23.835] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIPlugin starting main-reload for END.
[16Jun2024 13:21:23.835] [REI-ReloadPlugins/INFO] [REI/]: [REI] Plugins (5):
[16Jun2024 13:21:23.835] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:23.835] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:23.836] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[16Jun2024 13:21:23.836] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:23.836] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:23.836] [REI-ReloadPlugins/INFO] [REI/]: [REI] ----------------------------------------
[16Jun2024 13:21:23.880] [REI-ReloadPlugins/INFO] [REI/]: [REI] ****************************************
[16Jun2024 13:21:23.880] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIClientPlugin starting main-reload for END.
[16Jun2024 13:21:23.881] [REI-ReloadPlugins/INFO] [REI/]: [REI] Plugins (3):
[16Jun2024 13:21:23.881] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultClientPluginImpl of DefaultClientPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:23.882] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[16Jun2024 13:21:23.882] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:23.882] [REI-ReloadPlugins/INFO] [REI/]: [REI] ****************************************
[16Jun2024 13:21:23.987] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Unable to play empty soundEvent: minecraft:entity.salmon.ambient
[16Jun2024 13:21:24.218] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] ------------[Mekanism]------------
[16Jun2024 13:21:24.218] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Happy Pride Month, rednjw!
[16Jun2024 13:21:24.219] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Regardless of what anyone tells you,
[16Jun2024 13:21:24.219] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] you are important!
[16Jun2024 13:21:24.219] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT]  - The Mekanism Team
[16Jun2024 13:21:24.219] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] ------------[=======]------------
[16Jun2024 13:21:24.947] [Render thread/WARN] [ModernFix/]: Time from main menu to in-game was 4.33586 seconds
[16Jun2024 13:21:24.948] [Render thread/WARN] [ModernFix/]: Total time to load game and open world was 24.34486 seconds
[16Jun2024 13:21:25.077] [REI-ReloadPlugins/INFO] [REI/]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[16Jun2024 13:21:25.077] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIServerPlugin starting main-reload for END.
[16Jun2024 13:21:25.078] [REI-ReloadPlugins/INFO] [REI/]: [REI] Plugins (2):
[16Jun2024 13:21:25.078] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems]
[16Jun2024 13:21:25.078] [REI-ReloadPlugins/INFO] [REI/]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[16Jun2024 13:21:25.078] [REI-ReloadPlugins/INFO] [REI/]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[16Jun2024 13:21:25.086] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIPlugin finished post-reload for END in 712.1 μs, totaling 47.39 ms.
[16Jun2024 13:21:25.089] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIClientPlugin finished post-reload for END in 859.4 μs, totaling 1.199 s.
[16Jun2024 13:21:25.090] [REI-ReloadPlugins/INFO] [REI/]: [REI] REIServerPlugin finished post-reload for END in 438.5 μs, totaling 7.353 ms.
```

### Anything else?

![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/63887849/aabd4b08-dc06-46dd-9b5d-a32074eeb2fe)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by wendall911** [comment]
I'm unclear why the mod is a release version on CurseForge and Modrinth for NeoForge, as it does not work at all. I initially thought something was missing in my development environment, but it just does not work currently. Not sure if those can be archived, or a note added that it isn't working. Suggest pinning this issue and adding 1.21 in issue title as well, as there are not any release versions that work with any combination of NeoForge.

**Comment by steelshot** [comment]
@Shoes4Clues, try removing Mekanism. Also having AE2 installed (my personal observation) might be giving similar errors time to time.

> I'm unclear why the mod is a release version on CurseForge and Modrinth for NeoForge, as it does not work at all. I initially thought something was missing in my development environment, but it just does not work currently. Not sure if those can be archived, or a note added that it isn't working. Suggest pinning this issue and adding 1.21 in issue title as well, as there are not any release versions that work with any combination of NeoForge.

@wendall911 Both curseforge and modrinth, show any 1.21 version of REI as beta versions, hence they should be treated as such.

![image](https://github.com/user-attachments/assets/fc2c15db-4154-468a-8c93-bac4ab082b7f)
![image](https://github.com/user-attachments/assets/b5208527-c359-4a22-a47a-9ae0ff9931be)

**Comment by wendall911** [comment]
@steelshot I see, so beta means not working. Maybe it should be Alpha? I dunno. Anyhow, just wanted to say this should have higher visibility so other modders know it doesn't work. I wouldn't consider beta "not working at all on any version, but doesn't crash", but each to their own. The only upside is it compiles, but then it probably should have just been pushed to the maven repo only.
