### ISSUE TITLE
[Bug] cant open a world 

### ISSUE THREAD

**Issue by Morrison0011** [shedaniel/RoughlyEnoughItems#1699]
### What happened?

added roughly enough items mod in modrinth app and tried to go play my world and it just crashed put it saves the world first

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[22:47:46] [REI-ReloadPlugins/INFO] [REI] REIServerPlugin finished post-reload for END in 412.3 μs, totaling 15.53 ms.

[22:47:46] [REI-ReloadPlugins/TRACE] [REI] [REIClientPlugin END] Reloading Section: "post-stage/FavoriteEntryTypeRegistryImpl/"
```

### Anything else?

[2024-08-06-7.log.gz](https://github.com/user-attachments/files/16515064/2024-08-06-7.log.gz)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by LilyKensa** [comment]
Bro, although REI has some errors in your log, it's probably a [indium](https://github.com/comp500/Indium) bug.

Line 702 of your log:
```
[22:39:38] [Chunk Render Task Executor #0/ERROR]: Chunk build failed
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-fa8325fb44abed50.jar:?]
	at dev.ultimatchamp.bettergrass.FabricBetterGrassBakedModel.emitBlockQuads(FabricBetterGrassBakedModel.java:56) ~[FabricBetterGrass-1.0.21+1.21.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.34+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$ckm000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	... 4 more
```

## Edit

This may be the solution:
https://github.com/comp500/Indium/issues/327#issuecomment-2275873748
