### ISSUE TITLE
[Bug] REI cannot display items on the right side of the inventory normally

### ISSUE THREAD

**Issue by Karashok-Leo** [shedaniel/RoughlyEnoughItems#1726]
### What happened?

![image](https://github.com/user-attachments/assets/b8160fe4-d719-40dd-a319-abfa457e629f)
This issue only occurs when REI, [L2Hostility Fabricated](https://modrinth.com/mod/l2-hostility-fabricated), and [Modonomicon](https://modrinth.com/mod/modonomicon) are installed simultaneously.
If either l2hostility or modonomicon is removed, rei can work fine.
I also tested this issue on Forge, and although it cannot be stably reproduced on Forge, it is indeed possible for it to occur.
[The complete log is here](https://mclo.gs/1Q27JS5)
REI seems to have attempted to acquire the client player too early.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[19:02:06] [REI-ReloadPlugins/ERROR] [REI] DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems] plugin failed to reloadable-plugin/EntryRegistryImpl/!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:192)
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:151)
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69)
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51)
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:417)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:407)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:405)
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:485)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:190)
	... 18 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_37908()" because "dev.architectury.utils.GameInstance.getClient().field_1724" is null
	at me.shedaniel.rei.api.common.display.basic.BasicDisplay.lambda$static$0(BasicDisplay.java:49)
	at me.shedaniel.rei.api.common.display.basic.BasicDisplay.registryAccess(BasicDisplay.java:67)
	at me.shedaniel.rei.impl.client.fabric.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:45)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 20 more
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ainsley26** [comment]
I get a similar problem on Fabric but without those mods installed, if you go to the settings and reload the plugins do the items come back? I also get an error that occurs in the `DefaultClientPlugin`...

**Comment by james5922** [comment]
Having same issue.
Fabric 0.15.11 for Minecraft 1.20.1, REI v12.1.758 - a modified derivative of Quantum Freedom 2 pack. The pack was edited, not REI.

not using either of those mods but I do have a bunch of other mods ... error only mentions REI and Architectury. Reloading plugins makes the items reappear.

```
[14:33:27] [REI-ReloadPlugins/ERROR]: [REI] DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems] plugin failed to reloadable-plugin/EntryRegistryImpl/!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:192) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:151) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:417) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:407) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:405) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:485) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:190) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	... 18 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_37908()" because "dev.architectury.utils.GameInstance.getClient().field_1724" is null
	at me.shedaniel.rei.api.common.display.basic.BasicDisplay.lambda$static$0(BasicDisplay.java:49) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.api.common.display.basic.BasicDisplay.registryAccess(BasicDisplay.java:67) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at me.shedaniel.rei.impl.client.fabric.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:45) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:190) ~[RoughlyEnoughItems-12.1.758-fabric.jar:?]
	... 18 more
```

**Comment by james5922** [comment]
Upon further testing ... it appears to be some sort of regression in the latest 758 version (at least for 1.20.1 Fabric). 750 works fine.

**Comment by shedaniel** [comment]
I am trying to solve this issue, please try version 770 or above

**Comment by james5922** [comment]
Not seeing issue right now with 770. Item display works on first try with new world.
