### ISSUE TITLE
[Bug] REI Test Plugin is enabled in latest release (17.0.790)

### ISSUE THREAD

**Issue by JoshuaVandaele** [shedaniel/RoughlyEnoughItems#1761]
### What happened?

This line in the logs ask for this to be reported:
"REI Test Plugin is enabled! If you see this unintentionally, please report this!"

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[01:09:44] [Render thread/INFO]: Received config from the server: {}
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] REICommonPlugin finished post-reload for START in 936.8 μs, totaling 55.02 ms.
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 1.130 ms, totaling 279.3 ms.
[01:09:44] [REI-ReloadPlugins/ERROR]: [REI] REI Test Plugin is enabled! If you see this unintentionally, please report this!
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] REICommonPlugin starting main-reload for END.
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] Plugins (4):
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITestCommonPlugin
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[01:09:44] [Render thread/INFO]: Stopping worker threads
[01:09:44] [REI-ReloadPlugins/ERROR]: [REI] Failed to run end-reload task for reloadable [ServerDisplayRegistryImpl] in stage [END]
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3772()" because the return value of "dev.architectury.utils.GameInstance.getServer()" is null
	at knot/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.getAllSortedRecipes(ServerDisplayRegistryImpl.java:230) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.fillRecipes(ServerDisplayRegistryImpl.java:216) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.endReload(ServerDisplayRegistryImpl.java:209) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at knot/me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.reload(PluginManagerImpl.java:464) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.reloadPlugins0(ReloadManagerImpl.java:155) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.reloadPlugins0(ReloadManagerImpl.java:144) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.lambda$reloadPlugins$7(ReloadManagerImpl.java:122) ~[RoughlyEnoughItems-17.0.790-fabric.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1848) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] ########################################
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] Plugins (5):
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITestPlugin
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[01:09:44] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITooltipPlugin of REITooltipPlugin [appleskin]
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] ########################################
[01:09:44] [Render thread/INFO]: Started 10 worker threads
[01:09:44] [pool-10-thread-1/INFO]: [STDOUT]: Loaded region successfully in 333ms
[01:09:44] [Render thread/WARN]: Received passengers for unknown entity
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] REICommonPlugin finished post-reload for END in 280.7 μs, totaling 14.88 ms.
[01:09:44] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 1.698 ms, totaling 295.8 ms.
```

### Anything else?

This log entry also appears in the recent #1751 issue

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by mopsy14** [comment]
Can confirm in #1767.

**Comment by Clownarchy** [comment]
this is also an issue for me

**Comment by blockchaaain** [comment]
Still happening in v17.0.791
I don't think I'm seeing any negative consequences.
