### ISSUE TITLE
[Bug] Cannot resolve tags data in rei 17.0.792 and fabric 1.21.3

### ISSUE THREAD

**Issue by QiuShui1012** [shedaniel/RoughlyEnoughItems#1772]
### What happened?

I clicked on some items on the client and went to the tags page. On the page, it displays 'Failed to resolve tags! No tag data'

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
server-side latest.log:
[17:16:04] [main/INFO]: Loading Minecraft 1.21.3 with Fabric Loader 0.16.9
[17:16:04] [main/INFO]: Loading 101 mods:
	- appleskin 3.0.6+mc1.21.3
	- architectury 14.0.4
	- balm-fabric 21.3.3
	   \-- kuma_api 21.3.1-SNAPSHOT
	- carpet 1.4.158+v241022
	- carpet-extra 1.4.158
	- cesium 0.2.5
	   |-- com_github_jnr_jffi 1.3.12
	   |-- com_github_jnr_jffi_native 1.3.12
	   |-- com_github_jnr_jnr-a64asm 1.0.0
	   |-- com_github_jnr_jnr-constants 0.10.4
	   |-- com_github_jnr_jnr-ffi 2.2.15
	   |-- com_github_jnr_jnr-x86asm 1.0.2
	   |-- com_github_luben_zstd-jni 1.5.6-3
	   \-- org_lmdbjava_lmdbjava 0.9.0
	- cloth-config 16.0.141
	   \-- cloth-basic-math 0.6.1
	- collective 7.89
	- fabric-api 0.110.0+1.21.3
	   |-- fabric-api-base 0.4.50+119c825640
	   |-- fabric-api-lookup-api-v1 1.6.81+fd37071f40
	   |-- fabric-biome-api-v1 14.0.6+fd37071f40
	   |-- fabric-block-api-v1 1.0.28+fd37071f40
	   |-- fabric-block-view-api-v2 1.0.16+fd37071f40
	   |-- fabric-blockrenderlayer-v1 2.0.4+fd37071f40
	   |-- fabric-client-tags-api-v1 1.1.24+fd37071f40
	   |-- fabric-command-api-v1 1.2.58+f71b366f40
	   |-- fabric-command-api-v2 2.2.37+c9d82ab240
	   |-- fabric-commands-v0 0.2.75+df3654b340
	   |-- fabric-content-registries-v0 9.1.8+fd37071f40
	   |-- fabric-convention-tags-v1 2.1.3+7f945d5b40
	   |-- fabric-convention-tags-v2 2.9.3+84ebbb0e40
	   |-- fabric-crash-report-info-v1 0.3.3+fd37071f40
	   |-- fabric-data-attachment-api-v1 1.4.0+dbad41f140
	   |-- fabric-data-generation-api-v1 21.0.18+fd37071f40
	   |-- fabric-dimensions-v1 4.0.7+fd37071f40
	   |-- fabric-entity-events-v1 2.0.8+825023f840
	   |-- fabric-events-interaction-v0 2.0.12+c2c3ac4740
	   |-- fabric-game-rule-api-v1 1.0.59+fd37071f40
	   |-- fabric-item-api-v1 11.1.7+fd37071f40
	   |-- fabric-item-group-api-v1 4.1.17+fd37071f40
	   |-- fabric-key-binding-api-v1 1.0.53+fd37071f40
	   |-- fabric-keybindings-v0 0.2.51+df3654b340
	   |-- fabric-lifecycle-events-v1 2.5.1+6da5ef6940
	   |-- fabric-loot-api-v2 3.0.26+3f89f5a540
	   |-- fabric-loot-api-v3 1.0.14+fd37071f40
	   |-- fabric-message-api-v1 6.0.21+fd37071f40
	   |-- fabric-model-loading-api-v1 3.0.9+fd37071f40
	   |-- fabric-networking-api-v1 4.3.5+fd37071f40
	   |-- fabric-object-builder-api-v1 17.0.9+fd37071f40
	   |-- fabric-particles-v1 4.0.10+fd37071f40
	   |-- fabric-recipe-api-v1 7.0.4+fd37071f40
	   |-- fabric-registry-sync-v0 5.3.0+2758bfbf40
	   |-- fabric-renderer-api-v1 4.0.5+fd37071f40
	   |-- fabric-renderer-indigo 1.9.5+fd37071f40
	   |-- fabric-rendering-data-attachment-v1 0.3.54+73761d2e40
	   |-- fabric-rendering-fluids-v1 3.1.15+fd37071f40
	   |-- fabric-rendering-v0 1.1.84+df3654b340
	   |-- fabric-rendering-v1 8.0.8+6922831640
	   |-- fabric-resource-conditions-api-v1 5.0.8+fd37071f40
	   |-- fabric-resource-loader-v0 3.0.6+fd37071f40
	   |-- fabric-screen-api-v1 2.0.34+fd37071f40
	   |-- fabric-screen-handler-api-v1 1.3.101+fd37071f40
	   |-- fabric-sound-api-v1 1.0.29+fd37071f40
	   |-- fabric-transfer-api-v1 5.4.3+fd37071f40
	   \-- fabric-transitive-access-wideners-v1 6.2.0+54a41b1c40
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- fishontheline 3.4
	- fuji 6.0.0-0fe4718dac-mc1.21.2
	   |-- com_jayway_jsonpath_json-path 2.9.0
	   |-- net_luckperms_api 5.4
	   |-- org_quartz-scheduler_quartz 2.5.0-rc1
	   \-- sgui 1.7.2+1.21.2
	- image2map 0.8.0+1.21.3
	   |-- map-canvas-api 0.5.0+1.21.3
	   \-- sgui 1.7.2+1.21.2
	- jade 16.0.4+fabric
	- jamlib 1.2.2+1.21.3
	   \-- blue_endless_jankson 1.2.3
	- java 22
	- kleeslabs 21.3.1
	- ksyxis 1.3.2
	- leaves-end-below-2-inf 1.0.1
	- minecraft 1.21.3
	- mr_reinforced_deepslate 1.4
	- offline-uuid-fix 1.0.2
	- placeholder-api 2.5.1+1.21.3
	- qca 1.0.3
	- rightclickharvest 4.4.3+1.21.3
	- roughlyenoughitems 17.0.792
	   \-- error_notifier 1.0.11
	- servux 0.4.1
	   \-- fabric-permissions-api-v0 0.3.3
	- spark 1.10.119
	   \-- fabric-permissions-api-v0 0.3.3
	- syncmatica 0.3.13-sakura.1
	- trade_cycling 1.21.3-1.0.15
	   |-- fabric-key-binding-api-v1 1.0.53+c47b9d4340
	   \-- fabric-screen-api-v1 2.0.32+c47b9d4340
	- xaerominimap 24.6.2
	- xaeroworldmap 1.39.1
[17:16:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/********/multicraft/servers/server14477/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[17:16:04] [main/INFO]: Compatibility level set to JAVA_21
[17:16:04] [main/WARN]: Reference map 'kleeslabs.refmap.json' for kleeslabs.mixins.json could not be read. If this is a development environment you can ignore this message
[17:16:04] [main/WARN]: Reference map 'kleeslabs.refmap.json' for kleeslabs.fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[17:16:05] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[17:16:08] [main/WARN]: Method overwrite conflict for getClimateSettings in architectury.mixins.json:BiomeAccessor from mod architectury, previously written by carpet.mixins.Biome_scarpetMixin. Skipping method.
[17:16:11] [main/INFO]: Loading Collective version 7.89.
[17:16:11] [main/WARN]: @Redirect conflict. Skipping carpet-extra.mixins.json:ServerPlayNetworkHandlerMixin from mod carpet-extra->@Redirect::carpetextra_removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1000, already redirected by mixins.servux.json:MixinServerPlayNetworkHandler from mod servux->@Redirect::servux$removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1005
[17:16:12] [main/INFO]: Initializing JamLib on Fabric
[17:16:12] [main/INFO]: Ksyxis: Booting... (platform: Fabric, manual: false)
[17:16:12] [main/INFO]: Ksyxis: Found Mixin library. (version: 0.8.7)
[17:16:12] [main/INFO]: Ksyxis: Ready. As always, this mod will speed up your world loading and might or might not break it.
[17:16:12] [main/INFO]: Initializing...
[17:16:12] [main/INFO]: Initialized!
[17:16:12] [main/INFO]: Updated config file at /home/********/multicraft/servers/server14477/config/rightclickharvest.json5
[17:16:12] [main/INFO]: Initializing Right Click Harvest on FABRIC
[17:16:12] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[17:16:12] [main/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REICommonPlugin
[17:16:12] [main/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REICommonPlugin
[17:16:12] [main/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REICommonPlugin
[17:16:12] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[17:16:12] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[17:16:12] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[17:16:12] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[17:16:12] [main/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items_new
[17:16:12] [main/INFO]: Loading Xaero's Minimap - Stage 1/2 (Server)
[17:16:12] [main/INFO]: Loading Xaero's World Map - Stage 1/2 (Server)
[17:16:12] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[17:16:14] [main/INFO]: Loaded 1378 recipes
[17:16:14] [main/INFO]: Loaded 1465 advancements
[17:16:14] [main/INFO]: Applied 0 biome modifications to 0 of 65 new biomes in 1.178 ms
[17:16:14] [Server thread/INFO]: Starting background profiler...
[17:16:14] [Server thread/INFO]: Starting minecraft server version 1.21.3
[17:16:14] [Server thread/INFO]: Loading properties
[17:16:14] [Server thread/INFO]: Default game type: SURVIVAL
[17:16:14] [Server thread/INFO]: Generating keypair
[17:16:14] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:1070
[17:16:14] [Server thread/INFO]: Using epoll channel type
[17:16:14] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:16:14] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[17:16:14] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[17:16:14] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[17:16:15] [Server thread/INFO]: Preparing level "world"
[17:16:15] [Server thread/INFO]: [CM] Loaded 18 settings from carpet.conf
[17:16:16] [Server thread/INFO]: Ksyxis: Hey. This is Ksyxis. We will now load the world and will try to do it quickly. If the game is not responding after this, it's probably us to blame or delete for good. This message appears always, even if the mod works flawlessly. (modern)
[17:16:16] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:16:16] [Server thread/INFO]: Time elapsed: 6 ms
[17:16:16] [Server thread/INFO]: Done (0.378s)! For help, type "help"
[17:16:16] [Server thread/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[17:16:16] [Server thread/INFO]: [REI] REICommonPlugin starting main-reload for START.
[17:16:16] [Server thread/INFO]: [REI] Plugins (3):
[17:16:16] [Server thread/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[17:16:16] [Server thread/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[17:16:16] [Server thread/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[17:16:16] [Server thread/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[17:16:16] [Server thread/INFO]: [REI] REICommonPlugin finished post-reload for START in 1.238 ms, totaling 106.4 ms.
[17:16:16] [Server thread/INFO]: [REI] ########################################
[17:16:16] [Server thread/INFO]: [REI] REICommonPlugin starting main-reload for END.
[17:16:16] [Server thread/INFO]: [REI] Plugins (3):
[17:16:16] [Server thread/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[17:16:16] [Server thread/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[17:16:16] [Server thread/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[17:16:16] [Server thread/INFO]: [REI] ########################################
[17:16:16] [Server thread/INFO]: [REI] REICommonPlugin finished post-reload for END in 527.9 μs, totaling 119.9 ms.
[17:16:16] [Server thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.core.CorePlugin
[17:16:16] [Server thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.vanilla.VanillaPlugin
[17:16:16] [Server thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.universal.UniversalPlugin
[17:16:16] [Server thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.access.AccessibilityPlugin
[17:16:16] [Server thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.debug.DebugPlugin
[17:16:16] [Server thread/INFO]: enabled 20/112 modules -> [back, color.anvil, color.sign, command_toolbox.bed, command_toolbox.fly, command_toolbox.hat, command_toolbox.nickname, command_toolbox.ping, command_toolbox.realname, command_toolbox.sit, command_toolbox.suicide, command_toolbox.trashcan, command_toolbox.warp, fuji, gameplay.carpet.better_info, home, motd, placeholder, pvp, tpa]
[17:16:16] [Server thread/INFO]: Loading Xaero's Minimap - Stage 2/2 (Server)
[17:16:16] [Server thread/INFO]: Loading Xaero's World Map - Stage 2/2 (Server)
[17:18:06] [Server thread/ERROR]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_8710$class_9154.comp_2242()" because "type" is null
	at knot/dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:143) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:137) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:133) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:142) ~[architectury-14.0.4-fabric.jar:?]
	at knot/me.shedaniel.rei.plugin.common.displays.tag.TagNodes.lambda$init$1(TagNodes.java:137) ~[RoughlyEnoughItems-17.0.792-fabric.jar:?]
	at knot/dev.architectury.impl.NetworkAggregator.lambda$registerReceiver$1(NetworkAggregator.java:71) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.impl.NetworkAggregator.lambda$registerC2SReceiver$3(NetworkAggregator.java:108) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.networking.transformers.SplitPacketTransformer.inbound(SplitPacketTransformer.java:174) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.impl.NetworkAggregator.lambda$registerC2SReceiver$4(NetworkAggregator.java:102) ~[architectury-14.0.4-fabric.jar:?]
	at knot/dev.architectury.networking.fabric.NetworkManagerImpl$1.lambda$registerC2S$0(NetworkManagerImpl.java:58) ~[architectury-14.0.4-fabric.jar:?]
	at knot/net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.lambda$receive$0(ServerPlayNetworkAddon.java:72) ~[fabric-networking-api-v1-4.3.5+fd37071f40-a3ad55f5d27b7334.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:833) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
```

### Anything else?

[client-side latest.log](https://github.com/user-attachments/files/18047870/latest.log)
[client-side rei.log](https://github.com/user-attachments/files/18047872/rei.log)
[server-side rei.log](https://github.com/user-attachments/files/18047871/rei.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by electricsteve** [comment]
Still happening even after fix.
