### ISSUE TITLE
[Bug] Custom Recipe Category not working in Server (Multiplayer)

### ISSUE THREAD

**Issue by CoolerProYT** [shedaniel/RoughlyEnoughItems#1775]
### What happened?

Unable to view reicpe for my custom category added via plugin in 1.21.3, latest REI version. In single player everything is working fine. Other than custom recipe category, tags also not working.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[09Dec2024 18:14:47.933] [REI-ReloadPlugins/INFO][REI/]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO[09Dec2024 18:14:47.933] [REI-ReloadPlugins/INFO][REI/]: [REI] REICommonPlugin starting main-reload for END.[09Dec2024 18:14:47.933] [REI-ReloadPlugins/INFO][REI/]: [REI] Plugins (3):[09Dec2024 18:14:47.934] [REI-ReloadPlugins/INFO][REI/]: [REI]  - (-100.00) DefaultPluginImpl of DefaultPluginImpl [roughlyenoughitems][09Dec2024 18:14:47.934] [REI-ReloadPlugins/INFO][REI/]: [REI]  - (0.00) REIPluginServer of REIPluginServer [productiveslimes][09Dec2024 18:14:47.934] [REI-ReloadPlugins/INFO][REI/]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems][09Dec2024 18:14:47.934] [REI-ReloadPlugins/INFO][REI/]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO[09Dec2024 18:14:47.937] [REI-ReloadPlugins/ERROR][REI/]: [REI] Failed to run end-reload task for reloadable [ServerDisplayRegistryImpl] in stage [END]java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.getRecipeManager()" because the return value of "dev.architectury.utils.GameInstance.getServer()" is null
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.getAllSortedRecipes(ServerDisplayRegistryImpl.java:230) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.fillRecipes(ServerDisplayRegistryImpl.java:216) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.endReload(ServerDisplayRegistryImpl.java:209) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.reload(PluginManagerImpl.java:464) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.reloadPlugins0(ReloadManagerImpl.java:155) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.reloadPlugins0(ReloadManagerImpl.java:144) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at TRANSFORMER/roughlyenoughitems@17.0.792/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.lambda$reloadPlugins$7(ReloadManagerImpl.java:122) ~[RoughlyEnoughItems-17.0.792-neoforge.jar%23223!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### Anything else?

#1772 I think this is the tags issue I facing.

![image](https://github.com/user-attachments/assets/f0e12d2e-3363-4a88-9b5b-ebac244f8a24)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by mopsy14** [comment]
If I had to guess, something's wrong with the serializer. Although it wouldn't be weird if it is indeed caused by a REI bug, because the current versions is quite buggy...
