### ISSUE TITLE
[Bug] Game Crashes When Hovering Over Fluids

### ISSUE THREAD

**Issue by Jackepedia** [shedaniel/RoughlyEnoughItems#1783]
### What happened?

When hovering over a fluid like lava or water in the REI menu, the game crashes. I loaded an instance with just REI installed, and it crashed again.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-12-22 20:53:23
Description: Rendering entry extra

java.lang.NullPointerException: Cannot invoke "java.util.Optional.map(java.util.function.Function)" because "potionContents" is null
	at knot//net.fabricmc.fabric.impl.transfer.fluid.WaterPotionStorage.isWaterPotion(WaterPotionStorage.java:56)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.WaterPotionStorage.find(WaterPotionStorage.java:50)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.CombinedProvidersImpl.lambda$createEvent$0(CombinedProvidersImpl.java:42)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.CombinedProvidersImpl$Provider.find(CombinedProvidersImpl.java:80)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.CombinedProvidersImpl$Provider.find(CombinedProvidersImpl.java:65)
	at knot//net.fabricmc.fabric.impl.lookup.item.ItemApiLookupImpl.find(ItemApiLookupImpl.java:67)
	at knot//me.shedaniel.rei.impl.common.compat.FabricFluidAPISupportPlugin.lambda$registerFluidSupport$2(FabricFluidAPISupportPlugin.java:48)
	at knot//me.shedaniel.rei.impl.common.fluid.FluidSupportProviderImpl.itemToFluids(FluidSupportProviderImpl.java:73)
	at knot//me.shedaniel.rei.plugin.common.runtime.DefaultRuntimePlugin.lambda$registerEntryTypes$0(DefaultRuntimePlugin.java:59)
	at knot//me.shedaniel.rei.api.common.util.EntryStacks.equals(EntryStacks.java:108)
	at knot//me.shedaniel.rei.api.common.util.EntryStacks.equalsFuzzy(EntryStacks.java:163)
	at knot//me.shedaniel.rei.impl.client.view.ViewsImpl.checkUsages(ViewsImpl.java:295)
	at knot//me.shedaniel.rei.impl.client.view.ViewsImpl.isRecipesFor(ViewsImpl.java:278)
	at knot//me.shedaniel.rei.impl.client.registry.display.DisplayCache.lambda$getAllDisplaysByOutputs$1(DisplayCache.java:88)
	at knot//com.google.common.collect.Iterators$5.computeNext(Iterators.java:673)
	at knot//com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at knot//com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at knot//me.shedaniel.rei.impl.client.gui.widget.EntryWidget._getTransferHandler(EntryWidget.java:338)
	at knot//me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getTransferHandler(EntryWidget.java:387)
	at knot//me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:468)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.getCurrentTooltip(EntryListStackEntry.java:219)
	at knot//me.shedaniel.rei.impl.client.gui.widget.EntryWidget.queueTooltip(EntryWidget.java:444)
	at knot//me.shedaniel.rei.impl.client.gui.widget.DisplayedEntryWidget.queueTooltip(DisplayedEntryWidget.java:60)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:227)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:127)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:350)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:247)
	at knot//me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
	at knot//net.minecraft.class_465.handler$zfe000$architectury$renderBackground(class_465.java:2299)
	at knot//net.minecraft.class_465.method_25420(class_465.java:185)
	at knot//net.minecraft.class_437.method_25394(class_437.java:125)
	at knot//net.minecraft.class_465.method_25394(class_465.java:116)
	at knot//net.minecraft.class_10260.method_25394(class_10260.java:56)
	at knot//net.minecraft.class_490.method_25394(class_490.java:70)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$86(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bkh000$fabric-screen-api-v1$onRenderScreen(class_757.java:2914)
	at knot//net.minecraft.class_757.method_3192(class_757.java:551)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.fabricmc.fabric.impl.transfer.fluid.WaterPotionStorage.isWaterPotion(WaterPotionStorage.java:56)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.WaterPotionStorage.find(WaterPotionStorage.java:50)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.CombinedProvidersImpl.lambda$createEvent$0(CombinedProvidersImpl.java:42)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.CombinedProvidersImpl$Provider.find(CombinedProvidersImpl.java:80)
	at knot//net.fabricmc.fabric.impl.transfer.fluid.CombinedProvidersImpl$Provider.find(CombinedProvidersImpl.java:65)
	at knot//net.fabricmc.fabric.impl.lookup.item.ItemApiLookupImpl.find(ItemApiLookupImpl.java:67)
	at knot//me.shedaniel.rei.impl.common.compat.FabricFluidAPISupportPlugin.lambda$registerFluidSupport$2(FabricFluidAPISupportPlugin.java:48)
	at knot//me.shedaniel.rei.impl.common.fluid.FluidSupportProviderImpl.itemToFluids(FluidSupportProviderImpl.java:73)
	at knot//me.shedaniel.rei.plugin.common.runtime.DefaultRuntimePlugin.lambda$registerEntryTypes$0(DefaultRuntimePlugin.java:59)
	at knot//me.shedaniel.rei.api.common.util.EntryStacks.equals(EntryStacks.java:108)
	at knot//me.shedaniel.rei.api.common.util.EntryStacks.equalsFuzzy(EntryStacks.java:163)
	at knot//me.shedaniel.rei.impl.client.view.ViewsImpl.checkUsages(ViewsImpl.java:295)
	at knot//me.shedaniel.rei.impl.client.view.ViewsImpl.isRecipesFor(ViewsImpl.java:278)
	at knot//me.shedaniel.rei.impl.client.registry.display.DisplayCache.lambda$getAllDisplaysByOutputs$1(DisplayCache.java:88)
	at knot//com.google.common.collect.Iterators$5.computeNext(Iterators.java:673)
	at knot//com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at knot//com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at knot//me.shedaniel.rei.impl.client.gui.widget.EntryWidget._getTransferHandler(EntryWidget.java:338)
	at knot//me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getTransferHandler(EntryWidget.java:387)
	at knot//me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:468)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.getCurrentTooltip(EntryListStackEntry.java:219)

-- Screen details --
Details:
	Screen name: net.minecraft.class_490
Stacktrace:
	at knot//me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at knot//me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:235)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:127)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:350)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:247)
	at knot//me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
	at knot//net.minecraft.class_465.handler$zfe000$architectury$renderBackground(class_465.java:2299)
	at knot//net.minecraft.class_465.method_25420(class_465.java:185)
	at knot//net.minecraft.class_437.method_25394(class_437.java:125)
	at knot//net.minecraft.class_465.method_25394(class_465.java:116)
	at knot//net.minecraft.class_10260.method_25394(class_10260.java:56)
	at knot//net.minecraft.class_490.method_25394(class_490.java:70)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$86(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bkh000$fabric-screen-api-v1$onRenderScreen(class_757.java:2914)
	at knot//net.minecraft.class_757.method_3192(class_757.java:551)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1341)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry
	Bounds: me.shedaniel.math.Rectangle@669a75a[height=18,width=18,x=525,y=245]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Entry type: minecraft:fluid
	Is empty: false
	Entry identifier: minecraft:water

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition
	Fluid Type: minecraft:water
	Fluid Amount: 81000
	Fluid NBT: {}

-- Screen details --
Details:
	Screen name: net.minecraft.class_490

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2093871376 bytes (1996 MiB) / 2852126720 bytes (2720 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21921.1000
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 21693.83
	Virtual memory used (MiB): 18558.79
	Swap memory total (MiB): 14191.90
	Swap memory used (MiB): 1516.46
	Space in storage for jna.tmpdir (MiB): available: 214577.08, total: 487399.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 214577.08, total: 487399.00
	Space in storage for io.netty.native.workdir (MiB): available: 214577.08, total: 487399.00
	Space in storage for java.io.tmpdir (MiB): available: 214577.08, total: 487399.00
	Space in storage for workdir (MiB): available: 214577.08, total: 487399.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accessories: Accessories 1.2.6-beta+1.21.4
		appleskin: AppleSkin 3.0.6+mc1.21.3
		architectury: Architectury 15.0.1
		betteradvancements: Better Advancements 0.4.4.24
		betterthirdperson: Better Third Person 1.9.0
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		clean-debug: Clean F3 0.4.8
		cloth-config: Cloth Config v17 17.0.144
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.89
		controlify: Controlify 2.0.0-beta.21+1.21.4-fabric
			dev_isxander_libsdl4j: libsdl4j 3.preview-3.1.3-46
			dev_isxander_steamdeck4j: steamdeck4j 1.1.6
			mixinextras: MixinExtras 0.5.0-beta.4
			org_hid4java_hid4java: hid4java 0.8.0
			org_quiltmc_parsers_gson: gson 0.3.0
			org_quiltmc_parsers_json: json 0.3.0
		crawl: Crawl 0.14.1
		cubes-without-borders: Cubes Without Borders 3.0.0+mc1.21.3
		dynamiclights: Dynamic Lights 1.8.5+mod
		fabric-api: Fabric API 0.112.2+1.21.4
			fabric-api-base: Fabric API Base 0.4.54+b47eab6b04
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.86+b1caf1e904
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.5+b1caf1e904
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.8+7feeb73304
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.29+20ea1e2304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.62+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.41+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.79+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.14+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.9+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.9+3d1fb53904
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.6+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.2.2+20ea1e2304
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.12+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.2+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.14+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.23+7feeb73304
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.56+7feeb73304
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.54+df3654b304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.4+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.33+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.21+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.25+7feeb73304
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.1.1+7b6b225304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.9+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.8+d70d2c0604
			fabric-particles-v1: Fabric Particles (v1) 4.0.14+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.5+b1caf1e904
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.2+3d1fb53904
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.2+84404cdd04
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.2+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.19+7feeb73304
			fabric-rendering-v1: Fabric Rendering (v1) 10.1.2+b874120c04
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.11+b1caf1e904
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.38+7feeb73304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.109+7feeb73304
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.32+7feeb73304
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.2+20ea1e2304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.8+b1caf1e904
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
		fixedanvilrepaircost: Fixed Anvil Repair Cost 3.4
		infinitetrading: Infinite Trading 4.5
		iris: Iris 1.8.4+mc1.21.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 17.1.1+fabric
		java: OpenJDK 64-Bit Server VM 21
		midnightlib: MidnightLib 1.6.6
		minecraft: Minecraft 1.21.4
		modmenu: Mod Menu 13.0.0-beta.1
		moremobs: More Mobs 1.5.4+mod
		mousetweaks: Mouse Tweaks 2.27
		mru: Mineblock's Repeated Utilities 1.0.7+1.21.4+fabric
		noisium: Noisium 2.5.0+mc1.21.4
		notenoughtrials: Not Enough Trials 2.0
		oreharvester: Ore Harvester 1.4
		owo: oωo 0.12.19+1.21.4
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.9
			io_wispforest_endec_gson: gson 0.1.6
			io_wispforest_endec_jankson: jankson 0.1.6
			io_wispforest_endec_netty: netty 0.1.5
		placeholder-api: Placeholder API 2.5.1+1.21.3
		quad: Quad 1.2.11
		reactivemusic: Reactive Music 0.5.1+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.1+mc1.21.4
		replantingcrops: Replanting Crops 5.4
		roughlyenoughitems: Roughly Enough Items 18.0.796
			error_notifier: Error Notifier 1.0.11
		shulkerboxtooltip: Shulker Box Tooltip 5.2.2+1.21.4
		sodium: Sodium 0.6.5+mc1.21.4
		sodium-extra: Sodium Extra 0.6.1+mc1.21.4
		sound_physics_remastered: Sound Physics Remastered 1.21.4-1.4.8
		sounds: Sounds 2.3.0+1.21.4+fabric
		toms_storage: Tom's Simple Storage Mod 2.1.3
		treeharvester: Tree Harvester 9.0
		trimmable_tools: Trimmable Tools 2.0.5
		visuality: Visuality 0.7.9+1.21.4
		xaerominimap: Xaero's Minimap 24.6.2
		xaeroworldmap: Xaero's World Map 1.39.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21.4-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
		zoomify: Zoomify 2.14.2+1.21.3
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Loaded Shaderpack: (off)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by PersonHumanThing** [comment]
I have also had this issue

**Comment by mopsy14** [comment]
Same issue as #1767
