### ISSUE TITLE
"mc 1.13.2 rift" closest game to crash when chess opens as item menu on the left-hand side

### ISSUE THREAD

**Issue by crusher42** [shedaniel/RoughlyEnoughItems#209]
now for more info 
tested it with no other mods and still and still happens

system info info helps
os linux mint 19.2 64 bit
launcher multi MC 0..6.7-1290
open jdk 1.8.0-222

```
[10:22:13] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: cle cannot be cast to me.shedaniel.rei.api.AbstractInventoryScreenHooks
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_222]
	at k.a(SourceFile:200) [k.class:?]
	at cft.c(SourceFile:811) [cft.class:?]
	at cft.a(SourceFile:395) [cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: cle cannot be cast to me.shedaniel.rei.api.AbstractInventoryScreenHooks
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:26) ~[DefaultPotionEffectExclusionZones.class:?]
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:23) ~[DefaultPotionEffectExclusionZones.class:?]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.lambda$getCurrentExclusionZones$3(BaseBoundsHandlerImpl.java:100) ~[BaseBoundsHandlerImpl.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_222]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.getCurrentExclusionZones(BaseBoundsHandlerImpl.java:100) ~[BaseBoundsHandlerImpl.class:?]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.canItemSlotWidgetFit(BaseBoundsHandlerImpl.java:89) ~[BaseBoundsHandlerImpl.class:?]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.canItemSlotWidgetFit(BaseBoundsHandlerImpl.java:23) ~[BaseBoundsHandlerImpl.class:?]
	at me.shedaniel.rei.gui.widget.ItemListOverlay.canBeFit(ItemListOverlay.java:234) ~[ItemListOverlay.class:?]
	at me.shedaniel.rei.gui.widget.ItemListOverlay.getTotalFitSlotsPerPage(ItemListOverlay.java:227) ~[ItemListOverlay.class:?]
	at me.shedaniel.rei.gui.widget.ItemListOverlay.updateList(ItemListOverlay.java:170) ~[ItemListOverlay.class:?]
	at me.shedaniel.rei.gui.ContainerScreenOverlay.init(ContainerScreenOverlay.java:75) ~[ContainerScreenOverlay.class:?]
	at me.shedaniel.rei.client.ScreenHelper.getLastOverlay(ScreenHelper.java:45) ~[ScreenHelper.class:?]
	at ckd.handler$onPostInit$zcc000(SourceFile:572) ~[ckd.class:?]
	at ckd.a(SourceFile:313) ~[ckd.class:?]
	at cft.a(SourceFile:759) ~[cft.class:?]
	at ctj.a(SourceFile:623) ~[ctj.class:?]
	at crd.a(SourceFile:968) ~[crd.class:?]
	at jt.a(SourceFile:43) ~[jt.class:?]
	at jt.a(SourceFile:9) ~[jt.class:?]
	at ix.a(SourceFile:10) ~[ix.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
	at k.a(SourceFile:199) ~[k.class:?]
	... 17 more
[10:22:14] [main/FATAL]: Reported exception thrown!
h: Rendering screen
	at cty.a(SourceFile:801) ~[cty.class:?]
	at cft.c(SourceFile:850) ~[cft.class:?]
	at cft.a(SourceFile:395) [cft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: cle cannot be cast to me.shedaniel.rei.api.AbstractInventoryScreenHooks
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:26) ~[DefaultPotionEffectExclusionZones.class:?]
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:23) ~[DefaultPotionEffectExclusionZones.class:?]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.lambda$getCurrentExclusionZones$3(BaseBoundsHandlerImpl.java:100) ~[BaseBoundsHandlerImpl.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_222]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.getCurrentExclusionZones(BaseBoundsHandlerImpl.java:100) ~[BaseBoundsHandlerImpl.class:?]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.getStringFromCurrent(BaseBoundsHandlerImpl.java:84) ~[BaseBoundsHandlerImpl.class:?]
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.shouldRecalculateArea(BaseBoundsHandlerImpl.java:70) ~[BaseBoundsHandlerImpl.class:?]
	at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:313) ~[ContainerScreenOverlay.class:?]
	at ckd.handler$onPostDraw$zcc000(SourceFile:547) ~[ckd.class:?]
	at ckd.a(SourceFile:70) ~[ckd.class:?]
	at cky.a(SourceFile:86) ~[cky.class:?]
	at cle.a(SourceFile:33) ~[cle.class:?]
	at cty.a(SourceFile:792) ~[cty.class:?]
	... 17 more
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 13/12/19 10:22 AM
Description: Rendering screen

java.lang.ClassCastException: cle cannot be cast to me.shedaniel.rei.api.AbstractInventoryScreenHooks
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:26)
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:23)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.lambda$getCurrentExclusionZones$3(BaseBoundsHandlerImpl.java:100)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.getCurrentExclusionZones(BaseBoundsHandlerImpl.java:100)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.getStringFromCurrent(BaseBoundsHandlerImpl.java:84)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.shouldRecalculateArea(BaseBoundsHandlerImpl.java:70)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:313)
	at ckd.handler$onPostDraw$zcc000(SourceFile:547)
	at ckd.a(SourceFile:70)
	at cky.a(SourceFile:86)
	at cle.a(SourceFile:33)
	at cty.a(SourceFile:792)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:26)
	at me.shedaniel.rei.plugin.DefaultPotionEffectExclusionZones.apply(DefaultPotionEffectExclusionZones.java:23)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.lambda$getCurrentExclusionZones$3(BaseBoundsHandlerImpl.java:100)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.getCurrentExclusionZones(BaseBoundsHandlerImpl.java:100)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.getStringFromCurrent(BaseBoundsHandlerImpl.java:84)
	at me.shedaniel.rei.client.BaseBoundsHandlerImpl.shouldRecalculateArea(BaseBoundsHandlerImpl.java:70)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:313)
	at ckd.handler$onPostDraw$zcc000(SourceFile:547)
	at ckd.a(SourceFile:70)
	at cky.a(SourceFile:86)
	at cle.a(SourceFile:33)
```

**Comment by shedaniel** [comment]
Rift is no longer supported.
