### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by viclin0213** [shedaniel/RoughlyEnoughItems#227]
Crash when I open the backpack when I have a potion effect
Im playing 1.15.1

**Comment by shedaniel** [comment]
Logs?

**Comment by viclin0213** [comment]
---- Minecraft Crash Report ----
// You're mean.

Time: 2019/12/30 上午 12:39
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at me.shedaniel.rei.gui.widget.FavoritesListWidget.render(FavoritesListWidget.java:121)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.renderWidgets(ContainerScreenOverlay.java:513)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:450)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$7(RoughlyEnoughItemsCore.java:270)
	at me.shedaniel.rei.RoughlyEnoughItemsCore$$Lambda$1682/1448835002.render(Unknown Source)
	at net.minecraft.class_437.handler$zee000$onPostDraw(class_437.java:591)
	at net.minecraft.class_437.render(class_437.java:83)
	at net.minecraft.class_465.render(class_465.java:87)
	at net.minecraft.class_489.render(class_489.java:63)
	at net.minecraft.class_757.method_3192(class_757.java:604)
	at net.minecraft.class_310.method_1523(class_310.java:947)
	at net.minecraft.class_310.method_1514(class_310.java:585)
	at net.minecraft.client.main.Main.main(Main.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at me.shedaniel.rei.gui.widget.FavoritesListWidget.render(FavoritesListWidget.java:121)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.renderWidgets(ContainerScreenOverlay.java:513)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:450)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$7(RoughlyEnoughItemsCore.java:270)
	at me.shedaniel.rei.RoughlyEnoughItemsCore$$Lambda$1682/1448835002.render(Unknown Source)
	at net.minecraft.class_437.handler$zee000$onPostDraw(class_437.java:591)
	at net.minecraft.class_437.render(class_437.java:83)
	at net.minecraft.class_465.render(class_465.java:87)
	at net.minecraft.class_489.render(class_489.java:63)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_3873
	Mouse location: Scaled: (240, 125). Absolute: (960.000000, 500.000000)
	Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['viclin0213'/483, l='MpServer', x=-187.03, y=6.00, z=244.95]]
	Chunk stats: Client Chunk Cache: 625, 420
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 1620345264912301269
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-192,63,224), Chunk: (at 0,3,0 in -12,14; contains blocks -192,0,224 to -177,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2885422 game time, 509157 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1878)
	at net.minecraft.class_310.method_1514(class_310.java:600)
	at net.minecraft.client.main.Main.main(Main.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 889931264 bytes (848 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.2.9+1.15-pre5
		autoconfig1u: Auto Config v1 Updated 1.2.4
		cloth: Cloth Events 1.1.0
		cloth-config2: Cloth Config v2 2.5.3
		dynamicfps: Dynamic FPS 1.0.4
		fabric: Fabric API 0.4.25+build.282-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d95
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d95
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d95
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.3+06c939b395
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.6+12515ed995
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d95
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e195
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a730595
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d695
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a730595
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed995
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c395
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d695
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.7+f3d8141b95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.20+d830abd695
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6095
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d95
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed995
		fabric-rendering-v0: Fabric Rendering (v0) 1.0.1+b7f9825d95
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b375
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd9158095
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba795
		fabricloader: Fabric Loader 0.7.2+build.175
		lightoverlay: Light Overlay 4.1
		minecraft: Minecraft 1.15.1
		modmenu: Mod Menu 1.8.2+build.18
		mousewheelie: Mouse Wheelie 1.3.10+1.15.1-pre1
		nbttooltip: NBT Tooltip 1.14-1.0.3
		okzoomer: Ok Zoomer 1.0.3
		roughlyenoughitems: Roughly Enough Items 3.2.33
		tweed: Tweed API 2.2.8
		voxelmap: VoxelMap 1.9.13
		waila: Hwyla 1.9.19
	Launched Version: fabric-loader-0.7.2+build.175-1.15.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 23.20.16.4973, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 繁體中文 (台灣)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by viclin0213** [comment]
It also happens when I turn on the furnace

**Comment by shedaniel** [comment]
ok, I am looking into this error.
