### ISSUE TITLE
v2.2.0.16 REI + Optifine Conflict

### ISSUE THREAD

**Issue by peanutinky** [shedaniel/RoughlyEnoughItems#30]
game crashes with optifine installed here is the crash log

**Comment by peanutinky** [comment]
07:09:18	launcher	Preparing to launch minecraft client for 1.13.2-rift-1.0.4-SNAPSHOT
07:09:18	launcher	Couldn't get hash for org/dimdev/rift/1.0.4-SNAPSHOT/rift-1.0.4-SNAPSHOT.jar from https://www.dimdev.org/maven/org/dimdev/rift/1.0.4-SNAPSHOT/rift-1.0.4-SNAPSHOT.jar.sha1: HTTP 404: Not Found
07:09:18	launcher	Couldn't get hash for org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar from https://www.dimdev.org/maven/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar.sha1: HTTP 404: Not Found
07:09:18	launcher	Have local file C:/Users\wallace\AppData\Roaming\.minecraft\libraries\org/dimdev/rift/1.0.4-SNAPSHOT/rift-1.0.4-SNAPSHOT.jar but don't know what size or hash it should be. Have to assume it's good.
07:09:18	launcher	Have local file C:/Users\wallace\AppData\Roaming\.minecraft\libraries\org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar but don't know what size or hash it should be. Have to assume it's good.
07:09:19	launcher	Checking installations.
07:09:19	launcher	Minecraft client 1.13.2-rift-1.0.4-SNAPSHOT is ready to start.
07:09:19	launcher	Starting!
07:09:19	launcher	Using default game log configuration client-1.12.xml (outputs XML)
07:09:21	LaunchWrapper	Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
07:09:21	LaunchWrapper	Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
07:09:21	LaunchWrapper	Calling tweak class org.dimdev.riftloader.launch.RiftLoaderClientTweaker
07:09:21	RiftLoader	Searching mods on classpath
07:09:21	RiftLoader	Loaded mod 'rift'
07:09:21	RiftLoader	Searching for mods in j:\minecraft\mods
07:09:21	RiftLoader	Loaded mod 'bbor'
07:09:21	RiftLoader	Loaded mod 'easierchests'
07:09:21	RiftLoader	Loaded mod 'voxelmap'
07:09:21	RiftLoader	Loaded mod 'roughlyenoughitems'
07:09:21	RiftLoader	Loaded mod 'vanilladeathchest'
07:09:21	RiftLoader	Loaded 7 mods
07:09:21	RiftLoader	Initializing mods
07:09:21	org.dimdev.rift.Rift	Loading Rift!
07:09:21	mixin	SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/wallace/AppData/Roaming/.minecraft/libraries/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
07:09:22	mixin	FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
07:09:22	mixin	Compatibility level set to JAVA_8
07:09:23	RiftLoader	Done initializing mods
07:09:23	LaunchWrapper	Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
07:09:23	LaunchWrapper	Loading tweak class name org.dimdev.riftloader.OptifineLoader$Tweaker
07:09:23	LaunchWrapper	Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
07:09:23	LaunchWrapper	Calling tweak class org.dimdev.riftloader.OptifineLoader$Tweaker
02:09:23	game	OptiFine ClassTransformer
OptiFine ZIP file: j:\minecraft\mods\OptiFine_1.13.2_HD_U_E5.jar
  <log4j:Event logger="mixin" timestamp="1549282163458" level="INFO" thread="main">
    <log4j:Message><![CDATA[A re-entrant transformer 'org.dimdev.riftloader.RiftAccessTransformer' was detected and will no longer process meta class data]]></log4j:Message>
  </log4j:Event>
02:09:23	monitor	expected <
07:09:23	mixin	Error loading class: ckn (java.lang.ClassNotFoundException: The specified class 'ckn' was not found)
07:09:23	mixin	@Mixin target ckn was not found roughlyenoughitems.client.json:MixinGuiContainer
07:09:23	mixin	Error loading class: ckw (java.lang.ClassNotFoundException: The specified class 'ckw' was not found)
07:09:23	mixin	@Mixin target ckw was not found roughlyenoughitems.client.json:MixinGuiContainerCreative
07:09:23	mixin	Error loading class: clv (java.lang.ClassNotFoundException: The specified class 'clv' was not found)
07:09:23	mixin	@Mixin target clv was not found roughlyenoughitems.client.json:MixinGuiRecipeBook
07:09:23	mixin	Error loading class: ckn (java.lang.ClassNotFoundException: The specified class 'ckn' was not found)
07:09:23	mixin	null
java.lang.NullPointerException
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard.validate(MixinInfo.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:291)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:827)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:528)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:675)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
07:09:23	LaunchWrapper	Launching wrapped minecraft {net.minecraft.client.main.Main}
07:09:24	cft	Setting user: peanutinky
07:09:26	mixin	Mixin apply failed roughlyenoughitems.client.json:MixinKeyBinding -> cfe: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field d was not located in the target class cfe. Using refmap mixins.roughlyenoughitems.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field d was not located in the target class cfe. Using refmap mixins.roughlyenoughitems.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
	at aev.<clinit>(SourceFile:137)
	at pf.c(SourceFile:470)
	at cft.<init>(SourceFile:370)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
02:09:26	game	org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [roughlyenoughitems.client.json:MixinKeyBinding] from phase [DEFAULT] in config [roughlyenoughitems.client.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
	at aev.<clinit>(SourceFile:137)
	at pf.c(SourceFile:470)
	at cft.<init>(SourceFile:370)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field d was not located in the target class cfe. Using refmap mixins.roughlyenoughitems.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 21 more
  <log4j:Event logger="LaunchWrapper" timestamp="1549282166624" level="ERROR" thread="main">
    <log4j:Message><![CDATA[Unable to launch]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: aep.<init>(axy)void/newInvokeSpecial
	at aev.<clinit>(SourceFile:137)
	at pf.c(SourceFile:470)
	at cft.<init>(SourceFile:370)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	... 6 more
Caused by: java.lang.IllegalAccessError: no such constructor: aep.<init>(axy)void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: cfe
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source)
	... 11 more
Caused by: java.lang.ClassNotFoundException: cfe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [roughlyenoughitems.client.json:MixinKeyBinding] from phase [DEFAULT] in config [roughlyenoughitems.client.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 21 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field d was not located in the target class cfe. Using refmap mixins.roughlyenoughitems.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 21 more
]]></log4j:Throwable>
  </log4j:Event>
02:09:26	monitor	expected <
07:09:26	launcher	
02:09:26	monitor	Process crashed with exit code 1

**Comment by shedaniel** [comment]
Did you install the 1.13.2 version of REI?

**Comment by peanutinky** [comment]
my bad i just seen where the newest version is for 1.13 and not 1.13.2
