### ISSUE TITLE
Crash: mouseClicked event handler

### ISSUE THREAD

**Issue by Dienes16** [shedaniel/RoughlyEnoughItems#350]
Using:
- Minecraft 1.15.2
- fabric-loader-0.8.7+build.201-1.15.2
- fabric-api-0.12.0+build.313-1.15
- RoughlyEnoughItems-3.6.20

Clicking on "Options" -> "Controls" crashes the game with this message:

"The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler"

**Comment by shedaniel** [comment]
needs the whole log

**Comment by Dienes16** [comment]
Here's the crash report:

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 13.06.20 12:13
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at net.minecraft.class_304.method_1430(class_304.java:134)
	at me.shedaniel.clothconfig2.impl.FakeKeyBindings.compareTo(FakeKeyBindings.java:13)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203)
	at java.util.Arrays.sort(Arrays.java:1246)
	at net.minecraft.class_459.<init>(class_459.java:26)
	at net.minecraft.class_458.init(class_458.java:30)
	at net.minecraft.class_437.init(class_437.java:338)
	at net.minecraft.class_310.method_1507(class_310.java:863)
	at net.minecraft.class_429.method_19827(class_429.java:82)
	at net.minecraft.class_429$$Lambda$2417/1749476584.onPress(Unknown Source)
	at net.minecraft.class_4185.onPress(class_4185.java:18)
	at net.minecraft.class_4264.onClick(class_4264.java:15)
	at net.minecraft.class_339.mouseClicked(class_339.java:150)
	at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:86)
	at net.minecraft.class_312$$Lambda$2406/989728800.run(Unknown Source)
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_312$$Lambda$2405/440984718.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at net.minecraft.class_312$$Lambda$1861/1408662262.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:123)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_304.method_1430(class_304.java:134)
	at me.shedaniel.clothconfig2.impl.FakeKeyBindings.compareTo(FakeKeyBindings.java:13)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:258)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:203)
	at java.util.Arrays.sort(Arrays.java:1246)
	at net.minecraft.class_459.<init>(class_459.java:26)
	at net.minecraft.class_458.init(class_458.java:30)
	at net.minecraft.class_437.init(class_437.java:338)
	at net.minecraft.class_310.method_1507(class_310.java:863)
	at net.minecraft.class_429.method_19827(class_429.java:82)
	at net.minecraft.class_429$$Lambda$2417/1749476584.onPress(Unknown Source)
	at net.minecraft.class_4185.onPress(class_4185.java:18)
	at net.minecraft.class_4264.onClick(class_4264.java:15)
	at net.minecraft.class_339.mouseClicked(class_339.java:150)
	at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:86)
	at net.minecraft.class_312$$Lambda$2406/989728800.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at net.minecraft.class_312.method_22686(class_312.java:150)
	at net.minecraft.class_312$$Lambda$2405/440984718.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:150)
	at net.minecraft.class_312$$Lambda$1861/1408662262.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:123)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1282143648 bytes (1222 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 2.0.1
		cloth: Cloth Events 1.2.0
		cloth-basic-math: Cloth Basic Math 0.5.0
		cloth-config2: Cloth Config v2 2.13.4
		fabric: Fabric API 0.12.0+build.313-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+0121bd900c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+2af3af910c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+2af3af910c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.1+e7a4edb30c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabricloader: Fabric Loader 0.8.7+build.201
		minecraft: Minecraft 1.15.2
		org_jetbrains_annotations: annotations 18.0.0
		roughlyenoughitems: Roughly Enough Items 3.6.20
	Launched Version: fabric-loader-0.8.7+build.201-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Vanilla-PBR-1-0-2.zip
	Current Language: Deutsch (Deutschland)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
```
