### ISSUE TITLE
[Bug] Crash On 20w30a

### ISSUE THREAD

**Issue by TheBrokenRail** [shedaniel/RoughlyEnoughItems#389]
**Describe the bug**
It crashes when you open your inventory.

**Steps to Reproduce**
- Run REi on 20w30a
- Press "E"

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - 20w30a
 - Fabric Dev Environment

**Logs**
```
 net.minecraft.util.crash.CrashException: Rendering screen
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:612) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1020) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:653) [minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.20w30a.20w30a+build.8-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.20w30a.20w30a+build.8-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.20w30a.20w30a+build.8-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void me.shedaniel.rei.impl.widgets.ButtonWidget.method_27534(net.minecraft.client.util.math.MatrixStack, net.minecraft.client.font.TextRenderer, net.minecraft.text.StringRenderable, int, int, int)'
	at me.shedaniel.rei.impl.widgets.ButtonWidget.render(ButtonWidget.java:214) ~[RoughlyEnoughItems-4.10.3@net.fabricmc.yarn.20w30a.20w30a+build.8-v2.jar:?]
	at me.shedaniel.rei.gui.ContainerScreenOverlay.renderWidgets(ContainerScreenOverlay.java:592) ~[RoughlyEnoughItems-4.10.3@net.fabricmc.yarn.20w30a.20w30a+build.8-v2.jar:?]
	at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:510) ~[RoughlyEnoughItems-4.10.3@net.fabricmc.yarn.20w30a.20w30a+build.8-v2.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$12(RoughlyEnoughItemsCore.java:345) ~[RoughlyEnoughItems-4.10.3@net.fabricmc.yarn.20w30a.20w30a+build.8-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.handler$zfi000$onPostDraw(Screen.java:612) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.render(Screen.java:83) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:106) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:43) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen.java:677) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:603) ~[minecraft-20w30a-mapped-net.fabricmc.yarn-20w30a+build.8-v2.jar:?]
	... 11 more
```

**Comment by shedaniel** [comment]
Support for snapshots versions of non-major minectaft versions is not guaranteed, I am not sure if I will support this.

**Comment by TheBrokenRail** [comment]
OK, thank you.

**Comment by shedaniel** [comment]
I'm going to leave this issue up, for future reference purposes.
