### ISSUE TITLE
[Bug]Server crash

### ISSUE THREAD

**Issue by Romz24** [shedaniel/RoughlyEnoughItems#431]
**Describe the bug**
После обновления мода сервер больше не запускается.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Version: 5.8.0
 - Fabric API: 0.25.1+build.416-1.16

**Logs**
```
[14:43:49] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems-runtime'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: Fabric API is not installed! https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all
        at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:80) ~[a20ed3f0-2b3f-4373-aa60-3becc9973475.jar:?]
        at me.shedaniel.rei.RoughlyEnoughItemsState.checkRequiredFabricModules(RoughlyEnoughItemsState.java:72) ~[a20ed3f0-2b3f-4373-aa60-3becc9973475.jar:?]
        at me.shedaniel.rei.RoughlyEnoughItemsNetwork.onInitialize(RoughlyEnoughItemsNetwork.java:60) ~[a20ed3f0-2b3f-4373-aa60-3becc9973475.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more

```

**Comment by shedaniel** [comment]
Can you provide the full log?

**Comment by Romz24** [comment]
I see that the error says that the Fabric API is missing, but it is not. The server works stably with the mod version 5.7.1, but when I updated to 5.8.0 this error appeared. I also want to note that the server completely freezes on this error, so there is no crash log.

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/5494174/latest.log)
