### ISSUE TITLE
it crashes when i launch the game

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#467]
**Describe the bug**
If I fire up forge 1.16.5 it shows up with a error saying "RoughlyEnoughItems (roughlyenoughitems) encountered an error during the common_setup event phrase" and its weird
i launch forge
i crash

![Screenshot 2_9_2021 3_22_56 PM](https://user-images.githubusercontent.com/78827091/107436490-d72eeb80-6aea-11eb-8c28-93eff93127b5.png)

 minecraft 1.16.5
1.16.5-forge-36.0.19

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/9/21 3:16 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5069/810103755.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4705/26568117.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.19.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$437/648630181.call(Unknown Source) [forge-1.16.5-36.0.19.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD roughlyenoughitems --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: me/shedaniel/math/Point
		at me.shedaniel.rei.impl.Internals.<clinit>(Internals.java:70) ~[?:?] {re:classloading}
		at me.shedaniel.rei.impl.ClientHelperImpl.<init>(ClientHelperImpl.java:240) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at me.shedaniel.rei.RoughlyEnoughItemsCore.<clinit>(RoughlyEnoughItemsCore.java:110) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at me.shedaniel.rei.RoughlyEnoughItemsInit$$Lambda$4806/167056257.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:137) ~[?:?] {re:classloading}
		at me.shedaniel.rei.RoughlyEnoughItemsInit.<init>(RoughlyEnoughItemsInit.java:45) ~[?:?] {re:classloading}
		at me.shedaniel.rei.RoughlyEnoughItems.onSetup(RoughlyEnoughItems.java:37) ~[?:?] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_0_RoughlyEnoughItems_onSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2561/823178164.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.0] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3096/2045143855.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: RoughlyEnoughItems-Forge-5.9.1+20210130-0638.jar
	Failure message: Roughly Enough Items (roughlyenoughitems) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: me/shedaniel/math/Point
	Mod Version: 5.9.1+20210130-0638
	Mod Issue URL: https://github.com/shedaniel/RoughlyEnoughItems/issues
	Exception message: java.lang.ClassNotFoundException: me.shedaniel.math.Point
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at me.shedaniel.rei.impl.Internals.<clinit>(Internals.java:70) ~[?:?] {re:classloading}
	at me.shedaniel.rei.impl.ClientHelperImpl.<init>(ClientHelperImpl.java:240) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.RoughlyEnoughItemsCore.<clinit>(RoughlyEnoughItemsCore.java:110) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.RoughlyEnoughItemsInit$$Lambda$4806/167056257.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:137) ~[?:?] {re:classloading}
	at me.shedaniel.rei.RoughlyEnoughItemsInit.<init>(RoughlyEnoughItemsInit.java:45) ~[?:?] {re:classloading}
	at me.shedaniel.rei.RoughlyEnoughItems.onSetup(RoughlyEnoughItems.java:37) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_0_RoughlyEnoughItems_onSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2561/823178164.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3096/2045143855.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1334839544 bytes (1273 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.19.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.19.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.19.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.19.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.19.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.19
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.19-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|NOSIGNATURE
		RoughlyEnoughItems-Forge-5.9.1+20210130-0638.jar  |Roughly Enough Items          |roughlyenoughitems            |5.9.1+20210130-0638 |ERROR     |NOSIGNATURE
		forge-1.16.5-36.0.19-universal.jar                |Forge                         |forge                         |36.0.19             |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |SIDED_SETU|NOSIGNATURE
	Crash Report UUID: fa09f4a9-2e42-461e-9817-c319953f90cb

**Comment by shedaniel** [comment]
install cloth config
