### ISSUE TITLE
[Bug] REI and Kubejs electric boogaloo

### ISSUE THREAD

**Issue by Monster-Zer0** [shedaniel/RoughlyEnoughItems#545]
[16:45:57] [main/ERROR]: Failed to check if the recipe is visible!
java.lang.NullPointerException: null
	at dev.latvian.kubejs.integration.rei.REIPlugin.lambda$registerOthers$1(REIPlugin.java:47) ~[kubejs-1605.3.10-build.8-fabric.jar:?]
	at me.shedaniel.rei.impl.RecipeHelperImpl.isDisplayVisible(RecipeHelperImpl.java:587) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.rei.impl.RecipeHelperImpl.buildMapFor(RecipeHelperImpl.java:178) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.rei.impl.ClientHelperImpl$ViewSearchBuilder.lambda$new$0(ClientHelperImpl.java:271) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at net.minecraft.class_3528.method_15332(class_3528.java:16) ~[intermediary-1.16.5.jar:?]
	at me.shedaniel.rei.impl.ClientHelperImpl$ViewSearchBuilder.buildMap(ClientHelperImpl.java:354) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.rei.impl.ClientHelperImpl.openView(ClientHelperImpl.java:209) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.rei.gui.widget.EntryWidget.method_25404(EntryWidget.java:456) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.rei.gui.widget.EntryListWidget.method_25404(EntryListWidget.java:414) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.rei.gui.ContainerScreenOverlay.method_25404(ContainerScreenOverlay.java:664) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$22(RoughlyEnoughItemsCore.java:599) ~[6803fa9f-26d0-45b6-9479-375a4d9c1106.jar:?]
	at me.shedaniel.cloth.api.client.events.v0.ClothClientHooks.lambda$null$28(ClothClientHooks.java:159) ~[83e36ce6-688b-4bf3-a627-1a3e42554e50.jar:?]
	at net.minecraft.class_309.handler$bdd001$onKey(class_309.java:2106) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_309.method_1466(class_309.java:343) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_309.method_22678(class_309.java:433) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_309.method_22676(class_309.java:433) ~[intermediary-1.16.5.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1068) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171) ~[?:?]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) ~[?:?]
	at java.util.HashMap$Values.forEach(Unknown Source) [?:1.8.0_181]
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by shedaniel** [comment]
Is there a reproducable environment or can you run with Java 14+ Helpful NullPointerException?

**Comment by shedaniel** [comment]
Fixed.

**Comment by roflmuffin** [comment]
Hey shedaniel I am getting a very similar error in kubejs 3.11-build.35 against REI version 5.12.248. Do you know what version this was patched in or what commit fixed the issue?

**Comment by shedaniel** [comment]
It's most likely some incompatible REI plugins, try updating all the mods.

**Comment by roflmuffin** [comment]
Thanks shedaniel, I managed to find the problem mod by slowly removing mods
until the error disappeared.
