### ISSUE TITLE
[Bug]  Game keeps crashing spitting this ERR-Output

### ISSUE THREAD

**Issue by SirTwsted** [shedaniel/RoughlyEnoughItems#583]
Using Minecraft 1.17 with Fabric and a bunch of fabric mods on custom build.

`
---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/18/21, 4:27 AM
Description: Rendering background of entry

java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null
	at net.minecraft.class_918.method_23182(class_918.java:3048)
	at net.minecraft.class_918.method_23179(class_918.java:170)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:287)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:219)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:176)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:110)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:259)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:599)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:497)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$18(RoughlyEnoughItemsCoreClient.java:322)
	at net.minecraft.class_757.handler$zdd000$renderScreenPost(class_757.java:2013)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$cfo000$fillPatchouliContext(class_128.java:521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cfo000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:36)
	at net.minecraft.class_128.method_560(class_128.java:266)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:34)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:179)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:110)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:259)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:599)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:497)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$18(RoughlyEnoughItemsCoreClient.java:322)
	at net.minecraft.class_757.handler$zdd000$renderScreenPost(class_757.java:2013)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
`

**Comment by shedaniel** [comment]
I need your full crash log, yours is cut off

**Comment by shedaniel** [comment]
I am closing this issue due to inactivity, please attach the **full** logs and reopen this issue.
