### ISSUE TITLE
[Bug] Unable to launch game, crash report references RoughlyEnoughItems as the cause.

### ISSUE THREAD

**Issue by LiviiYS** [shedaniel/RoughlyEnoughItems#584]
Using Minecraft 1.17.1 with Fabric and a bunch of fabric mods on custom build.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/18/21, 7:14 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.redirect$bma000$catchFabricInit(class_310.java:5564)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:79)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:39)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:194)
	at jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy32.onInitialize(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at me.shedaniel.rei.impl.common.registry.RecipeManagerContextImpl.supplier(RecipeManagerContextImpl.java:50)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.attachCommonInternals(RoughlyEnoughItemsCore.java:97)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.<clinit>(RoughlyEnoughItemsCore.java:71)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:56)
	... 16 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Encountered undecorated Accessor method in patchouli.mixins.json:AccessorRecipeManager applying to net.minecraft.class_1863
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.isAlreadyMerged(MixinApplicatorStandard.java:632)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:548)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1054)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$cgh000$fillPatchouliContext(class_128.java:1521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cgh000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:37)
	at net.minecraft.class_310.redirect$bma000$catchFabricInit(class_310.java:5566)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 127188240 bytes (121 MiB) / 847249408 bytes (808 MiB) up to 5402263552 bytes (5152 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f50
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18691.55
	Virtual memory used (MB): 10761.33
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5152m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		adaptivebrightness: Adaptive Brightness 1.0.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		amecsapi: Amecs API 1.1.4+mc21w16a
		apoli: Apoli 1.0.4
		architectury: Architectury 2.2.21
		artifality: Artifality 0.3.3
		attributefix: Attribute Fix {FABRIC} 1.0.2
		axesareweapons: Axes Are Weapons 1.3-1.17
		barrenisles: Barren Isles 1.17-1.0.4
		bclib: BCLib 0.2.3
		betterbeds: Better Beds 1.2.0
		betterbiomeblend: Better Biome Blend 1.17.0-1.1.9-fabric
		betterend: Better End 0.10.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betternether: Better Nether 5.1.3
		bettersafebed: BetterSafeBed fabric-1.17-1.4
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		blockus: Blockus 2.2.6+1.17.1
		bobby: Bobby 2.0.4
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.2-1.17
		calio: Calio 1.0.2
		canvas: Canvas Renderer 1.0.1802
		cardinal-components: Cardinal Components API 3.0.1
		cardinal-components-base: Cardinal Components API (base) 3.0.1
		cardinal-components-block: Cardinal Components API (blocks) 3.0.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.1
		cardinal-components-entity: Cardinal Components API (entities) 3.0.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		cardinal-components-level: Cardinal Components API (world saves) 3.0.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.1
		cardinal-components-util: Cardinal Components API (utilities) 3.0.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.1
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.20.0+build.633
		charm: Charm 3.3.0
		charmonium: Charmonium 3.3.0
		classicbeaches: Classic Beaches 0.3.1
		cleanview: CleanView 1.17.1-v1-fabric
		clientsidenoteblocks: ClientSideNoteblocks 2.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		clumps: Clumps fabric-1.17-7.0.0.2
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		compactstatuseffects: Compact Status Effects 2.0.1
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		creeperaiupdated: Creeper AI Updated 1.4.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customspawns: Custom Spawns 0.3-1.17.1
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.2
		enchant_giver: Enchant Giver 1.1.0
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.1
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.2
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.2
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.1
		expandedstorage: Expanded Storage 7.0.0-alpha.33
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fasttransferlib: Fast Transfer Lib 0.5.5
		fermion: Fermion 2.11.243
		fermion-orientation: Fermion Orientation 1.2.243
		fermion-varia: Fermion Varia 2.6.243
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.21
		food_highlight: FoodHighlight 1.0.1
		frex: FREX 5.2.225
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.8
		grondag_bitraster: bitraster 1.4.12
		harderzombies: Harder Zombies 1.0.0
		hologram-api: Hologram API 0.1.2+1.17.1
		hwg: Happiness is a Warm Gun 1.0.6
		hydrogen: Hydrogen 0.3
		illuminations: Illuminations 1.6.1
		indrev: Industrial Revolution 1.10.0-alpha.9
		inventoryprofilesnext: Inventory Profiles Next 0.8.2
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		ironfurnaces: Iron Furnaces 1.17.1-2.6.0-fabric
		itemmodelfix: Item Model Fix 1.0.2+1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		json-model-extensions: JSON Model Extensions 1.22.201
		krypton: Krypton 0.1.4
		lakeside: Lakeside 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		maelstrom_library: Maelstrom Library 1.2.1-1.17-pre1
		magna: Magna 0.3.0-1.17-pre4
		mcda: MC Dungeons Armors 1.7.5
		mcdar: MC Dungeons Artifacts 1.3.1
		mcdw: MC Dungeons Weapons 3.2.4
		minecraft: Minecraft 1.17.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.3-1.17-pre1
		modmenu: Mod Menu 2.0.2
		more_gems: More Gems 1.2.25
		morevillagers-fabric: MoreVillagersFabric 2.0.3-SNAPSHOT
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		multipart_entities: MultipartEntities 1.1.2-1.17
		nbtcrafting: NBT Crafting 2.0.16+mc1.17
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		npcvariety: NPC Variety 2.1.2
		nyfsquivers: Nyf's Quivers Fabric-0.2.4
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.0.3
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		particlerain: Particle Rain 1.3.1
		patchouli: Patchouli 1.17-52-FABRIC-SNAPSHOT
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		placeholder-api: Fabric Placeholder API 1.0.1+1.17
		platinum: Platinum Mod 6.3.0
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		polymer: Polymer 0.1.0-pre9+1.17.1
		pugh_tools: Pugh Tools ${version}
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		roughlyenoughitems: Roughly Enough Items 6.0.262-alpha
		scorch: Scorch 1.0.2
		secondchance: Second Chance 1.0.0
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc3-1.17.1
		simple_backpack: SimpleBackpack 1.1.13
		special-circumstances: Special Circumstances 1.9.243
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stepup: StepUp 1.17.1-fabric0.36.1-1.1
		stonevaults: Stonevaults 1.0.0
		taxfreelevels: Tax Free Levels 1.2.1
		team_reborn_energy: Energy 0.1.1
		trinkets: Trinkets 3.0.2
		tweed: Tweed 3.0.0-beta.26
		universal-graves: Universal Graves 1.0.7+1.17.1
		villagershats: Goosik's Villager Hats 1.2.0
		waystones: Waystones 2.0.2
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.5
		woods_and_mires: Woods and Mires 1.1.0+1.17
		wthit: wthit 3.7.0
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Fabric Loader (fabricloader), Roughly Enough Items (roughlyenoughitems)

**Comment by shedaniel** [comment]
Patchouli's mixin failed to apply, not REI's issue.
