### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SylisMC** [shedaniel/RoughlyEnoughItems#611]
Game crash with RoughlyEnoughItems-6.0.268-alpha-fabric.jar randomly when in menus (usually when editing settings or in recipie viewer

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/26/21, 11:25 AM
Description: mouseClicked event handler

java.lang.ClassCastException: class net.minecraft.class_481 cannot be cast to class net.minecraft.class_518 (net.minecraft.class_481 and net.minecraft.class_518 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultRecipeBookExclusionZones.provide(DefaultRecipeBookExclusionZones.java:41)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.lambda$register$0(ExclusionZonesImpl.java:121)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.getExclusionZones(ExclusionZonesImpl.java:104)
	at me.shedaniel.rei.api.client.registry.screen.ExclusionZones.getExclusionZones(ExclusionZones.java:41)
	at badasintended.cpas.runtime.rei.CpasReiPlugin.lambda$registerExclusionZones$1(CpasReiPlugin.java:27)
	at badasintended.cpas.runtime.CpasClient.panel(CpasClient.java:179)
	at badasintended.cpas.runtime.CpasClient.injectCpasWidget(CpasClient.java:159)
	at badasintended.cpas.runtime.CpasClient.lambda$onInitializeClient$4(CpasClient.java:68)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:103)
	at net.minecraft.class_437.handler$zpm000$afterInitScreen(class_437.java:2307)
	at net.minecraft.class_437.method_25423(class_437.java:391)
	at net.minecraft.class_310.method_1507(class_310.java:984)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.saveAll(AbstractConfigScreen.java:178)
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen.lambda$init$4(GlobalizedClothConfigScreen.java:150)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:264)
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen.method_25402(GlobalizedClothConfigScreen.java:307)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1137)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultRecipeBookExclusionZones.provide(DefaultRecipeBookExclusionZones.java:41)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.lambda$register$0(ExclusionZonesImpl.java:121)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.getExclusionZones(ExclusionZonesImpl.java:104)
	at me.shedaniel.rei.api.client.registry.screen.ExclusionZones.getExclusionZones(ExclusionZones.java:41)
	at badasintended.cpas.runtime.rei.CpasReiPlugin.lambda$registerExclusionZones$1(CpasReiPlugin.java:27)
	at badasintended.cpas.runtime.CpasClient.panel(CpasClient.java:179)
	at badasintended.cpas.runtime.CpasClient.injectCpasWidget(CpasClient.java:159)
	at badasintended.cpas.runtime.CpasClient.lambda$onInitializeClient$4(CpasClient.java:68)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:103)
	at net.minecraft.class_437.handler$zpm000$afterInitScreen(class_437.java:2307)
	at net.minecraft.class_437.method_25423(class_437.java:391)
	at net.minecraft.class_310.method_1507(class_310.java:984)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.saveAll(AbstractConfigScreen.java:178)
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen.lambda$init$4(GlobalizedClothConfigScreen.java:150)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at me.shedaniel.clothconfig2.gui.AbstractConfigScreen.method_25402(AbstractConfigScreen.java:264)
	at me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen.method_25402(GlobalizedClothConfigScreen.java:307)
	at net.minecraft.class_312.method_1611(class_312.java:94)

-- Affected screen --
Details:
	Screen name: me.shedaniel.clothconfig2.gui.GlobalizedClothConfigScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_746['Sylis'/216, l='ClientLevel', x=-30.98, y=64.00, z=4.20]]
	Chunk stats: 1024, 550
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,69,2), Section: (at 0,5,2 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 9359 game time, 9359 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 865445328 bytes (825 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21966.85
	Virtual memory used (MB): 14944.44
	Swap memory total (MB): 5632.00
	Swap memory used (MB): 32.22
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.2
		adorn: Adorn 2.1.3+1.17.1
		adventurez: AdventureZ 1.2.11
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.4.26
		bclib: BCLib 0.3.1
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterbiomeblend: Better Biome Blend 1.17.0-1.2.9-fabric
		betterend: Better End 0.11.0-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		bettermounthud: Better Mount HUD 1.1.2
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		betteruiscale: Better UI Scaling 1.1.0
		biom4st3r_repackaged_expressions: expj4_repackaged 0.1.0
		blur: Blur (Fabric) 2.1.0
		caelus: Caelus API 0.0.16-1.17
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-item: Cardinal Components API (items) 3.0.0-nightly.1.17-pre2
		carpet: Carpet Mod 1.4.45
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chipped: Chipped 1.1.1
		cleanview: CleanView 1.17.1-v1-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		consistency_plus: Consistency Plus 0.4.0
		couplings: Couplings 1.5.0+1.17
		cpas: cpas 2.0.0
		cpas-api: cpas-api 2.0.0
		cpas-runtime: cpas-runtime 2.0.0
		cpas-trinkets: cpas-trinkets 2.0.0
		croptopia: Croptopia 1.6.1
		dark-loading-screen: Dark Loading Screen 1.6.7
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		doublejump: Double Jump Mod 1.0.1+mc1.17
		dragonloot: DragonLoot 1.0.9
		dual_riders: DualRiders 1.0.5
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enhancedcelestials: Enhanced Celestials 2.0.3
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.7
		fpsdisplay: FPS-Display 1.4.1+1.17
		geckolib3: Geckolib 3.0.13
		illuminations: Illuminations 1.6.4
		improved-stations: Improved Stations 2.0.7
		inventorio: Inventorio 1.6.2
		inventoryhud: Inventory HUD + 3.4.0
		iris: Iris 1.1.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		lakeside: Lakeside 1.1.0+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lapisreserve: Lapis Reserve 1.0.8
		lengthyladders: Lengthy Ladders 1.0.4
		levelz: LevelZ 1.0.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		logistical_mining: Logistical Mining 0.1.0
		lovely_snails: Lovely Snails 1.0.3+1.17
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.5
		moenchant_lib: Mo'Enchantment Library 0.1.2
		moenchantments: Mo'Enchantments 1.17.5
		moretotems: More Totems 2.8.0
		mythic-mounts: Mythic Mounts 1.17.1-1.1
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		netherchest: Nether Chest 2.0
		newcaves: New Caves 2.2
		no-potion-offset: No Potion Offset ${version}
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		particle_emitter_biom4st3r: Particle Emitters LIB 0.1.0
		particlerain: Particle Rain 1.4.1
		physicsmod: Physics Mod 2.5.5
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		rangers_haven: Ranger's Haven 2.3.1
		repurposed_structures: Repurposed Structures 2.3.1+1.17.1
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.268-alpha
		satin: Satin 1.6.0-nightly.1.17-pre3
		silver: Silver Mod 6.2.1
		simplyplatinum: Simply Platinum 3.0
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.3.0+IRIS2
		spruceui: SpruceUI 3.2.0+1.17
		stoneholm: Stoneholm 1.3
		tooltipfix: ToolTip Fix 1.0.3-1.16
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.2
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		wthit: wthit 3.8.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.68, NVIDIA Corporation
	Window size: 2560x1377
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, charmonium/journeyman
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
	Player Count: 1 / 8; [class_3222['Sylis'/216, l='ServerLevel[New World]', x=-30.98, y=64.00, z=4.20]]
	Data Packs: vanilla, Fabric Mods
```

**Comment by alexmozaidze** [comment]
Try removing Conveniently Placed Armor Slots (cpas) and attempt to reproduce the crash
