### ISSUE TITLE
[Bug] Recipes do not show in inventory on multiplayer server

### ISSUE THREAD

**Issue by walshyb** [shedaniel/RoughlyEnoughItems#612]
**Describe the bug**
Hi, I have a multiplayer server with [Another Quality Modpack 2](https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2) -- that has this mod in it -- running on a curseforge client. Upon startup of the curseforge client and going directly onto my server, when I open my inventory, I don't see the list of all blocks on the right side of my screen. Furthermore, the recipe book is empty.

How I fix this is by entering a single player world, then going onto my server, then I see all the blocks / items and my recipe book is populated. I believe the issue stems from this mod. 

The issue might be a permissions / environment error that gets fixed once you go to a singleplayer world (where you're given granted almost all perms and access to commands). I couldn't find a config file for this, probably because this is a client side mod (I think).  

**Steps to Reproduce**
- Open up curseforge
- Connect to a server running this mod
- Open the inventory

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
pt1: https://pastebin.com/aRjzCuty
pt2: https://pastebin.com/ywD7yLxs

**Comment by shedaniel** [comment]
Do you have logs from the server?

**Comment by walshyb** [comment]
Here it is from a freshly restarted server: 
https://pastebin.com/sp3KfcZY

Didn't see much there though

**Comment by shedaniel** [comment]
Can you show a server log with some players joining it?

**Comment by walshyb** [comment]
Sure! I went on a couple times and another person did too just now:
https://pastebin.com/ju6Dpqxn

**Comment by shedaniel** [comment]
It seems like NBTCrafting is causing it to fail:
```
[13:28:10] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Server player entity cannot be null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.46) ~[?:?]
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.canSend(ServerPlayNetworking.java:182) ~[6a0c5f32-c8ff-41ab-86c0-83af735be162.jar:?]
	at de.siphalor.nbtcrafting.NbtCrafting.hasClientMod(NbtCrafting.java:142) ~[8eadedaf-2f43-4b91-80a0-a7a9d8f95304.jar:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.handler$zpe000$onWrite(SynchronizeRecipesS2CPacket:541) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.write(SynchronizeRecipesS2CPacket) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.handler$bob000$replaceRecipesOnClient(SynchronizeRecipesS2CPacket:1049) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.getRecipes(SynchronizeRecipesS2CPacket) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onSynchronizeRecipes(ClientPlayNetworkHandler:1240) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:32) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:14) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1075) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```
I am going to add a thing that "tries" to detect things like this, NBTCrafting is causing a lot of issues recently.

**Comment by itsdinkd** [comment]
Hey guys, it was due to McDoom

@walshyb update the modpack to the latest version, grab the server pack on curseforge. I edited McDoom to take out NBTCrafting as the author of Mcdoom didn't care to fix the recipe that required this nbtcrafting dependacy.
