### ISSUE TITLE
[Bug] No Recipes - Error in log

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#626]
Latest.log error, joined single player, not able to view any recipes.

1.17.1, latest version of REI, latest fabric API

[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: java.util.ConcurrentModificationException
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_2588.method_27660(class_2588.java:131)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_2561.method_27658(class_2561.java:79)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_5223.method_27476(class_5223.java:128)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_5225.method_27488(class_5225.java:47)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_327.method_27525(class_327.java:360)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_1799.md489193$lambda$appendEnchantmentsHead$0$0(class_1799.java:1214)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:698)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_1799.localvar$ggn000$appendEnchantmentsHead(class_1799.java:1214)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_17870(class_1799.java)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7950(class_1799.java:682)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:201)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:341)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:181)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:81)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:208)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:193)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:177)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:57)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:46)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[12:09:35] [ForkJoinPool.commonPool-worker-13/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by itsdinkd** [comment]
modlist







    MC Story Mode Armors (by chronos_sacaria)
    DragonLoot (by pois1xlive)
    Charmonium (by svenhjol)
    AdventureZ (by Globox_Z)
    Patchouli (Fabric) (by williewillus)
    Harvest Scythes (by LordDeatHunter)
    I Know What I'm Doing (IKWID) (by HeckinChloe)
    Motschen's Better Leaves (by Motschen)
    Your Options Shall Be Respected (YOSBR) (by shedaniel)
    Conjuring [Fabric/Forge] (by gliscowo)
    Workbench Factory (by puggan)
    Chipped (by grimbop)
    Cardinal Components (by UpcraftLP)
    Balm (Fabric Edition) (by BlayTheNinth)
    Universal Graves (by Patbox)
    Tech Reborn (by modmuss50)
    Addendum (Fabric) (by eltrutlikes)
    Kibe Utilities (by D4rkness_King)
    Respawnable Pets (by MoriyaShiine)
    LazyDFU (by tuxed)
    Pehkui (by Virtuoel)
    Logical Zoom (by logicalgeekboy)
    Somnus API (by TheIllusiveC4)
    MCDoom (by AzureDoomC)
    Konkrete [Fabric] (by Keksuccino)
    MinecraftCapes Mod (by james090500)
    Near-Sightedly (by ItsPonks)
    More Villagers [Fabric] (by SameDifferent)
    Nyf's Quivers (by theNyfaria)
    Hwyla Addon Horse Info (by Pancham138)
    Glassential (Fabric) (by Lykrast)
    Enchantment Descriptions (by DarkhaxDev)
    ConnectedTexturesMod for Fabric (by Pepper_Bell)
    When Dungeons Arise - Fabric! (by Aureljz)
    Just Enough Keys [JEK] [Fabric] (by starmun)
    Drippy Loading Screen [Fabric] (by Keksuccino)
    Additional Enchanted Miner (by Kotori316)
    Open Loader (by DarkhaxDev)
    LambDynamicLights (by LambdAurora)
    Presence Footsteps (by S0llace)
    KubeJS Extras (by thetechnici4n)
    FabricTailor (by samo_lego)
    Fabric Enchantments (by safrodev)
    Farmer's Delight [Fabric] (by NewHoryzon)
    Tom's Simple Storage Mod (Fabric) (by tom54541)
    BetterEnd (by paulevs)
    Explorer's Compass (by Chaosyr)
    Entity Culling Fabric/Forge (by tr9zw)
    BLAST 💣 (by doctor4t)
    Auth Me (by Axieum)
    BCLib (by paulevs)
    Carrier (by GabrielHOlv)
    Building Wands (by nicguzzo)
    YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)
    RSWires (by 2xsaiko)
    Resource Tools [FABRIC] (by kwpugh)
    Advancements Enlarger (by shedaniel)
    Blur (Fabric) (by Motschen)
    Draylar's Battle Towers (by Draylar1)
    NoMoreGlowingPots (by zabi94)
    Fast Furnace for Fabric (by tfarecnim)
    Void Totem (Fabric) (by Affehund)
    Nature's Compass (by Chaosyr)
    Mod Menu (by ProspectorDev)
    MaLiLib (by masady)
    megane (by badasintended)
    Things [Fabric] (by gliscowo)
    Repurposed Structures (Fabric) (by telepathicgrunt)
    An Origins Addon - Libra (by JaselUmena)
    Inventory Sorting (by Kyrptonaught)
    LambdaBetterGrass (by LambdAurora)
    Better Hearts (by milesdemillas)
    Light Overlay (Rift/Forge/Fabric) (by shedaniel)
    KubeJS (Fabric) (by shedaniel)
    Artifality (by PinkGoosik)
    Winged (by AdrianTodt)
    Mo Glass (by alexander9892)
    Health Overlay (Fabric) (by Terrails)
    Fabric Language Kotlin (by modmuss50)
    Mythic Mounts (by chirpycricket__)
    Gobber [FABRIC] (by kwpugh)
    Audio Output (by Maximumgame)
    Extra Alchemy (by zabi94)
    ToolTipFix (by Kyrptonaught)
    Clear Despawn (Fabric) (by StrikerRocker)
    Bosses of Mass Destruction (by Barribob)
    Better Enchanted Books (Fabric) (by Bernasss12)
    YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)
    Custom Portals (by palyon_1)
    Charm (by svenhjol)
    YUNG's API (Fabric) (by YUNGNICKYOUNG)
    Upgraded Shulkers (by Kyrptonaught)
    Xaero's World Map (by xaero96)
    Fabric API (by modmuss50)
    Pipe (by Flytre7)
    GeckoLib (by ThanosGecko)
    Mining Dimensions [FABRIC] (by kwpugh)
    Couplings (by HeckinChloe)
    Trinkets (Fabric) (by EmilyPloszaj)
    Dramatic Skys (by thebaum64)
    Visuality (by PinkGoosik)
    Caracal Mod (by AqUpd)
    Enchanted Book Redesign Fabric (by tfarecnim)
    Bewitchment (by MoriyaShiine)
    Incantationem (by Luligabi12)
    Rat's Mischief 🐀 (by doctor4t)
    [Fabric] Expanded Storage (by NinjaPhenix)
    No Angled Brackets (by Flytre7)
    MC Dungeons Armors (by chronos_sacaria)
    Inmis (by Draylar1)
    BetterF3 (by cominixo)
    Blockus (by Brandcraft_)
    Plant In A Jar (by cool_mineman)
    Impersonate (by PyrofabTheModsmith)
    SlotLock (by D4rkness_King)
    JumpOverFences (by Martmists)
    Red Bits (by magistermaks)
    Staff of Building (by Draylar1)
    Tool Stats (by DarkhaxDev)
    Chest Tracker (by JackFred2)
    Secret Rooms Fabric (by SpacemanKeybs)
    Deep Mob Learning: Simulacrum (by ProjectET)
    Ambient Environment (by Jaredlll08)
    Roughly Enough Items Fabric (REI) (by shedaniel)
    Cloth Config API (Fabric) (by shedaniel)
    Golems Galore (by ffrannny)
    Bits And Chisels (by cool_mineman)
    ValleyCraft (by llnkle)
    Mo' Structures (Fabric) (by ffrannny)
    MC Dungeons Weapons (by chronos_sacaria)
    Carpet (by gnembon)
    Carpet Extra (by gnembon)
    CleanCut (by Rongmario)
    Adorn (by Juicebus)
    Industrial Revolution (by GabrielHOlv)
    Quick Shulker (by Kyrptonaught)
    Lithium (Fabric) (by jellysquid3)
    Extra Origins (by MoriyaShiine)
    FerriteCore (Fabric) (by malte0811)
    Schmucks! (by ALotOfBeans)
    Heartbond [FABRIC] (by Apace100)
    Item Scroller (by masady)
    Right Click Clear (by shedaniel)
    Iron Furnaces [FABRIC] (by pizzaatime)
    ColorUtility (by axeryok)
    AppleSkin (by squeek502)
    ShulkerBoxTooltip (by MisterPeModder)
    Architectury API (Fabric) (by shedaniel)
    Origins: Classes (by Apace100)
    Prefab - Fabric (by wuestman)
    Reese's Sodium Options (by FlashyReese)
    BetterNether (by paulevs)
    Dark Paintings (by DarkhaxDev)
    Simple Backpack [FABRIC] (by kwpugh)
    Falling Leaves (Fabric) (by RandomMcSomethin)
    Sodium Extra (by FlashyReese)
    Give Me Hats! [FABRIC] (by Acrogenous)
    WTHIT (by badasintended)
    Break Progress (by haykam)
    Iris Shaders (by coderbot)
    [Fabric] Fat Experience Orbs (by NinjaPhenix)
    E Magnet [FABRIC] (by Rangetuur)
    Detail Armor Bar [Fabric] (by 빨간라임)
    Polymorph (Fabric) (by TheIllusiveC4)
    Space Dimensions (Fabric) (by captaintenneal81)
    Not Enough Crashes (Fabric) (by NatanFudge)
    The Aether Reborn (by ImmortalDevs)
    Xaero's Minimap (by xaero96)
    Art of Alchemy: Memoriam (by wtoll1)
    Beenfo (by Giselbaer)
    Skin Layers 3D (Fabric/Forge) (by tr9zw)
    Deep Mob Learning: Refabricated (by NathanPB)
    Fabric Waystones (by LordDeatHunter)
    PlayerAbilityLib (by PyrofabTheModsmith)
    Attribute Fix {FABRIC} (by Flytre7)
    Carpet TIS Addition (by Fallen_Breath)
    Simple Grinder (by Rumaruka)
    Better Wandering Traders (by cyborg_pigeon)
    Fabric Language Scala (by modmuss50)
    Crafting Tweaks (Fabric Edition) (by BlayTheNinth)
    Origins (Fabric) (by Apace100)
    Ward Blocks [FABRIC] (by kwpugh)
    Cloth API (Fabric) (by shedaniel)
    Grim's Transportables (by TheGrimsey)
    Blockshifter [Fabric] (by LolHens)
    Cull Leaves (by Motschen)
    Cosmetic Armor [FABRIC] (by Apace100)
    Croptopia [FABRIC/FORGE] (by thethonk)
    CraftPresence (by CDAGaming_)
    True Secret Rooms (by LudoCrypt)
    Unity: Dark Edition (by theCyanideX)
    cAn i MiNe thIS bLOCk? (by shedaniel)
    Flytre Lib (FlytreLib) (by Flytre7)
    Golden Hoppers (by haykam)
    FallingTree (Forge&Fabric) (by RakSrinaNa)
    Advancement Plaques [Fabric] (by Grend_G)
    Dark Enchanting (by ffrannny)
    Eldritch Mobs (by cyborg_pigeon)
    Storage Cabinet (by AshIndigo)
    VoidZ (by Globox_Z)
    Status Effect Timer (by mag_icus)
    RPGStats (by TheoreticallyUseful)
    Mo' Colors (by GabrielHOlv)
    Go Fish (by Draylar1)
    Hookshot (by Camellias_)
    Reborn Core (by modmuss50)
    Torcherino (by sci4me)
    ToroHealth Damage Indicators (by ToroCraft)
    Wireless Networks (by GabrielHOlv)

**Comment by shedaniel** [comment]
Should be fixed in newer versions
