### ISSUE TITLE
[Bug] [Fabric] ExclusionZone causes crash on 1.18 snapshot

### ISSUE THREAD

**Issue by 27rogi** [shedaniel/RoughlyEnoughItems#638]
**Describe the bug**
Installing mod on snapshot causes game to crash when you open inventory in the world.
Error points at DefaultPotionEffectExclusionZones class.

**Steps to Reproduce**
- Install REI on 1.18 snapshot (21w39a in my case)
- Open world
- Open inventory

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18 (21w39a)
 - Mod Loader: Fabric

**Logs**
```Java
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultPotionEffectExclusionZones.provide(DefaultPotionEffectExclusionZones.java:44)
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultPotionEffectExclusionZones.provide(DefaultPotionEffectExclusionZones.java:40)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.lambda$register$0(ExclusionZonesImpl.java:121)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.isInZone(ExclusionZonesImpl.java:72)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.canItemSlotWidgetFit(EntryListWidget.java:134)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.notSteppingOnExclusionZones(EntryListWidget.java:125)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.updateEntriesPosition(EntryListWidget.java:370)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.updateSearch(EntryListWidget.java:441)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:471)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$19(RoughlyEnoughItemsCoreClient.java:329)
	at net.minecraft.class_757.handler$zgh000$renderScreenPost(class_757.java:1539)
```

**Comment by 27rogi** [comment]
I tried to build it myself with removal of that class, but got problems in IDEA, would be nice to have some instructions about building it 😞

**Comment by shedaniel** [comment]
1.18 isn't supported.
