### ISSUE TITLE
[Bug] Crash on Single Player upon loading world

### ISSUE THREAD

**Issue by joex92** [shedaniel/RoughlyEnoughItems#646]
When trying to load any world, even new ones, the game crashes...

<details>
  <summary>Here's the NotEnoughCrashes log</summary>

```yaml
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/23/21, 5:40 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: 'java.util.List net.minecraft.class_3898.method_17210(net.minecraft.class_1923, boolean)'
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.49)
	at net.fabricmc.fabric.api.networking.v1.PlayerLookup.tracking(PlayerLookup.java:94)
	at net.fabricmc.fabric.api.networking.v1.PlayerLookup.tracking(PlayerLookup.java:158)
	at net.fabricmc.fabric.api.networking.v1.PlayerLookup.tracking(PlayerLookup.java:145)
	at net.minecraft.block.entity.BlockEntity.getRecipientsForComponentSync(BlockEntity:1598)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.sync(ComponentKey.java:165)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.sync(ComponentKey.java:128)
	at dev.onyxstudios.cca.internal.CardinalComponentsBlock.lambda$init$1(CardinalComponentsBlock.java:61)
	at net.minecraft.server.world.ChunkHolder.localvar$zkn000$sendBlockEntityUpdate(ChunkHolder:1555)
	at net.minecraft.server.world.ChunkHolder.sendBlockEntityUpdatePacket(ChunkHolder:279)
	at net.minecraft.server.world.ChunkHolder.tryUpdateBlockEntityAt(ChunkHolder:272)
	at net.minecraft.server.world.ChunkHolder.method_30312(ChunkHolder:263)
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.visitUpdates(ChunkDeltaUpdateS2CPacket:72)
	at net.minecraft.server.world.ChunkHolder.flushUpdates(ChunkHolder:263)
	at java.util.Optional.ifPresent(Unknown Source)
	at net.minecraft.server.world.ServerChunkManager.method_37411(ServerChunkManager:379)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:379)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:324)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:372)
	at net.minecraft.server.MinecraftServer.redirect$cad000$ficUpdateSuppressionCrashTick(MinecraftServer:3273)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:891)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:96)
	at net.minecraft.server.MinecraftServer.handler$dhm000$modifiedRunLoop(MinecraftServer:5890)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.api.networking.v1.PlayerLookup.tracking(PlayerLookup.java:94)
	at net.fabricmc.fabric.api.networking.v1.PlayerLookup.tracking(PlayerLookup.java:158)
	at net.fabricmc.fabric.api.networking.v1.PlayerLookup.tracking(PlayerLookup.java:145)
	at net.minecraft.class_2586.getRecipientsForComponentSync(class_2586.java:1598)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.sync(ComponentKey.java:165)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.sync(ComponentKey.java:128)
	at dev.onyxstudios.cca.internal.CardinalComponentsBlock.lambda$init$1(CardinalComponentsBlock.java:61)
	at net.minecraft.class_3193.localvar$zkn000$sendBlockEntityUpdate(class_3193.java:1555)
	at net.minecraft.class_3193.method_14009(class_3193.java:279)
	at net.minecraft.class_3193.method_30311(class_3193.java:272)
	at net.minecraft.class_3193.method_30312(class_3193.java:263)
	at net.minecraft.class_2637.method_30621(class_2637.java:72)
	at net.minecraft.class_3193.method_14006(class_3193.java:263)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at net.minecraft.class_3215.method_37411(class_3215.java:379)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.redirect$cad000$ficUpdateSuppressionCrashTick(MinecraftServer.java:3273)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,4,0), Section: (at 0,4,0 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1564 game time, 1564 day time
	Level name: Void
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 46533 (now: false), thunder time: 16274 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.handler$dhm000$modifiedRunLoop(MinecraftServer.java:5890)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 16.0.2, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 1053380176 bytes (1004 MiB) / 2181038080 bytes (2080 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 2.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel HD Graphics 4000
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0166
	Graphics card #0 versionInfo: Revision ID: 0x0009, gMux Version: 1.9.23
	Graphics card #1 name: NVIDIA GeForce GT 650M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x0fd5
	Graphics card #1 versionInfo: Revision ID: 0x00a2, ROM Revision: 3682, gMux Version: 1.9.23
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 11264.00
	Virtual memory used (MB): 7834.50
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 1946.75
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementinfo: AdvancementInfo 1.17.1-fabric0.36.1-1.2.1
		animatica: Animatica 0.1+1.17
		antighost: AntiGhost 1.17.1-fabric0.36.1-1.1.4
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.5.32
		autoconfig1u: Auto Config v1 Updated 3.2.2
		bedrodium: Bedrodium 0.1
		betterbeds: Better Beds 1.2.0
		bettermounthud: Better Mount HUD 1.1.2
		capes: Capes 1.2.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		carpet: Carpet Mod 1.4.48
		carpet-extra: Carpet Extra 1.4.43
		cem: Custom Entity Models 0.6.2
		citresewn: CITResewn 0.8.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		colormatic: Colormatic 2.3.0+mc.1.17.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		completeconfig: CompleteConfig 1.2.0
		continuity: Continuity 1.0.1+1.17
		crowdin-translate: CrowdinTranslate 1.3+1.17
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		cullleaves: Cull Leaves 2.3.1
		dcch: DCCH 1.0
		durabilityviewer: Giselbaers Durability Viewer 1.17.1-fabric0.36.1-1.10.1
		dynamicfps: Dynamic FPS 2.0.6
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.41.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+6eb8b35a88
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.11.6
		fabrishot: Fabrishot 1.5.1
		fastchest: FastChest 1.2+1.17
		ferritecore: FerriteCore 3.0.3
		freelook: freelook 1.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		hydrogen: Hydrogen 0.3
		indium: Indium 1.0.0+mc1.17.1
		iris: Iris 1.1.2+build.9
		itemmodelfix: Item Model Fix 1.0.2+1.17
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		java: OpenJDK 64-Bit Server VM 16
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		languagereload: Language Reload 1.1
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.0.0-dev.20210713.103711
		lithium: Lithium 0.7.4
		littletweaks: LittleTweaks 0.1.1
		malilib: MaLiLib 0.10.0-dev.24
		midnightlib: MidnightLib 0.2.7
		minecraft: Minecraft 1.17.1
		minecraftcapes: MinecraftCapes Mod 11.0.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 2.0.14
		morechathistory: MoreChatHistory 1.1.0
		multiconnect: MultiConnect 1.4.15
		multiconnect-api: MultiConnect API 1.4.15
		no-potion-offset: No Potion Offset ${version}
		nofade: No Fade 1.17-2.0.0
		notenoughcrashes: Not Enough Crashes 3.7.0+1.17.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_pircbotx_pircbotx: pircbotx 2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.13
		plasmo_voice: Plasmo Voice 1.2.2
		polymorph: Polymorph 0.0.14-1.17.1
		reeses-sodium-options: Reese's Sodium Options 1.2.0
		replaymod: Replay Mod 1.17.1-2.6.1
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.0.306-alpha
		screenshotclipboard: Screenshot to Clipboard 1.0.6
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.2+IRIS2-build.9
		sodium-extra: Sodium Extra 0.3.5
		spruceui: SpruceUI 3.3.0+1.17
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		twitchchat: Twitch Chat Bridge 0.11.2b
		voicechat: Simple Voice Chat 1.17.1-1.1.9
		voxelmap: VoxelMap 1.10.15
		worldedit: WorldEdit 7.2.6+4b2d1e7
		worldeditcui: WorldEditCUI 1.17.1+01-SNAPSHOT
		yosbr: YOSBR 0.1.1
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	Suspected Mods: Cardinal Components API (blocks) (cardinal-components-block), Fabric Networking API (v1) (fabric-networking-api-v1), Cardinal Components API (base) (cardinal-components-base), Roughly Enough Items (roughlyenoughitems)
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 4
```
</details>

**Comment by joex92** [comment]
ok, seems like it's not REI fault...
