### ISSUE TITLE
[Bug] Minecraft shuts down when using smaller GUI scale

### ISSUE THREAD

**Issue by SmialyBoleq** [shedaniel/RoughlyEnoughItems#660]
**Minecraft shuts down when GUI scale is changed to 2.0**
When using 3.0 scale everything is okay, but REI got problem with smaller GUI scale. It seems okay when entering the game but after a couple of times I open inventory or check recipes game shuts down and displays an error log. I got newest version of REI including every API

**Steps to Reproduce**
- Enter the inventory or click on recipe in REI interface couple of times with scale 2.0 of GUI

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric
 - JAVA 16.0.1

**Minecraft log**
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 19.11.2021, 23:44
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index 7 out of bounds for length 7
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.set(ArrayList.java:441)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplImpl.handler$ddm000$onRenderTooltip(ScreenOverlayImplImpl.java:538)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplImpl.renderTooltipInner(ScreenOverlayImplImpl.java:60)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltipInner(ScreenOverlayImpl.java)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:585)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:572)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:342)
	at net.minecraft.class_757.handler$zcp000$renderScreenPost(class_757.java:1539)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.set(ArrayList.java:441)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplImpl.handler$ddm000$onRenderTooltip(ScreenOverlayImplImpl.java:538)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplImpl.renderTooltipInner(ScreenOverlayImplImpl.java:60)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltipInner(ScreenOverlayImpl.java)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:585)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:572)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:342)
	at net.minecraft.class_757.handler$zcp000$renderScreenPost(class_757.java:1539)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (640, 254). Absolute: (1280.000000, 509.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by shedaniel** [comment]
Do you have AppleSkin, this looks like a crash by that
