### ISSUE TITLE
[Bug]Crash on Startup

### ISSUE THREAD

**Issue by MoonlightSystem** [shedaniel/RoughlyEnoughItems#746]
**Describe the bug**
With the latest version of Fabric REI on curseforge, I crash on startup

**Steps to Reproduce**
- Launch the game
- crash

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [1.18.1]
 - Mod Loader: [Fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://paste.ee/p/F68Wh
https://paste.ee/p/dFSlX

**Additional context**
Using Fabulously Optimised, if that helps...

**Comment by egeesin** [comment]
For me, since 7.2.416 Fabric version, client crashes at startup when only one mod is enabled excluding dependencies and REI itself.

- **BetterBlockOutline 1.4.1-1.18.1**
- Architectury 3.4.9
- Cloth Config 6.1.50
- Fabric API 0.46.2+1.18
- Roughly Enough Items 7.2.416

Also there wasn't any problem when exact same version of BetterBlockOutline is enabled with prior version of REI (7.2.409).
Here's my [latest.log](https://paste.ee/p/WtXRF).

**Comment by magneticflux-** [comment]
Same issue. Full log: https://paste.ee/p/rM4YV
The relevant part of the log:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.impl.client.ClientHelperImpl
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:80)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitializeClient(RoughlyEnoughItemsInitializer.java:48)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy82.onInitializeClient(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 19 more
Caused by: java.lang.RuntimeException: Mixin transformation of me.shedaniel.rei.impl.client.gui.screen.CompositeDisplayViewingScreen failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:57)
	... 23 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector fillGradient(Lme/shedaniel/rei/impl/client/gui/screen/CompositeDisplayViewingScreen;Lnet/minecraft/class_4587;IIIIII)V in slight-gui-modifications.mixins.json:rei.MixinVillagerRecipeViewingScreen from mod slight-gui-modifications failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap slight-gui-modifications-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject$failsoft(gist.github.com/517e2d6d4c6a75303721b7e2e995a9f8)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 32 more
```

**Comment by shedaniel** [comment]
Issue with Slight Gui Modifications, please report to them
