### ISSUE TITLE
[Bug] crash after opening inventory

### ISSUE THREAD

**Issue by freopt** [shedaniel/RoughlyEnoughItems#761]
### What happened?

first time opening inventory after world creation
crash

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[17:29:23] [Server thread/WARN]: JEI not present, can't lookup item colors
java.lang.NoClassDefFoundError: mezz/jei/color/ColorGetter
	at sirttas.elementalcraft.item.ECItem.lookupColor(ECItem.java:61) ~[elementalcraft-1.18.1-4.1.7.jar%23110!/:1.18.1-4.1.7]
	at sirttas.elementalcraft.item.pureore.PureOreManager$Entry.lambda$addRecipe$3(PureOreManager.java:227) ~[elementalcraft-1.18.1-4.1.7.jar%23110!/:1.18.1-4.1.7]
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[fmlcore-1.18.1-39.0.64.jar%23251!/:?]
	at sirttas.elementalcraft.item.pureore.PureOreManager$Entry.addRecipe(PureOreManager.java:227) ~[elementalcraft-1.18.1-4.1.7.jar%23110!/:1.18.1-4.1.7]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at sirttas.elementalcraft.item.pureore.PureOreManager.lambda$generatePureOres$9(PureOreManager.java:118) ~[elementalcraft-1.18.1-4.1.7.jar%23110!/:1.18.1-4.1.7]
	at com.google.common.collect.Maps$KeySet.lambda$forEach$0(Maps.java:3916) ~[guava-31.0.1-jre.jar%2321!/:?]
	at com.google.common.collect.HashBiMap$Inverse.lambda$forEach$0(HashBiMap.java:738) ~[guava-31.0.1-jre.jar%2321!/:?]
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2321!/:?]
	at com.google.common.collect.HashBiMap$Inverse.forEach(HashBiMap.java:738) ~[guava-31.0.1-jre.jar%2321!/:?]
	at com.google.common.collect.Maps$KeySet.forEach(Maps.java:3916) ~[guava-31.0.1-jre.jar%2321!/:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at sirttas.elementalcraft.item.pureore.PureOreManager.generatePureOres(PureOreManager.java:116) ~[elementalcraft-1.18.1-4.1.7.jar%23110!/:1.18.1-4.1.7]
	at sirttas.elementalcraft.item.pureore.PureOreManager.reload(PureOreManager.java:191) ~[elementalcraft-1.18.1-4.1.7.jar%23110!/:1.18.1-4.1.7]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at sirttas.dpanvil.DataPackAnvil.onReloadComplet(DataPackAnvil.java:71) ~[dpanvil-1.18.1-3.2.0.jar%23103!/:1.18.1-3.2.0]
	at sirttas.dpanvil.DataPackAnvil.serverStarted(DataPackAnvil.java:50) ~[dpanvil-1.18.1-3.2.0.jar%23103!/:1.18.1-3.2.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:107) ~[forge-1.18.1-39.0.64-universal.jar%23254!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:645) ~[client-1.18.1-20211210.034407-srg.jar%23250!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23250!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: mezz.jei.color.ColorGetter
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 28 more

net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: elementalcraft:elementalcraft:water
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.18.1-20211210.034407-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getResourceLocation(IIngredientHelper.java:108) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getDisplayModId(IIngredientHelper.java:81) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.jeicompat.wrap.JEIEntryDefinition.getContainingNamespace(JEIEntryDefinition.java:95) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getContainingNamespace(AbstractEntryStack.java:134) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:214) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.18.1-20211210.034407-srg.jar%23250!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getResourceLocation(IIngredientHelper.java:108) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getDisplayModId(IIngredientHelper.java:81) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
-- Screen details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:49) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:43) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:231) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106) ~[RoughlyEnoughItems-7.2.422.jar%23215!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: elementalcraft:main_ingredientelementtype
	Is empty: false
	Entry identifier: ~~ERROR~~ ResourceLocationException: Non [a-z0-9/._-] character in path of location: elementalcraft:elementalcraft:water

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.jeicompat.wrap.JEIEntryDefinition

-- Screen details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen

-- Search entry details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: elementalcraft:main_ingredientelementtype
	Is empty: false
	Entry identifier: ~~ERROR~~ ResourceLocationException: Non [a-z0-9/._-] character in path of location: elementalcraft:elementalcraft:water

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.jeicompat.wrap.JEIEntryDefinition

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['freopt'/39, l='ClientLevel', x=232.62, y=68.00, z=149.20]]
	Chunk stats: 1024, 321
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,86,0), Section: (at 0,6,0 in 1,5,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4972 game time, 15541 day time
	Server brand: forge
	Server type: Integrated singleplayer server
```

**Comment by freopt** [comment]
still happens


---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/6/22, 1:45 PM
Description: Getting tooltips

net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: elementalcraft:elementalcraft:water
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.18.1-20211210.034407-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getResourceLocation(IIngredientHelper.java:108) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getDisplayModId(IIngredientHelper.java:81) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.jeicompat.wrap.JEIEntryDefinition.getContainingNamespace(JEIEntryDefinition.java:95) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getContainingNamespace(AbstractEntryStack.java:134) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:214) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.18.1-20211210.034407-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.mrl.mixin.json:ResourceLocationAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getResourceLocation(IIngredientHelper.java:108) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at mezz.jei.api.ingredients.IIngredientHelper.getDisplayModId(IIngredientHelper.java:81) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
-- Screen details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:49) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:43) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:231) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:85) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106) ~[RoughlyEnoughItems-7.2.425.jar%23217!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:epic_rei_lmao:A}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: elementalcraft:main_ingredientelementtype
	Is empty: false
	Entry identifier: ~~ERROR~~ ResourceLocationException: Non [a-z0-9/._-] character in path of location: elementalcraft:elementalcraft:water

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.jeicompat.wrap.JEIEntryDefinition

-- Screen details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen

-- Search entry details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: elementalcraft:main_ingredientelementtype
	Is empty: false
	Entry identifier: ~~ERROR~~ ResourceLocationException: Non [a-z0-9/._-] character in path of location: elementalcraft:elementalcraft:water

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.jeicompat.wrap.JEIEntryDefinition

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen
