### ISSUE TITLE
[Bug] Render thread error

### ISSUE THREAD

**Issue by Connorado07** [shedaniel/RoughlyEnoughItems#766]
### What happened?

Having a NoSuchFieldError: field_2900 for the latest version for 1.18.1
java.lang.NoSuchFieldError: field_2900
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultPotionEffectExclusionZones.provide(DefaultPotionEffectExclusionZones.java:44)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// You're mean.

Time: 2/6/22, 5:21 PM
Description: Rendering screen

java.lang.NoSuchFieldError: field_2900
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultPotionEffectExclusionZones.provide(DefaultPotionEffectExclusionZones.java:44)
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultPotionEffectExclusionZones.provide(DefaultPotionEffectExclusionZones.java:40)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.lambda$register$0(ExclusionZonesImpl.java:142)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.isInZone(ExclusionZonesImpl.java:75)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.canItemSlotWidgetFit(EntryListWidget.java:145)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.notSteppingOnExclusionZones(EntryListWidget.java:136)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.updateEntriesPosition(EntryListWidget.java:428)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.updateArea(EntryListWidget.java:404)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.init(ScreenOverlayImpl.java:252)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:562)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:389)
	at net.minecraft.class_757.handler$zgg000$renderScreenPost(class_757.java:8552)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultPotionEffectExclusionZones.provide(DefaultPotionEffectExclusionZones.java:44)
	at me.shedaniel.rei.plugin.client.exclusionzones.DefaultPotionEffectExclusionZones.provide(DefaultPotionEffectExclusionZones.java:40)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.lambda$register$0(ExclusionZonesImpl.java:142)
	at me.shedaniel.rei.impl.client.registry.screen.ExclusionZonesImpl.isInZone(ExclusionZonesImpl.java:75)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.canItemSlotWidgetFit(EntryListWidget.java:145)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.notSteppingOnExclusionZones(EntryListWidget.java:136)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.updateEntriesPosition(EntryListWidget.java:428)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.updateArea(EntryListWidget.java:404)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.init(ScreenOverlayImpl.java:252)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:562)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:389)
	at net.minecraft.class_757.handler$zgg000$renderScreenPost(class_757.java:8552)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (280, 175). Absolute: (840.000000, 525.000000)
	Screen size: Scaled: (560, 350). Absolute: (1680, 1050). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['TYB_Ronnoc'/122, l='ClientWorld minecraft:overworld', x=6.73, y=143.18, z=5.92]]
	Chunk stats: Client Chunks (ImmPtl) 415
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,140,0), Section: (at 0,12,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 88 game time, 88 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 545124312 bytes (519 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 37583.22
	Virtual memory used (MB): 13180.20
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 17.69
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		ae2: Applied Energistics 2 10.1.0-beta.1
		apoli: Apoli 2.2.2
		architectury: Architectury 3.6.17
		authme: Auth Me 2.2.0
		basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
		bclib: BCLib 1.3.0
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.4
		betterf3: BetterF3 1.2.2
		bitsandchisels: BitsAndChisels 2.6.4
		blockus: Blockus 2.3.4+1.18.1
		calio: Calio 1.4.2
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config: Cloth Config v6 6.1.48
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		cosmetic-armor: Cosmetic Armor 1.2.1
		croptopia: Croptopia 1.8.0
		decorative_blocks: Decorative Blocks 2.0.4
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dragonloot: DragonLoot 1.0.10
		dynamicfps: Dynamic FPS 2.1.0
		explorerscompass: Explorer's Compass 1.18.1-2.0.2-fabric
		extraalchemy: Extra Alchemy 1.7.0
		extraorigins: Extra Origins 1.18-8
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.5.0-1.18
		ferritecore: FerriteCore 4.1.1
		fiber: fiber 0.23.0-2
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		geodes: More Geodes 1.2.0
		imm_ptl_core: Immersive Portals Core 1.2.5
		immersive_portals: Immersive Portals 1.2.5
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libcd: LibCapableData 3.0.3+1.16.3
		magna: Magna 1.7.0-1.18-pre1
		mcda: MC Dungeons Armors 2.0.1
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		moborigins: Mob Origins 1.8.0
		modern_industrialization: Modern Industrialization 1.0.4
		modmenu: Mod Menu 3.0.1
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		omega-config: OmegaConfig 1.0.8
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.3.1
		origins-classes: Origins: Classes 1.2.4
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.4.0
		q_misc_util: QMiscUtil 1.2.5
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.9
		roughlyenoughitems: Roughly Enough Items 6.4.426
		seedfix: Seed Fix 1.0.0
		simplesabers: The Simple Sabers Mod 1.0.0
		skinlayers: 3d Skin Layers 1.4.0
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.4.1-1.18.1
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0-beta.9
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.12
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		twigs: Twigs 1.1.2
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.1
		waystones: Waystones 2.4.1
		wthit: wthit 4.5.1
		xaerominimap: Xaero's Minimap 22.1.2
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 456.71, NVIDIA Corporation
	Window size: 1680x1050
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['TYB_Ronnoc'/122, l='ServerWorld minecraft:overworld ModpackTest', x=6.73, y=143.18, z=5.92]]
	Data Packs: vanilla, Fabric Mods
```

**Comment by shedaniel** [comment]
You are using REI 1.17 on 1.18
