### ISSUE TITLE
[Bug] Architectury not detected

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#780]
### What happened?

Minecraft version is 1.18.1, REI 7.2.425 is not detecting architectury version 3.6.17 and is showing the architectury not installed screen.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[15:39:27] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[15:39:27] [main/WARN]: Warnings were found!
 - Mod 'Taterzens' (taterzens) 1.8.0 recommends version 1.0.0 or later of disguiselib, which is missing!
	 - You should install version 1.0.0 or later of disguiselib for the optimal experience.
[15:39:27] [main/INFO]: Loading 112 mods:
	- advanced-xray-fabric 0.7.0-build.10
	- antighost 1.18-fabric0.43.1-1.1.4
	- apoli 2.2.2 via origins
	- appleskin mc1.18-2.2.0
	- betterf3 1.2.2
	- caffeineconfig 1.0.0 via sodium-extra
	- calio 1.4.2 via apoli
	- cardinal-components-base 4.0.1 via golemancy
	- cardinal-components-entity 4.0.1 via golemancy
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport
	- com_neovisionaries_nv-websocket-client 2.14 via figura
	- config2brigadier 1.0.2 via taterzens
	- crowdin-translate 1.4+1.18 via antighost
	- disable_custom_worlds_advice 1.4
	- entityoutliner 1.2.0
	- extraorigins 1.18-8
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via taterzens
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabricloader 0.12.12
	- fallingleaves 1.8.0+1.18
	- farsight 1.18-1.5
	- figura 0.0.7
	- forgeconfigapiport 3.1.0
	- golemancy 1.2.3
	- illuminations 1.10.2
	- iris 1.1.5
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- lambdynlights 2.1.0+1.17
	- libzoomer 0.3.0+1.17.1 via okzoomer
	- lithium 0.7.7
	- malilib 0.10.0-dev.26
	- minecraft 1.18.1
	- modmenu 3.0.1
	- mousetweaks 2.16
	- narratoroff 0.0.1
	- net_gudenau_lib_unsafe 1.4.3 via narratoroff
	- no_fog 1.2.0+1.16.5-1.18.1
	- notenoughcrashes 4.1.4+1.18.1
	- nullscape 1.1
	- okzoomer 5.0.0-beta.3+1.17.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_luaj_luaj-jse 3.0.1 via figura
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- org_slf4j_slf4j-api 1.7.12 via iris
	- origins 1.3.1
	- pehkui 3.1.0+1.14.4-1.18.1
	- playerabilitylib 1.3.0 via apoli
	- pride 1.1.0+1.17 via lambdynlights
	- reach-entity-attributes 2.1.1 via origins
	- reeses-sodium-options 1.3.0
	- roughlyenoughitems 7.2.425
	- rpgdifficulty 1.0.8
	- seedfix 1.0.0 via nullscape
	- sgui 1.0.0-rc5+1.18+pre5 via taterzens
	- sodium 0.4.0-alpha6+build.14
	- sodium-extra 0.3.8
	- spruceui 3.3.0+1.17 via lambdynlights
	- taterzens 1.8.0
	- wthit 4.4.1
	- xaerominimap 21.23.1
	- xaeroworldmap 1.19.1
[15:39:27] [main/WARN]: Mod `appleskin` (mc1.18-2.2.0) does not respect SemVer - comparison support is limited.
[15:39:27] [main/WARN]: Mod `sgui` (1.0.0-rc5+1.18+pre5) does not respect SemVer - comparison support is limited.
[15:39:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/david/Documents/Curse/Minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[15:39:28] [main/INFO]: Compatibility level set to JAVA_16
[15:39:28] [main/INFO]: Compatibility level set to JAVA_17
[15:39:28] [main/INFO]: Loaded configuration file for Lithium: 88 options available, 0 override(s) found
[15:39:28] [main/WARN]: Reference map 'narrator-off-refmap.json' for narratoroff.mixins.json could not be read. If this is a development environment you can ignore this message
[15:39:28] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[15:39:28] [main/INFO]: Loaded configuration file for Sodium Extra: 17 options available, 0 override(s) found
[15:39:28] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[15:39:29] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[15:39:33] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zhp000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[15:39:35] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[15:39:35] [Render thread/INFO]: sodium-extra.mixins.json:features.gui.MinecraftClientAccessor->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[15:39:35] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:39:36] [Render thread/INFO]: Setting user: The_Nanuak
[15:39:36] [Render thread/INFO]: XRay mod has been initialized
[15:39:36] [Render thread/INFO]: Apoli 2.2.2 has initialized. Ready to power up your game!
[15:39:36] [Render thread/INFO]: Loaded C2B lib.
[15:39:36] [Render thread/INFO]: Origins 1.3.1 is initializing. Have fun!
[15:39:36] [Render thread/ERROR]: Architectury API is not installed! https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/all
[15:39:36] [Render thread/INFO]: Loaded seedfix v1.0.0 by Justsnoopy30!
[15:39:37] [Render thread/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[15:39:37] [Render thread/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[15:39:37] [Render thread/INFO]: [WTHIT] Plugin config reloaded
[15:39:37] [Render thread/INFO]: [BetterF3] Loading...
[15:39:37] [Render thread/INFO]: [BetterF3] All done!
[15:39:37] [Render thread/INFO]: [STDOUT]: Added Cert for CN=blancworks.org
[15:39:37] [Render thread/INFO]: [STDOUT]: Headers of https://google.com => {Transfer-Encoding=[chunked], null=[HTTP/1.1 200 OK], Alt-Svc=[h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"], Server=[gws], P3P=[CP="This is not a P3P policy! See g.co/p3phelp for more info."], Date=[Sat, 12 Feb 2022 15:39:37 GMT], Accept-Ranges=[none], X-Frame-Options=[SAMEORIGIN], Cache-Control=[private, max-age=0], Vary=[Accept-Encoding], Set-Cookie=[CONSENT=PENDING+364; expires=Mon, 12-Feb-2024 15:39:37 GMT; path=/; domain=.google.com; Secure], Expires=[-1], X-XSS-Protection=[0], Content-Type=[text/html; charset=ISO-8859-1]}
[15:39:38] [Render thread/INFO]: [STDOUT]: Headers of https://www.thawte.com => {null=[HTTP/1.1 200 OK], Cache-Control=[max-age=0], Etag=["3a50b8bf"], X-CDN=[Imperva], X-Iinfo=[2-1450450-0 0CNN RT(1644680376751 26) q(0 -1 -1 -1) r(0 -1)], Set-Cookie=[incap_ses_340_2208647=RttlTbW4bxgKekQr0ey3BLjUB2IAAAAAAIzAjNb6tfxx0P6/zgkhrA==; path=/; Domain=.thawte.com, visid_incap_2208647=XjAMaKzoRQyaDKdGml0kHrjUB2IAAAAAQUIPAAAAAADoSAYT+qWI0J+dDlGddp2R; expires=Sat, 11 Feb 2023 23:48:20 GMT; HttpOnly; path=/; Domain=.thawte.com], Content-Length=[27682], Date=[Sat, 12 Feb 2022 15:39:36 GMT], Content-Type=[text/html; charset=UTF-8]}
[15:39:38] [Render thread/INFO]: [STDOUT]: Headers of https://helloworld.letsencrypt.org => {null=[HTTP/1.1 200 OK], Server=[nginx], X-Content-Type-Options=[nosniff], Connection=[keep-alive], Last-Modified=[Tue, 10 Aug 2021 04:05:36 GMT], Date=[Sat, 12 Feb 2022 15:39:38 GMT], Accept-Ranges=[bytes], Strict-Transport-Security=[max-age=604800], ETag=["6111fb10-12ee"], Vary=[Accept-Encoding], X-XSS-Protection=[1; mode=block], Content-Length=[4846], Content-Type=[text/html]}
[15:39:38] [Render thread/INFO]: [STDOUT]: Headers of https://letsencrypt.org => {date=[Fri, 11 Feb 2022 11:38:59 GMT], null=[HTTP/1.1 200 OK], content-length=[33667], server=[Netlify], x-frame-options=[DENY], permissions-policy=[geolocation=(), midi=(), notifications=(), push=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(self), vibrate=(), fullscreen=(self), interest-cohort=()], x-nf-request-id=[01FVQ9DXYVBAENCAMHSTBVY19Z], strict-transport-security=[max-age=31536000], content-security-policy=[default-src 'none'; font-src 'self'; style-src 'unsafe-inline' 'self'; script-src 'unsafe-eval' 'unsafe-inline' 'self' data: https://www.google-analytics.com https://www.googleadservices.com https://www.googletagmanager.com https://googleads.g.doubleclick.net https://donorbox.org https://js.stripe.com/v3/ https://sdks.shopifycdn.com ; img-src 'self' data: blob: https://www.google-analytics.com https://www.paypal.com https://www.paypalobjects.com https://ak2s.abmr.net https://ak1s.abmr.net https://www.google.com https://cdn.shopify.com https://v.shopify.com ; frame-src https://donorbox.org https://www.youtube.com https://www.youtube-nocookie.com https://bid.g.doubleclick.net https://js.stripe.com/v3/ https://js.stripe.com/v2/ ; connect-src 'self' https://d4twhgtvn0ff5.cloudfront.net/ https://letsencrypt-merch.myshopify.com https://monorail-edge.shopifysvc.com ;], x-content-type-options=[nosniff], x-xss-protection=[1; mode=block], referrer-policy=[no-referrer], etag=["79458d2d328d0cb205122763ed9b6b39-ssl"], content-type=[text/html; charset=UTF-8], cache-control=[public, max-age=0, must-revalidate], age=[100840]}
[15:39:38] [Render thread/WARN]: Error loading class: org/spongepowered/asm/synthetic/args/Args$4 (java.lang.ClassNotFoundException: org/spongepowered/asm/synthetic/args/Args$4)
[15:39:38] [Render thread/INFO]: [STDERR]: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 442: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:296)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:859)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:828)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:782)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:752)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:545)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:154)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:148)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector$Context.<init>(ModifyVariableInjector.java:71)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.preInject(ModifyVariableInjector.java:159)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1367)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.emirikol.golemancy.GolemancyClient.registerEntities(GolemancyClient.java:50)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.emirikol.golemancy.GolemancyClient.onInitializeClient(GolemancyClient.java:33)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.redirect$bld000$catchFabricInit(class_310.java:10978)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:452)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:199)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[15:39:38] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.asm.MixinVerifier.isAssignableFrom(MixinVerifier.java:104)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:213)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:401)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:43)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
[15:39:38] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:188)
[15:39:38] [Render thread/INFO]: [STDERR]: 	... 55 more
[15:39:39] [Render thread/INFO]: [LambDynLights] Initializing LambDynamicLights...
[15:39:39] [Render thread/INFO]: [LambDynLights] Configuration loaded.
[15:39:39] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Main.initialize()
[15:39:39] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Initialized.
[15:39:39] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[15:39:39] [Render thread/INFO]: Loading Xaero's World Map - Stage 1/2
[15:39:39] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[15:39:41] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[15:39:41] [Render thread/INFO]: Shaders are disabled
[15:39:41] [Render thread/INFO]: Hardware information:
[15:39:41] [Render thread/INFO]: CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
[15:39:41] [Render thread/INFO]: GPU: Radeon RX 580 Series (Supports OpenGL 3.2.13571 Core Profile Forward-Compatible Context 19.30.02 26.20.13002.133)
[15:39:41] [Render thread/INFO]: OS: Windows 10 (10.0)
[15:39:42] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[15:39:42] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Advanced XRay (Fabric), AntiGhost, Apoli, AppleSkin, BetterF3, CaffeineConfig, Calio, Cloth Config v6, Disable Custom Worlds Advice, Entity Outliner, Extra Origins, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Falling Leaves, Farsight Mod, Figura, Forge Config API Port, Golemancy, Illuminations, Iris, Kanos Config, LambDynamicLights, LibZoomer, Lithium, MaLiLib, Mod Menu, narrator off, No Fog, Not Enough Crashes, Ok Zoomer, Origins, Pehkui, Pal, Pride Lib, Reach Entity Attributes, Reese's Sodium Options, Roughly Enough Items, Rpg Difficulty, Sodium, Sodium Extra, SpruceUI, wthit, Xaero's Minimap, Xaero's World Map)
[15:39:42] [Render thread/INFO]: [STDOUT]: Inject generated resource packs.
[15:39:42] [Render thread/INFO]: [Ok Zoomer] öwö what's this
[15:39:42] [Render thread/INFO]: Loading Xaero's Minimap - Stage 2/2
[15:39:42] [Render thread/INFO]: [STDOUT]: Xaero's Minimap: World Map found!
[15:39:42] [Render thread/INFO]: [STDOUT]: No Optifine!
[15:39:42] [Render thread/INFO]: Loading Xaero's World Map - Stage 2/2
[15:39:42] [Render thread/INFO]: [STDOUT]: New world map region cache hash code: 687554333
[15:39:42] [Render thread/INFO]: Xaero's WorldMap Mod: Xaero's minimap found!
[15:39:42] [Render thread/INFO]: [STDOUT]: No Optifine!
[15:39:42] [Render thread/INFO]: [STDOUT]: No Vivecraft!
[15:39:47] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Headphones (2- David headphones     Stereo)
[15:39:47] [Render thread/INFO]: Sound engine started
[15:39:47] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[15:39:47] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[15:39:47] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:39:47] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:39:47] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[15:39:48] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[15:39:48] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:39:49] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[15:39:49] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:39:49] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:39:49] [Render thread/INFO]: [STDOUT]: Successfully reloaded the minimap shaders!
[15:39:49] [Render thread/INFO]: [STDOUT]: Successfully reloaded the world map shaders!
[15:41:55] [Render thread/INFO]: Stopping!
```

**Comment by shedaniel** [comment]
architectury is definitely not installed by your logs.

**Comment by ghost** [comment]
For some reason, I had to install it through the curseforge GUI and it wasn't detecting manually from the mods folder.
