### ISSUE TITLE
[Bug] not workign with questcraft. 

### ISSUE THREAD

**Issue by soyasauce-best** [shedaniel/RoughlyEnoughItems#799]
### What happened?

i understand your busy. and take your time at this but could you fix the fabric version of rei TwT. it wont work with quest craft and the devs of questcraft dont know how they can fix it. so i was wondering if you could look into it yourself. the version is 1.18.1 fabric

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[03:44:11] [main/INFO]: Loading 68 mods:
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42 via hookshot
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fart 1.0.0 via mcxr-play
	- gateofbabylon 1.6.0-1.18.1
	- gobber2 2.5.62
	- hookshot 24.0
	- java 17
	- lazydfu 0.1.2
	- mcxr-core 0.1.1
	- mcxr-play 0.1.3
	- minecraft 1.18.1
	- modmenu 3.0.0
	- org_joml_joml 1.10.2 via mcxr-core
	- org_lwjgl_lwjgl-egl 3.2.3 via mcxr-play
	- org_lwjgl_lwjgl-opengles 3.2.3 via mcxr-play
	- pugh_lib 1.2.15 via gobber2
	- pugh_tools 1.1.17 via gobber2
	- reach-entity-attributes 2.1.1 via gateofbabylon
	- roughlyenoughitems 7.2.418
	- titleworlds 0.0.1
	- torohealth 1.18-fabric-2
	- xaerominimap 22.2.0.1
[03:44:11] [main/WARN]: Mod `xaerominimap` (22.2.0.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[03:44:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[03:44:11] [main/INFO]: Compatibility level set to JAVA_16
[03:44:11] [main/INFO]: Compatibility level set to JAVA_17
[03:44:16] [main/INFO]: Gobber Mod Info Message: Max value of attribute.name.generic.armor is currently set to 80.0
[03:44:19] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdf000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[03:44:21] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[03:44:22] [Render thread/INFO]: Setting user: rubberboy
[03:44:22] [Render thread/INFO]: PughLib has loaded - v1.2.15
[03:44:22] [Render thread/INFO]: PughTools has loaded - v1.1.17
[03:44:22] [Render thread/ERROR]: Architectury API is not installed! https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/all
[03:44:22] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[03:44:22] [Render thread/INFO]: [STDOUT]: XrResult:0
[03:44:22] [Render thread/INFO]: Opening level storage source
[03:44:22] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[03:44:23] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[03:44:24] [Render thread/WARN]: ERROR : Couldn't load Narrator library : /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna14695744264884968718.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna14695744264884968718.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch.debug/runtimes/Internal/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
[03:44:25] [Render thread/INFO]: Reloading ResourceManager: Default, assets-v0.zip, Fabric Mods (Cloth Config v6, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Fart, Gate Of Babylon, Gobber2, Hookshot, LazyDFU, [MCXR] Core, [MCXR] Play, Mod Menu, Reach Entity Attributes, Roughly Enough Items, Title Worlds, ToroHealth Damage Indicators, Xaero's Minimap)
[03:44:25] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[03:44:27] [Render thread/INFO]: Loading title world
[03:44:27] [Render thread/INFO]: Loading world resources
[03:44:28] [ForkJoinPool.commonPool-worker-1/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:44:28] [ForkJoinPool.commonPool-worker-1/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:44:28] [ForkJoinPool.commonPool-worker-1/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:44:28] [ForkJoinPool.commonPool-worker-1/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[03:44:28] [ForkJoinPool.commonPool-worker-1/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[03:44:28] [ForkJoinPool.commonPool-worker-1/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Gate Of Babylon, Gobber2, Hookshot, Pugh Tools)
[03:44:28] [Render thread/INFO]: Loading server resources
[03:44:31] [Worker-Main-4/WARN]: Invalid frame index on sprite gobber2:block/gobber2_ore frame 1: 1
[03:44:31] [Worker-Main-4/WARN]: Invalid frame index on sprite gobber2:block/gobber2_ore frame 2: 2
[03:44:31] [Worker-Main-4/WARN]: Invalid frame index on sprite gobber2:block/gobber2_ore frame 3: 1
[03:44:31] [Worker-Main-4/WARN]: Invalid frame index on sprite gobber2:block/gobber2_ore_deepslate frame 1: 1
[03:44:31] [Worker-Main-4/WARN]: Invalid frame index on sprite gobber2:block/gobber2_ore_deepslate frame 2: 2
[03:44:31] [Worker-Main-4/WARN]: Invalid frame index on sprite gobber2:block/gobber2_ore_deepslate frame 3: 1
[03:44:32] [Render thread/INFO]: OpenAL initialized on device OpenSL
[03:44:32] [Render thread/INFO]: Sound engine started
[03:44:32] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[03:44:33] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[03:44:33] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[03:44:33] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[03:44:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[03:44:33] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[03:44:33] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[03:44:34] [Render thread/WARN]: Shader rendertype_text could not find sampler named Sampler2 in the specified shader program.
[03:44:34] [Render thread/WARN]: Shader rendertype_text_intensity could not find sampler named Sampler2 in the specified shader program.
[03:44:35] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[03:44:35] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[03:44:35] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[03:44:35] [Render thread/INFO]: Successfully reloaded the minimap shaders!
[03:44:35] [Render thread/ERROR]: Parsing error loading recipe gobber2:gobber2_helmet_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_helmet_dragon_no_flight'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.loadTitleWorld(class_310.java:7236) [client-intermediary.jar:?]
	at net.minecraft.class_310.tryLoadTitleWorld(class_310.java:7169) [client-intermediary.jar:?]
	at net.minecraft.class_310.handler$znd000$init(class_310.java:7154) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:637) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:199) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[03:44:35] [Render thread/ERROR]: Parsing error loading recipe gobber2:gobber2_chestplate_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_chestplate_dragon_no_flight'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.loadTitleWorld(class_310.java:7236) [client-intermediary.jar:?]
	at net.minecraft.class_310.tryLoadTitleWorld(class_310.java:7169) [client-intermediary.jar:?]
	at net.minecraft.class_310.handler$znd000$init(class_310.java:7154) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:637) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:199) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[03:44:35] [Render thread/ERROR]: Parsing error loading recipe gobber2:gobber2_boots_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_boots_dragon_no_flight'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.loadTitleWorld(class_310.java:7236) [client-intermediary.jar:?]
	at net.minecraft.class_310.tryLoadTitleWorld(class_310.java:7169) [client-intermediary.jar:?]
	at net.minecraft.class_310.handler$znd000$init(class_310.java:7154) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:637) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:199) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[03:44:35] [Render thread/ERROR]: Parsing error loading recipe gobber2:gobber2_leggings_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_leggings_dragon_no_flight'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.loadTitleWorld(class_310.java:7236) [client-intermediary.jar:?]
	at net.minecraft.class_310.tryLoadTitleWorld(class_310.java:7169) [client-intermediary.jar:?]
	at net.minecraft.class_310.handler$znd000$init(class_310.java:7154) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:637) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:199) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[03:44:35] [Render thread/INFO]: Loaded 7 recipes
[03:44:35] [Render thread/ERROR]: Parsing error loading custom advancement gobber2:gobber2_armor_dragon_no_flight: Expected item to be an item, was unknown string 'gobber2:gobber2_chestplate_dragon_no_flight'
[03:44:36] [Render thread/INFO]: Loaded 1214 advancements
[03:44:36] [Render thread/INFO]: Starting server
[03:44:36] [ForkJoinPool.commonPool-worker-1/INFO]: Applied 215 biome modifications to 60 of 61 new biomes in 159.5 ms
[03:44:36] [ForkJoinPool.commonPool-worker-1/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[03:44:40] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[03:44:40] [Server thread/INFO]: Starting integrated minecraft server version 1.18.1
[03:44:40] [Server thread/INFO]: Generating keypair
[03:44:41] [Server thread/INFO]: Changing view distance to 6, from 10
[03:44:41] [Server thread/INFO]: Changing simulation distance to 5, from 0
[03:44:41] [Render thread/INFO]: Joining singleplayer server
[03:44:41] [Render thread/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 0c:0e:71:01:c9:db:77:22
[03:44:41] [Render thread/INFO]: Loading chunks
[03:44:41] [Render thread/INFO]: Loading Xaero's Minimap - Stage 2/2
[03:44:41] [Netty Local Client IO #0/INFO]: Received login packet
[03:44:41] [Netty Server IO #1/INFO]: Received XR login packet from 4aef5897-c2b2-4639-842f-baa369752835
[03:44:43] [Render thread/INFO]: No Optifine!
[03:44:46] [Server thread/INFO]: rubberboy[local:E:49f04e3b] logged in with entity id 1 at (-31.44678835391045, 90.86813599529884, 32.21024963530446)
[03:44:46] [Render thread/INFO]: New minimap session initialized!
[03:44:46] [Server thread/INFO]: rubberboy joined the game
[03:44:46] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4802ms or 96 ticks behind
[03:44:47] [Render thread/INFO]: Loaded 0 advancements.
```

### Anything else?

it may say the game loaded but the screenw as still loading and went black. everyone has this problem

**Comment by shedaniel** [comment]
Have you installed Architectury API?

**Comment by soyasauce-best** [comment]
Ok I have tried and I'm ahving troubles still.

**Comment by soyasauce-best** [comment]
I was also told to use cloth config. Do need cloth API too?

**Comment by soyasauce-best** [comment]
you can close this issue now. i had to download older versions of each mod. rei, cloth api and arcitctury. i got the righr versions and it finnally worked
