### ISSUE TITLE
[Bug] Roughlyenoughitems refusing to start my game

### ISSUE THREAD

**Issue by TheAweSum1** [shedaniel/RoughlyEnoughItems#805]
### What happened?

 i dont have anything to say except "minecraft didnt start due to an unknown error"...
also this only happens once i put the roughlyenoughitems.jar file into .minecraft\mods folder 
without roughlyenoughitems it works fine and dandy, minecraft fabric with other fabric mods i.e.
using windows 10 if that helps

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/6/22, 5:06 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:86)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:46)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy2/com.sun.proxy.jdk.proxy2.$Proxy30.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_2370: method 'void <init>(net.minecraft.class_5321, com.mojang.serialization.Lifecycle)' not found
	at me.shedaniel.rei.impl.client.entry.filtering.FilteringRule.<clinit>(FilteringRule.java:50)
	at me.shedaniel.rei.impl.client.config.ConfigManagerImpl.saveConfig(ConfigManagerImpl.java:277)
	at me.shedaniel.rei.impl.client.config.ConfigManagerImpl.<init>(ConfigManagerImpl.java:133)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.attachClientInternals(RoughlyEnoughItemsCoreClient.java:202)
	at dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:35)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.<clinit>(RoughlyEnoughItemsCore.java:86)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:63)
	... 15 more
```

**Comment by TheAweSum1** [comment]
tell me if you need the whole crash report file tho

**Comment by TheAweSum1** [comment]
I really wanna use REI

**Comment by shedaniel** [comment]
You likely used the wrong REI version for your Minecraft Version, REI 7 for 1.18.1, REI 8 for 1.18.2
