### ISSUE TITLE
[Bug] REI server side crash on server boot 1.18

### ISSUE THREAD

**Issue by RoyalShooter** [shedaniel/RoughlyEnoughItems#811]
### What happened?

I am troubleshooting my server mod pack and I found REI is causing my server to crash on his own.

mod list
-fabric-api-0.48.0+1.18.2
-RoughlyEnoughItems-8.0.442

download thought Curseforge client

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
C:\Users\Administrator\Desktop\MC\MPWF01 Server>java -Xmx8G -Xms2G -jar fabric-server-launch.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[15:44:15] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[15:44:15] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[15:44:15] [main/INFO]: Loading 35 mods:
        - fabric 0.48.0+1.18.2
        - fabric-api-base 0.4.4+d7c144a860 via fabric
        - fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
        - fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
        - fabric-command-api-v1 1.1.9+d7c144a860 via fabric
        - fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
        - fabric-containers-v0 0.1.21+d7c144a860 via fabric
        - fabric-content-registries-v0 3.0.2+d82b939260 via fabric
        - fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
        - fabric-dimensions-v1 2.1.17+2540745460 via fabric
        - fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
        - fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
        - fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
        - fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
        - fabric-item-api-v1 1.3.3+691a79b560 via fabric
        - fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
        - fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
        - fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
        - fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
        - fabric-networking-api-v1 1.0.21+d882b91560 via fabric
        - fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
        - fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
        - fabric-particles-v1 0.2.12+526dc1ac60 via fabric
        - fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
        - fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
        - fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
        - fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
        - fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
        - fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
        - fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
        - fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
        - fabricloader 0.13.3
        - java 17
        - minecraft 1.18.2
        - roughlyenoughitems 8.0.442
[15:44:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Administrator/Desktop/MC/MPWF01%20Server/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[15:44:15] [main/INFO]: Compatibility level set to JAVA_16
[15:44:18] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zca000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[15:44:19] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.RuntimeException: Architectury API is not installed! https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/all
        at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:62) ~[RoughlyEnoughItems-8.0.442.jar:?]
        at me.shedaniel.rei.fabric.RoughlyEnoughItemsInitializerImpl.checkMods(RoughlyEnoughItemsInitializerImpl.java:62) ~[RoughlyEnoughItems-8.0.442.jar:?]
        at me.shedaniel.rei.RoughlyEnoughItemsInitializer.checkMods(RoughlyEnoughItemsInitializer.java) ~[RoughlyEnoughItems-8.0.442.jar:?]
        at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:43) ~[RoughlyEnoughItems-8.0.442.jar:?]
        at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
        at com.sun.proxy.jdk.proxy3.$Proxy30.onInitialize(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
        ... 15 more

C:\Users\Administrator\Desktop\MC\MPWF01 Server>pause
```

**Comment by shedaniel** [comment]
Install Architectury API
