### ISSUE TITLE
[Bug] Items are not showing 1.18.1

### ISSUE THREAD

**Issue by Jellomaker** [shedaniel/RoughlyEnoughItems#818]
### What happened?

When scrolling through the pages found in my inventory, I am not able to see the majority of items. Some items do show, while others don't. I believe that all of the vanilla items are shown. The items do show that they are there, it's only the icons that are missing, you can also still click on them.
![Screenshot_1532](https://user-images.githubusercontent.com/102331415/160022002-e1e5b573-499a-4e91-9271-e75f92d7143e.png)
![Screenshot_1533](https://user-images.githubusercontent.com/102331415/160022034-8f75e15f-fe7c-4820-8680-5303c1233e95.png)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [x] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[18:00:50] [ForkJoinPool.commonPool-worker-5/ERROR] Failed to fill displays!
java.lang.NullPointerException: Cannot invoke "cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredient.isConfigurable()" because the return value of "net.minecraftforge.common.util.Lazy.get()" is null
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe.getRecipeOutputs(AdvancedBeehiveRecipe.java:69)
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.integrations.jei.AdvancedBeehiveRecipeCategory.setRecipe(AdvancedBeehiveRecipeCategory.java:145)
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.integrations.jei.AdvancedBeehiveRecipeCategory.setRecipe(AdvancedBeehiveRecipeCategory.java:31)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay.cache(JEIWrappedDisplay.java:66)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay.<init>(JEIWrappedDisplay.java:60)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.JEIPluginDetector$JEIPluginWrapper.lambda$registerCategories$1(JEIPluginDetector.java:475)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.tryFillDisplayGenerics(DisplayRegistryImpl.java:287)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.tryFillDisplay(DisplayRegistryImpl.java:269)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.api.client.registry.display.DisplayRegistry.tryFillDisplay(DisplayRegistry.java:321)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.api.common.util.CollectionUtils.map(CollectionUtils.java:120)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIRecipeRegistration.lambda$addRecipesOptimized$1(JEIRecipeRegistration.java:114)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[18:00:50] [ForkJoinPool.commonPool-worker-6/ERROR] Failed to fill displays![18:00:50] [ForkJoinPool.commonPool-worker-3/ERROR] Failed to fill displays!

java.lang.NullPointerException: Cannot invoke "cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredient.isConfigurable()" because the return value of "net.minecraftforge.common.util.Lazy.get()" is null
java.lang.NullPointerException: Cannot invoke "cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredient.isConfigurable()" because the return value of "net.minecraftforge.common.util.Lazy.get()" is null
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe.getRecipeOutputs(AdvancedBeehiveRecipe.java:69)
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.integrations.jei.AdvancedBeehiveRecipeCategory.setRecipe(AdvancedBeehiveRecipeCategory.java:145)
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.integrations.jei.AdvancedBeehiveRecipeCategory.setRecipe(AdvancedBeehiveRecipeCategory.java:31)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay.cache(JEIWrappedDisplay.java:66)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay.<init>(JEIWrappedDisplay.java:60)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.JEIPluginDetector$JEIPluginWrapper.lambda$registerCategories$1(JEIPluginDetector.java:475)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.tryFillDisplayGenerics(DisplayRegistryImpl.java:287)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.tryFillDisplay(DisplayRegistryImpl.java:269)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.api.client.registry.display.DisplayRegistry.tryFillDisplay(DisplayRegistry.java:321)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.api.common.util.CollectionUtils.map(CollectionUtils.java:120)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIRecipeRegistration.lambda$addRecipesOptimized$1(JEIRecipeRegistration.java:114)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe.getRecipeOutputs(AdvancedBeehiveRecipe.java:69)
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.integrations.jei.AdvancedBeehiveRecipeCategory.setRecipe(AdvancedBeehiveRecipeCategory.java:145)
	at TRANSFORMER/productivebees@1.18.1-0.8.0.7/cy.jdkdigital.productivebees.integrations.jei.AdvancedBeehiveRecipeCategory.setRecipe(AdvancedBeehiveRecipeCategory.java:31)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay.cache(JEIWrappedDisplay.java:66)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay.<init>(JEIWrappedDisplay.java:60)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.JEIPluginDetector$JEIPluginWrapper.lambda$registerCategories$1(JEIPluginDetector.java:475)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.tryFillDisplayGenerics(DisplayRegistryImpl.java:287)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.tryFillDisplay(DisplayRegistryImpl.java:269)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.api.client.registry.display.DisplayRegistry.tryFillDisplay(DisplayRegistry.java:321)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.api.common.util.CollectionUtils.map(CollectionUtils.java:120)
	at TRANSFORMER/roughlyenoughitems@7.3.443/me.shedaniel.rei.jeicompat.wrap.JEIRecipeRegistration.lambda$addRecipesOptimized$1(JEIRecipeRegistration.java:114)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Anything else?

I have tried updating every mod that I can think of and am using the lastest versions of REI, Achitectury, Cloth Config API
![Screenshot_1534](https://user-images.githubusercontent.com/102331415/160022256-0a152389-dc4f-4629-9f7b-bef04b1c9f01.png)
,

The logs folder was very long and can send more or all of the logs if they will help.

**Comment by softestpoly** [comment]
This is happening to me too. It's fixed if you turn off Caching Entry Rendering, but that's not good for performance. I assume it's an issue with having a bad rendering cache?

**Comment by shedaniel** [comment]
Should be fixed along with tinkers modifiers entries
