### ISSUE TITLE
[Bug] [Forge 1.16.5] REI breaks modded fluid buckets

### ISSUE THREAD

**Issue by connor135246** [shedaniel/RoughlyEnoughItems#847]
### What happened?

If you have REI and another mod that adds fluid buckets, the fluid buckets will no longer work. Right clicking with them does nothing. 
I tested with [my mod](https://www.curseforge.com/minecraft/mc-mods/simply-hot-springs) and with [Tinkers' Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct/files/3695126).

According to the log, it appears to be an error with the access transformer. This error appears even if the only mods you have are REI, Architectury, and Cloth Config. I'm pretty sure the issue is REI in particular because this line is in REI's accesstransformer.cfg: `public net.minecraft.item.BucketItem field_77876_a`

Versions:
Forge 36.2.34
REI 6.5.436
Architectury 1.31.60
Cloth Config 4.14.54

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[19:38:15] [pool-3-thread-1/ERROR] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod META-INF/fieldtomethodtransformers.js function bucketitem
java.lang.IllegalStateException: Field field_77876_a is not private and an instance field
	at net.minecraftforge.coremod.api.ASMAPI.redirectFieldToMethod(ASMAPI.java:260) ~[coremods-4.0.6.jar:?] {re:classloading}
	at jdk.nashorn.internal.scripts.Script$Recompilation$16$1352A$\^eval\_.initializeCoreMod#transformer-2(<eval>:35) ~[?:?] {re:classloading}
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?] {}
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?] {}
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?] {}
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?] {}
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551] {}
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-4.0.6.jar:?] {}
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-4.0.6.jar:?] {}
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-4.0.6.jar:?] {}
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:117) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraft.util.registry.Registry.func_218353_F(Registry.java:159) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Registry.lambda$static$51(Registry.java:466) ~[?:?] {re:classloading}
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:465) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) ~[?:?] {re:classloading}
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251] {}
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251] {}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}
```

**Comment by MaxNeedsSnacks** [comment]
@shedaniel Didn't we backport the FluidBucketHooks fix to 1.16? That would make the REI bucket AW/AT unnecessary

**Comment by shedaniel** [comment]
> @shedaniel Didn't we backport the FluidBucketHooks fix to 1.16? That would make the REI bucket AW/AT unnecessary

It's been a while since last 1.16 update

**Comment by MaxNeedsSnacks** [comment]
Just double-checked, yeah we did backport that. I do understand why backporting this *now* would be a pain in the ass, though, since it doesn't even look like you have the 6.x branch for Forge 1.16 anymore, so fair enough :p Would this then be able to be closed as "won't fix"?
