### ISSUE TITLE
[Bug] Fabric 1.18.2 version does not work with 1.18.2

### ISSUE THREAD

**Issue by TheButterbrotMan** [shedaniel/RoughlyEnoughItems#862]
### What happened?

![image](https://user-images.githubusercontent.com/64548098/169679985-5056f5aa-9b9e-42b6-a722-011500a0e77c.png)

Is tagged as 1.18.2 so sould work as 1.18.2?

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[07:12:53] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.6
[07:12:53] [ForkJoinPool-1-worker-6/WARN]: Mod amethystequipment uses the version fabric-1.18.2-v1.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:53] [ForkJoinPool-1-worker-2/WARN]: Mod bcc uses the version fabric-1.0.5 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-4/WARN]: Mod bowinfinityfix uses the version rv11 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'rv11'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-5/WARN]: Mod createaddition uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-3/WARN]: Mod create uses the version mc1.18.2_v0.4.1+576 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-6/WARN]: Mod ctov uses the version FINAL-bugfix 2 which isn't compatible with Loader's extended semantic version format (Invalid prerelease string 'bugfix 2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-4/WARN]: The mod "dwarfcoal" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 16 column 9
[07:12:54] [ForkJoinPool-1-worker-5/WARN]: Mod endgoblintraders uses the version 1.5 (Re-upload) which isn't compatible with Loader's extended semantic version format (Invalid prerelease string 'upload)'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-4/WARN]: Mod exlineawnings uses the version fabric-1.18.2-v1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-3/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.0.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-1/WARN]: Mod lava_walker uses the version Fabric-1.18.2-0.1.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-3/WARN]: Mod gromovspaintings uses the version 1.18.2 - 1.1.1 which isn't compatible with Loader's extended semantic version format (Invalid prerelease string ' 1.1.1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-3/WARN]: Mod me_hypherionmc_night-config_toml uses the version 3.6.5_custom which isn't compatible with Loader's extended semantic version format (Could not parse version number component '5_custom'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-3/WARN]: Mod me_hypherionmc_night-config_core uses the version 3.6.5_custom which isn't compatible with Loader's extended semantic version format (Could not parse version number component '5_custom'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-6/WARN]: Mod mavm uses the version 1.0.7a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '7a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-2/WARN]: Mod reinforced_bows uses the version 1.18.2 - 1.1 which isn't compatible with Loader's extended semantic version format (Invalid prerelease string ' 1.1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-5/WARN]: Mod sandwichmod uses the version fabric-1.18.2-v2.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-1/WARN]: Mod sushimod uses the version fabric-1.18.2-v1.0.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:54] [ForkJoinPool-1-worker-6/WARN]: The mod "thonkutil-customization-v1" contains invalid entries in its mod json:
- Unsupported root entry "disabled:mixins" at line 11 column 20
[07:12:55] [ForkJoinPool-1-worker-5/WARN]: Mod xps uses the version 0.3.9.b_for_1.18.x_Fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'b_for_1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:56] [main/WARN]: Mod resolution failed
[07:12:56] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE expandedstorage 7.4.0-beta.2 {depends ellemes_container_lib @ [>=1.4.0-beta.1]}, ROOT_FORCELOAD_SINGLE expandedstorage 7.4.0-beta.2]
[07:12:56] [main/INFO]: Reason: [HARD_DEP expandedstorage 7.4.0-beta.2 {depends ellemes_container_lib @ [>=1.4.0-beta.1]}, HARD_DEP roughlyenoughitems 9.0.462 {depends minecraft @ [~1.19-beta.1]}, HARD_DEP roughlyenoughprofessions 1.0.1 {depends roughlyenoughitems @ [8.x.x]}]
[07:12:56] [main/INFO]: CLIENT environment disabled: [ledger]
[07:12:56] [main/INFO]: Fix: add [add:ellemes_container_lib 1.4.0-beta.1 ([[1.4.0-beta.1,?)])], remove [], replace [[roughlyenoughitems 9.0.462] -> add:roughlyenoughitems 8- ([[8-,9-)])]
[07:12:56] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install ellemes_container_lib, version 1.4.0-beta.1 or later.
	 - Replace mod 'Roughly Enough Items' (roughlyenoughitems) 9.0.462 with any 8.x version.
Unmet dependency listing:
	 - Mod 'Expanded Storage' (expandedstorage) 7.4.0-beta.2 requires version 1.4.0-beta.1 or later of ellemes_container_lib, which is missing!
	 - Mod 'Roughly Enough Items' (roughlyenoughitems) 9.0.462 requires any version between 1.19-beta.1 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'Roughly Enough Professions' (roughlyenoughprofessions) 1.0.1 requires any 8.x version of mod 'Roughly Enough Items' (roughlyenoughitems), but only the wrong version is present: 9.0.462!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
```

**Comment by Phoenix-Starlight** [comment]
The mod was mistakenly marked as 1.18 support in it when it was a beta meant for 1.19-1.20.  Possibly there was no tags...

**Comment by shedaniel** [comment]
Sorry, I have properly mark the 1.18.2 version as 1.18.2, and 1.19 version as 1.19
