### ISSUE TITLE
[Bug] Game sometimes crashes when searching a recipe.

### ISSUE THREAD

**Issue by KevinKharma1** [shedaniel/RoughlyEnoughItems#869]
### What happened?

This has happen 3 times to me over the past two days and before the game crashes, my screen glitches and shows the Minecraft dirt background where the recipes are, and then the game closes.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/26/22, 3:26 PM
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index 1906 out of bounds for length 1253
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:427)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.render(EntryListWidget.java:294)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:738)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.render(ScreenOverlayImpl.java:637)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:389)
	at net.minecraft.client.render.GameRenderer.handler$zjd000$renderScreenPost(GameRenderer:9059)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:294)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:738)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:637)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:389)
	at net.minecraft.class_757.handler$zjd000$renderScreenPost(class_757.java:9059)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (555, 430). Absolute: (1110.781250, 860.410156)
	Screen size: Scaled: (720, 450). Absolute: (1440, 900). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Kharma_'/84, l='ClientLevel', x=824.14, y=113.06, z=-1462.10]]
	Chunk stats: 4096, 1026
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 124844 game time, 134324 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, minecraft/supporteatinganimation, guiretextures-darkmode-1.7.4

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 12.3.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 628705776 bytes (599 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 6122.95
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 10.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.12
		advanced-xray-fabric: Advanced XRay (Fabric) 1.18.2-1.0.0-build.11
		ambientenvironment: Ambient Environment 7.0+19
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.2.50
		autofish: Autofish 0.9.4
		autorun: AutoRun 0.4.0
		axesareweapons: Axes Are Weapons 1.5.1
		balm-fabric: Balm 3.0.0+0
		bclib: BCLib 1.4.5
		betterf3: BetterF3 1.2.5
		bettermounthud: Better Mount HUD 1.1.4
		caffeineconfig: CaffeineConfig 1.1.0
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cloth-api: Cloth API 3.2.64
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.2.64
		cloth-common-events-v1: Cloth Common Events v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
		cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
		cloth-utils-v1: Cloth Utils v1 3.2.64
		collective-fabric: Collective (Fabric) 4.26
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_llamalad7_mixinextras: MixinExtras 0.0.9
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		controlling: Controlling For Fabric 9.0+19
		create: Create mc1.18.2_v0.4.1+586
		creativecore: CreativeCore (Fabric) 2.6.10
		customfov: Custom FoV 1.4.1-1.18.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
		dynamicfps: Dynamic FPS 2.1.0
		easiervillagertrading: EasierVillagerTrading 1.18.2-fabric0.47.10-1.5.4
		eatinganimationid: Eating Animation 1.6
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.3+1.18
		entityculling: EntityCulling-Fabric 1.5.1
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 2.0.9+e19de87d60
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabric-tree-chopper: Fabric Tree Chopper 0.8.5
		fabricloader: Fabric Loader 0.14.5
		fake-player-api: Fake Player API 0.3.0
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		flywheel: Flywheel 1.18-0.6.2.25
		forge_tags: Forge Tags 2.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		fps: FPS Monitor 1.18-1.2.1-Fabric
		freecam: Freecam 1.0.6
		gbfabrictools: GBfabrictools 1.3.4+1.18.2
		goosik-config: goosik-config 0.2.0
		grindenchantments: Grind Enchantments 1.6.1+1.18.2
		guiclock-fabric: GUI Clock (Fabric) 3.0
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.3+mc1.18.2
		interactic: Interactic 0.1.10+1.18
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.4-build.38
		itemborders: Item Borders 1.1.5
		itemmodelfix: Item Model Fix 1.0.3+1.18
		itemsortermod: ItemSorterMod 1.10.0
		java: OpenJDK 64-Bit Server VM 17
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.7.9
		malilib: MaLiLib 0.12.1
		milk: Milk Lib 0.3.2
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modmanager: Mod Manager 1.2.3+1.18
		modmenu: Mod Menu 3.2.2
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.18
		mostructures: Mo' Structures 1.4.2+1.18.2
		noindium: No Indium? 1.0.1+1.18.2
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		numismatic-overhaul: Numismatic Overhaul 0.2.1+1.18
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		owo: oωo 0.7.2+1.18
		porting_lib: Porting Lib 1.1.0-beta+1.18.2-dev.ffa2ca8
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		roughlyenoughitems: Roughly Enough Items 8.0.442
		shulkerboxtooltip: Shulker Box Tooltip 3.0.7+1.18.2
		signtools: Sign Tools 1.0.0
		skinlayers: 3d Skin Layers 1.4.4-mc1.18.2
		sleepwarp: SleepWarp 1.1.1+1.18.2
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.4+mc1.18.2-build.39
		stacc: Stacc 1.3.0
		starlight: Starlight 1.0.2+fabric.89b8d9f
		taxfreelevels: Tax Free Levels 1.3
		tlcosmetica: Cosmetica 0.4.0
		trinkets: Trinkets 3.3.1
		visuality: Visuality 0.4.2
		walllanterns: Lanterns Belong on Walls 1.2.0
		waveycapes: WaveyCapes 1.2.0
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.5-1.18.2
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Apple M1 GL version 4.1 Metal - 76.3, Apple
	Window size: 1440x900
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, minecraft/supporteatinganimation, file/guiretextures-darkmode-1.7.4
	Current Language: English (US)
	CPU: 8x Apple M1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Kharma_'/84, l='ServerLevel[Create Survival]', x=824.14, y=113.06, z=-1462.10]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Roughly Enough Items (roughlyenoughitems)
```

**Comment by shedaniel** [comment]
Please update REI
