### ISSUE TITLE
[Bug] [Fabric 1.19] in dev client, gives me this crash

### ISSUE THREAD

**Issue by ianm1647** [shedaniel/RoughlyEnoughItems#904]
### What happened?

i was just trying to update my current mod to 1.19 and testing it in the dev client and this error occurred when launching, not sure as to why its happening , thought you might know

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy31.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:65)
	... 12 more
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.autoconfig.ConfigData.validatePostLoad()" because "this.config" is null
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106)
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53)
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66)
	at me.shedaniel.rei.impl.client.config.ConfigManagerImpl.<init>(ConfigManagerImpl.java:102)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.attachClientInternals(RoughlyEnoughItemsCoreClient.java:203)
	at dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:35)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.<clinit>(RoughlyEnoughItemsCore.java:86)
	... 15 more
```
```


### Anything else?

_No response_

**Comment by shedaniel** [comment]
Is it easily reproducible?

**Comment by ianm1647** [comment]
> Is it easily reproducible?

im not sure , all i know is its when rei is loaded, this is the first time its happened for me.

i tried loading rei in another dev client and it loaded fine, but i don't know what would be causing this problem

**Comment by ianm1647** [comment]
i just recreated the workspace with the same mod and it works now 
i dont know what happened
