### ISSUE TITLE
[Bug] crash when opening inventory before everything is loaded in properly

### ISSUE THREAD

**Issue by jklw10** [shedaniel/RoughlyEnoughItems#911]
### What happened?

Game crashed when I pressed e, better crashes told me 'twas rei.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
java.util.concurrent.RejectedExecutionException: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2179) ~[?:?]
	at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2196) ~[?:?]
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2664) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.execute(TaskExecutor:135) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.send(TaskExecutor:124) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.enqueueChunk(ChunkTaskPrioritySystem:129) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17624(ChunkTaskPrioritySystem:95) ~[?:?]
	at net.minecraft.class_3906$1.send(class_3906.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17259(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1147) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager:552) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager:561) ~[?:?]
	at net.minecraft.server.world.ServerChunkManager.executeQueuedTasks(ServerChunkManager:278) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:796) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[19:23:51] [IO-Worker-33/ERROR]: Cound not schedule mailbox
java.util.concurrent.RejectedExecutionException: Task IOWorker-chunk 2 false rejected from java.util.concurrent.ThreadPoolExecutor@66b3c657[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 84881]
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.execute(TaskExecutor:135) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[19:23:53] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5136823120ms or 102736462 ticks behind
```

### Anything else?

[2022-06-12-6.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8886268/2022-06-12-6.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8886269/rei.log)

**Comment by shedaniel** [comment]
No, this is unrelated to REI, REI has already successfully loaded in your logs.

**Comment by jklw10** [comment]
it is plausible the log was over written after said crash, i was doing alot of testing at that time.
