### ISSUE TITLE
[Bug] Forge - REI crash when attempting to render lava?

### ISSUE THREAD

**Issue by Sousanators** [shedaniel/RoughlyEnoughItems#924]
### What happened?

The last page of REI always causes a crash, even when it's the only mod installed

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [x] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-06-15, 7:33 p.m.
Description: Adding entry

java.lang.NoSuchMethodError: 'net.minecraftforge.fluids.FluidAttributes net.minecraft.world.level.material.Fluid.getAttributes()'
	at dev.architectury.hooks.fluid.forge.FluidStackHooksImpl.getStillTexture(FluidStackHooksImpl.java:81) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading}
	at dev.architectury.hooks.fluid.FluidStackHooks.getStillTexture(FluidStackHooks.java) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading}
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getExtraData(FluidEntryDefinition.java:221) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getExtraData(FluidEntryDefinition.java:210) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.add(BatchedEntryRendererManager.java:77) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.addAll(BatchedEntryRendererManager.java:61) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.<init>(BatchedEntryRendererManager.java:55) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.m_6305_(EntryListWidget.java:314) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:741) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_6305_(ScreenOverlayImpl.java:640) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:393) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.EventHandlerImplClient.eventDrawScreenEvent(EventHandlerImplClient.java:158) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_eventDrawScreenEvent_Post.invoke(.dynamic) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%232!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:383) ~[forge-1.19-41.0.35-universal.jar%2383!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:375) ~[forge-1.19-41.0.35-universal.jar%2383!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1071) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.architectury.hooks.fluid.forge.FluidStackHooksImpl.getStillTexture(FluidStackHooksImpl.java:81) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading}
	at dev.architectury.hooks.fluid.FluidStackHooks.getStillTexture(FluidStackHooks.java) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading}
-- Screen details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.error.ErrorsScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.add(BatchedEntryRendererManager.java:90) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.addAll(BatchedEntryRendererManager.java:61) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.<init>(BatchedEntryRendererManager.java:55) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.m_6305_(EntryListWidget.java:314) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:741) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_6305_(ScreenOverlayImpl.java:640) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading}
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:393) ~[RoughlyEnoughItems-9.0.480.jar%2377!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.EventHandlerImplClient.eventDrawScreenEvent(EventHandlerImplClient.java:158) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_eventDrawScreenEvent_Post.invoke(.dynamic) ~[architectury-5.6.24.jar%2375!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%232!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:383) ~[forge-1.19-41.0.35-universal.jar%2383!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:375) ~[forge-1.19-41.0.35-universal.jar%2383!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1071) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%2378!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}


-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: minecraft:fluid
	Is empty: false
	Entry identifier: minecraft:lava

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition
	Fluid Type: minecraft:lava
	Fluid Amount: 1000
	Fluid NBT: null

-- Screen details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.error.ErrorsScreen

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1287906648 bytes (1228 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1165
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23917.56
	Virtual memory used (MB): 14689.47
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 98.48
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.1+10.0.1+main.e9521dc3
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		RoughlyEnoughItems-9.0.480.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |9.0.480             |DONE      |Manifest: NOSIGNATURE
		cloth-config-7.0.72-forge (1).jar                 |Cloth Config v4 API           |cloth_config                  |7.0.72              |DONE      |Manifest: NOSIGNATURE
		forge-1.19-41.0.35-universal.jar                  |Forge                         |forge                         |41.0.35             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		architectury-5.6.24.jar                           |Architectury                  |architectury                  |5.6.24              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 67c6fa82-70d2-4cb8-91d8-e1e1f86665d2
	FML: 41.0
	Forge: net.minecraftforge:41.0.35
```

**Comment by MaxNeedsSnacks** [comment]
Forge's Fluid API has changed significantly in releases as recent as *yesterday*, meaning Architectury API is going to need an update, see https://github.com/architectury/architectury-api/pull/280. This is going to be merged later today, until then, I recommend you downgrade to a Forge version <41.0.28

**Comment by shedaniel** [comment]
A new architectury API is now released, please update both Architectury and Forge.
