### ISSUE TITLE
[Bug] 1.19 server unable to start. [Fabric]

### ISSUE THREAD

**Issue by drakosoldier298** [shedaniel/RoughlyEnoughItems#978]
### What happened?

making a server for modpack i amde and its just refusing to launch

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[06:39:56] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[06:39:57] [ForkJoinPool-1-worker-2/WARN]: Mod io_netty_netty-codec-http uses the version 4.1.77.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[06:39:57] [main/INFO]: Loading 159 mods:
	- additionalentityattributes 1.0.0+1.19 via apoli
	- advanced_reborn 1.0.8
	- alloy_forgery 2.0.15+1.19
	- amecs 1.3.8+mc.1.16.3
	- apoli 2.5.1 via origins
	- appleskin 2.4.0+mc1.19
	- architectury 5.8.29
	- autoconfig1u 3.4.0 via advanced_reborn
	- backslot 1.2.8
	- bclib 2.0.10
	- betterend 2.0.5
	- blockus 2.5.1+1.19
	- blue_endless_jankson 1.2.1 via jankson
	- calio 1.7.0 via apoli
	- cardinal-components-base 5.0.0-beta.1 via mythicmetals
	- cardinal-components-entity 5.0.0-beta.1 via mythicmetals
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.72
	- cloth-utils-v1 2.0.54 via computercraft
	- cmods 1.3.0+fabric-1.19 via purpeille
	- com_electronwill_night-config_core 3.6.3 via computercraft
	- com_electronwill_night-config_toml 3.6.3 via computercraft
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_typesafe_config 1.4.1 via croptopia
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- computercraft 1.101.0
	- croptopia 2.0.6
	- entitybanners 1.1-BETA+1.19
	- fabric 0.57.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
	- fabric-language-kotlin 1.8.1+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- fiber 0.23.0-2 via patchouli
	- frame 0.22.1+1.19
	- frame-api-base 0.2.0 via frame
	- frame-blocks-v0 0.1.2 via frame
	- frame-config-v0 0.2.1 via frame
	- frame-content-registries-v0 0.4.0+2876b511a9 via frame
	- frame-game-rules-v0 0.2.3 via frame
	- frame-items-v0 0.1.2 via frame
	- frame-loot-tables-v0 0.1.4 via frame
	- frame-rendering-v0 0.1.4 via frame
	- frame-tabbed-item-groups-v0 0.2.1 via frame
	- frame-toymaker-v0 0.6.0+c2d5b470a9 via frame
	- frame-woods-v0 0.1.0+ea73347fa9 via frame
	- gearreborn 1.19-0.1.15
	- geckolib3 3.1.5
	- icarus 1.13
	- imm_ptl_core 2.0.4 via immersive_portals
	- immersive_portals 2.0.4
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- io_netty_netty-codec-http 4.1.77.Final via computercraft
	- ironchests 1.7.2
	- itemnbt 3.4 via technototem
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- krypton 0.2.0
	- libgui 6.0.0+1.19 via ironchests
	- libninepatch 1.1.0 via libgui
	- lithium 0.8.0
	- magna 1.8.0-1.19 via mythicmetals
	- mantori 1.1.1-1.19
	- mcpitanlib 1.4.4 via advanced_reborn
	- midnightlib 0.5.2
	- minecraft 1.19
	- modid 2.2.0+1.19
	- mousewheelie 1.10.1+mc1.19-pre1
	- mythicmetals 0.15.1
	- nochatreports 1.19-v1.2.3
	- omega-config 1.0.8 via magna
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_objenesis_objenesis 3.2 via plantinajar
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- org_squiddev_cobalt 0.5.5 via computercraft
	- origins 1.6.2
	- origins-classes 1.4.0
	- owo 0.7.3+1.19
	- packet_tweaker 0.3.0+1.18.2 via polymer
	- patchouli 1.19-73-FABRIC
	- pehkui 3.3.3+1.14.4-1.19.1
	- plantinajar 2.4.1
	- plasmo_voice 1.2.17
	- playerabilitylib 1.6.0 via apoli
	- polymer 0.2.5+1.19 via polymer-all
	- polymer-all 0.2.5+1.19
	- polymer-autohost 0.1.0+1.19 via polymer-all
	- polymer-blocks-ext 0.1.0-alpha.8+1.19 via polymer-all
	- polymer-registry-sync-manipulator 0.0.1+1.19 via polymer-autohost
	- purpeille 3.0.0+fabric-1.19-hotfix
	- q_misc_util 2.0.4 via immersive_portals
	- quarrymod 1.0.2
	- reach-entity-attributes 2.3.0 via origins
	- reborncore 5.3.2
	- roughlyenoughitems 9.1.503
	- roughlysearchable 2.5.0+1.19
	- sculkhornid 0.1.1
	- sky 0.6.0
	- sonic_deflect 1.0.0+1.19
	- splatus_spellbound_weapons 3.3.0
	- starlight 1.1.1+fabric.ae22326
	- team_reborn_energy 2.2.0 via reborncore
	- technototem 1.0.0+mc1.19
	- techreborn 5.3.2
	- terraform-wood-api-v1 4.1.0 via blockus
	- trinkets 3.4.0
	- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
	- tweed4_base 1.6.0+mc22w17a via mousewheelie
	- tweed4_data 1.2.1+mc22w17a via mousewheelie
	- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie
	- twigs 2.0.0-beta.7+1.19
	- voidcrafting 1.7.1+fabric-1.19 via purpeille
	- yosbr 0.1.1
[06:39:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[06:39:57] [main/INFO]: Compatibility level set to JAVA_17
[06:39:57] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 1 override(s) found
[06:39:57] [main/WARN]: Reference map 'plasmovoice-fabric-refmap.json' for plasmovoice.mixins.json could not be read. If this is a development environment you can ignore this message
[06:39:57] [main/WARN]: Reference map 'sky-refmap.json' for sky.mixins.json could not be read. If this is a development environment you can ignore this message
[06:39:58] [main/WARN]: Error loading class: net/minecraft/class_1059$class_4007 (java.lang.ClassNotFoundException: net/minecraft/class_1059$class_4007)
[06:39:58] [main/WARN]: @Mixin target net.minecraft.class_1059$class_4007 was not found alloy-forgery.mixins.json:SpriteAtlasTextureDataAccessor from mod alloy_forgery
[06:39:58] [main/WARN]: Error loading class: net/minecraft/class_459$class_462 (java.lang.ClassNotFoundException: net/minecraft/class_459$class_462)
[06:39:58] [main/WARN]: @Mixin target net.minecraft.class_459$class_462 was not found amecs.mixins.json:ControlsListWidgetKeyBindingEntryAccessor from mod amecs
[06:39:58] [main/WARN]: Error loading class: net/minecraft/class_309 (java.lang.ClassNotFoundException: net/minecraft/class_309)
[06:39:58] [main/WARN]: @Mixin target net.minecraft.class_309 was not found amecs.mixins.json:MixinKeyboard from mod amecs
[06:39:58] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [immersive_portals, krypton]) disables it and children
[06:39:58] [main/WARN]: Error loading class: net/minecraft/class_5602 (java.lang.ClassNotFoundException: net/minecraft/class_5602)
[06:39:58] [main/WARN]: @Mixin target net.minecraft.class_5602 was not found mythicmetals.mixins.json:AccessorEntityModelLayers from mod mythicmetals
[06:39:58] [main/WARN]: Error loading class: net/minecraft/class_1007 (java.lang.ClassNotFoundException: net/minecraft/class_1007)
[06:39:58] [main/WARN]: @Mixin target net.minecraft.class_1007 was not found mythicmetals.mixins.json:PlayerEntityRendererMixin from mod mythicmetals
[06:39:58] [main/WARN]: Error loading class: net/minecraft/class_1078 (java.lang.ClassNotFoundException: net/minecraft/class_1078)
[06:39:58] [main/WARN]: @Mixin target net.minecraft.class_1078 was not found mythicmetals.mixins.json:TranslationStorageMixin from mod mythicmetals
[06:39:59] [main/WARN]: Error loading class: me/shedaniel/rei/impl/client/config/ConfigObjectImpl (java.lang.RuntimeException: Cannot load class me.shedaniel.rei.impl.client.config.ConfigObjectImpl in environment type SERVER)
[06:39:59] [main/WARN]: @Mixin target me.shedaniel.rei.impl.client.config.ConfigObjectImpl was not found roughlysearchable.mixins.json:ConfigObjectMixin from mod roughlysearchable
[06:39:59] [main/WARN]: Error loading class: net/minecraft/class_918 (java.lang.ClassNotFoundException: net/minecraft/class_918)
[06:39:59] [main/WARN]: @Mixin target net.minecraft.class_918 was not found roughlysearchable.mixins.json:ItemRendererMixin from mod roughlysearchable
[06:39:59] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[06:40:01] [main/INFO]: Mixing MixinPlayer from nochatreports.mixins.json into net.minecraft.class_1657
[06:40:07] [main/INFO]: Building unoptimized datafixer
[06:40:07] [main/INFO]: Trying to read config file...
[06:40:07] [main/INFO]: A config file was found, loading it..
[06:40:07] [main/INFO]: Successfully loaded config file.
[06:40:09] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[06:40:09] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[06:40:10] [main/INFO]: apoli.mixins.json:ItemSlotArgumentTypeAccessor from mod apoli->@Accessor[FIELD_GETTER]::getSlotNamesToSlotCommandId()Ljava/util/Map; should be static as its target is
[06:40:10] [main/INFO]: Mixing MixinServerGamePacketListenerImpl from nochatreports.mixins.json into net.minecraft.class_3244
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:prismarine_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:deepslate_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:prismarine_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:deepslate_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:prismarine_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:polished_blackstone_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:end_stone_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:deepslate_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:prismarine_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:polished_blackstone_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:end_stone_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:deepslate_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:prismarine_bricks_forge_controller
[06:40:10] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:polished_blackstone_forge_controller
[06:40:11] [main/INFO]: Apoli 2.5.1 has initialized. Ready to power up your game!
[06:40:11] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[06:40:11] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[06:40:11] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[06:40:11] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[06:40:11] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[06:40:11] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[06:40:26] [main/INFO]: Combining the Modifiers...
[06:40:28] [main/INFO]: Loading Immersive Portals config
[06:40:28] [main/INFO]: IP Config Applied
[06:40:28] [main/INFO]: Immersive Portals Mod Initializing
[06:40:28] [main/INFO]: Dimensional Threading is not present
[06:40:28] [main/INFO]: Pehkui is present
[06:40:28] [main/INFO]: Gravity API is not present
[06:40:28] [main/INFO]: Compression will use libdeflate (Linux aarch64), encryption will use OpenSSL (Linux aarch64)
[06:40:28] [main/INFO]: [STDOUT]: Registering ModConfiguredFeatures for mantori
[06:40:28] [main/INFO]: [STDOUT]: Registering ModBlocks for mantori
[06:40:28] [main/INFO]: Registering mod items for mantori
[06:40:28] [main/INFO]: [STDOUT]: Registering ModSounds for mantori
[06:40:28] [main/INFO]: [STDOUT]: Registering mod enchantments for mantori
[06:40:28] [main/INFO]: Loaded MCPitanLib
[06:40:28] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:end_stone_bricks_forge_controller
[06:40:28] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:deepslate_bricks_forge_controller
[06:40:28] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:stone_bricks_forge_controller
[06:40:28] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:bricks_forge_controller
[06:40:28] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:prismarine_bricks_forge_controller
[06:40:28] [main/WARN]: Encountered duplicate API provider registration for block: alloy_forgery:polished_blackstone_forge_controller
[06:40:28] [main/INFO]: [Mythic Metals] Have fun using Origins!
[06:40:28] [main/INFO]: [Mythic Metals] Mythic Metals is now initialized.
[06:40:28] [main/INFO]: KONNICHIWA ZA WARUDO!
[06:40:28] [main/INFO]: Origins 1.6.2 is initializing. Have fun!
[06:40:28] [main/INFO]: [STDOUT]: You Can Put Your Plants In Jars Now!
[06:40:28] [main/INFO]: Purpeille: Harness the Void!
[06:40:28] [main/WARN]: Purpeille support for REI is limited; use EMI for better integration! https://modrinth.com/mod/emi
[06:40:29] [main/INFO]: [STDOUT]: All 5 have been set properly
[06:40:29] [main/INFO]: [STDOUT]: Registering Mod Items for sculkhornid
[06:40:29] [main/INFO]: Hello Fabric world!
[06:40:29] [main/INFO]: Blood for the Blood God
[06:40:29] [main/INFO]: TechReborn setup done!
[06:40:29] [main/INFO]: Found ComputerCraft
[06:40:30] [main/INFO]: Initializing Twigs
[06:40:30] [main/INFO]: Initialized Twigs (took 275ms)
[06:40:30] [main/INFO]: Initializing Void Crafting
[06:40:30] [main/WARN]: Void Crafting support on REI is limited; use EMI for better integration! https://modrinth.com/mod/emi
[06:40:30] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19-loader.0.14.8-launcher.0.11.0.jar:0.11.0]
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(Unknown Source) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy30.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Mythic Metals. Please use "rei_server", "rei_client" or "rei_common" instead.
	at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:53) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:107) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:136) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at me.shedaniel.rei.PluginDetector.detectCommonPlugins(PluginDetector.java) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:153) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.503.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(Unknown Source) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy30.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 8 more
```

**Comment by shedaniel** [comment]
This is caused by Mythic Metals
