### ISSUE TITLE
[Bug] 1.18.2 FTB Dripper JEI plugin integration

### ISSUE THREAD

**Issue by Raidobw2** [shedaniel/RoughlyEnoughItems#980]
### What happened?

FTB Dripper's plugin integration seems off, unsure if it's to be fixed by FTB or REI, but there's an issue on both trackers.

Relayed from https://github.com/FTBTeam/FTB-Mods-Issues/issues/326

FTB Dripper `ftb-dripper-1802.1.1-build.21.jar`
REI `RoughlyEnoughItems-8.3.502.jar`
REI Hacks `RoughlyEnoughItems-jei-internals-workaround-8.3.502.jar`

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[26Jun2022 20:18:25.228] [REI-ReloadPlugins/ERROR] [REI/]: [REI] JEI Plugin [FTBDripperJEIPlugin:ftbdripper:jei] [ftbdripper] plugin failed to reloadable-plugin/DisplayRegistryImpl/!
java.lang.ExceptionInInitializerError: null
	at dev.ftb.mods.ftbdripper.jei.FTBDripperJEIPlugin.registerRecipes(FTBDripperJEIPlugin.java:43) ~[ftb-dripper-1802.1.2-build.23.jar%2361!/:1802.1.2-build.23]
	at me.shedaniel.rei.jeicompat.JEIPluginDetector$JEIPluginWrapper.registerDisplays(JEIPluginDetector.java:564) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:141) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:57) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:329) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:189) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:319) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:187) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:317) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:142) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:133) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:458) ~[RoughlyEnoughItems-8.2.492.jar%2378!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:recipe_type / ftbdripper:drip])
	at net.minecraft.core.MappedRegistry.m_205921_(MappedRegistry.java:78) ~[client-1.18.2-20220404.173914-srg.jar%2384!/:?]
	at net.minecraft.core.MappedRegistry.m_205857_(MappedRegistry.java:87) ~[client-1.18.2-20220404.173914-srg.jar%2384!/:?]
	at net.minecraft.core.MappedRegistry.m_203704_(MappedRegistry.java:83) ~[client-1.18.2-20220404.173914-srg.jar%2384!/:?]
	at net.minecraft.core.MappedRegistry.m_203505_(MappedRegistry.java:129) ~[client-1.18.2-20220404.173914-srg.jar%2384!/:?]
	at net.minecraft.core.Registry.m_194579_(Registry.java:564) ~[client-1.18.2-20220404.173914-srg.jar%2384!/:?]
	at net.minecraft.core.Registry.m_122965_(Registry.java:560) ~[client-1.18.2-20220404.173914-srg.jar%2384!/:?]
	at net.minecraft.world.item.crafting.RecipeType.m_44119_(RecipeType.java:20) ~[client-1.18.2-20220404.173914-srg.jar%2384!/:?]
	at dev.ftb.mods.ftbdripper.recipe.FTBDripperRecipeSerializers.<clinit>(FTBDripperRecipeSerializers.java:18) ~[ftb-dripper-1802.1.2-build.23.jar%2361!/:1802.1.2-build.23]
	... 20 more
```

### Anything else?

Thanks in advance! :)

**Comment by shedaniel** [comment]
In Line 18 of this file, https://github.com/FTBTeam/FTB-Dripper/blob/main/src/main/java/dev/ftb/mods/ftbdripper/recipe/FTBDripperRecipeSerializers.java

The recipe type should be registered through a DeferredRegister

**Comment by Raidobw2** [comment]
Sunekaer told me it's indeed a FTB Dripper issue. I'll pass the information along to Mikey, thanks Shedaniel! (Closing this as will be fixed in FTB Dripper)
