### ISSUE TITLE
[Bug] CHANGE ME

### ISSUE THREAD

**Issue by Scorpions95** [shedaniel/RoughlyEnoughItems#988]
### What happened?

Just see the the picture bellow
https://i.imgur.com/tAI0aTP.png

I just install Vein Meiner and sell this bug (see the link)

Minecraft version: 1.19
Forge version: 41.0.94

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[13:05:04] [main/INFO]: ModLauncher running: args [--username, ivailo, --version, test, --gameDir, C:\Users\ivail\AppData\Roaming\.minecraft\versions\test, --assetsDir, C:\Users\ivail\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 6d8b0fe906a94e89b139fe86f838b3ad, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, release, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 41.0.94, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129]
[13:05:04] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[13:05:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/ivail/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2390!/ Service=ModLauncher Env=CLIENT
[13:05:04] [main/INFO]: Found mod file cloth-config-7.0.72-forge.jar of type MOD with provider {mods folder locator at C:\Users\ivail\AppData\Roaming\.minecraft\versions\test\mods}
[13:05:04] [main/INFO]: Found mod file tl_skin_cape_forge_1.19-1.26.jar of type MOD with provider {mods folder locator at C:\Users\ivail\AppData\Roaming\.minecraft\versions\test\mods}
[13:05:04] [main/WARN]: Mod file C:\Users\ivail\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19-41.0.94\fmlcore-1.19-41.0.94.jar is missing mods.toml file
[13:05:04] [main/WARN]: Mod file C:\Users\ivail\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19-41.0.94\javafmllanguage-1.19-41.0.94.jar is missing mods.toml file
[13:05:04] [main/WARN]: Mod file C:\Users\ivail\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19-41.0.94\lowcodelanguage-1.19-41.0.94.jar is missing mods.toml file
[13:05:04] [main/WARN]: Mod file C:\Users\ivail\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19-41.0.94\mclanguage-1.19-41.0.94.jar is missing mods.toml file
[13:05:04] [main/INFO]: Found mod file fmlcore-1.19-41.0.94.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4bd2f0dc
[13:05:04] [main/INFO]: Found mod file javafmllanguage-1.19-41.0.94.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4bd2f0dc
[13:05:04] [main/INFO]: Found mod file lowcodelanguage-1.19-41.0.94.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4bd2f0dc
[13:05:04] [main/INFO]: Found mod file mclanguage-1.19-41.0.94.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4bd2f0dc
[13:05:04] [main/INFO]: Found mod file client-1.19-20220607.102129-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4bd2f0dc
[13:05:04] [main/INFO]: Found mod file forge-1.19-41.0.94-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4bd2f0dc
[13:05:04] [main/INFO]: No dependencies to load found. Skipping!
[13:05:05] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[13:05:05] [main/INFO]: Launching target 'forgeclient' with arguments [--version, test, --gameDir, C:\Users\ivail\AppData\Roaming\.minecraft\versions\test, --assetsDir, C:\Users\ivail\AppData\Roaming\.minecraft\assets, --uuid, 6d8b0fe906a94e89b139fe86f838b3ad, --username, ivailo, --assetIndex, 1.19, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, release, --width, 925, --height, 530]
[13:05:06] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[13:05:06] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[13:05:06] [main/WARN]: Disabling further attempts to query Paging File.
[13:05:07] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[13:05:08] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[13:05:10] [Render thread/WARN]: Assets URL 'union:/C:/Users/ivail/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23148!/assets/.mcassetsroot' uses unexpected schema
[13:05:10] [Render thread/WARN]: Assets URL 'union:/C:/Users/ivail/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23148!/data/.mcassetsroot' uses unexpected schema
[13:05:10] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:05:11] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.5.41.jar%23120!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:140) ~[authlib-3.5.41.jar%23120!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:47) ~[authlib-3.5.41.jar%23120!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:158) ~[authlib-3.5.41.jar%23120!/:?]
	at net.minecraft.client.Minecraft.m_193585_(Minecraft.java:615) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.main.Main.main(Main.java:170) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.94.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.5.41.jar%23120!/:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.5.41.jar%23120!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-3.5.41.jar%23120!/:?]
	... 18 more
[13:05:11] [Render thread/INFO]: Setting user: ivailo
[13:05:11] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[13:05:11] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: cloth_config, class me.shedaniel.clothconfig.ClothConfigForge
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.94.jar%23150!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.94.jar%23149!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/ConfigGuiHandler$ConfigGuiFactory
	at me.shedaniel.clothconfig.ClothConfigForgeDemo.registerModsPage(ClothConfigForgeDemo.java:28) ~[cloth-config-7.0.72-forge.jar%23143!/:?]
	at net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:123) ~[fmlcore-1.19-41.0.94.jar%23149!/:?]
	at me.shedaniel.clothconfig.ClothConfigForge.<init>(ClothConfigForge.java:34) ~[cloth-config-7.0.72-forge.jar%23143!/:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.ConfigGuiHandler$ConfigGuiFactory
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.shedaniel.clothconfig.ClothConfigForgeDemo.registerModsPage(ClothConfigForgeDemo.java:28) ~[cloth-config-7.0.72-forge.jar%23143!/:?]
	at net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:123) ~[fmlcore-1.19-41.0.94.jar%23149!/:?]
	at me.shedaniel.clothconfig.ClothConfigForge.<init>(ClothConfigForge.java:34) ~[cloth-config-7.0.72-forge.jar%23143!/:?]
	... 14 more
[13:05:11] [modloading-worker-0/INFO]: Forge mod loading, version 41.0.94, for MC 1.19 with MCP 20220607.102129
[13:05:11] [modloading-worker-0/INFO]: MinecraftForge v41.0.94 Initialized
[13:05:11] [Render thread/FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[13:05:11] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[13:05:11] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state
[13:05:11] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state
[13:05:11] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterParticleProvidersEvent to a broken mod state
[13:05:12] [Render thread/INFO]: Narrator library for x64 successfully loaded
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterTextureAtlasSpriteLoadersEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterKeyMappingsEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterGuiOverlaysEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state
[13:05:12] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state
[13:05:12] [Worker-Main-1/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233789_(ProfileKeyPairManager.java:137) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233796_(ProfileKeyPairManager.java:63) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[13:05:12] [Render thread/INFO]: Reloading ResourceManager: Default
[13:05:12] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state
[13:05:12] [Worker-Main-1/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:12] [Worker-Main-11/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:12] [Worker-Main-6/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:15] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state
[13:05:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:05:16] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[13:05:16] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[13:05:16] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (USB Audio Device)
[13:05:16] [Render thread/INFO]: Sound engine started
[13:05:16] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[13:05:16] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$BakingCompleted to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[13:05:17] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:17] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:05:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:05:18] [Render thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[13:05:18] [Render thread/FATAL]: Preparing crash report with UUID a0143faf-ce1a-434c-baab-3fc2b050d84f
[13:05:18] [Render thread/FATAL]: Crash report saved to C:\Users\ivail\AppData\Roaming\.minecraft\versions\test\crash-reports\crash-2022-07-12_13.05.18-fml.txt
[13:05:18] [Render thread/FATAL]: Preparing crash report with UUID 986e349c-5fba-4479-8127-3d0bf7277284
```

**Comment by shedaniel** [comment]
Update REI and its dependencies before reporting!

**Comment by Scorpions95** [comment]
> Update REI and its dependencies before reporting!

how can i update it?
https://i.imgur.com/1FzMKGW.png
